### ISSUE TITLE
Builds failing because number-float64-base-to-float32 is not found

### ISSUE THREAD

**Issue by thomask** [stdlib-js/stdlib#1006]
### Description

Our builds are failing with the following error:

```
error An unexpected error occurred: "https://registry.yarnpkg.com/@stdlib/number-float64-base-to-float32/-/number-float64-base-to-float32-0.0.7.tgz: Request failed \"404 Not Found\"".
```

If I look for @stdlib/number-float64-base-to-float32 on NPM, it still shows up in search results:

![image](https://github.com/stdlib-js/stdlib/assets/448755/b5fd67d2-4f81-43f0-ae1b-fb1f86ad947a)

However, trying to click the link takes me to the NPM login screen which could perhaps mean the lib was (accidentally?) marked as private?

### Checklist

- [X] Read and understood the [Code of Conduct](https://github.com/stdlib-js/stdlib/blob/develop/CODE_OF_CONDUCT.md).
- [X] Searched for existing issues and pull requests.

**Comment by t-moennich** [comment]
nvm, working again 🤷🏼

**Comment by TheHogginator** [comment]
Started working again for us to, could be related to https://status.npmjs.org/incidents/drj38qn6qm59

**Comment by thomask** [comment]
Yep, working again. Closing
