### ISSUE TITLE
[RFC]: Organize the information on the website 

### ISSUE THREAD

**Issue by payalpm** [stdlib-js/stdlib#1013]
### Description

 more effectively by creating clear and concise menus and using headings and subheadings to break up the text.

### Related Issues

Related issues # , # , and # .

### Questions

No.

### Other

No.

### Checklist

- [X] I have read and understood the [Code of Conduct](https://github.com/stdlib-js/stdlib/blob/develop/CODE_OF_CONDUCT.md).
- [X] Searched for existing issues and pull requests.
- [X] The issue name begins with `RFC:`.

**Comment by kgryte** [comment]
@payalpm Do you have specific proposals in mind?

**Comment by payalpm** [comment]
Yes i have

**Comment by kgryte** [comment]
Great! And what are those proposals? As a project, we cannot really move forward on this without concrete ideas of the proposed changes.

**Comment by kgryte** [comment]
As this issue is missing follow up and is missing concrete proposals, I will go ahead and close.
