### ISSUE TITLE
`@stdlib/string/base/constantcase` doesn't change hyphens to underscores

### ISSUE THREAD

**Issue by romanstetsyk** [stdlib-js/stdlib#1017]
### Description

Encountered a bug in `@stdlib/string/base/constantcase`. If a string contains hyphens, '-', they are not changed to '_'. The issue is in [this line of code](https://github.com/stdlib-js/stdlib/blob/develop/lib/node_modules/%40stdlib/string/base/constantcase/lib/main.js#L31). The regular expression doesn't contain a hyphen (U+002D), but it does contain an endash (U+2013).
Other similar packages for changing string cases contain both characters in the regular expression.

<img width="701" alt="image" src="https://github.com/stdlib-js/stdlib/assets/25715951/1e47fb9e-84c5-4919-876a-a29344271cad">

### Questions

No.

### Reproduction

```shell
`console.log(constantcase('foo-bar'))`
```

### Expected Results

```shell
`'FOO_BAR'`
```

### Actual Results

```shell
`'FOO-BAR'`
```

### Version

v0.0.96

### Environments

N/A

### Checklist

- [X] Read and understood the [Code of Conduct](https://github.com/stdlib-js/stdlib/blob/develop/CODE_OF_CONDUCT.md).
- [X] Searched for existing issues and pull requests.

**Comment by romanstetsyk** [comment]
If you can confirm/reproduce the bug, I'll submit a pr with a fix and updated test cases.

**Comment by Planeshifter** [comment]
Thank you for filing this bug report, which I am able to reproduce. A PR with a fix and updated test cases would be greatly appreciated!
