### ISSUE TITLE
RFC: complex number flipsign

### ISSUE THREAD

**Issue by kgryte** [stdlib-js/stdlib#102]
## Checklist

> Please ensure the following tasks are completed before filing an issue.

* [x] Read and understood the [Code of Conduct][code-of-conduct].
* [x] Searched for existing issues and pull requests.
* [x] If this is a general question, searched the [FAQ][faq] for an existing answer.
* [x] If this is a feature request, the issue name begins with `RFC: `.

## Description

> Description of the issue (or feature request).

Add support for returning a complex number which has the same magnitude as `z` and is `-z` if `y` is negative. Equivalent to `flipsign` for reals.

Package: `@stdlib/math/base/complex/flipsign`
alias: `cflipsign`

Behavior:

``` javascript
var v = cflipsign( re, im, +y );
// returns [ re, im ]

v = cflipsign( re, im, -y );
// returns [ -re, -im ]
```

## Related Issues

> Does this issue (or feature request) have any related issues?

None.

## Questions

> Any questions for reviewers?

No.

## Other

> Any other information relevant to this issue (or feature request)? This may include screenshots, references, stack traces, sample output, and/or implementation notes.

No.

[code-of-conduct]: https://github.com/stdlib-js/stdlib/blob/develop/CODE_OF_CONDUCT.md
[faq]: https://github.com/stdlib-js/stdlib/blob/develop/FAQ.md

**Comment by rreusser** [comment]
`complex/negate`, perhaps? No strong preference.

**Comment by rreusser** [comment]
Edit: never mind. Didn't fully process.
