### ISSUE TITLE
Typo in README

### ISSUE THREAD

**Issue by rajeevkumar504** [stdlib-js/stdlib#1021]
I encountered this issue in the Readme. md file of this project, It's in this screenshot,
<img width="855" alt="Screenshot 2023-05-29 at 4 39 05 PM" src="https://github.com/stdlib-js/stdlib/assets/97542658/52c63f16-6383-4916-9a02-374754d18ee3">

But according to me, It should be:- "I want to perform data analysis and data science-related tasks in JavaScript and Node.js, similar to how I might use Python, Julia, R, and MATLAB."

**Comment by kgryte** [comment]
@Rajeevjewar According to this SO [post](https://english.stackexchange.com/questions/2908/should-i-use-related-or-related), you are correct, as "data science-related" comes before "tasks". However, this would also mean that we should have "data analysis- and/or data science-related tasks", as "data analysis" is part of the compound adjective.

If you want to submit a PR, we can review.

**Comment by ghost** [comment]
"Like how I might use Python, Julia, R, and MATLAB, I wish to execute data analysis and data science-related jobs with JavaScript and Node.js."

This will sound better, I believe.

**Comment by arin-paliwal** [comment]
> @Rajeevjewar According to this SO [post](https://english.stackexchange.com/questions/2908/should-i-use-related-or-related), you are correct, as "data science-related" comes before "tasks". However, this would also mean that we should have "data analysis- and/or data science-related tasks", as "data analysis" is part of the compound adjective.
> 
> If you want to submit a PR, we can review.

Can I submit a PR for that ?

**Comment by PiyushBhatnagar09** [comment]
Hello @Rajeevjewar  sir, the correct sentence should be "I want to perform data analysis and/or data science-related tasks in JavaScript and Node.js, similar to how I might use IPython, Julia, R, and/or MATLAB."

**Comment by debsouryadatta** [comment]
Hello @kgryte  , I want to work on this issue, can you please assign it to me.

**Comment by Narcos101** [comment]
if this issue isn't solved, i would like to work on it!
