### ISSUE TITLE
`make install` fails on Apple Silicon M1 `darwin-arm64`

### ISSUE THREAD

**Issue by walterra** [stdlib-js/stdlib#1061]
### Description

Encountered an error when running `make install` from the [development setup instructions](https://github.com/stdlib-js/stdlib/blob/develop/docs/development.md).

### Questions

No.

### Reproduction

Follow the [development setup instructions](https://github.com/stdlib-js/stdlib/blob/develop/docs/development.md) and run `make install`.

### Expected Results

`make install` should complete without error.

### Actual Results

When running `make install` on Apple M1, I get the following error related to the `electron` dependency:

```shell
Downloading Electron...
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     9    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
curl: (22) The requested URL returned error: 404
make: *** [/Users/<redacted>/deps/tmp/electron-v6.0.10-darwin-arm64.zip] Error 22
```

It looks like `electron` needs to be at least version 11 to support Apple Silicon/M1/darwin-arm64.

I did some local tests with updating the setup to version 12 and `make install` was able to complete.

```shell
Verifying download...
Success.

Extracting Electron...
Running tests...
v12.2.3

Success.
```

### Version

`develop` branch

### Environments

N/A

### Platform

macos M1

### Checklist

- [X] Read and understood the [Code of Conduct](https://github.com/stdlib-js/stdlib/blob/develop/CODE_OF_CONDUCT.md).
- [X] Searched for existing issues and pull requests.

**Comment by kgryte** [comment]
@walterra Thanks for reporting this issue. Will try and push a fix later this evening.

**Comment by kgryte** [comment]
Should be resolved in https://github.com/stdlib-js/stdlib/commit/d33368119f5cd6d037eed7e1d9f24be3368832a9.

If you still encounter issues when installing repository dependencies, feel free to reopen this issue.
