### ISSUE TITLE
[RFC]: add `@stdlib/assert/is-well-formed-string`

### ISSUE THREAD

**Issue by kgryte** [stdlib-js/stdlib#1065]
### Description

This RFC proposes adding support for asserting whether an input value is a well-formed string (i.e. does not contain lone surrogates).

Package: `@stdlib/assert/is-well-formed-string`
Alias: `isWellFormedString`

### Related Issues

None.

### Questions

No.

### Other

Resources:

- Lone surrogates: <https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String#utf-16_characters_unicode_code_points_and_grapheme_clusters>
- isWellFormed: <https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String/isWellFormed>

Prior art in stdlib:

- `@stdlib/assert/is-string`
- `@stdlib/assert/is-empty-string`

### Checklist

- [X] I have read and understood the [Code of Conduct](https://github.com/stdlib-js/stdlib/blob/develop/CODE_OF_CONDUCT.md).
- [X] Searched for existing issues and pull requests.
- [X] The issue name begins with `RFC:`.

**Comment by gunjjoshi** [comment]
I would like to work on this issue. Can you please assign this to me ?

**Comment by kgryte** [comment]
@gunjjoshi When working on this issue, I suggest first studying some of the implementations in `@stdlib/string/base` and also consulting the surrogate pair regexp in `@stdlib/regexp`.

**Comment by gunjjoshi** [comment]
@kgryte I would surely do that.
Also, I was thinking of checking 2 things - 
  1. Input value is a string, using `is-string`
  2. Input value is well formed, using [`isWellFormed`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String/isWellFormed) function

Is this approach correct ?

**Comment by kgryte** [comment]
The `isWellFormed` function is not universally supported. We typically roll our own implementations. If the built-in exists, you can defer to it, but if it is missing, we need to fallback to a functional polyfill.

**Comment by gunjjoshi** [comment]
Got it. I will try to implement it from scratch, after having a look at the packages you mentioned earlier.

**Comment by gunjjoshi** [comment]
@kgryte I found `@stdlib/regexp/utf16-surrogate-pair` to be somewhat useful for this.

Firstly we can check if an input string str contains any surrogate pairs by using `reUtf16SurrogatePair()`. Also, we will be checking each character individually in the string, based on the conditions for lone surrogates.

```
var reUtf16SurrogatePair = require('@stdlib/regexp/utf16-surrogate-pair');

var RE_UTF16_SURROGATE_PAIR = reUtf16SurrogatePair();

function containsLoneSurrogates(str) {
    var hasSurrogatePairs = RE_UTF16_SURROGATE_PAIR.test(str);
    if (hasSurrogatePairs) {
        return false;
    }
    for (var i = 0; i < str.length; i++) {
        var charCode = str.charCodeAt(i);
        if ((charCode >= 0xD800 && charCode <= 0xDBFF) || (charCode >= 0xDC00 && charCode <= 0xDFFF)) {
            return false;
        }
    }
    return true;
}
```

Is this approach correct ? Any suggestions ?

**Comment by kgryte** [comment]
Your approach is not correct. Simply because a string has surrogate pairs does not mean that it does not also contain lone surrogates.

For reference, we have various packages which attempt to accommodate/detect lone surrogates (e.g., https://github.com/stdlib-js/stdlib/blob/bb104f6a5138d600a4d1460af5380cb4960481d3/lib/node_modules/%40stdlib/string/base/for-each-code-point/lib/main.js), so you want to do a bit more R&D on the approach.

**Comment by gunjjoshi** [comment]
Went a bit deeper, and came up with this.

Rather than checking for each character as I was trying previously, we check for each code point, using `@stdlib/string/base/for-each-code-point`. 

Suggestions on this ? Is there anything I am missing out ?

```
var forEachCodePoint = require('@stdlib/string/base/for-each-code-point');

function containsLoneSurrogates(str) {
    var hasLoneSurrogates = false;

    forEachCodePoint(str, function(cp) {

        if ((cp >= 0xD800 && cp <= 0xDBFF) || (cp >= 0xDC00 && cp <= 0xDFFF)) {
            hasLoneSurrogates = true;
            return false;
        }
    });

    return hasLoneSurrogates;
}

```

**Comment by kgryte** [comment]
In general, I suggest avoiding using callbacks, especially in this case, as the anonymous function used with `forEachCodePoint` cannot be readily compiler optimized, as the JS compiler must create a new context for each invocation of `containsLoneSurrogates` and the function depends on the value of `hasLoneSurrogates` in the parent scope.

Additionally, `forEachCodePoint` does not early exit, so if I have a 100 character string and the first character is a lone surrogate, I'll still iterate over the entire string.

You can, however, copy over and modify the logic in `forEachCodePoint` to better handle this particular use case.

**Comment by gunjjoshi** [comment]
Avoided callbacks in this. Also, made an early exit mechanism.

For each code point, we check for high surrogates first. If it is found, we immediately break the loop and return false.
Otherwise, we move on to check low surrogates, and repeat the process.

```
var forEachCodePoint = require('@stdlib/string/base/for-each-code-point');

function isWellFormedString(str) {

    var hasLoneSurrogates = false;

    for (var i = 0, len = str.length; i < len; i++) {

        var ch1 = str[i];
        var cp = ch1.codePointAt(0);

        if (cp >= 0xD800 && cp <= 0xDBFF) {

            if (i === len - 1 || (str[i + 1].codePointAt(0) < 0xDC00 || str[i + 1].codePointAt(0) > 0xDFFF)) {
                hasLoneSurrogates = true;
                break;
            }
        }

        if ( hasLoneSurrogates ) return false; 

        if (cp >= 0xDC00 && cp <= 0xDFFF) {

            if (i === 0 || (str[i - 1].codePointAt(0) < 0xD800 || str[i - 1].codePointAt(0) > 0xDBFF)) {
                hasLoneSurrogates = true;
                break;
            }
        }
    }

    return !hasLoneSurrogates;
}
```
How about this one ?

**Comment by kgryte** [comment]
`codePointAt` is not supported in older Node.js versions. I suggest just emulating the logic in `for-each-code-point`.

**Comment by kgryte** [comment]
Also, you don't need to the `hasLoneSurrogates` variable. By default, you return `true`. If you encounter a lone surrogate, you immediately return `false`, thus exiting the loop and function.

**Comment by gunjjoshi** [comment]
Made the changes now.  How about this one ?
```
var RE_UTF16_LOW_SURROGATE = /[\uDC00-\uDFFF]/;
var RE_UTF16_HIGH_SURROGATE = /[\uD800-\uDBFF]/;

function isWellFormedString(str) {
    for (var i = 0; i < str.length; i++) {
        var ch1 = str[i];
        var ch2;

        if (i < str.length - 1 && RE_UTF16_HIGH_SURROGATE.test(ch1)) {
            ch2 = str[i + 1];
            if (RE_UTF16_LOW_SURROGATE.test(ch2)) {
                i += 1;
            } else {
                return false;
            }
        } else if (RE_UTF16_LOW_SURROGATE.test(ch1)) {
            return false;
        }
    }

    return true;
}
```

**Comment by gunjjoshi** [comment]
How about this one ? It checks all the conditions for lone surrogates.

```
var RE_UTF16_LOW_SURROGATE = /[\uDC00-\uDFFF]/;
var RE_UTF16_HIGH_SURROGATE = /[\uD800-\uDBFF]/;

function isWellFormedString(str) {
    for (var i = 0; i < str.length; i++) {
        var ch1 = str[i];
        var ch2;

        if (i < str.length - 1 && RE_UTF16_HIGH_SURROGATE.test(ch1)) {
            ch2 = str[i + 1];
            if (RE_UTF16_LOW_SURROGATE.test(ch2)) {
                i += 1;
            } else {
                return false;
            }
        } else if (RE_UTF16_LOW_SURROGATE.test(ch1)) {
            if (i === 0 || !RE_UTF16_HIGH_SURROGATE.test(str[i - 1])) {
                return false;
            }
        } else if (RE_UTF16_HIGH_SURROGATE.test(ch1)) {
            return false;
        }
    }

    return true;
}
```

**Comment by kgryte** [comment]
That should work, @gunjjoshi, but I think you can make it a bit cleaner.

1. `i = 0`: if low surrogate, return `false`.
2. `i = str.length-1`: if high surrogate, return `false`.

Both of those checks can be done before you hit the loop, as they are your edge cases: a leading low surrogate and a trailing high surrogate.

If you make it past your two edge cases, run the loop looking for a low surrogate which is not preceded by a high surrogate or a high surrogate which is not followed by a low surrogate.

**Comment by gunjjoshi** [comment]
Sure, I will do those changes, for checking the edge cases first. 

I will now move on to the implementation part, and will be making a PR in a while, thanks for the guidance.

**Comment by gunjjoshi** [comment]
@kgryte Should I make only a `main.js` along with `index.js`, as in the [for-each-code-point](https://github.com/stdlib-js/stdlib/blob/bb104f6a5138d600a4d1460af5380cb4960481d3/lib/node_modules/%40stdlib/string/base/for-each-code-point/lib/main.js) package, or should I make 2 seperate `object.js` for string objects and `primitive.js` for string primitives, along with that ?

**Comment by kgryte** [comment]
Let's go ahead and have two separate; however, both can reference a common internal function so you can avoid code duplication. E.g.,

```javascript
function isWellFormed( str ) {...}

function isPrimitive( str ) {
	return ( isString( str ) && isWellFormed( str ) );
}

function isObject( str ) {
	return ( isStringObject( str ) && isWellFormed( str.valueOf() ) );
}
``
