### ISSUE TITLE
[RFC]: add `@stdlib/string/to-well-formed`

### ISSUE THREAD

**Issue by kgryte** [stdlib-js/stdlib#1066]
### Description

This RFC proposes adding support for replacing lone surrogates in a provided string in order to create a string which is "well-formed".

This is a functional API analog of the recently standardized `String.prototype.toWellFormed`.

Package: `@stdlib/string/to-well-formed`
alias: `str2wellformed`

### Related Issues

None.

### Questions

No.

### Other

Resources:

- [`String.prototype.toWellFormed`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String/toWellFormed)

### Checklist

- [X] I have read and understood the [Code of Conduct](https://github.com/stdlib-js/stdlib/blob/develop/CODE_OF_CONDUCT.md).
- [X] Searched for existing issues and pull requests.
- [X] The issue name begins with `RFC:`.

**Comment by soham2312** [comment]
@Planeshifter @kgryte I would like to work on it
Please assign this to me

**Comment by vr-varad** [comment]
@kgryte @Planeshifter @Pranavchiku  i am done with the first issue and made a pr can i work on this

**Comment by Pranavchiku** [comment]
@vr-varad please address code review on #1349, once merged you can be assigned another issue. Thanks!

**Comment by Pranavchiku** [comment]
@soham2312 thanks for volunteering, if you are still interested in implementing this, please let us know, we can assign this to you.

**Comment by Pratik772846** [comment]
@kgryte @Pranavchiku @Planeshifter I am interested in implementing this, please assign this issue to me.

**Comment by Pranavchiku** [comment]
Thanks @Pratik772846 for volunteering, assigned you the issue.

**Comment by Pratik772846** [comment]
@kgryte @Planeshifter @Pranavchiku  What I am thinking of implementing is this: If the string is well-formed, I will simply return a shallow copy of that particular string. However, if it is not well-formed, I will replace all lone surrogates ( whether they are high surrogates or low surrogates ) with the Unicode replacement character U+FFFD. Could you please confirm whether I am thinking in the right direction or not?

**Comment by Pratik772846** [comment]
@kgryte @Planeshifter 
function str2wellformed( str ) {
	if ( !isString( str ) ) {
		throw new TypeError( format( 'invalid argument. Must provide a string. Value: `%s`.', str ) );
	}
    var modifiedString;
    if ( isWellFormed( str ) ) {
        for ( var i = 0; i < str.length; i++ ) {
            modifiedString += str[i];
        }
        return modifiedString;
    }
	for ( var i =0; i < str.length; i++ ) {
        if ( RE_UTF16_LOW_SURROGATE.test( str[i] ) || RE_UTF16_HIGH_SURROGATE.test( str[i] ) ) {
            modifiedString += 'U+FFFD';
        }
        else {
            modifiedString += str[i];
        }
    }
    return modifiedString;
}
Is this the correct implementation?
