### ISSUE TITLE
Bug: website is missing a landing page

### ISSUE THREAD

**Issue by jondot** [stdlib-js/stdlib#107]
FYI stdlib.io shows directory listing and not a website.

**Comment by kgryte** [comment]
Yeah, the site is under active development. We have yet to create a landing page. :)

To see API docs, just follow the directory links: `develop -> docs -> api -> @stdlib -> <dir>`.

**Comment by cristiano-belloni** [comment]
> To see API docs, just follow the directory links: `develop -> docs -> api -> @stdlib -> <dir>`

I checked, but there is no such directory in the repo.

**Comment by kgryte** [comment]
@cristiano-belloni Here is the link: https://stdlib.io/develop/docs/api/@stdlib/

**Comment by cristiano-belloni** [comment]
@kgryte Ah, cool, it seems I misread your previous response! Thanks!

**Comment by kgryte** [comment]
We've updated the website. For API docs, see https://stdlib.io/docs/api. Closing out...
