### ISSUE TITLE
Can't resolve './dataview.js' error importing @stdlib/stats

### ISSUE THREAD

**Issue by alexebl** [stdlib-js/stdlib#1072]
### Description

I have an angular project where I want to use @stdlib/stats library
I have installed the library via npm:
      npm install @stdlib/stats
and then included it within one component using import statement
      import {dists} from '@stdlib/stats/base';

when I trying to compile project I'm getting this error:

./main.js:24:21-45 - Error: Module not found: Error: Can't resolve './dataview.js' in '<project path>\node_modules\@stdlib\assert\has-arraybuffer-support\lib'

lokking in node_modules path, I could not find dataview.js either, so it seems that something changed in sources and needs to be adapted

### Reproduction

```shell
Create an angular projects
npm install @stdlib/stats

add
import {dists} from '@stdlib/stats/base';
```

### Expected Results

```shell
compiles
```

### Actual Results

```shell
compiles with error
```

### Version

"@stdlib/stats": "^0.0.13",

### Environments

Chrome

### Platform

Windows

### Checklist

- [X] Read and understood the [Code of Conduct](https://github.com/stdlib-js/stdlib/blob/develop/CODE_OF_CONDUCT.md).
- [X] Searched for existing issues and pull requests.

**Comment by kgryte** [comment]
@alexebl Heya! Are you looking to use many of the distributions of `@stdlib/stats/base/dist/*` or just a couple? If the latter, you can install the individual distributions you want to use directly. E.g.,

```bash
$ npm install @stdlib/stats-base-dists-normal
```

If the former, then we can investigate a bit further. My guess is that a published package is out-of-sync with its dependencies.

**Comment by Planeshifter** [comment]
@alexebl Created a test repository with a new Angular project to reproduce the reported issue: 

https://github.com/Planeshifter/angular-stdlib-stats-test

However, importing

```ts
import {dists} from '@stdlib/stats/base';
```

and using one of its functions works without any issues for me, so the problem must be somehow tied to your project's configuration. Do you use any other `@stdlib` packages besides `stats`? It would be great if you could create a reproducible example so we can figure out what is going on.

**Comment by alexebl** [comment]
yes, it seems to be issue of broken project configuration,
I have just created another new Angular project and copied the package.json from the faulty project, that one works.
I then deleted node_modules and package-lock.json from the faulty one and reinstalled everything, still not working
So, it seems to be a problem of my configuration.

**Comment by kgryte** [comment]
Can we close this issue then?

**Comment by alexebl** [comment]
Actually I was able to reproduce the error.
Steps:
1. ng new test
2. npm install @stdlib/stats
3. add to src\app\app.component.ts following statements:
    import {dists} from '@stdlib/stats/base';
    import {kstest} from '@stdlib/stats';

    constructor() {
      let cdf = dists.normal.cdf(2,5,3);
      let test = kstest( [ 2.0, 1.0, 5.0, -5.0, 3.0, 0.5, 6.0 ], 'normal', 0.0, 1.0 )
    }
=> compilation failed with:
./node_modules/@stdlib/assert/has-arraybuffer-support/lib/main.js:24:21-45 - Error: Module not found: Error: Can't resolve './dataview.js' in 'C:\Source\PowerBiVisuals\Development\node_modules\@stdlib\assert\has-arraybuffer-support\lib'  

the error occured after I have added the kstest function call, not sure if additional parts need to be installed for kstest

**Comment by Planeshifter** [comment]
@alexebl Thank you for these detailed instructions. We can reproduce the problem and will look into a solution. 

In the meantime, you may try using the standalone packages, i.e. `@stdlib/stats-kstest` and `@stdlib/stats-base-dists-normal-cdf` for the above example.

**Comment by kgryte** [comment]
@alexebl Did you try using the standalone packages?

**Comment by kgryte** [comment]
@Planeshifter Is this issue resolved now that we've released new minor versions of the top-level namespaces?

**Comment by Planeshifter** [comment]
This issue is now resolved. Closing this issue thread.
