### ISSUE TITLE
[RFC]: add `@stdlib/fs/read-ndjson`

### ISSUE THREAD

**Issue by kgryte** [stdlib-js/stdlib#1074]
### Description

This RFC proposes adding a filesystem utility to read a file which is newline-delimited JSON (NDJSON).

Package: `@stdlib/fs/read-ndjson`
Alias: `readNDJSON`

### Related Issues

The following RFC is a prerequisite to being able to implement this feature:

- https://github.com/stdlib-js/stdlib/issues/1075

### Questions

No.

### Other

For a reference package, see

- [`@stdlib/fs/read-json`](https://github.com/stdlib-js/stdlib/tree/1dbb5491b16d4f969cf4748bd1fc7bcd80b89ccc/lib/node_modules/%40stdlib/fs/read-json)

### Checklist

- [X] I have read and understood the [Code of Conduct](https://github.com/stdlib-js/stdlib/blob/develop/CODE_OF_CONDUCT.md).
- [X] Searched for existing issues and pull requests.
- [X] The issue name begins with `RFC:`.

**Comment by maniksharma17** [comment]
@kgryte Hey, I can take it up after #1075 gets merged. I've already made PR for #1075.

**Comment by kgryte** [comment]
@maniksharma17 Yes, that seems like a natural follow-up. I'll go ahead and assign you.

**Comment by Pratik772846** [comment]
Hey @kgryte @Planeshifter , if no one is working on this issue , can I take this?

**Comment by maniksharma17** [comment]
@Pratik772846 Hey, parse-ndjson got merged a day ago. I've started working on this one.

**Comment by aayush0325** [comment]
I'd love to work on this issue since a PR hasn't been raised for a long time and I'd love some clarification on how to write examples for this


``` javascript

 @example
* var resolve = require( 'path' ).resolve;
* var readNDJSON = require( '@stdlib/fs/read-ndjson' );
*
* function onNDJSON( error, data ) {
*     if ( error ) {
*         throw error;
*     }
*     console.dir( data );
* }
*
* read	NDJSON( resolve( __dirname, '..', 'example.ndjson' ), onNDJSON );
*
* @example
* var resolve = require( 'path' ).resolve;
* var instanceOf = require( '@stdlib/assert/instance-of' );
* var readNDJSON = require( '@stdlib/fs/read-ndjson' );
*
* var out = readNDJSON.sync( resolve( __dirname, '..', 'example.ndjson' ) );
* if ( instanceOf( out, Error ) ) {
*     throw out;
* }
* console.dir( out );
*/

```

![image](https://github.com/user-attachments/assets/27ef6f6c-283c-4652-8f68-5bf53d07ad16)

To demonstrate the usage for this package i have made an example.ndjson in the root directory of this package for now, however if there is something else that you expect from this kindly let me know.

**Comment by yaswanthkosuru** [comment]
Can I work on these issue if no one is working

**Comment by aayush0325** [comment]
@yaswanthkosuru , I've been working on this, i can raise a PR by the weekend. Thank you.

**Comment by aayush0325** [comment]
@yaswanthkosuru  please feel free to take over this as i cannot come up with a solution as of now

**Comment by yaswanthkosuru** [comment]
@aayush0325 
May I know the challenges you faced so that i will help if possible or it can help me

**Comment by aayush0325** [comment]
@yaswanthkosuru I couldn't write accurate examples for this as I am not familiar with ndjson spec, tried reading about it but it really didn't work out. my index.js in examples was giving expected output when i manually ran it via Node.js but it was giving errors while i tried committing it

**Comment by yaswanthkosuru** [comment]
ok it seems like there is knowledge gap .i can take these issue .Thank u
FYI:Examples look like in fs/readjson but here it can Parse \n lines also
Intial Thoughts:Package look like @stdlib/fs/read-json,use parsendjson to parse

**Comment by aayush0325** [comment]
yup i tried, all the best!!!

**Comment by yaswanthkosuru** [comment]
hey @Planeshifter @kgryte  when i am commiting 
![image](https://github.com/user-attachments/assets/8c0d2bbe-2686-4d6d-a52d-51940465e551)
can i commit and create pull request without changing lint configurations for now and create Pr?

**Comment by kgryte** [comment]
I don't think you need to support a separate `*.ndjson` filename extension. Just use `*.json`.

**Comment by yaswanthkosuru** [comment]
@kgryte  
@Planeshifter 
```
var readNDJSON = require( '@stdlib/fs/read-ndjson' );
readNDJSON("package.json")=>returns content
readNDJSON("package.ndjson")=>returns content
```
is package needs to support both file formats  like above?
if above is the case,    `@stdlib/utils/parse-ndjson` can only parse  ndjson.
Then Based on file name we can use parsejson or parsenjson to parse content.
How ever i dont think it is good to go with `*.json`. correct me if am wrong.

**Comment by kgryte** [comment]
No, the filename extension has no bearing here. As a user, I should be able to provide a file path having any extension and the described APIs should read the file contents and attempt to parse as NDJSON. So again, we do not need to add support for a specific ndjson filename extension. The same has been true of other packages (eg, read-json, read-wasm); none of those packages care about what the filename extension is, nor should they.
