### ISSUE TITLE
[RFC]: add `@stdlib/utils/parse-ndjson`

### ISSUE THREAD

**Issue by kgryte** [stdlib-js/stdlib#1075]
### Description

This RFC proposes adding a utility to parse a string containing serialized newline-delimited JSON (NDJSON).

The exposed API should have the same signature as [`@stdlib/utils/parse-json`](https://github.com/stdlib-js/stdlib/tree/1dbb5491b16d4f969cf4748bd1fc7bcd80b89ccc/lib/node_modules/%40stdlib/utils/parse-json), and the reviver should be applied to each line of NDJSON.

Package: `@stdlib/utils/parse-ndjson`
Alias: `parseNDJSON`

### Related Issues

- https://github.com/stdlib-js/stdlib/issues/1074

### Questions

No.

### Other

The following should serve as a reference package:

- [`@stdlib/utils/parse-json`](https://github.com/stdlib-js/stdlib/tree/1dbb5491b16d4f969cf4748bd1fc7bcd80b89ccc/lib/node_modules/%40stdlib/utils/parse-json)

### Checklist

- [X] I have read and understood the [Code of Conduct](https://github.com/stdlib-js/stdlib/blob/develop/CODE_OF_CONDUCT.md).
- [X] Searched for existing issues and pull requests.
- [X] The issue name begins with `RFC:`.

**Comment by maniksharma17** [comment]
Hey @kgryte, I can take up this issue. I've already made out the logic. Please assign this to me.

**Comment by kgryte** [comment]
Thank you for volunteering to work on this, @maniksharma17. Please feel to open a PR which implements this feature.

**Comment by maniksharma17** [comment]
Hey @kgryte, this is the desired output, right?
// var obj = parseNDJSON( '{"name":"John"}\n{"name":"Doe"}' );
// Returns [{'name':'John'}, {'name':'Doe'}]

**Comment by maniksharma17** [comment]
@kgryte This is my first open-source contribution. When I made the pull requests, the workflow showed an error.
Will the PR be merged? Or, I need to resolve the error? 
 
![image](https://github.com/stdlib-js/stdlib/assets/130829163/df80040c-a951-4a6c-9c54-07433fdec266)

**Comment by Planeshifter** [comment]
@maniksharma17 Don't worry about; this is something for us to look into. Thank you for your contribution; we will try to review it soon!

**Comment by maniksharma17** [comment]
@Planeshifter 
Okay, Looking forward to contribute more!
