### ISSUE TITLE
[RFC]: improve type declarations for `@stdlib/utils/group-own`

### ISSUE THREAD

**Issue by kgryte** [stdlib-js/stdlib#1085]
### Description

This RFC proposes improving the TypeScript type declarations for `@stdlib/utils/group-own`. Currently, considerable type information is lost when returning results, which are presently typed as `any`.

Ideally, we'd improve declarations similar to [`@stdlib/utils/group-by`](https://github.com/stdlib-js/stdlib/blob/1bf88f1a75366df27e02072018699487680ab597/lib/node_modules/%40stdlib/utils/group-by/docs/types/index.d.ts) which better preserves type info.

### Related Issues

https://github.com/stdlib-js/stdlib/issues/1084

### Questions

No.

### Other

No.

### Checklist

- [X] I have read and understood the [Code of Conduct](https://github.com/stdlib-js/stdlib/blob/develop/CODE_OF_CONDUCT.md).
- [X] Searched for existing issues and pull requests.
- [X] The issue name begins with `RFC:`.

**Comment by BhaveshP443** [comment]
@kgryte I want to work on this issue please assign this issue to me.

**Comment by Shubh942** [comment]
@kgryte  I understand this issue, and I would like to work on it
 Please assign this to me

**Comment by Planeshifter** [comment]
@Shubh942 Assigned! Looking forward to your contribution; please feel free to check in if you have any questions.
