### ISSUE TITLE
[RFC]: improve type declarations for `@stdlib/utils/group`

### ISSUE THREAD

**Issue by kgryte** [stdlib-js/stdlib#1086]
### Description

This RFC proposes improving the TypeScript type declarations for `@stdlib/utils/group`. Currently, considerable type information is lost when returning results, which are presently typed as `any`.

Ideally, we'd improve declarations similar to [`@stdlib/utils/group-by`](https://github.com/stdlib-js/stdlib/blob/1bf88f1a75366df27e02072018699487680ab597/lib/node_modules/%40stdlib/utils/group-by/docs/types/index.d.ts) which better preserves type info.

### Related Issues

https://github.com/stdlib-js/stdlib/issues/1084

### Questions

No.

### Other

No.

### Checklist

- [X] I have read and understood the [Code of Conduct](https://github.com/stdlib-js/stdlib/blob/develop/CODE_OF_CONDUCT.md).
- [X] Searched for existing issues and pull requests.
- [X] The issue name begins with `RFC:`.

**Comment by BhaveshP443** [comment]
@kgryte I want to work on this issue please assign this issue to me.

**Comment by performant23** [comment]
Hello, just noticed that this issue is currently unassigned. Since I don't have any issue at hand as of now and have reviewed both the ‘group’ and ‘group by’ sections and have identified the necessary changes, if it’s alright, may I proceed to work on this issue @kgryte?
Thank you!

**Comment by rajutkarsh07** [comment]
@Planeshifter @kgryte I have understood this issue, I would like to work on it Please assign this to me

**Comment by kgryte** [comment]
@performant23 Since you already have a few issues in-flight, let's focus getting those over the finish line before moving on to other issues.

@rajutkarsh07 Feel free to submit a PR implementing this improvement.
