### ISSUE TITLE
[RFC]: improve type declarations for `@stdlib/utils/map-arguments`

### ISSUE THREAD

**Issue by kgryte** [stdlib-js/stdlib#1087]
### Description

This RFC proposes improving the TypeScript type declarations for `@stdlib/utils/map-arguments`. Currently, considerable type information is lost when using this function.

Ideally, we'd improve declarations for the input and callback functions and the `thisArg`.

### Related Issues

No.

### Questions

No.

### Other

No.

### Checklist

- [X] I have read and understood the [Code of Conduct](https://github.com/stdlib-js/stdlib/blob/develop/CODE_OF_CONDUCT.md).
- [X] Searched for existing issues and pull requests.
- [X] The issue name begins with `RFC:`.

**Comment by BhaveshP443** [comment]
i have started to work on this issue please assign this issue to me.

**Comment by kgryte** [comment]
Thanks for volunteering to work on this @iItachiUchiha. Please feel free to submit a PR with your proposed updates to the declarations for this package.

**Comment by BhaveshP443** [comment]
> Thanks for volunteering to work on this @iItachiUchiha. Please feel free to submit a PR with your proposed updates to the declarations for this package.

 thanks @kgryte i will make pr probably tomorrow.

**Comment by BhaveshP443** [comment]
@kgryte as i studied in codebase the fcn will be array of type : any, clbk : (value: any, index:number  ) and thisArg will be of any type. are these  correct ? if not then can you give some suggestions ?

**Comment by BhaveshP443** [comment]
@kgryte  ?
