### ISSUE TITLE
[RFC]: improve type declarations for `@stdlib/utils/async/if-else`

### ISSUE THREAD

**Issue by kgryte** [stdlib-js/stdlib#1095]
### Description

This RFC proposes improving the TypeScript type declarations for `@stdlib/utils/async/if-else`. Currently, considerable type information is lost when using this function.

Ideally, we'd improve declarations for `x`, `y`, and the `done` callback.

### Related Issues

No.

### Questions

No.

### Other

No.

### Checklist

- [X] I have read and understood the [Code of Conduct](https://github.com/stdlib-js/stdlib/blob/develop/CODE_OF_CONDUCT.md).
- [X] Searched for existing issues and pull requests.
- [X] The issue name begins with `RFC:`.

**Comment by rajutkarsh07** [comment]
@kgryte  I have understood this issue, and I would like to work on this please assign this to me

**Comment by prajwalkulkarni** [comment]
Hey @kgryte I'm picking this up, will submit a PR in some time!
