### ISSUE TITLE
[RFC]: improve type declarations for `@stdlib/utils/async/if-then`

### ISSUE THREAD

**Issue by kgryte** [stdlib-js/stdlib#1096]
### Description

This RFC proposes improving the TypeScript type declarations for `@stdlib/utils/async/if-then`. Currently, considerable type information is lost when using this function.

Ideally, we'd improve declarations for `x`, `y`, and the `done` callback.

### Related Issues

No.

### Questions

No.

### Other

No.

### Checklist

- [X] I have read and understood the [Code of Conduct](https://github.com/stdlib-js/stdlib/blob/develop/CODE_OF_CONDUCT.md).
- [X] Searched for existing issues and pull requests.
- [X] The issue name begins with `RFC:`.

**Comment by BhaveshP443** [comment]
i want to work on this issue please assign this to me

**Comment by itsspriyansh** [comment]
@kgryte 
I would like to work on this issue. Please assign this to me.

**Comment by kgryte** [comment]
Thanks for volunteering to work on this, @itsspriyansh. Please feel free to submit a PR improving the declarations.

@iItachiUchiha As you are already assigned an issue, it would be best if you first submit a PR for that issue (and have it merged) before moving onto resolving others.

**Comment by kgryte** [comment]
Actually, @itsspriyansh I see that you have also already been assigned an issue. Please work on https://github.com/stdlib-js/stdlib/issues/1323 before working on any others. Thanks!

**Comment by prajwalkulkarni** [comment]
Hey @kgryte, I went through the existing type definition for this function and was able to identify the shortcomings. I feel the type definitions can be improved by incorporating generics. I would like to work on this, could you kindly assign it to me?

**Comment by kgryte** [comment]
Thank you for volunteering to work on this @prajwalkulkarni. Feel free to submit a PR implementing the improvement.
