### ISSUE TITLE
Error: Cannot find module '@stdlib/string/base/trim' using @stdlib/bench

### ISSUE THREAD

**Issue by pjeby** [stdlib-js/stdlib#1132]
### Description

Encountered an error when trying to `require("@stdlib/bench")`

### Questions

No.

### Reproduction
- Install `@stdlib/bench` in a new project folder
- Create a script containing `require("@stdlib/bench")`
- Run it

### Expected Results
Module loads

### Actual Results
Error message:

```
Error: Cannot find module '@stdlib/string/base/trim'
Require stack:
- /home/pje/eventful/bench/node_modules/@stdlib/bench/harness/lib/benchmark-class/comment.js
- /home/pje/eventful/bench/node_modules/@stdlib/bench/harness/lib/benchmark-class/index.js
- /home/pje/eventful/bench/node_modules/@stdlib/bench/harness/lib/harness/index.js
- /home/pje/eventful/bench/node_modules/@stdlib/bench/harness/lib/main.js
- /home/pje/eventful/bench/node_modules/@stdlib/bench/harness/lib/index.js
- /home/pje/eventful/bench/node_modules/@stdlib/bench/lib/index.js
- /home/pje/eventful/bench/harness.js
    at Function.Module._resolveFilename (node:internal/modules/cjs/loader:1026:15)
    at Function.Module._load (node:internal/modules/cjs/loader:871:27)
    at Module.require (node:internal/modules/cjs/loader:1098:19)
    at require (node:internal/modules/cjs/helpers:108:18)
    at Object.<anonymous> (/home/pje/eventful/bench/node_modules/@stdlib/bench/harness/lib/benchmark-class/comment.js:23:12)
    at Module._compile (node:internal/modules/cjs/loader:1196:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1250:10)
    at Module.load (node:internal/modules/cjs/loader:1074:32)
    at Function.Module._load (node:internal/modules/cjs/loader:909:12)
    at Module.require (node:internal/modules/cjs/loader:1098:19) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/home/pje/eventful/bench/node_modules/@stdlib/bench/harness/lib/benchmark-class/comment.js',
    '/home/pje/eventful/bench/node_modules/@stdlib/bench/harness/lib/benchmark-class/index.js',
    '/home/pje/eventful/bench/node_modules/@stdlib/bench/harness/lib/harness/index.js',
    '/home/pje/eventful/bench/node_modules/@stdlib/bench/harness/lib/main.js',
    '/home/pje/eventful/bench/node_modules/@stdlib/bench/harness/lib/index.js',
    '/home/pje/eventful/bench/node_modules/@stdlib/bench/lib/index.js',
    '/home/pje/eventful/bench/harness.js'
  ]
}
```

### Version

@stdlib/bench version 0.2.0

### Environments

Node.js

### Checklist

- [X] Read and understood the [Code of Conduct](https://github.com/stdlib-js/stdlib/blob/develop/CODE_OF_CONDUCT.md).
- [X] Searched for existing issues and pull requests.

**Comment by pjeby** [comment]
Further investigation shows that this is due to a few modules referencing `@stdlib/string/base/something` that should be `@stdlib/string/something` (trim and replace, specifically).  The modules in question (in `@stdlib/bench`) are `harness/lib/runner/encode_assertion.js` and `harness/lib/benchmark-class/comment.js`.

**Comment by kgryte** [comment]
@pjeby As a workaround, install `@stdlib/bench-harness` instead. `@stdlib/bench` is a top-level namespace which exposes as its main export the benchmark harness.

**Comment by kgryte** [comment]
@pjeby **Update**: we just triggered a patch release for `@stdlib/bench`. Can you try installing that package again?

We also discovered a small issue in the published `@stdlib/bench-harness` package which we are working to address. This issue should not affect the top-level namespace, however.

**Comment by pjeby** [comment]
Looks like 0.2.1 fixes the issue.  Thanks!

**Comment by kgryte** [comment]
@pjeby Of course! Thanks for taking the time to file an issue!
