### ISSUE TITLE
RFC: compute scaled complementary error function

### ISSUE THREAD

**Issue by kgryte** [stdlib-js/stdlib#116]
## Checklist

> Please ensure the following tasks are completed before filing an issue.

-   [x] Read and understood the [Code of Conduct][code-of-conduct].
-   [x] Searched for existing issues and pull requests.
-   [x] If this is a general question, searched the [FAQ][faq] for an existing answer.
-   [x] If this is a feature request, the issue name begins with `RFC:`.

## Description

> Description of the issue (or feature request).

Add support for computing the scaled complementary error function: `exp(x**2) * erfc(x)`.

Package: `@stdlib/math/base/special/erfcx`
Alias: `base.erfcx`

## Related Issues

> Does this issue (or feature request) have any related issues?

None.

## Questions

> Any questions for reviewers?

No.

## Other

> Any other information relevant to this issue (or feature request)? This may include screenshots, references, stack traces, sample output, and/or implementation notes.

Reference implementations:

-   SciPy \[[1](https://github.com/scipy/scipy/blob/2526df72e5d4ca8bad6e2f4b3cbdfbc33e805865/scipy/special/Faddeeva.cc#L1281)\]\[[2](https://docs.scipy.org/doc/scipy/reference/generated/scipy.special.erfcx.html#scipy.special.erfcx)\]

[code-of-conduct]: https://github.com/stdlib-js/stdlib/blob/develop/CODE_OF_CONDUCT.md

[faq]: https://github.com/stdlib-js/stdlib/blob/develop/FAQ.md

**Comment by kgryte** [comment]
@Planeshifter This has now been done, correct?

**Comment by Planeshifter** [comment]
Yes. Closing.
