### ISSUE TITLE
RFC: compute the Box-Cox transformation of `1+x`

### ISSUE THREAD

**Issue by kgryte** [stdlib-js/stdlib#118]
## Checklist

> Please ensure the following tasks are completed before filing an issue.

-   [x] Read and understood the [Code of Conduct][code-of-conduct].
-   [x] Searched for existing issues and pull requests.
-   [x] If this is a general question, searched the [FAQ][faq] for an existing answer.
-   [x] If this is a feature request, the issue name begins with `RFC:`.

## Description

> Description of the issue (or feature request).

Add support for computing the [Box-Cox transformation](https://en.wikipedia.org/wiki/Power_transform#Box.E2.80.93Cox_transformation) of `1+x`.

Package: `@stdlib/math/base/special/boxcox1p`
Alias: `base.boxcox1p`

The implementation should be similar to `@stdlib/math/base/special/boxcox`, except with special consideration for small `x` values.

## Related Issues

> Does this issue (or feature request) have any related issues?

No.

## Questions

> Any questions for reviewers?

No.

## Other

> Any other information relevant to this issue (or feature request)? This may include screenshots, references, stack traces, sample output, and/or implementation notes.

Reference implementations:

-   SciPy \[[1](https://docs.scipy.org/doc/scipy/reference/generated/scipy.special.boxcox1p.html)\]\[[2](https://github.com/scipy/scipy/blob/2526df72e5d4ca8bad6e2f4b3cbdfbc33e805865/scipy/special/_boxcox.pxd#L18)\]

[code-of-conduct]: https://github.com/stdlib-js/stdlib/blob/develop/CODE_OF_CONDUCT.md

[faq]: https://github.com/stdlib-js/stdlib/blob/develop/FAQ.md

**Comment by justin1dennison** [comment]
I would be willing to work on this, but would it be best to leave this as a good first issue for someone else?

**Comment by kgryte** [comment]
@justin1dennison Go for it!
