### ISSUE TITLE
[RFC]: add `@stdlib/array/base/count-if`

### ISSUE THREAD

**Issue by kgryte** [stdlib-js/stdlib#1324]
### Description

This RFC proposes adding the package `@stdlib/array/base/count-if`.

The package should be structured similarly to [`@stdlib/array/base/count-truthy`](https://github.com/stdlib-js/stdlib/tree/64931c5fdb4abc3a339b619658d3b5acc089e556/lib/node_modules/%40stdlib/array/base/count-truthy).

The package should expose an API having the same signature as `countTruthy`, with the addition of `predicate` and `thisArg` arguments.

```javascript
function countIf( x, predicate[, thisArg] ) {...}
```

The `predicate` function should return a boolean value. If true, the function should increment a count; otherwise, the value is ignored. 

Package: `@stdlib/array/base/count-if`
Alias: `countIf`

### Related Issues

None.

### Questions

No.

### Other

This package should expose an API similar to the Excel/GSheets function of the same name: https://support.google.com/docs/answer/3093480?sjid=2342692862647625777-NC.

### Checklist

- [X] I have read and understood the [Code of Conduct](https://github.com/stdlib-js/stdlib/blob/develop/CODE_OF_CONDUCT.md).
- [X] Searched for existing issues and pull requests.
- [X] The issue name begins with `RFC:`.

**Comment by Alzamer** [comment]
I've just started working on this issue, can someone assign me?

**Comment by kgryte** [comment]
@Alzamer Thanks for volunteering to work on this issue. Please feel free to submit a PR implementing the requested feature.

**Comment by bad-in-coding** [comment]
Hi, I would like to work on this, can you assign this issue to me?

**Comment by kgryte** [comment]
Thanks for volunteering to work on this @Ut-the-pro. Please feel free to submit a PR implementing this feature.
