### ISSUE TITLE
[RFC]: add `@stdlib/array/base/count-same-value-zero`

### ISSUE THREAD

**Issue by kgryte** [stdlib-js/stdlib#1326]
### Description

This RFC proposes adding the package `@stdlib/array/base/count-same-value-zero`.

The package should be structured similarly to [`@stdlib/array/base/count-truthy`](https://github.com/stdlib-js/stdlib/tree/64931c5fdb4abc3a339b619658d3b5acc089e556/lib/node_modules/%40stdlib/array/base/count-truthy).

The package should expose an API having the same signature as `countTruthy`, with the addition of a `value` argument.

```javascript
function countSameValueZero( x, value ) {...}
```

Internally, the package should use [`@stdlib/assert/is-same-value-zero`](https://github.com/stdlib-js/stdlib/tree/64931c5fdb4abc3a339b619658d3b5acc089e556/lib/node_modules/%40stdlib/assert/is-same-value-zero) to test whether an element `x[i]` is equal to a specified `value`.

Package: `@stdlib/array/base/count-same-value-zero`
Alias: `countSameValueZero`

### Related Issues

Related issues #1324, #1325.

### Questions

No.

### Other

No.

### Checklist

- [X] I have read and understood the [Code of Conduct](https://github.com/stdlib-js/stdlib/blob/develop/CODE_OF_CONDUCT.md).
- [X] Searched for existing issues and pull requests.
- [X] The issue name begins with `RFC:`.

**Comment by TheNourhan** [comment]
I want to work on this

**Comment by kgryte** [comment]
@TheNourhan Please first work on getting https://github.com/stdlib-js/stdlib/pull/1350 merged before moving on to other issues.

**Comment by AgPriyanshu18** [comment]
@kgryte I have understood this issue and would like to work on it.Please assign this to me.

**Comment by kgryte** [comment]
Thanks for volunteering to work on this @AgPriyanshu18. Please feel free to submit a PR implementing this feature.
