### ISSUE TITLE
[RFC]: add `@stdlib/array/base/join`

### ISSUE THREAD

**Issue by kgryte** [stdlib-js/stdlib#1327]
### Description

This RFC proposes adding the package `@stdlib/array/base/join`.

The package should have a structure similar to [`@stdlib/array/base/slice`](https://github.com/stdlib-js/stdlib/tree/64931c5fdb4abc3a339b619658d3b5acc089e556/lib/node_modules/%40stdlib/array/base/slice) and should similarly check for the existence of a `join` method. If not present, the function should manually construct the output string and similarly treat `null` and `undefined` as an empty string (see [MDN](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/join#description)).

```javascript
function join( x, separator ) {...}
```

The `separator` argument should be required.

Package: `@stdlib/array/base/join`
Alias: `join`.

### Related Issues

None.

### Questions

No.

### Other

No.

### Checklist

- [X] I have read and understood the [Code of Conduct](https://github.com/stdlib-js/stdlib/blob/develop/CODE_OF_CONDUCT.md).
- [X] Searched for existing issues and pull requests.
- [X] The issue name begins with `RFC:`.

**Comment by prasadf18** [comment]
hey ! @kgryte  i want to work on this issue , can you please assign this to me.

**Comment by kgryte** [comment]
Thanks for volunteering to work on this, @prasad-1803. Please feel free to submit a PR implementing this feature.

**Comment by adityacodes30** [comment]
It has been a while @prasad-1803,  if you're not working on this one perhaps i could take it up ?
