### ISSUE TITLE
[RFC]: add `@stdlib/array/base/with`

### ISSUE THREAD

**Issue by kgryte** [stdlib-js/stdlib#1328]
### Description

This RFC proposes adding the package `@stdlib/array/base/with`.

This package should follow the same structure as [`@stdlib/array/base/at`](https://github.com/stdlib-js/stdlib/tree/64931c5fdb4abc3a339b619658d3b5acc089e556/lib/node_modules/%40stdlib/array/base/at) and be the functional equivalent of [`Array.prototype.with()`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/with).

As with `at`, the function should check whether a provided input array has a `with` method. If the method does not exist, the function should perform a manual copy and assignment.

```javascript
function with( x, index, value ) {...}
```

Package: `@stdlib/array/base/with`
Alias: `with`

### Related Issues

None.

### Questions

No.

### Other

No.

### Checklist

- [X] I have read and understood the [Code of Conduct](https://github.com/stdlib-js/stdlib/blob/develop/CODE_OF_CONDUCT.md).
- [X] Searched for existing issues and pull requests.
- [X] The issue name begins with `RFC:`.

**Comment by BhaveshP443** [comment]
@kgryte i want to work on this issue.

**Comment by Pratik772846** [comment]
@kgryte I have understood this issue and would like to work on it. Can you assign it to me?

**Comment by kgryte** [comment]
Thanks for volunteering to work on this @Pratik772846. Please feel to submit a PR implementing this feature.
