### ISSUE TITLE
[RFC]: improve README examples in namespace packages

### ISSUE THREAD

**Issue by kgryte** [stdlib-js/stdlib#1329]
### Description

This RFC proposes improving README examples in namespace packages. Currently, namespace package READMEs only include minimal examples which are not particularly informative and do not showcase namespace functionality. For example, see [`@stdlib/array`](https://github.com/stdlib-js/stdlib/tree/64931c5fdb4abc3a339b619658d3b5acc089e556/lib/node_modules/%40stdlib/array#examples).

Historically, namespace examples were not given much effort due to the rapidly changing nature of the project; however, now that development and organization has settled, it would be good to revisit these packages and add proper examples to better communicate to users how to use namespace contents.

For those wanting to contribute to this issue, you can use the following steps:

- Browse through the stdlib codebase and identify namespaces having only minimal README examples (e.g., start from the root directory: https://github.com/stdlib-js/stdlib/tree/64931c5fdb4abc3a339b619658d3b5acc089e556/lib/node_modules/%40stdlib)
- Leave a message on this issue letting project maintainers know that you are planning on updating a particular namespace README.
- After identifying a namespace README needing updates, update the README for that namespace and that namespace only and open a PR.
- When updating the README, examples should follow existing project conventions (e.g., ES5).
- Examples may `require` functionality from other packages to help make examples more interesting.

### Related Issues

None.

### Questions

No.

### Other

No.

### Checklist

- [X] I have read and understood the [Code of Conduct](https://github.com/stdlib-js/stdlib/blob/develop/CODE_OF_CONDUCT.md).
- [X] Searched for existing issues and pull requests.
- [X] The issue name begins with `RFC:`.

**Comment by vr-varad** [comment]
Added new example for namespace packages #1338

**Comment by vr-varad** [comment]
https://github.com/stdlib-js/stdlib/pull/1338#issue-2147547365  changed the namespace example.

**Comment by vr-varad** [comment]
https://github.com/stdlib-js/stdlib/pull/1349 added new examples

**Comment by kgryte** [comment]
@vr-varad I replied on #1349. If you are going to update namespace examples, please read the OP above. We are **not** seeking changes to the main project README. We are seeking improvements to namespace package READMEs.

**Comment by Tufailahmed-Bargir** [comment]
i am interested in doing  this , please assign this to me

**Comment by kgryte** [comment]
@Tufailahmed-Bargir We've since added individual issues for both documentation and code contributions. I suggest searching for another individual issue to pursue.
