### ISSUE TITLE
[RFC]: add `@stdlib/math/iter/sequences/tribonacci`

### ISSUE THREAD

**Issue by kgryte** [stdlib-js/stdlib#1331]
### Description

This RFC proposes adding the package `@stdlib/math/iter/sequences/tribonacci`.

The package should be similar in structure as [`@stdlib/math/iter/sequences/fibonacci`](https://github.com/stdlib-js/stdlib/tree/64931c5fdb4abc3a339b619658d3b5acc089e556/lib/node_modules/%40stdlib/math/iter/sequences/fibonacci).

Package: `@stdlib/math/iter/sequences/tribonacci`
Alias: `iterTribonacciSeq`

### Related Issues

None.

### Questions

No.

### Other

[Tribonacci sequence](https://en.wikipedia.org/wiki/Generalizations_of_Fibonacci_numbers#Tribonacci_numbers)

### Checklist

- [X] I have read and understood the [Code of Conduct](https://github.com/stdlib-js/stdlib/blob/develop/CODE_OF_CONDUCT.md).
- [X] Searched for existing issues and pull requests.
- [X] The issue name begins with `RFC:`.

**Comment by PraneGIT** [comment]
hey @kgryte  I have located and studied the structure of [@stdlib/math/iter/sequences/fibonacci](https://github.com/stdlib-js/stdlib/tree/64931c5fdb4abc3a339b619658d3b5acc089e556/lib/node_modules/%40stdlib/math/iter/sequences/fibonacci).

I also have studied about [Tribonacci sequence](https://en.wikipedia.org/wiki/Generalizations_of_Fibonacci_numbers#Tribonacci_numbers) , 
I can add the package `@stdlib/math/iter/sequences/tribonacci`, similar to the fibonacci package
Can I work on this ?

**Comment by kgryte** [comment]
Thanks for volunteering to work on this, @PraneGIT. Please feel free to submit a PR implementing this feature.
