### ISSUE TITLE
[RFC]: add `@stdlib/assert/is-same-date-object`

### ISSUE THREAD

**Issue by kgryte** [stdlib-js/stdlib#1337]
### Description

This RFC proposes adding the package `@stdlib/assert/is-same-date-object` to test whether two input values resolve to the same `Date` value.

The package should be similar in structure to [`@stdlib/assert/is-same-array`](https://github.com/stdlib-js/stdlib/tree/64931c5fdb4abc3a339b619658d3b5acc089e556/lib/node_modules/%40stdlib/assert/is-same-array), but should validate whether both arguments are `Date` objects and both resolve to the same timestamp.

```javascript
function isSameDateObject( v1, v2 ) { ... }
```

Package: `@stdlib/assert/is-same-date-object`
Alias: `isSameDateObject`

### Related Issues

None.

### Questions

No.

### Other

No.

### Checklist

- [X] I have read and understood the [Code of Conduct](https://github.com/stdlib-js/stdlib/blob/develop/CODE_OF_CONDUCT.md).
- [X] Searched for existing issues and pull requests.
- [X] The issue name begins with `RFC:`.

**Comment by Pushpendra766** [comment]
I would like to work on this issue, please assign.

**Comment by Planeshifter** [comment]
@Pushpendra766 Just did. Thank you for your interest in working on this issue; looking forward to your contribution!

**Comment by adityacodes30** [comment]
im working on this is well ~ almost done with it

**Comment by kgryte** [comment]
@adityacodes30 To avoid duplicate work, it would be best to first communicate with core devs before working on an issue so we can ensure that work is fairly distributed. If @Pushpendra766 is already working on this, may be good to choose another issue.

**Comment by adityacodes30** [comment]
i understand, i started working on this one ~12-13 hours ago - lapse on my part that i did not communicate, I am almost done with the implementation

 @Pushpendra766 if you haven't done much work could i please take this one up ?

**Comment by Pushpendra766** [comment]
As @adityacodes30 have already worked on this issue, I am unassigning myself from this issue.
