### ISSUE TITLE
random-base-uniform 0.2.0 depends on random-base 0.1.1, causing installation of duplicate versions of dependencies

### ISSUE THREAD

**Issue by ellis** [stdlib-js/stdlib#1342]
### Description

I installed the following two packages, `@stdlib/random-base-uniform` and `@stdlib/stats-base-dists-binomial-pmf`, and ended up with both v0.2 and v0.1 versions of most dependencies.

My first guess is that [package.json](https://github.com/stdlib-js/random-base-uniform/blob/main/package.json) has the wrong version number in the dependencies of `random-base`:

```
"@stdlib/random-base": "^0.1.1",
```

### Related Issues

Related issues #1199

### Reproduction

```shell
I installed the following two packages:


pnpm add @stdlib/random-base-uniform @stdlib/stats-base-dists-binomial-pmf
```

### Expected Results

```shell
v0.2 packages installed, rather than both v0.2 and v0.2
```

### Actual Results

```shell
This results in the installation of lots of duplicates packages, e.g., here's a tiny excerpt from node_modules:


node_modules/.pnpm/@stdlib+math-base-special-sinpi@0.1.0
node_modules/.pnpm/@stdlib+math-base-special-sinpi@0.2.0
node_modules/.pnpm/@stdlib+math-base-special-sqrt@0.1.1
node_modules/.pnpm/@stdlib+math-base-special-sqrt@0.2.0
node_modules/.pnpm/@stdlib+math-base-special-tan@0.1.0
node_modules/.pnpm/@stdlib+math-base-special-trunc@0.1.1
node_modules/.pnpm/@stdlib+math-base-special-trunc@0.2.0
```
```


### Version

0.2.0

### Environments

Node.js

### Browser Version

_No response_

### Node.js / npm Version

v20.11.0

### Platform

Linux

### Checklist

- [X] Read and understood the [Code of Conduct](https://github.com/stdlib-js/stdlib/blob/develop/CODE_OF_CONDUCT.md).
- [X] Searched for existing issues and pull requests.

**Comment by kgryte** [comment]
Thanks for reporting this @ellis. We know the issue and will work on getting a patch out shortly. We'll circle back once we have an update.

**Comment by kgryte** [comment]
As mentioned in https://github.com/stdlib-js/stdlib/issues/1199#issuecomment-2010950250, I believe this issue has been resolved. Closing...

cc @Planeshifter

**Comment by ellis** [comment]
Thanks @kgryte , I updated the dependency and the issue is fixed on my end too.

**Comment by kgryte** [comment]
@ellis Great! And thanks for circling back!
