### ISSUE TITLE
[RFC]: add `@stdlib/assert/is-nonpositive-finite`

### ISSUE THREAD

**Issue by kgryte** [stdlib-js/stdlib#1343]
### Description

This RFC proposes adding the package `@stdlib/assert/is-nonpositive-finite`.

The package should be similar in structure to [`@stdlib/assert/is-nonpositive-number`](https://github.com/stdlib-js/stdlib/tree/develop/lib/node_modules/%40stdlib/assert/is-nonpositive-number) and should have a similar implementation except negative infinity should evaluate to `false`.

```javascript
function isNonPositiveFinite( value ) { ... }
```

Package: `@stdlib/assert/is-nonpositive-finite`
Alias: `isNonPositiveFinite`

### Related Issues

None.

### Questions

No.

### Other

No.

### Checklist

- [X] I have read and understood the [Code of Conduct](https://github.com/stdlib-js/stdlib/blob/develop/CODE_OF_CONDUCT.md).
- [X] Searched for existing issues and pull requests.
- [X] The issue name begins with `RFC:`.

**Comment by AuenKr** [comment]
I would like to work on this, can I be assigned this issue?

**Comment by dainik10** [comment]
Heyy @kgryte I think I have figured this out, please assign me this task. Thank You.

**Comment by dainik10** [comment]
function isNonPositiveFinite(value) {
    return typeof value === 'number' && !isNaN(value) && value <= 0 && isFinite(value);
}
This should almost work and have another solution as well

**Comment by kgryte** [comment]
@dainik10 The solution outline should work; however, it is not likely to be accepted as is. Instead, you should use stdlib functions, not built-in globals. E.g., see https://github.com/stdlib-js/stdlib/blob/develop/lib/node_modules/%40stdlib/assert/is-nonpositive-number/lib/primitive.js.

Instead of `isFinite`, you can test directly against `@stdlib/constants/float64/ninf`.

**Comment by kgryte** [comment]
I'll go ahead and assign you this task. Please feel free to submit a PR.
