### ISSUE TITLE
[RFC]: add `@stdlib/assert/is-nonnegative-finite`

### ISSUE THREAD

**Issue by kgryte** [stdlib-js/stdlib#1344]
### Description

This RFC proposes adding the package `@stdlib/assert/is-nonnegative-finite`.

The package should be similar in structure to [`@stdlib/assert/is-nonnegative-number`](https://github.com/stdlib-js/stdlib/tree/develop/lib/node_modules/%40stdlib/assert/is-nonnegative-number) and should have a similar implementation except positive infinity should evaluate to `false`.

```javascript
function isNonNegativeFinite( value ) { ... }
```

Package: `@stdlib/assert/is-nonnegative-finite`
Alias: `isNonNegativeFinite`

### Related Issues

None.

### Questions

No.

### Other

No.

### Checklist

- [X] I have read and understood the [Code of Conduct](https://github.com/stdlib-js/stdlib/blob/develop/CODE_OF_CONDUCT.md).
- [X] Searched for existing issues and pull requests.
- [X] The issue name begins with `RFC:`.

**Comment by marsian83** [comment]
Hi, I would like to work on this, can I be assigned this issue?

**Comment by Planeshifter** [comment]
@marsian83 Just assigned you; looking forward to your contribution!
