### ISSUE TITLE
[RFC]: add `@stdlib/assert/is-negative-finite`

### ISSUE THREAD

**Issue by kgryte** [stdlib-js/stdlib#1345]
### Description

This RFC proposes adding the package `@stdlib/assert/is-negative-finite`.

The package should be similar in structure to [`@stdlib/assert/is-negative-number`](https://github.com/stdlib-js/stdlib/tree/develop/lib/node_modules/%40stdlib/assert/is-negative-number) and should have a similar implementation except negative infinity should evaluate to `false`.

```javascript
function isNegativeFinite( value ) { ... }
```

Package: `@stdlib/assert/is-negative-finite`
Alias: `isNegativeFinite`

### Related Issues

None.

### Questions

No.

### Other

No.

### Checklist

- [X] I have read and understood the [Code of Conduct](https://github.com/stdlib-js/stdlib/blob/develop/CODE_OF_CONDUCT.md).
- [X] Searched for existing issues and pull requests.
- [X] The issue name begins with `RFC:`.

**Comment by adityacodes30** [comment]
looks very similar to #1346 , would love to take this up as well - please assign

**Comment by Planeshifter** [comment]
@adityacodes30 Sounds good, thanks for working on this!

**Comment by kgryte** [comment]
@adityacodes30 Please only work on one issue at a time. It is important that you first get each PR merged, before moving onto other issues.

**Comment by gunjjoshi** [comment]
Can you please assign this to me ? I have understood the project structure.

**Comment by kgryte** [comment]
Thank you for volunteering to work on this @gunjjoshi. Please feel free to submit a PR implementing this feature.

**Comment by adityacodes30** [comment]
alright , no problem at all @kgryte  took this one up as well because it seemed quite similar to #1346 which i am implementing 

@gunjjoshi let me know if you need any help

**Comment by gunjjoshi** [comment]
Thanks @adityacodes30, for now I am almost done with this one, will be making a PR in a while.
