### ISSUE TITLE
[RFC]: add `@stdlib/assert/is-ragged-nested-array`

### ISSUE THREAD

**Issue by kgryte** [stdlib-js/stdlib#1347]
### Description

This RFC proposes adding the package `@stdlib/assert/is-ragged-nested-array`.

The package should be similar in structure to [`@stdlib/assert/is-array-like-object`](https://github.com/stdlib-js/stdlib/blob/develop/lib/node_modules/%40stdlib/assert/is-array-like-object/lib/main.js).

A ragged nested array is a nested array having inner dimensions of varying lengths. E.g.,

```javascript
[
  [ 1, 2, 3 ],
  [ 4, 5 ]
]
```

is a ragged nested array.

```javascript
function isRaggedNestedArray( value ) { ... }
```

Package: `@stdlib/assert/is-ragged-nested-array`
Alias: `isRaggedNestedArray`

### Related Issues

None.

### Questions

- Should this package only check for two-dimensional ragged arrays (i.e., an array of arrays)? Or should it recurse and check at each potential inner nested array depth?

**Answer**: we should only support two-dimensional nested arrays.

- Should we require strict `Array` instances or are array-like objects okay?

**Answer**: we should not use `isArray`, but `isArrayLikeObject`. In order for a value to be a nested ragged array, the input value must be an array-like object and each element must be an array-like object and at least one element must have a length which differs from another element.

### Other

No.

### Checklist

- [X] I have read and understood the [Code of Conduct](https://github.com/stdlib-js/stdlib/blob/develop/CODE_OF_CONDUCT.md).
- [X] Searched for existing issues and pull requests.
- [X] The issue name begins with `RFC:`.

**Comment by performant23** [comment]
Hey @kgryte, I can take this up and have reviewed the feature and also the package, 'is-array-like-object'! Could you please assign me this issue?

**Comment by kgryte** [comment]
Thanks for volunteering to work on this, @performant23. Please feel free to submit a PR implementing this feature.

**Comment by performant23** [comment]
Hello @kgryte, hope you're doing well! Just to confirm and ensure I don't take any conditions for granted, when we say an array is a ragged nested array, are we considering it the exclusive sense (with only arrays having different lengths are allowed or do we allow some or all the arrays inside the main array to have same lengths)?

Edit: Actually nevermind, got it! The description says, "at least one element must have a length which differs from another element" - I must have overlooked

**Comment by Ruwaid884** [comment]
@kgryte i want to contribute to this issue could you also assign me this please

**Comment by performant23** [comment]
Hey, @Ruwaid884 , actually I'm done with the feature and am just testing it.

**Comment by Ruwaid884** [comment]
@performant23, okay sounds nice
 but i feel it is a good first issue this will give me the understanding of the code how it is being written by the developers. i will also be working on this issue just to get grasp of the codebase.

**Comment by kgryte** [comment]
@performant23 Feel free to open a draft PR.

@Ruwaid884 You can also check out other "good first issues" which can be found on the issue tracker.
