### ISSUE TITLE
Missing Success Message Upon Initialization Completion

### ISSUE THREAD

**Issue by gunjjoshi** [stdlib-js/stdlib#1400]
### Description

This RFC proposes :

Upon successful initialization by the `make init` command, nothing is displayed on the console. Error messages are displayed only when there are errors. If everything goes right, nothing is displayed. This might make new contributors a bit confused, whether they are on the right track to set up the project or not.

### Related Issues

Related issues # , # , and # .

### Questions

No.

### Other

A success message can be displayed once the initialization is successful.

### Checklist

- [X] I have read and understood the [Code of Conduct](https://github.com/stdlib-js/stdlib/blob/develop/CODE_OF_CONDUCT.md).
- [X] Searched for existing issues and pull requests.
- [ ] The issue name begins with `RFC:`.

**Comment by gunjjoshi** [comment]
I would like to be assigned for this issue.

**Comment by Planeshifter** [comment]
Sounds good, thanks for looking into this @gunjjoshi!
