### ISSUE TITLE
RFC: Add cis(z) function, exp(iz)

### ISSUE THREAD

**Issue by rreusser** [stdlib-js/stdlib#142]
## Checklist

> Please ensure the following tasks are completed before filing an issue.

-   [x] Read and understood the [Code of Conduct][code-of-conduct].
-   [x] Searched for existing issues and pull requests.
-   [x] If this is a general question, searched the [FAQ][faq] for an existing answer.
-   [x] If this is a feature request, the issue name begins with `RFC:`.

## Description

> Description of the issue (or feature request).

Add [cis](https://en.wikipedia.org/wiki/Cis_(mathematics)) function. Usage would be:

- `cis(x)`: returns `[cos(x), sin(x)]`
- `cis([0, 0], x)`: returns `[cos(x), sin(x)]` in-place
- `cis(x, y)`: returns `[exp(-y) cos(x), exp(-y) sin(x)]`
- `cis([0, 0], x, y)`: returns `[exp(-y) cos(x), exp(-y) sin(x)]` in-place

Note for the last two cases: `exp(ix)` is generalized to complex z, `exp(iz)`. If `z = x + iy`, then this is `exp(i (x + iy))` = `exp(ix - y)` = `exp(-y) * (cos(x) + i sin(x))`, hence the `-y` in the above formulas.

## Other

> Any other information relevant to this issue (or feature request)? This may include screenshots, references, stack traces, sample output, and/or implementation notes.

- [Julia implementation](https://github.com/JuliaLang/julia/blob/0df3f7dc0280525349ae23e3ac4fc96621befc50/base/complex.jl#L459-L480)
- [Wikipedia entry](https://en.wikipedia.org/wiki/Cis_(mathematics))

[code-of-conduct]: https://github.com/stdlib-js/stdlib/blob/develop/CODE_OF_CONDUCT.md

[faq]: https://github.com/stdlib-js/stdlib/blob/develop/FAQ.md

**Comment by kgryte** [comment]
Should we make the interface polymorphic or have two separate implementations:

```
@stdlib/math/base/special/cis
@stdlib/math/base/complex/cis
```
where the latter is aliased `ccis`?

**Comment by rreusser** [comment]
Yeah, it's unambiguous but I wasn't sure whether it was desirable. Perhaps `base` is not the place for polymorphic implementations. It feels just slightly weird to have `cis` in `special` though since it's definitely for complex numbers.

(Though really, `cis(x)` is just shorthand for `cis(x, 0)` making it slightly less polymorphic-feeling.)

**Comment by kgryte** [comment]
Then, for now, maybe we just focus on the complex use case and put in `base/complex`.

**Comment by rreusser** [comment]
That seems valid. If `imag === 0.0`, then we can avoid the `exp` so it's not like it's wasting too many cpu cycles.

**Comment by kgryte** [comment]
Awesome! Sounds good!
