### ISSUE TITLE
[RFC]: Add C implementation for `@stdlib/math/base/special/logaddexp`

### ISSUE THREAD

**Issue by Pranavchiku** [stdlib-js/stdlib#1432]
### Description

This RFC proposes adding native C implementation for [`@stdlib/math/base/special/logaddexp`](https://github.com/stdlib-js/stdlib/blob/develop/lib/node_modules/%40stdlib/math/base/special/logaddexp/).

```c
double stdlib_base_logaddexp( const double x, const double y );
```

### Related Issues

None.

### Questions

No.

### Other

No.

### Checklist

- [X] I have read and understood the [Code of Conduct](https://github.com/stdlib-js/stdlib/blob/develop/CODE_OF_CONDUCT.md).
- [X] Searched for existing issues and pull requests.
- [X] The issue name begins with `RFC:`.

**Comment by aman-095** [comment]
Hey @kgryte @Pranavchiku I would like to work on this issue.
