### ISSUE TITLE
[RFC]: Add C implementation for `@stdlib/math/base/special/max`

### ISSUE THREAD

**Issue by Pranavchiku** [stdlib-js/stdlib#1433]
### Description

This RFC proposes adding native C implementation for [`@stdlib/math/base/special/max`](https://github.com/stdlib-js/stdlib/blob/develop/lib/node_modules/%40stdlib/math/base/special/max/).

```c
double stdlib_base_max( const double x, const double y );
```

### Related Issues

None.

### Questions

No.

### Other

No.

### Checklist

- [X] I have read and understood the [Code of Conduct](https://github.com/stdlib-js/stdlib/blob/develop/CODE_OF_CONDUCT.md).
- [X] Searched for existing issues and pull requests.
- [X] The issue name begins with `RFC:`.

**Comment by Shashankss1205** [comment]
Please assign it to me @Pranavchiku , as my previous PR has been made.

**Comment by Ccivam** [comment]
@Pranavchiku I have understood the issue.Can you please assign it to me

**Comment by rajutkarsh07** [comment]
@Planeshifter @kgryte I have understood this issue, I would like to work on it Please assign this to me

**Comment by Shashankss1205** [comment]
I have added the PR #1459 for this Issue. Kindly review it @Pranavchiku
