### ISSUE TITLE
[RFC]: refactor `blas/ext/base/dfill` to follow current project conventions

### ISSUE THREAD

**Issue by kgryte** [stdlib-js/stdlib#1434]
### Description

This RFC proposes refactoring [`@stdlib/blas/ext/base/dfill`](https://github.com/stdlib-js/stdlib/tree/1096686e16dd4515a7aaa5bdc35ff5803ec0349f/lib/node_modules/%40stdlib/blas/ext/base/dfill) to follow current project conventions.

These conventions are outlined in more detail in https://github.com/stdlib-js/stdlib/issues/788. Namely, we want to migrate from C++ add-on interfaces to C add-on interfaces and then make various style and simplification changes. 

Some example commits which perform most, if not all, of the requested changes include https://github.com/stdlib-js/stdlib/commit/d66d80cfcbab1da95cb5ae8cfae4a1fc4c5129d1 (saxpy),  https://github.com/stdlib-js/stdlib/commit/3c82fe7b6c0f9fd6ef02c86d6e2024d708ac8c14 (cswap), and https://github.com/stdlib-js/stdlib/commit/5b15c9675be434c0e11b1ec1e1f78d7b089abbcd (dasum).

### Related Issues

Related issues #788, #1152.

### Questions

No.

### Other

No.

### Checklist

- [X] I have read and understood the [Code of Conduct](https://github.com/stdlib-js/stdlib/blob/develop/CODE_OF_CONDUCT.md).
- [X] Searched for existing issues and pull requests.
- [X] The issue name begins with `RFC:`.

**Comment by Snehil-Shah** [comment]
@kgryte Can I  work on this?

**Comment by kgryte** [comment]
Thanks for volunteering to work on this @Snehil-Shah. Feel free to submit a PR implementing the refactoring.
