### ISSUE TITLE
[RFC]: Add C implementation for `@stdlib/math/base/special/ellipe`

### ISSUE THREAD

**Issue by Pranavchiku** [stdlib-js/stdlib#1444]
### Description

This RFC proposes adding native C implementation for [`@stdlib/math/base/special/ellipe`](https://github.com/stdlib-js/stdlib/blob/develop/lib/node_modules/%40stdlib/math/base/special/ellipe/).

```c
double stdlib_base_ellipe( const double x );
```

### Related Issues

None.

### Questions

No.

### Other

Refer: https://github.com/stdlib-js/stdlib/pull/769

### Checklist

- [X] I have read and understood the [Code of Conduct](https://github.com/stdlib-js/stdlib/blob/develop/CODE_OF_CONDUCT.md).
- [X] Searched for existing issues and pull requests.
- [X] The issue name begins with `RFC:`.

**Comment by bad-in-coding** [comment]
@Pranavchiku I would like to work on this. Can you assign it to me.

**Comment by Pranavchiku** [comment]
Hi @Ut-the-pro I will wait till your PR #1445 gets merged.

**Comment by Pranavchiku** [comment]
Ahh this is duplicate of #772, I am sorry will have to close this.
