### ISSUE TITLE
[RFC]: Add C implementation for `@stdlib/math/base/special/minabs`

### ISSUE THREAD

**Issue by aman-095** [stdlib-js/stdlib#1449]
### Description

This RFC proposes adding native C implementation for [`@stdlib/math/base/special/minabs`](https://github.com/stdlib-js/stdlib/blob/develop/lib/node_modules/%40stdlib/math/base/special/minabs/)

```c
double stdlib_base_minabs( const double x, const double y );
```

### Related Issues

None.

### Questions

No.

### Other

No.

### Checklist

- [X] I have read and understood the [Code of Conduct](https://github.com/stdlib-js/stdlib/blob/develop/CODE_OF_CONDUCT.md).
- [X] Searched for existing issues and pull requests.
- [X] The issue name begins with `RFC:`.

**Comment by aman-095** [comment]
I have changes ready for this will open PR once #1443 is merged.

**Comment by Pranavchiku** [comment]
Thanks for volunteering, we appreciate it!
