### ISSUE TITLE
[RFC]: Add C implementation for `@stdlib/math/base/special/log`

### ISSUE THREAD

**Issue by aman-095** [stdlib-js/stdlib#1453]
### Description

This RFC proposes adding native C implementation for [`@stdlib/math/base/special/log`](https://github.com/stdlib-js/stdlib/blob/develop/lib/node_modules/%40stdlib/math/base/special/log/)

``` c
double stdlib_base_log( const double x, const double b );
```

### Related Issues

None. 

### Questions

No.

### Other

No.

### Checklist

- [X] I have read and understood the [Code of Conduct](https://github.com/stdlib-js/stdlib/blob/develop/CODE_OF_CONDUCT.md).
- [X] Searched for existing issues and pull requests.
- [X] The issue name begins with `RFC:`.

**Comment by aman-095** [comment]
I have PR ready for the issue and will push in a while.

**Comment by Pranavchiku** [comment]
Thanks for volunteering!
