### ISSUE TITLE
Docs: Time constants are generalisations, add disclaimer

### ISSUE THREAD

**Issue by Glutnix** [stdlib-js/stdlib#146]
## Checklist

> Please ensure the following tasks are completed before filing an issue.

-   [x] Read and understood the [Code of Conduct][code-of-conduct].
-   [x] Searched for existing issues and pull requests.
-   [x] If this is a general question, searched the [FAQ][faq] for an existing answer.
-   [x] If this is a feature request, the issue name begins with `RFC:`.

## Description

The time constants and calculation methods are useful, but are by no means accurate. They may reinforce [falsehoods programmers believe about time](http://infiniteundo.com/post/25326999628/falsehoods-programmers-believe-about-time). I suggest adding a disclaimer to the documentation on each constant and method about their assumed accuracy across timezones, leap-seconds, leap-years, and daylight savings boundaries.

Suggestion for the warning:
> Warning: This method|constant uses a value|calculation that is a generalisation. It does not take into consideration timezones, leap seconds, leap years, daylight savings boundaries or other complications with time and dates.

## Questions

> Any questions for reviewers?

No.

[code-of-conduct]: https://github.com/stdlib-js/stdlib/blob/develop/CODE_OF_CONDUCT.md

[faq]: https://github.com/stdlib-js/stdlib/blob/develop/FAQ.md

**Comment by kgryte** [comment]
@Glutnix This is a reasonable request. We will work on adding disclaimers, and, once done, I'll circle back and close this issue.
