### ISSUE TITLE
[RFC]: Add C implementation for `@stdlib/math/base/special/maxabs`

### ISSUE THREAD

**Issue by Shashankss1205** [stdlib-js/stdlib#1460]
### Description

This RFC proposes adding native C implementation for [`@stdlib/math/base/special/maxabs`](https://github.com/stdlib-js/stdlib/tree/develop/lib/node_modules/%40stdlib/math/base/special/maxabs).

```c
double stdlib_base_maxabs( const double x, const double y );
```

### Related Issues

Related issues #1433, #1449.

### Questions

No.

### Other

No.

### Checklist

- [X] I have read and understood the [Code of Conduct](https://github.com/stdlib-js/stdlib/blob/develop/CODE_OF_CONDUCT.md).
- [X] Searched for existing issues and pull requests.
- [X] The issue name begins with `RFC:`.

**Comment by Pranavchiku** [comment]
@Shashankss1205 can you please refer to #1449 and populate description well. Thanks for opening this.  Also mark related issue as #1433.

**Comment by rajutkarsh07** [comment]
@Pranavchiku @Planeshifter @kgryte I have understood this issue, I want to work on it. So please assign this issue to me

**Comment by kgryte** [comment]
@Shashankss1205 Are you planning on implementing this, given that you opened the issue?

**Comment by Shashankss1205** [comment]
Yes I am already working on this @kgryte . Please assign it to me.

**Comment by Shashankss1205** [comment]
> @Shashankss1205 can you please refer to #1449 and populate description well. Thanks for opening this. Also mark related issue as #1433.

I didn't understand about "populating the description", I just kept it the way other similar issues were made. Please suggest the required changes that I should make.

**Comment by kgryte** [comment]
@Shashankss1205 I've updated the OP.

**Comment by Shashankss1205** [comment]
> @Shashankss1205 I've updated the OP.

Thank you @kgryte for the guiding help.

**Comment by Shashankss1205** [comment]
Please Review the PR and suggest the needful changes @kgryte .
