### ISSUE TITLE
Please consider reducing the number of Mac jobs created on Travis CI

### ISSUE THREAD

**Issue by BanzaiMan** [stdlib-js/stdlib#147]
## Checklist

> Please ensure the following tasks are completed before filing an issue.

-   [x] Read and understood the [Code of Conduct][code-of-conduct].
-   [x] Searched for existing issues and pull requests.
-   [x] If this is a general question, searched the [FAQ][faq] for an existing answer.
-   [ ] If this is a feature request, the issue name begins with `RFC:`.

## Description

> Description of the issue (or feature request).

Each build request in this repository currently creates 48 jobs on Travis CI. It is also very actively developed, and each day we see 30 to 40 commits, resulting in upwards of 2000 builds per day.

While we appreciate your using our service, this is a severe strain on our resources, and it impacts other users on our system.

Please consider reducing the number of Mac jobs to an essential minimum. If you would like to maintain this level of usage, please let us know at the email address below, so that we can arrange special queue and payment.

Thank you.

## Related Issues

> Does this issue (or feature request) have any related issues?

None.

## Questions

> Any questions for reviewers?

If you would like to discuss this further in private, you can email support@travis-ci.com.

**Comment by kgryte** [comment]
Temporarily disabled builds on MacOS until we are able to determine an effective strategy for reducing build times (and loads).

**Comment by BanzaiMan** [comment]
Thanks for your understanding.

**Comment by kgryte** [comment]
Thanks for providing the service and for all the work that TravisCI does!
