### ISSUE TITLE
RFC: 2d Gaussian Kernel Density Estimation

### ISSUE THREAD

**Issue by Planeshifter** [stdlib-js/stdlib#150]
## Checklist

> Please ensure the following tasks are completed before filing an issue.

-   [x] Read and understood the [Code of Conduct][code-of-conduct].
-   [x] Searched for existing issues and pull requests.
-   [x] If this is a general question, searched the [FAQ][faq] for an existing answer.
-   [x] If this is a feature request, the issue name begins with `RFC:`.

## Description

> Description of the issue (or feature request).

This RFC proposes adding a function for calculating a two-dimensional (Gaussian) kernel density estimate for bivariate data. The [kde2d][kde2d] function from the R package `MASS` might serve as an inspiration. The function would internally evaluate the density for elements of a square grid determined by the ranges of the input points. It could return an `ndarray` with the estimated densities, with rows corresponding to `x`-values and columns to `y`-values. One use-case of this function would be in creating heat maps for two quantitative variables.

A potential place for the function would be `@stdlib/math/stats/kde2d`.

## Related Issues

> Does this issue (or feature request) have any related issues?

No.

## Questions

> Any questions for reviewers?

No.

## Other

> Any other information relevant to this issue (or feature request)? This may include screenshots, references, stack traces, sample output, and/or implementation notes.

No.

[code-of-conduct]: https://github.com/stdlib-js/stdlib/blob/develop/CODE_OF_CONDUCT.md

[faq]: https://github.com/stdlib-js/stdlib/blob/develop/FAQ.md

[kde2d]: https://stat.ethz.ch/R-manual/R-devel/library/MASS/html/kde2d.html

**Comment by kgryte** [comment]
I think this functionality would be good to have. I would also be interested in a `1d` implementation `kde`, which could live as a separate package. Agreed on the pkgs location in `@stdlib/math/stats/kde2d`. May want to also consult the MATLAB function [ksdensity](https://www.mathworks.com/help/stats/ksdensity.html).
