### ISSUE TITLE
[RFC]: refactor `blas/ext/base/ssortins` to follow current project conventions

### ISSUE THREAD

**Issue by Planeshifter** [stdlib-js/stdlib#1538]
### Description

This RFC proposes refactoring [`@stdlib/blas/ext/base/ssortins`](https://github.com/stdlib-js/stdlib/tree/develop/lib/node_modules/%40stdlib/blas/ext/base/ssortins) to follow current project conventions.

These conventions are outlined in more detail in https://github.com/stdlib-js/stdlib/issues/788. Namely, we want to migrate from C++ add-on interfaces to C add-on interfaces and then make various style and simplification changes.

Some example commits which perform most, if not all, of the requested changes include https://github.com/stdlib-js/stdlib/commit/d66d80cfcbab1da95cb5ae8cfae4a1fc4c5129d1 (saxpy),  https://github.com/stdlib-js/stdlib/commit/3c82fe7b6c0f9fd6ef02c86d6e2024d708ac8c14 (cswap), and https://github.com/stdlib-js/stdlib/commit/5b15c9675be434c0e11b1ec1e1f78d7b089abbcd (dasum).

### Related Issues

Related issues #788, #1152.

### Questions

No.

### Other

No.

### Checklist

- [X] I have read and understood the [Code of Conduct](https://github.com/stdlib-js/stdlib/blob/develop/CODE_OF_CONDUCT.md).
- [X] Searched for existing issues and pull requests.
- [X] The issue name begins with `RFC:`.

**Comment by mayankkamboj47** [comment]
@Planeshifter Please assign this to me

**Comment by Planeshifter** [comment]
@mayankkamboj47 thanks for working on this!

**Comment by mayankkamboj47** [comment]
@Planeshifter In the file  `blas/base/ext/ssortins/benchmark/benchmark.mostly_sorted_few_uniques.js`, am I supposed to remove the use of `floor` ?  All the commits I saw so far replace the value of floor with just a literal, which isn't possible here. I'm also just wondering why we're removing floor. Also, if you'd like me to remove it, is this approach okay :   
```
x = <whatever expression>
x -= x%1
```

**Comment by aayush0325** [comment]
I've went through the given commits and the codebase for similar addons, I'd love to work on this issue.

**Comment by Planeshifter** [comment]
@aayush0325 Feel free to open a PR! Looking forward to your contribution.
