### ISSUE TITLE
[RFC]: improve README examples of `ndarray/base/napi` namespace

### ISSUE THREAD

**Issue by Planeshifter** [stdlib-js/stdlib#1587]
### Description

This RFC proposes to improve the [README examples](https://github.com/stdlib-js/stdlib/tree/develop/lib/node_modules/%40stdlib/ndarray/base/napi#examples) of the `ndarray/base/napi` namespace package. Currently, namespace package READMEs only include minimal examples which are not particularly informative and do not showcase namespace functionality.

Historically, namespace examples were not given much effort due to the rapidly changing nature of the project; however, now that development and organization has settled, it would be good to revisit these packages and add proper examples to better communicate to users how to use namespace contents.

For those wanting to contribute to this issue, you can use the following steps:

- Browse through the [contents](https://github.com/stdlib-js/stdlib/tree/develop/lib/node_modules/%40stdlib/ndarray/base/napi) of the `ndarray/base/napi` namespace and identify interesting functions and packages to showcase.
- Update the example code block in the "Examples" section of the README for the `ndarray/base/napi` namespace and open a PR.
- When updating the README, examples should follow existing project conventions (e.g., ES5).
- Examples may `require` functionality from other packages to help make examples more interesting.

### Related Issues

None.

### Questions

No.

### Other

No.

### Checklist

- [X] I have read and understood the [Code of Conduct](https://github.com/stdlib-js/stdlib/blob/develop/CODE_OF_CONDUCT.md).
- [X] Searched for existing issues and pull requests.
- [X] The issue name begins with `RFC:`.

**Comment by performant23** [comment]
Hello, I was just done with implementing an example for ndarray/base/napi. Since I've just started working with native add-ons, I just wanted to ask if there's any way to test C code in the repo itself (we could import the project externally and test  that way, but that would be a bit more time-taking). I have roughly sketched the example based on the source C files and header files but needed to debug and test.

```c
#include "stdlib/ndarray/base/napi/unary.h"
#include "stdlib/ndarray/base/napi/dtype_string_to_dtype.h"
#include <stdio.h>

// Defining the square function
void unary_square( double *input, double *output, int length ) {
    int j;
    for ( j = 0; j < length; j++ ) {
        output[ j ] = input[ j ] * input[ j ];
    }
}

int main() {
    const char *dtypeString;
    double inputArray[] = { 1.0, 2.0, 3.0, 4.0, 5.0 };
    double outputArray[ 5 ];
    int dtype;
    int i;

    // Defining the ndarray function object
    static const struct ndarrayFunctionObject obj = {
        "unary_square",
        1,
        1,
        2,
        { &unary_square },
        1,
        { STDLIB_NDARRAY_FLOAT64, STDLIB_NDARRAY_FLOAT64 },        
        { NULL }
    };

    stdlib_ndarray_napi_unary( NULL, NULL, &obj, inputArray, outputArray, 5 );

    // Printing the result of applying the unary operation (square)
    for ( i = 0; i < 5; i++ ) {
        printf("%.2f ", outputArray[ i ]);
    }
    printf( "\n" );

    dtypeString = "float64";

    dtype = stdlib_ndarray_napi_dtype_string_to_dtype( dtypeString );

    // Printing the result of converting dtype string to dtype
    printf( "%d", dtype );

    return 0;
}
```

I'd be really grateful for your help! Thanks!
@kgryte , @Pranavchiku , @steff456 , @Planeshifter

**Comment by rxbryan** [comment]
Hi @Planeshifter I can see that this issue is taken. Is there any other issue related to ndarray, that I can work on to get more familiar with the API

**Comment by performant23** [comment]
Hi @rxbryan , since I have been working on the implementations lately, even though I have coded an example, I still have debugging and testing which would be a major component of the issue. So, if you're new and want to explore the API, feel free to work on this one!

**Comment by rxbryan** [comment]
Thanks @performant23 
@Planeshifter I would love to work on this issue.

**Comment by kgryte** [comment]
@performant23 For C examples, you should create an `examples/c/example.c` file (along with a corresponding `Makefile`). You can then compile and run C examples using the following `make` command from the root project directory:

```bash
$ make examples-c EXAMPLES_FILTER=".*/ndarray/base/napi/examples/.*"
```
