### ISSUE TITLE
[RFC]: improve README examples of `ndarray/iter` namespace

### ISSUE THREAD

**Issue by Planeshifter** [stdlib-js/stdlib#1589]
### Description

This RFC proposes to improve the [README examples](https://github.com/stdlib-js/stdlib/tree/develop/lib/node_modules/%40stdlib/ndarray/iter#examples) of the `ndarray/iter` namespace package. Currently, namespace package READMEs only include minimal examples which are not particularly informative and do not showcase namespace functionality.

Historically, namespace examples were not given much effort due to the rapidly changing nature of the project; however, now that development and organization has settled, it would be good to revisit these packages and add proper examples to better communicate to users how to use namespace contents.

For those wanting to contribute to this issue, you can use the following steps:

- Browse through the [contents](https://github.com/stdlib-js/stdlib/tree/develop/lib/node_modules/%40stdlib/ndarray/iter) of the `ndarray/iter` namespace and identify interesting functions and packages to showcase.
- Update the example code block in the "Examples" section of the README for the `ndarray/iter` namespace and open a PR.
- When updating the README, examples should follow existing project conventions (e.g., ES5).
- Examples may `require` functionality from other packages to help make examples more interesting.

### Related Issues

None.

### Questions

No.

### Other

No.

### Checklist

- [X] I have read and understood the [Code of Conduct](https://github.com/stdlib-js/stdlib/blob/develop/CODE_OF_CONDUCT.md).
- [X] Searched for existing issues and pull requests.
- [X] The issue name begins with `RFC:`.

**Comment by performant23** [comment]
Hello, I hope this message finds you well! At the moment, I don’t have any significant issues to address (although I anticipate some minor adjustments for #1437). Therefore, I would be delighted to contribute to this issue. Given that we’ll be exploring similar packages and the patterns for examples in ndarray would be alike, I would also be more than happy to work on #1588, #1587, and #1586 if that works for you. Thank You!

**Comment by Planeshifter** [comment]
@performant23 Your open PR should be ready for merging, so this sounds good. And it makes sense to treat the linked issues as one. Thanks for taking this on!

When updating the `README.md` examples, please make sure to also update the `examples/index.js` file(s) accordingly.
