### ISSUE TITLE
RFC: add assertion utility to test for an ES6 class

### ISSUE THREAD

**Issue by kgryte** [stdlib-js/stdlib#159]
## Checklist

> Please ensure the following tasks are completed before filing an issue.

-   [x] Read and understood the [Code of Conduct][code-of-conduct].
-   [x] Searched for existing issues and pull requests.
-   [x] If this is a general question, searched the [FAQ][faq] for an existing answer.
-   [x] If this is a feature request, the issue name begins with `RFC:`.

## Description

> Description of the issue (or feature request).

This RFC proposes adding a new assertion utility to test for an ES6 class. Based on prior art, this requires analyzing the output of built-in string serialization, but other methods may be possible.

Prior art:

-   [is-class](https://github.com/miguelmota/is-class/blob/master/is-class.js): also includes Babel classes, which should **not** be supported by the proposed utility.
-   [is-callable](https://github.com/ljharb/is-callable/blob/6fb3fbe1e63e87bb32b00ed34b67632edc6062b6/index.js): check is an implementation detail, rather than exposed API.

Package: `@stdlib/assert/is-class`
Alias: `isClass`

## Related Issues

> Does this issue (or feature request) have any related issues?

No.

## Questions

> Any questions for reviewers?

No.

## Other

> Any other information relevant to this issue (or feature request)? This may include screenshots, references, stack traces, sample output, and/or implementation notes.

No.

[code-of-conduct]: https://github.com/stdlib-js/stdlib/blob/develop/CODE_OF_CONDUCT.md

[faq]: https://github.com/stdlib-js/stdlib/blob/develop/FAQ.md

**Comment by Planeshifter** [comment]
This function has now been added.
