### ISSUE TITLE
[RFC]: improve README examples of `random/iter` namespace

### ISSUE THREAD

**Issue by Planeshifter** [stdlib-js/stdlib#1607]
### Description

This RFC proposes to improve the [README examples](https://github.com/stdlib-js/stdlib/tree/develop/lib/node_modules/%40stdlib/random/iter#examples) of the `random/iter` namespace package. Currently, namespace package READMEs only include minimal examples which are not particularly informative and do not showcase namespace functionality.

Historically, namespace examples were not given much effort due to the rapidly changing nature of the project; however, now that development and organization has settled, it would be good to revisit these packages and add proper examples to better communicate to users how to use namespace contents.

For those wanting to contribute to this issue, you can use the following steps:

- Browse through the [contents](https://github.com/stdlib-js/stdlib/tree/develop/lib/node_modules/%40stdlib/random/iter) of the `random/iter` namespace and identify interesting functions and packages to showcase.
- Update the example code block in the "Examples" section of the README for the `random/iter` namespace and open a PR.
- When updating the README, examples should follow existing project conventions (e.g., ES5).
- Examples may `require` functionality from other packages to help make examples more interesting.

### Related Issues

None.

### Questions

No.

### Other

No.

### Checklist

- [X] I have read and understood the [Code of Conduct](https://github.com/stdlib-js/stdlib/blob/develop/CODE_OF_CONDUCT.md).
- [X] Searched for existing issues and pull requests.
- [X] The issue name begins with `RFC:`.

**Comment by saisrikardumpeti** [comment]
hey @Planeshifter i would like to ask how we want to document this like list one example of each package in examples just like overview of namespace library or only example for a few of them?

**Comment by Planeshifter** [comment]
@the-r3aper7 Only a few examples so people can get a sense of the typical function signature in the namespace when browsing the docs. Best to come up with some new code example that potentially even combines usage of some of the packages.

**Comment by the-r3aper7** [comment]
something like this will work? @Planeshifter 
```
var iterator = require('@stdlib/random/iter/uniform');
var shuffle = require('@stdlib/random/shuffle');

var min = 1;
var max = 10;
var iterations = 7;
var uniformIter;
var numbers;
var shuffled;

// Create an iterator for generating uniform random numbers
uniformIter = iterator(min, max, {
  'iter' : iterations
});

// Generate random numbers
numbers = Array.from({length: iterations}, () => uniformIter.next().value);

// Shuffle the array
shuffled = shuffle(numbers);
``
