### ISSUE TITLE
RFC: add assertion utility to test if a value is an arrow function

### ISSUE THREAD

**Issue by kgryte** [stdlib-js/stdlib#163]
## Checklist

> Please ensure the following tasks are completed before filing an issue.

-   [x] Read and understood the [Code of Conduct][code-of-conduct].
-   [x] Searched for existing issues and pull requests.
-   [x] If this is a general question, searched the [FAQ][faq] for an existing answer.
-   [x] If this is a feature request, the issue name begins with `RFC:`.

## Description

> Description of the issue (or feature request).

This RFC proposes adding an assertion utility to test if a value is an ES6 arrow function.

Package: `@stdlib/assert/is-arrow-function`
Alias: `isArrowFunction`

## Related Issues

> Does this issue (or feature request) have any related issues?

No.

## Questions

> Any questions for reviewers?

No.

## Other

> Any other information relevant to this issue (or feature request)? This may include screenshots, references, stack traces, sample output, and/or implementation notes.

Prior art:

-   [is-arrow-function](https://github.com/ljharb/is-arrow-function/blob/master/index.js): depends on `isCallable` (see https://github.com/stdlib-js/stdlib/issues/160).

[code-of-conduct]: https://github.com/stdlib-js/stdlib/blob/develop/CODE_OF_CONDUCT.md

[faq]: https://github.com/stdlib-js/stdlib/blob/develop/FAQ.md

**Comment by Planeshifter** [comment]
Added per https://github.com/stdlib-js/stdlib/commit/d1d583aad5860282e602ca82ca72c82e482f7b6a.
