### ISSUE TITLE
[RFC]: improve README examples of `stats/base/dists/normal` namespace

### ISSUE THREAD

**Issue by Planeshifter** [stdlib-js/stdlib#1638]
### Description

This RFC proposes to improve the [README examples](https://github.com/stdlib-js/stdlib/tree/develop/lib/node_modules/%40stdlib/stats/base/dists/normal#examples) of the `stats/base/dists/normal` namespace package. Currently, namespace package READMEs only include minimal examples which are not particularly informative and do not showcase namespace functionality.

Historically, namespace examples were not given much effort due to the rapidly changing nature of the project; however, now that development and organization has settled, it would be good to revisit these packages and add proper examples to better communicate to users how to use namespace contents.

For those wanting to contribute to this issue, you can use the following steps:

- Browse through the [contents](https://github.com/stdlib-js/stdlib/tree/develop/lib/node_modules/%40stdlib/stats/base/dists/normal) of the `stats/base/dists/normal` namespace and identify interesting functions and packages to showcase.
- Update the example code block in the "Examples" section of the README for the `stats/base/dists/normal` namespace and open a PR.
- When updating the README, examples should follow existing project conventions (e.g., ES5).
- Examples may `require` functionality from other packages to help make examples more interesting.

### Related Issues

None.

### Questions

No.

### Other

No.

### Checklist

- [X] I have read and understood the [Code of Conduct](https://github.com/stdlib-js/stdlib/blob/develop/CODE_OF_CONDUCT.md).
- [X] Searched for existing issues and pull requests.
- [X] The issue name begins with `RFC:`.

**Comment by nightknighto** [comment]
I would like to work on this issue.

Question, in addition to the README present in this package, there is also `examples/index.js` file that includes the same example from README, possibly to be run directly from node. That isn't mentioned in the issues but that would need to be updated as well, correct?

**Comment by nightknighto** [comment]
Another question, do the examples need to include every function or just some of them?

**Comment by Planeshifter** [comment]
@Deadreyo Yes, the `examples/index.js` should match the example code in the `README.md`; I will update the descriptions to make that clear. Thanks for bringing that up! 

The example code should usually only highlight a chosen subset of the namespace's functionality. It should give prospective users an idea of the included functionality and function signatures, but not be overwhelming.

I just assigned you; looking forward to your PR!

**Comment by nightknighto** [comment]
Is this what you're looking for for an example?
## Example 1
```javascript
var normal = require( '@stdlib/stats/base/dists/normal' );

var mean = 2;
var sigma = 3;

console.log(normal.entropy( mean, sigma ));
// ~ 2.517

console.log(normal.mean( mean, sigma ));
// 2.0

console.log(normal.median( mean, sigma ));
// 2.0

console.log(normal.mode( mean, sigma ));
// 2.0

console.log(normal.variance( mean, sigma ));
// 9.0

console.log(normal.skewness( mean, sigma ));
// 0.0
```

**Comment by Planeshifter** [comment]
@Deadreyo That's a fair start, but I would also include demonstration of how to use one or two of the distribution functions (`cdf`, `pdf`, `quantile`...) and maybe the constructor function as well. Feel free to create a PR with your proposal!
