### ISSUE TITLE
RFC: add assertion utility to test if a value is a DataView

### ISSUE THREAD

**Issue by kgryte** [stdlib-js/stdlib#164]
## Checklist

> Please ensure the following tasks are completed before filing an issue.

-   [x] Read and understood the [Code of Conduct][code-of-conduct].
-   [x] Searched for existing issues and pull requests.
-   [x] If this is a general question, searched the [FAQ][faq] for an existing answer.
-   [x] If this is a feature request, the issue name begins with `RFC:`.

## Description

> Description of the issue (or feature request).

This RFC proposes adding an assertion utility to test if a value is a [`DataView`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/DataView). Similar to assertion utilities testing for typed arrays and other built-ins, this may require testing methods particular to a built-in, as "brand-checking" in ES2015+ environments is more difficult due to `toStringTag`.

Package: `@stdlib/assert/is-dataview`
Alias: `isDataView`

## Related Issues

> Does this issue (or feature request) have any related issues?

No.

## Questions

> Any questions for reviewers?

No.

## Other

> Any other information relevant to this issue (or feature request)? This may include screenshots, references, stack traces, sample output, and/or implementation notes.

No.

[code-of-conduct]: https://github.com/stdlib-js/stdlib/blob/develop/CODE_OF_CONDUCT.md

[faq]: https://github.com/stdlib-js/stdlib/blob/develop/FAQ.md

**Comment by Planeshifter** [comment]
Closing as this feature [has already been added](https://github.com/stdlib-js/stdlib/commit/16ce64d639321aa79023608193f2bb7970ded211#diff-45c4bd632f160158fb1a8ee6ca9080c3352ca7ec6aacb6a3afcc11dbec289caf).
