### ISSUE TITLE
[RFC]: improve README examples of `stats/base/dists/uniform` namespace

### ISSUE THREAD

**Issue by Planeshifter** [stdlib-js/stdlib#1648]
### Description

This RFC proposes to improve the [README examples](https://github.com/stdlib-js/stdlib/tree/develop/lib/node_modules/%40stdlib/stats/base/dists/uniform#examples) of the `stats/base/dists/uniform` namespace package. Currently, namespace package READMEs only include minimal examples which are not particularly informative and do not showcase namespace functionality.

Historically, namespace examples were not given much effort due to the rapidly changing nature of the project; however, now that development and organization has settled, it would be good to revisit these packages and add proper examples to better communicate to users how to use namespace contents.

For those wanting to contribute to this issue, you can use the following steps:

- Browse through the [contents](https://github.com/stdlib-js/stdlib/tree/develop/lib/node_modules/%40stdlib/stats/base/dists/uniform) of the `stats/base/dists/uniform` namespace and identify interesting functions and packages to showcase.
- Update the example code block in the "Examples" section of the README for the `stats/base/dists/uniform` namespace and open a PR.
- When updating the README, examples should follow existing project conventions (e.g., ES5).
- Examples may `require` functionality from other packages to help make examples more interesting.

### Related Issues

None.

### Questions

No.

### Other

No.

### Checklist

- [X] I have read and understood the [Code of Conduct](https://github.com/stdlib-js/stdlib/blob/develop/CODE_OF_CONDUCT.md).
- [X] Searched for existing issues and pull requests.
- [X] The issue name begins with `RFC:`.

**Comment by kunal-511** [comment]
In this we have to update example of each function?

**Comment by headlessNode** [comment]
Hi @Planeshifter,

I'm interested in taking on the task of improving the README examples for the `stats/base/dists/uniform` namespace. I have already browsed through the functions/packages this namespace provides and have selected those I find interesting based on their use cases.

I've chosen the following functions to focus on:

- Cumulative Distribution Function (CDF)
- Entropy
- Mean
- Standard Deviation
- Variance
- Probability Density Function (PDF)

If there are any specific guidelines or suggestions for this task, please let me know, and I'll be happy to incorporate them.

Looking forward to working with you all!

**Comment by kunal-511** [comment]
Welcome @headlessNode Looking forward to contribute with you !!!!
