### ISSUE TITLE
RFC: add assertion utility to test if a value is an ArrayBuffer view

### ISSUE THREAD

**Issue by kgryte** [stdlib-js/stdlib#165]
## Checklist

> Please ensure the following tasks are completed before filing an issue.

-   [x] Read and understood the [Code of Conduct][code-of-conduct].
-   [x] Searched for existing issues and pull requests.
-   [x] If this is a general question, searched the [FAQ][faq] for an existing answer.
-   [x] If this is a feature request, the issue name begins with `RFC:`.

## Description

> Description of the issue (or feature request).

This RFC proposes adding a utility to test whether a value is an `ArrayBuffer` view. The implementation should be a straightforward wrapper for [`ArrayBuffer.view`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/ArrayBuffer/isView) (including the polyfill for older environments lacking `ArrayBuffer` support; i.e., a constant function always returning `false`).

Package: `@stdlib/assert/is-arraybuffer-view`
Alias: `isArrayBufferView`

## Related Issues

> Does this issue (or feature request) have any related issues?

No.

## Questions

> Any questions for reviewers?

No.

## Other

> Any other information relevant to this issue (or feature request)? This may include screenshots, references, stack traces, sample output, and/or implementation notes.

No.

[code-of-conduct]: https://github.com/stdlib-js/stdlib/blob/develop/CODE_OF_CONDUCT.md

[faq]: https://github.com/stdlib-js/stdlib/blob/develop/FAQ.md

**Comment by Planeshifter** [comment]
This function has now been added.
