### ISSUE TITLE
[RFC]: improve README examples of `stats/base` namespace

### ISSUE THREAD

**Issue by Planeshifter** [stdlib-js/stdlib#1650]
### Description

This RFC proposes to improve the [README examples](https://github.com/stdlib-js/stdlib/tree/develop/lib/node_modules/%40stdlib/stats/base#examples) of the `stats/base` namespace package. Currently, namespace package READMEs only include minimal examples which are not particularly informative and do not showcase namespace functionality.

Historically, namespace examples were not given much effort due to the rapidly changing nature of the project; however, now that development and organization has settled, it would be good to revisit these packages and add proper examples to better communicate to users how to use namespace contents.

For those wanting to contribute to this issue, you can use the following steps:

- Browse through the [contents](https://github.com/stdlib-js/stdlib/tree/develop/lib/node_modules/%40stdlib/stats/base) of the `stats/base` namespace and identify interesting functions and packages to showcase.
- Update the example code block in the "Examples" section of the README for the `stats/base` namespace and open a PR.
- When updating the README, examples should follow existing project conventions (e.g., ES5).
- Examples may `require` functionality from other packages to help make examples more interesting.

### Related Issues

None.

### Questions

No.

### Other

No.

### Checklist

- [X] I have read and understood the [Code of Conduct](https://github.com/stdlib-js/stdlib/blob/develop/CODE_OF_CONDUCT.md).
- [X] Searched for existing issues and pull requests.
- [X] The issue name begins with `RFC:`.

**Comment by headlessNode** [comment]
Hi @Planeshifter,

I'm interested in taking this task of improving the README examples for the `stats/base` namespace.

Given the extensive list of functions within this namespace, I suggest focusing on showcasing basic functions in the main README to provide users with a foundational understanding of the namespace's capabilities. 

For the more niche functions within the namespace, we can provide a high-level overview in a separate section or in individual function documentation files. This approach ensures that users can easily access information about specialized functions while keeping the main README focused on essential concepts.

If you agree with this approach or have any other suggestions, please let me know.

**Comment by sudoevans** [comment]
@headlessNode Hello, please let me know if you need someone to pair with as there is no one assigned this task and I am interested in working on the same.

**Comment by headlessNode** [comment]
@Planeshifter I've already commented on another issue to be assigned #1505 . Please assign this issue to @sudoevans.

**Comment by Rupa-Rd** [comment]
Hi @Planeshifter,
I am interested in contributing to this issue, assign this issue to me.
can you tell me whether I've got to write examples for all the functions?

**Comment by BarryByte** [comment]
@Planeshifter @kgryte May i work on this issue ? It is labelled as good first issue, it might help me to start contributing to this organization.

**Comment by kgryte** [comment]
@BarryByte I suggest finding a good first issue focused more on writing code. E.g., https://github.com/stdlib-js/stdlib/issues/2324.

**Comment by BarryByte** [comment]
@kgryte I appreciate your guidance and will definitely look into issue #2324  . However, since I have already requested to work on issue #2330 , I would love to start with it as it seems like a manageable task for my first contribution. If it's possible to assign it to me, I would be very grateful.
