### ISSUE TITLE
[RFC]: improve README examples of `stats/iter` namespace

### ISSUE THREAD

**Issue by Planeshifter** [stdlib-js/stdlib#1652]
### Description

This RFC proposes to improve the [README examples](https://github.com/stdlib-js/stdlib/tree/develop/lib/node_modules/%40stdlib/stats/iter#examples) of the `stats/iter` namespace package. Currently, namespace package READMEs only include minimal examples which are not particularly informative and do not showcase namespace functionality.

Historically, namespace examples were not given much effort due to the rapidly changing nature of the project; however, now that development and organization has settled, it would be good to revisit these packages and add proper examples to better communicate to users how to use namespace contents.

For those wanting to contribute to this issue, you can use the following steps:

- Browse through the [contents](https://github.com/stdlib-js/stdlib/tree/develop/lib/node_modules/%40stdlib/stats/iter) of the `stats/iter` namespace and identify interesting functions and packages to showcase.
- Update the example code block in the "Examples" section of the README for the `stats/iter` namespace and open a PR.
- When updating the README, examples should follow existing project conventions (e.g., ES5).
- Examples may `require` functionality from other packages to help make examples more interesting.

### Related Issues

None.

### Questions

No.

### Other

No.

### Checklist

- [X] I have read and understood the [Code of Conduct](https://github.com/stdlib-js/stdlib/blob/develop/CODE_OF_CONDUCT.md).
- [X] Searched for existing issues and pull requests.
- [X] The issue name begins with `RFC:`.

**Comment by kumarsuraj212003** [comment]
i am working on this issue.

**Comment by pankaj-2503** [comment]
Hey @Planeshifter  there are already average of about 60-70 examples do you want to increase the examples or you want some interesting examples to showcase .

**Comment by Planeshifter** [comment]
@pankaj-2503 

Specifically, this PR is about changing the namespace example code block, which currently looks like this:

```js
var getKeys = require( '@stdlib/utils/keys' );
var ns = require( '@stdlib/stats/iter' );

console.log( getKeys( ns ) );
```

Instead, it would be good to show a few functions and how they are used. It's better here to be selective, for example we could show one example with for a regular iterator and then also one using an iterator that computes a moving statistic, i.e. one supporting a window (`W`) parameter. Would be good to not just reuse examples from the individual packages, but for example come up with one conceptual example that involves multiple packages.

Hope this makes sense. Please let me know if you would like to give this a shot!

**Comment by pankaj-2503** [comment]
Yeah i would like to contribute to this readme files . Also can you show an example for the same, i just landed on this repo

**Comment by Megh2005** [comment]
I would like to contribute to this read me files . Also can you show an example for the same, i just landed on this repo
