### ISSUE TITLE
[RFC]: Add C implementation for `@stdlib/math/base/special/pow`

### ISSUE THREAD

**Issue by Pranavchiku** [stdlib-js/stdlib#1656]
### Description

This RFC proposes adding native C implementation for [`@stdlib/math/base/special/pow`](https://github.com/stdlib-js/stdlib/blob/develop/lib/node_modules/%40stdlib/math/base/special/pow/).

```c
double stdlib_base_pow( const double b, const double x )
```

### Related Issues

None.

### Questions

No.

### Other

No.

### Checklist

- [X] I have read and understood the [Code of Conduct](https://github.com/stdlib-js/stdlib/blob/develop/CODE_OF_CONDUCT.md).
- [X] Searched for existing issues and pull requests.
- [X] The issue name begins with `RFC:`.

**Comment by Pranavchiku** [comment]
Implementing this will unblock a lot of packages, but it will take some time and is on a difficult side. Requesting new comers to avoid unless they have added C implementation for atleast 5 math functions ( feel confident enough ).

**Comment by Pratik772846** [comment]
@Pranavchiku I would like to work on this issue.

**Comment by aman-095** [comment]
Hey, @Pranavchiku I have added C implementations for a few math functions, and I have a fair understanding of the code flow. I would like to contribute to this issue.

**Comment by Pranavchiku** [comment]
@Pratik772846 you may feel free to pick over any of easy math packages, this will be tricky for you at moment. I'll let @aman-095 give a shot to this.

**Comment by aman-095** [comment]
I have implementation ready for this, but it requires C implementation of is-even and is-odd functions.  Should I go ahead and implement these two as well?

**Comment by Pranavchiku** [comment]
Ahh, I might have missed out checking those, it will be fairly simple, proceed and get those done.

**Comment by gunjjoshi** [comment]
Hey @aman-095, are you still working on this ?

**Comment by aman-095** [comment]
Yes @gunjjoshi , I am working on this.
