### ISSUE TITLE
[RFC]: Add C implementation for `@stdlib/math/base/special/nonfibonacci `

### ISSUE THREAD

**Issue by Pranavchiku** [stdlib-js/stdlib#1660]
### Description

This RFC proposes adding native C implementation for [`@stdlib/math/base/special/nonfibonacci`](https://github.com/stdlib-js/stdlib/blob/develop/lib/node_modules/%40stdlib/math/base/special/nonfibonacci/).

```c
double stdlib_base_nonfibonacci( const int32_t n );
```

### Related Issues

None.

### Questions

No.

### Other

No.

### Checklist

- [X] I have read and understood the [Code of Conduct](https://github.com/stdlib-js/stdlib/blob/develop/CODE_OF_CONDUCT.md).
- [X] Searched for existing issues and pull requests.
- [X] The issue name begins with `RFC:`.

**Comment by lovelindhoni** [comment]
hey @Pranavchiku I would like to work on this issue :)
