### ISSUE TITLE
[RFC]: Add C implementation for `math/base/special/cot`

### ISSUE THREAD

**Issue by soham2312** [stdlib-js/stdlib#1663]
### Description

This RFC proposes adding a C implementation for [`@stdlib/math/base/special/cot`](https://github.com/stdlib-js/stdlib/tree/b43a75923e47775446d3b6d7219ee42e07f7ce63/lib/node_modules/%40stdlib/math/base/special/cot)

```c
double stdlib_base_cot( const double x )
```

### Related Issues

None

### Questions

No.

### Other

No.

### Checklist

- [X] I have read and understood the [Code of Conduct](https://github.com/stdlib-js/stdlib/blob/develop/CODE_OF_CONDUCT.md).
- [X] Searched for existing issues and pull requests.
- [X] The issue name begins with `RFC:`.

**Comment by soham2312** [comment]
hey @Pranavchiku  I would like to work on this issue :)

**Comment by soham2312** [comment]
@Planeshifter @kgryte @Pranavchiku please assigne this issue to me

**Comment by Planeshifter** [comment]
@soham2312 done; looking forward to your PR!

**Comment by Shashankss1205** [comment]
If this hasn't been completed yet, I am ready to take up this issue. @Planeshifter

**Comment by Pranavchiku** [comment]
This is a blocked as we do not have C implementation for `stdlib/math/base/special/tan`. @Shashankss1205 you may lookup other issues. Thanks for your interest.

**Comment by kgryte** [comment]
This has now been implemented. Closing...
