### ISSUE TITLE
[RFC]: Add C implementation for `@stdlib/math/base/special/bernoulli`

### ISSUE THREAD

**Issue by rajutkarsh07** [stdlib-js/stdlib#1664]
### Description

This RFC proposes adding native C implementation for `@stdlib/math/base/special/bernoulli`
```
double stdlib_base_bernoulli( const int n );
```

### Questions

No.

### Other

No.

### Checklist

- [X] I have read and understood the [Code of Conduct](https://github.com/stdlib-js/stdlib/blob/develop/CODE_OF_CONDUCT.md).
- [X] Searched for existing issues and pull requests.
- [X] The issue name begins with `RFC:`.

**Comment by rajutkarsh07** [comment]
@Planeshifter @Pranavchiku @kgryte I am working on this issue, please assign this issue to me

**Comment by Pranavchiku** [comment]
This depends on #1670.

**Comment by Pranavchiku** [comment]
Also on `@stdlib/math/base/assert/is-nonnegative-integer` which donot have C implementation, you may proceed to add that if you wish.

**Comment by gunjjoshi** [comment]
Hey @Pranavchiku, can I get assigned for this ? I can work on this after my PR for the C implementation of [`@stdlib/math/base/assert/is-nonnegative-integer`](https://github.com/stdlib-js/stdlib/pull/1746) gets merged.

**Comment by rajutkarsh07** [comment]
@Pranavchiku @Planeshifter assign me this issue

**Comment by gunjjoshi** [comment]
Hey @rajutkarsh07, if you want to work on this, you can get assigned and go ahead ! No problem with that. Thanks !
