### ISSUE TITLE
[RFC]: Add C implementation for `@stdlib/math/base/assert/is-odd`

### ISSUE THREAD

**Issue by Shashankss1205** [stdlib-js/stdlib#1668]
### Description

This RFC proposes adding native C implementation for [`@stdlib/math/base/assert/is-odd` ](https://github.com/stdlib-js/stdlib/tree/develop/lib/node_modules/%40stdlib/math/base/assert/is-odd)
```c
double stdlib_base_is_odd( const double x )
```

### Related Issues

No

### Questions

No.

### Other

No.

### Checklist

- [X] I have read and understood the [Code of Conduct](https://github.com/stdlib-js/stdlib/blob/develop/CODE_OF_CONDUCT.md).
- [X] Searched for existing issues and pull requests.
- [X] The issue name begins with `RFC:`.

**Comment by Shashankss1205** [comment]
I would like to get it assigned to myself.

**Comment by Pranavchiku** [comment]
@Shashankss1205 you'll have to wait till #1667 gets merged.

**Comment by Pranavchiku** [comment]
@Shashankss1205 feel free to work on this, refer #1667, and I will request you to be quick as this is blocker for #1656. Your volunteering is highly appreciated, thanks!

**Comment by Shashankss1205** [comment]
Have made the PR for this issue, please review it @Pranavchiku
