### ISSUE TITLE
[RFC]: add auto-closing brackets and quotations in REPL

### ISSUE THREAD

**Issue by Snehil-Shah** [stdlib-js/stdlib#1672]
### Description

This RFC proposes adding auto-closing brackets in the REPL.

@kgryte @Planeshifter @Pranavchiku will this be a good addition?

### Related Issues

Related Issue https://github.com/stdlib-js/google-summer-of-code/issues/1

### Questions

No.

### Other

No.

### Checklist

- [X] I have read and understood the [Code of Conduct](https://github.com/stdlib-js/stdlib/blob/develop/CODE_OF_CONDUCT.md).
- [X] Searched for existing issues and pull requests.
- [X] The issue name begins with `RFC:`.

**Comment by kgryte** [comment]
Thanks for opening this issue, @Snehil-Shah. By auto-closing brackets, what is the behavior you have in mind? Are you thinking behavior similar to an IDE where if you type `[` or `(`, we automatically append `]` or `)`, respectively?

**Comment by Snehil-Shah** [comment]
> Thanks for opening this issue, @Snehil-Shah. By auto-closing brackets, what is the behavior you have in mind? Are you thinking behavior similar to an IDE where if you type `[` or `(`, we automatically append `]` or `)`, respectively?

Yes!

**Comment by Snehil-Shah** [comment]
> Thanks for opening this issue, @Snehil-Shah. By auto-closing brackets, what is the behavior you have in mind? Are you thinking behavior similar to an IDE where if you type `[` or `(`, we automatically append `]` or `)`, respectively?

If the idea is good to be implemented, I would like to work on it..

**Comment by kgryte** [comment]
@Snehil-Shah Yes, I can see that being useful and something that the REPL currently lacks. Similar to an IDE, we'd likely want this behavior to be capable of being controlled by a setting.

If you'd like to work on this, feel free to do so.

**Comment by kgryte** [comment]
Do note, however, that we'll still need to support splitting over multiple lines. Meaning, if I type

```javascript
> function foo( <cursor> )
```

and hit ENTER where `<cursor>` is (i.e., within brackets), we have some ambiguity: do we want to execute or move to the next line?

Currently, when a user types an incomplete expression and hits ENTER, the cursor moves to the next line without executing the expression.

One way to support the above behavior is to support modifier keys (e.g., SHIFT+ENTER) to allow insertion of a newline when within a valid expression.

**Comment by Snehil-Shah** [comment]
> @Snehil-Shah Yes, I can see that being useful and something that the REPL currently lacks. Similar to an IDE, we'd likely want this behavior to be capable of being controlled by a setting.
> 
> If you'd like to work on this, feel free to do so.

"Controlled by a setting", do you mean an option to disable this behaviour?

**Comment by kgryte** [comment]
Yes, that is correct. In editors, you can typically disable this setting. Some folks don't like auto-closing brackets, preferring instead to avoid magic and to manually type brackets.
