### ISSUE TITLE
[RFC]: Add C implementation for `@stdlib/math/base/special/acsc`

### ISSUE THREAD

**Issue by gunjjoshi** [stdlib-js/stdlib#1674]
### Description

This RFC proposes adding C implementation for [`@stdlib/math/base/special/acsc`](https://github.com/stdlib-js/stdlib/tree/develop/lib/node_modules/%40stdlib/math/base/special/acsc).

`double stdlib_base_acsc( const double x );`

### Related Issues

Related issues #649 

### Questions

No.

### Other

No.

### Checklist

- [X] I have read and understood the [Code of Conduct](https://github.com/stdlib-js/stdlib/blob/develop/CODE_OF_CONDUCT.md).
- [X] Searched for existing issues and pull requests.
- [X] The issue name begins with `RFC:`.

**Comment by gunjjoshi** [comment]
I would love to work on this, along with other[ C implementations to unary base special math functions ](https://github.com/stdlib-js/stdlib/issues/649), once [this](https://github.com/stdlib-js/stdlib/pull/1452) gets merged.

**Comment by rajutkarsh07** [comment]
A PR has already been raised on the same issue

**Comment by gunjjoshi** [comment]
This is the duplicate of #859. I will be closing this.
