### ISSUE TITLE
[RFC]: update the contributing to explicitly require running `make install`

### ISSUE THREAD

**Issue by Shashankss1205** [stdlib-js/stdlib#1678]
### Description

This RFC proposes to add the install command:
```c
$ make install-node-modules
```
before the initialisation command:
```c
$ make init
```
used for testing in **[Step-6: Test](https://github.com/stdlib-js/stdlib/blob/develop/CONTRIBUTING.md#step-6-test)** of [Contributing Guidelines.](https://github.com/stdlib-js/stdlib/blob/develop/CONTRIBUTING.md#contribution-guidelines)

This ensures that a person setting-up the repository for the first-time as a contributor doesn't receive an initialisation error while testing.

### Related Issues

No

### Questions

No.

### Other

No.

### Checklist

- [X] I have read and understood the [Code of Conduct](https://github.com/stdlib-js/stdlib/blob/develop/CODE_OF_CONDUCT.md).
- [X] Searched for existing issues and pull requests.
- [X] The issue name begins with `RFC:`.

**Comment by kgryte** [comment]
@Shashankss1205 Thanks for posting this issue. Yes, we should likely be more explicit here.

In https://github.com/stdlib-js/stdlib/blob/develop/CONTRIBUTING.md#code, we explicitly ask that contributors follow the Development Guide, which has contributors run `make install` before `make init`, but it is likely that people will gloss over those links and move on immediately to the listed steps in the contributing guide. Meaning, we should anticipate that individuals will not follow instructions and save ourselves the headache of common dev questions.

**Comment by Shashankss1205** [comment]
Thanks For your valuable insights into this issue @kgryte , shall I change it similar to the image attached and send it as a PR ?
![Screenshot (231)](https://github.com/stdlib-js/stdlib/assets/123410790/2c8cb3a8-0b9b-4f15-9ccb-cfbb4597a623)

**Comment by Shashankss1205** [comment]
Please suggest if that's like how you want this to be @kgryte
