### ISSUE TITLE
[RFC]: Add C implementation for `@stdlib/math/base/special/asec`

### ISSUE THREAD

**Issue by gunjjoshi** [stdlib-js/stdlib#1695]
### Description

This RFC proposes adding C implementation for [`@stdlib/math/base/special/asec`](https://github.com/stdlib-js/stdlib/tree/develop/lib/node_modules/%40stdlib/math/base/special/asec).

### Related Issues

Related issues #649. 

### Questions

No.

### Other

No.

### Checklist

- [X] I have read and understood the [Code of Conduct](https://github.com/stdlib-js/stdlib/blob/develop/CODE_OF_CONDUCT.md).
- [X] Searched for existing issues and pull requests.
- [X] The issue name begins with `RFC:`.

**Comment by gunjjoshi** [comment]
I would like to work on this.

**Comment by rajutkarsh07** [comment]
There is already same issue with someone assigned #861

**Comment by gunjjoshi** [comment]
@rajutkarsh07 Thanks for pointing it out. This issue can be closed.
