### ISSUE TITLE
[RFC]: add `@stdlib/string/base/last-code-point`

### ISSUE THREAD

**Issue by adityacodes30** [stdlib-js/stdlib#1702]
### Description

This RFC proposes adding the package `string/base/last-code-point` which returns the last `n` Unicode code points of a string.

signature 
`lastCodePoint( string, n )`

Eg.
```
var s = lastCodePoint( 'JavaScript', 6 );
// returns 'Script'
```

Package: `@stdlib/string/base/last-code-point`
Alias: lastCodePoint

This will help with development of `@stdlib/string/last`.

### Related Issues

Related issues #854

### Questions

No.

### Other

No.

### Checklist

- [X] I have read and understood the [Code of Conduct](https://github.com/stdlib-js/stdlib/blob/develop/CODE_OF_CONDUCT.md).
- [X] Searched for existing issues and pull requests.
- [X] The issue name begins with `RFC:`.

**Comment by adityacodes30** [comment]
I would like to work on this

edit: implemented, will pr once #1697 is merged

**Comment by adityacodes30** [comment]
@Planeshifter @kgryte could you please review this issue and add appropriate labels

**Comment by kgryte** [comment]
@adityacodes30 Thanks for opening. I've reviewed, added labels, and assigned you.

**Comment by adityacodes30** [comment]
pr is generated
