### ISSUE TITLE
[RFC]: Add C implementation for @stdlib/math/base/special/asec

### ISSUE THREAD

**Issue by Pratik772846** [stdlib-js/stdlib#1715]
### Description

This RFC proposes adding native C implementation for [@stdlib/math/base/special/asec](https://github.com/stdlib-js/stdlib/tree/develop/lib/node_modules/%40stdlib/math/base/special/asec).
`double stdlib_base_asec( const double x );`

### Related Issues

Related issues # [649](https://github.com/stdlib-js/stdlib/issues/649)

### Questions

No.

### Other

No.

### Checklist

- [X] I have read and understood the [Code of Conduct](https://github.com/stdlib-js/stdlib/blob/develop/CODE_OF_CONDUCT.md).
- [X] Searched for existing issues and pull requests.
- [X] The issue name begins with `RFC:`.

**Comment by Pratik772846** [comment]
Can I work on this?

**Comment by Snehil-Shah** [comment]
@Pratik772846 duplicate issue, see #861

**Comment by Pratik772846** [comment]
@Snehil-Shah Thanks for mentioning

**Comment by Pratik772846** [comment]
Already in Progress
