### ISSUE TITLE
BUG: No such file or directory , this error thrown on package utils/any-in-by while running benchmark tests

### ISSUE THREAD

**Issue by Pratik772846** [stdlib-js/stdlib#1732]
### Description

![image](https://github.com/stdlib-js/stdlib/assets/97464067/3ff06bdf-7ddb-4c75-8105-88ef53d8e2bc)
@kgryte @Pranavchiku Can you please take a look at this?

### Related Issues

Related issues # , # , and # .

### Questions

No.

### Environments

N/A

### Checklist

- [X] Read and understood the [Code of Conduct](https://github.com/stdlib-js/stdlib/blob/develop/CODE_OF_CONDUCT.md).
- [X] Searched for existing issues and pull requests.

**Comment by kgryte** [comment]
@Pratik772846 There shouldn't be a Julia benchmark in `utils/any-in-by`.

**Comment by Pratik772846** [comment]
@kgryte Similarly I think we do not need Julia benchmark in utils/every-own-by. But these packages with Julia benchmark have been merged , should I remove Julia benchmark from every-own-by also?

**Comment by kgryte** [comment]
@Pratik772846 No, that was an oversight. Those packages (e.g., `utils/every-own-by`, etc) should not have Julia benchmarks. This was a copy-paste bug introduced by copying files from, e.g., `utils/every`, where having Julia benchmarks is appropriate.

**Comment by kgryte** [comment]
cc @Planeshifter

**Comment by Pratik772846** [comment]
Thanks for the information, I will remove the Julia files while pushing my commit.
