### ISSUE TITLE
[RFC]: Refactor `function/docs/types` to follow current project conventions

### ISSUE THREAD

**Issue by Pinti0001** [stdlib-js/stdlib#1752]
### Description

This RFC proposes refactoring [`@stdlib/function/docs/types`](https://github.com/stdlib-js/stdlib/tree/develop/lib/node_modules/%40stdlib/function/docs/types) to follow current project conventions.

These conventions are need to make various style and simplification changes.

Some examples commits which perform most, the requested changes into moderat. 
I think we need to update the files

### Related Issues

None.

### Questions

No.

### Other

No.

### Checklist

- [X] I have read and understood the [Code of Conduct](https://github.com/stdlib-js/stdlib/blob/develop/CODE_OF_CONDUCT.md).
- [X] Searched for existing issues and pull requests.
- [X] The issue name begins with `RFC:`.

**Comment by Planeshifter** [comment]
Those TS files are auto-generated and should not be manually edited. Please find some other issue if you would like to contribute.
