### ISSUE TITLE
[RFC]: Add C implementation for `@stdlib/math/base/special/fibonacci-index`

### ISSUE THREAD

**Issue by tudor-pagu** [stdlib-js/stdlib#1756]
### Description

This RFC proposes adding native C implementation for `@stdlib/math/base/special/fibonacci-index`.
```
double stdlib_base_fibonacci_index( const double F );
```

### Related Issues

Tracked in issue #649.

### Questions

I am not sure about the method's signature. In the original JavaScript code, both the return type and the parameter are {NonNegativeInteger}. However, in some tests they take on the value NaN, which as far as I know does not exist for integer types in C. For this reason, I decided on using double, but please tell me if there is a more suitable solution.

### Other

The implementation depends on the `round` function, which is addressed in #735. I can use the round method from C until the method is implemented in stdlib, and I can also contribute to implementing `round`.

### Checklist

- [X] I have read and understood the [Code of Conduct](https://github.com/stdlib-js/stdlib/blob/develop/CODE_OF_CONDUCT.md).
- [X] Searched for existing issues and pull requests.
- [X] The issue name begins with `RFC:`.

**Comment by tudor-pagu** [comment]
Hi @kgryte @Planeshifter @Pranavchiku, I would like to work on this issue, could it please be assigned to me?

**Comment by kgryte** [comment]
@tudor-pagu We cannot use C round as it's behavior diverges from JS's behavior. This RFC is blocked until we can get #735 over the finish line.

**Comment by vivek-anand-singh** [comment]
Since #735 issue is closed now. Can you please assign this to me @kgryte @Pranavchiku

**Comment by kgryte** [comment]
@vivek-anand-singh Yes, assigned. Thanks for volunteering to work on this.

**Comment by gunjjoshi** [comment]
@kgryte We can close this issue, as it is completed by #2272.

**Comment by kgryte** [comment]
Thanks, @gunjjoshi, for following up here.
