### ISSUE TITLE
[RFC]: Add C implementation for `@stdlib/math/base/special/negafibonacci`

### ISSUE THREAD

**Issue by gunjjoshi** [stdlib-js/stdlib#1758]
### Description

This RFC proposes adding C implementation for [`@stdlib/math/base/special/negafibonacci`](https://github.com/stdlib-js/stdlib/tree/develop/lib/node_modules/%40stdlib/math/base/special/negafibonacci).

### Related Issues

Related issues #649 

### Questions

No.

### Other

No.

### Checklist

- [X] I have read and understood the [Code of Conduct](https://github.com/stdlib-js/stdlib/blob/develop/CODE_OF_CONDUCT.md).
- [X] Searched for existing issues and pull requests.
- [X] The issue name begins with `RFC:`.

**Comment by gunjjoshi** [comment]
I would like to work on this issue.

**Comment by kgryte** [comment]
Thanks for posting this RFC, @gunjjoshi. Yes, this works, so long as we have all the requisite C dependencies implemented.

**Comment by gunjjoshi** [comment]
Hey @kgryte, while working on this, I found that even in the C implementation of [`@stdlib/math/base/special/fibonacci`](https://github.com/stdlib-js/stdlib/blob/develop/lib/node_modules/%40stdlib/math/base/special/fibonacci/src/main.c), there is no check for identifying if the given number is an integer or not, or the given number is NaN or not. But in its Javascript implementation, those checks are being done. 

As a result, the last 2 examples in its [native.js](https://github.com/stdlib-js/stdlib/blob/develop/lib/node_modules/%40stdlib/math/base/special/fibonacci/lib/native.js) file give error messages, indicating that the expected values are something else, and not NaN. 

Or else, am I getting wrong somewhere ?

**Comment by kgryte** [comment]
@gunjjoshi I think you are right. For `fibonacci`, we should remove the non-integer, negative integer, and `NaN` input examples for the `native.js` file. That was a mistake and should be addressed in a separate PR.
