### ISSUE TITLE
[RFC]: add C implementation for `@stdlib/math/base/assert/is-negative-integer`

### ISSUE THREAD

**Issue by Userf1995** [stdlib-js/stdlib#1761]
### Description

This RFC proposes adding a C implementation for `@stdlib/math/base/assert/is-negative-integer`.

### Related Issues

Related issues #649.

### Questions

No.

### Other

No.

### Checklist

- [X] I have read and understood the [Code of Conduct](https://github.com/stdlib-js/stdlib/blob/develop/CODE_OF_CONDUCT.md).
- [X] Searched for existing issues and pull requests.
- [X] The issue name begins with `RFC:`.

**Comment by Userf1995** [comment]
I would like to work on this.

**Comment by kgryte** [comment]
@Rejoan-Sardar Thank you for posting this RFC. Feel free to submit a PR implementing this feature.

**Comment by Shashankss1205** [comment]
If this isn't done yet, I am willing to contribute as I already understand this well. @kgryte

**Comment by Userf1995** [comment]
@Shashankss1205 almost done.I will make my PR.

**Comment by Shashankss1205** [comment]
Ok sure.
