### ISSUE TITLE
[RFC]: add prompt marker to make multi-line code more readable in the REPL

### ISSUE THREAD

**Issue by Snehil-Shah** [stdlib-js/stdlib#1763]
### Description

This RFC proposes adding a prompt marker to make multi-line code more readable in the REPL by separating the prompt from the code more clearly.

**Before:**

![image](https://github.com/stdlib-js/stdlib/assets/130062020/329f400b-df0e-400f-9bfe-88756f3f8e8a)

**After:**

![after](https://github.com/stdlib-js/stdlib/assets/130062020/ba567de9-8fb6-4d18-bfc0-9072dce6f12e)

### Related Issues

Related Issue https://github.com/stdlib-js/google-summer-of-code/issues/1

### Questions

No.

### Other

Inspired by IPython..

### Checklist

- [X] I have read and understood the [Code of Conduct](https://github.com/stdlib-js/stdlib/blob/develop/CODE_OF_CONDUCT.md).
- [X] Searched for existing issues and pull requests.
- [X] The issue name begins with `RFC:`.

**Comment by Snehil-Shah** [comment]
@Planeshifter @kgryte @Pranavchiku I have the changes ready, will raise a PR if this issue is accepted.

**Comment by kgryte** [comment]
@Snehil-Shah Is the thinking behind this to allow better visual alignment for starting and closing braces?

I am not sure about this addition. Wouldn't another possibility if a user wanted to align brackets to just, say, hit ALT+ENTER to move to the next line and begin typing?

**Comment by Snehil-Shah** [comment]
> @Snehil-Shah Is the thinking behind this to allow better visual alignment for starting and closing braces?
> 
> I am not sure about this addition. Wouldn't another possibility if a user wanted to align brackets to just, say, hit ALT+ENTER to move to the next line and begin typing?

It's actually a small change, not directly related to the other PR. The goal is just to make it visually better by making each line start from the same position. (The colons align with each other in image)

**Comment by kgryte** [comment]
How would the line continuation adjust as the line counter increments to 2 digits and then to 3 digits? Would you just keep pushing over the ellipses? How does IPython handle this? Does it also provide a prompt prefix for multiline input?

**Comment by Snehil-Shah** [comment]
> How would the line continuation adjust as the line counter increments to 2 digits and then to 3 digits? Would you just keep pushing over the ellipses? How does IPython handle this? Does it also provide a prompt prefix for multiline input?

we can use the internal line counter to adjust for that. just 2 lines of change:

![image](https://github.com/stdlib-js/stdlib/assets/130062020/6b6de40e-2f0f-44e2-9847-9393db48e858)

as mentioned in op, this is inspired by ipython

ipython:

![image](https://github.com/stdlib-js/stdlib/assets/130062020/e1768d01-acf5-40dc-b05a-ceb23d5669c2)

**Comment by kgryte** [comment]
Okay. This is reasonable. We have a different convention in REPL text docs (see https://github.com/stdlib-js/stdlib/blob/5108869248f78854546359b8ce35916c612a90cb/docs/repl_text.md#examples), but this is probably fine.

**Comment by kgryte** [comment]
@Snehil-Shah Thank you for exploring this. Even if not ultimately accepted, we explored enough to discover some reasons for why not, so definitely useful and still a contribution.
