### ISSUE TITLE
[RFC]: Add auto-completion preview for REPL

### ISSUE THREAD

**Issue by tudor-pagu** [stdlib-js/stdlib#1775]
### Description

This RFC proposes adding a gray preview for auto-completion in the cases where the `completer` decides that there is only one valid completion. This aims to be similar to the behaviour of the node.js REPL:
![image](https://github.com/stdlib-js/stdlib/assets/104032457/78c79107-4455-4929-9eef-cc89902b5500)
After seeing the preview, the user can press tab for the completion to be filled in normally. Additionally, to mimic the node.js REPL, if the user presses the `up` arrow, the completion should also be filled in, and if the user presses `enter` the completion should be filled in and the line should be executed.

### Related Issues

Related issue https://github.com/stdlib-js/google-summer-of-code/issues/1
This issue also involves adding a listener for every key press in the REPL: https://github.com/stdlib-js/stdlib/issues/1672
### Questions

Is the behaviour I proposed when pressing up/enter good? Are there any other interactions which I've missed that I should implement?

### Other

No.

### Checklist

- [X] I have read and understood the [Code of Conduct](https://github.com/stdlib-js/stdlib/blob/develop/CODE_OF_CONDUCT.md).
- [X] Searched for existing issues and pull requests.
- [X] The issue name begins with `RFC:`.

**Comment by tudor-pagu** [comment]
Hi @kgryte @Planeshifter, if the issue is accepted I would like to be assigned to it, please. I have made some progress on it.

**Comment by kgryte** [comment]
@tudor-pagu This would be a welcome addition. Feel free to open a PR.
