### ISSUE TITLE
[RFC]: feat: add C implementation for `@stdlib/math/base/assert/int32-is-even`

### ISSUE THREAD

**Issue by Shashankss1205** [stdlib-js/stdlib#1805]
### Description

This RFC proposes adding native C implementation for [`@stdlib/math/base/assert/int32-is-even`](https://github.com/stdlib-js/stdlib/tree/develop/lib/node_modules/%40stdlib/math/base/assert/int32-is-even).

```c
double stdlib_base_int32_is_even( int32_t x );
```

### Related Issues

Related Issues

Related issues #1433, #1449.

### Questions

No.

### Other

No.

### Checklist

- [X] I have read and understood the [Code of Conduct](https://github.com/stdlib-js/stdlib/blob/develop/CODE_OF_CONDUCT.md).
- [X] Searched for existing issues and pull requests.
- [X] The issue name begins with `RFC:`.

**Comment by Shashankss1205** [comment]
Please Assign this issue to me @kgryte , @Planeshifter , I have code nearly ready for this.

**Comment by kgryte** [comment]
@Shashankss1205 Assigned.

**Comment by Userf1995** [comment]
working on it.

**Comment by kgryte** [comment]
@Rejoan-Sardar Please don't work on issues which have already been assigned. This helps ensure we don't duplicate work and also ensures that other folks have the opportunity to contribute.

**Comment by Userf1995** [comment]
@kgryte Got it, thank you for clarifying.
