### ISSUE TITLE
[RFC]: feat: add C implementation for `@stdlib/math/base/assert/int32-is-odd`

### ISSUE THREAD

**Issue by Shashankss1205** [stdlib-js/stdlib#1806]
### Description

This RFC proposes adding native C implementation for [`@stdlib/math/base/assert/int32-is-odd`](https://github.com/stdlib-js/stdlib/tree/develop/lib/node_modules/%40stdlib/math/base/assert/int32-is-odd).

```c
double stdlib_base_int32_is_odd( int32_t x );
```

### Related Issues

Related issues #1433 , #1449 , #.

### Questions

No.

### Other

No.

### Checklist

- [X] I have read and understood the [Code of Conduct](https://github.com/stdlib-js/stdlib/blob/develop/CODE_OF_CONDUCT.md).
- [X] Searched for existing issues and pull requests.
- [X] The issue name begins with `RFC:`.

**Comment by Shashankss1205** [comment]
Please Assign it to me @kgryte , @Planeshifter as it is related to my previous issues and PR's for `is-odd` and `int32-is-even`

**Comment by Abhikumar9896** [comment]
Description

This RFC proposes adding native C implementation for [@stdlib/math/base/assert/int32-is-odd](https://github.com/stdlib-js/stdlib/tree/develop/lib/node_modules/%40stdlib/math/base/assert/int32-is-odd).

double stdlib_base_int32_is_odd( int32_t x );
Related Issues

Related issues https://github.com/stdlib-js/stdlib/issues/1433 , https://github.com/stdlib-js/stdlib/issues/1449 , #.

Questions

No.

Other

No.

Checklist

 I have read and understood the [Code of Conduct](https://github.com/stdlib-js/stdlib/blob/develop/CODE_OF_CONDUCT.md).
 Searched for existing issues and pull requests.
 The issue name begins with RFC:.

**Comment by Userf1995** [comment]
@kgryte @Planeshifter I would like to work on it.
