### ISSUE TITLE
[RFC]: add C implementation for `math/base/special/xlogy`

### ISSUE THREAD

**Issue by performant23** [stdlib-js/stdlib#1815]
### Description

This RFC proposes adding native C implementation for `@stdlib/math/base/special/xlogy`:

```javascript
double stdlib_base_xlogy( const double x, const double y );
```

### Related Issues

Related issues: None

### Questions

No.

### Other

No.

### Checklist

- [X] I have read and understood the [Code of Conduct](https://github.com/stdlib-js/stdlib/blob/develop/CODE_OF_CONDUCT.md).
- [X] Searched for existing issues and pull requests.
- [X] The issue name begins with `RFC:`.

**Comment by performant23** [comment]
Hi, I have checked the existing issues and the current JS implementation for the function and would like to work on this issue!

**Comment by kgryte** [comment]
@performant23 Sounds good. Thanks for raising this issue and volunteering to make the contribution.
