### ISSUE TITLE
[RFC]:  add C implementation for @stdlib/math/base/special/csc.

### ISSUE THREAD

**Issue by Userf1995** [stdlib-js/stdlib#1821]
### Description

This RFC proposes adding C implementation for @stdlib/math/base/special/csc .

### Related Issues

Related issues #649.

### Questions

No.

### Other

No.

### Checklist

- [X] I have read and understood the [Code of Conduct](https://github.com/stdlib-js/stdlib/blob/develop/CODE_OF_CONDUCT.md).
- [X] Searched for existing issues and pull requests.
- [X] The issue name begins with `RFC:`.

**Comment by Userf1995** [comment]
I would like to work on this.

**Comment by gunjjoshi** [comment]
Hey @Rejoan-Sardar, this would first require the C implementation of `@stdlib/math/base/special/sin`, which currently, is not implemented.

**Comment by Rejoan-Sardar** [comment]
@gunjjoshi yeah, I will open a RFC for this.

**Comment by Userf1995** [comment]
As the C implementation of `@stdlib/math/base/special/sin` not exists, we can close this issue. I had confused this for some other package.
