### ISSUE TITLE
[RFC]:  add C implementation for @stdlib/math/base/special/maxabsn

### ISSUE THREAD

**Issue by Userf1995** [stdlib-js/stdlib#1825]
### Description

This RFC proposes adding C implementation for @stdlib/math/base/special/maxabsn .

### Related Issues

Related issues #649.

### Questions

No.

### Other

No.

### Checklist

- [X] I have read and understood the [Code of Conduct](https://github.com/stdlib-js/stdlib/blob/develop/CODE_OF_CONDUCT.md).
- [X] Searched for existing issues and pull requests.
- [X] The issue name begins with `RFC:`.

**Comment by Userf1995** [comment]
I would like to work on this. @kgryte  could you please review this issue and add appropriate labels

**Comment by rohit-sharma-1802** [comment]
@stdlib-bot assign

**Comment by rohit-sharma-1802** [comment]
@kgryte Hi, I want to work on this task. if you allow.

**Comment by kgryte** [comment]
This is a variadic JavaScript API, no? If so, there will be no C implementation.

**Comment by Userf1995** [comment]
As no  C implementation of @stdlib/math/base/special/maxabsn required, we can close this issue. I had confused this for some other package.
