### ISSUE TITLE
[RFC]: add C implementation for `@stdlib/math/base/assert/is-nonpositive-finite`

### ISSUE THREAD

**Issue by performant23** [stdlib-js/stdlib#1831]
### Description

This RFC proposes adding native C implementation for `math/base/assert/is-nonpositive-finite`:

```c
bool stdlib_base_is_nonpositive_finite( const double x );
```

### Related Issues

N/A

### Questions

No.

### Other

No.

### Checklist

- [X] I have read and understood the [Code of Conduct](https://github.com/stdlib-js/stdlib/blob/develop/CODE_OF_CONDUCT.md).
- [X] Searched for existing issues and pull requests.
- [X] The issue name begins with `RFC:`.

**Comment by performant23** [comment]
Hi, I'd like to work on this issue!

**Comment by Userf1995** [comment]
@kgryte @Planeshifter I have assaigned no issue at that time,can I work on thise issue.

**Comment by performant23** [comment]
Hi @Rejoan-Sardar, I think the maintainers are yet to accept the issue yet. But then again, if accepted, I have finished the development for the most part. So, could you please explore other issues?

**Comment by Userf1995** [comment]
@performant23 ok sure.

**Comment by Planeshifter** [comment]
@performant23 Given you have almost finished implementation, I just assigned you. Looking forward to the PR!
