### ISSUE TITLE
[RFC]: add C implementation for @stdlib/math/base/special/xlog1py

### ISSUE THREAD

**Issue by Userf1995** [stdlib-js/stdlib#1842]
### Description

This RFC proposes  adding C implementation for @stdlib/math/base/special/xlog1py

### Related Issues

Related issues #649 .

### Questions

No.

### Other

No.

### Checklist

- [X] I have read and understood the [Code of Conduct](https://github.com/stdlib-js/stdlib/blob/develop/CODE_OF_CONDUCT.md).
- [X] Searched for existing issues and pull requests.
- [X] The issue name begins with `RFC:`.

**Comment by Userf1995** [comment]
working on it.

**Comment by Rejoan-Sardar** [comment]
@Planeshifter @kgryte sir wrong line in @stdlib/math/base/special/acoversin/lib/native.js (line no 29).Sir please confrom it.
