### ISSUE TITLE
[RFC]: add C implementation for `math/base/special/cos`

### ISSUE THREAD

**Issue by raunak-dev-edu** [stdlib-js/stdlib#1848]
### Description

This RFC proposes adding C implementation for [@stdlib/math/base/special/cos](https://github.com/stdlib-js/stdlib/blob/develop/lib/node_modules/%40stdlib/math/base/special/cos)

```javascript
double stdlib_base_cos( const double x );
```

### Related Issues

Related issues #649.

### Questions

No.

### Other

No.

### Checklist

- [X] I have read and understood the [Code of Conduct](https://github.com/stdlib-js/stdlib/blob/develop/CODE_OF_CONDUCT.md).
- [X] Searched for existing issues and pull requests.
- [X] The issue name begins with `RFC:`.

**Comment by raunak-dev-edu** [comment]
I would like to work on this issue.

**Comment by Pranavchiku** [comment]
@raunak-dev-edu we cannot do this as it depends on `math/base/special/rempio2` which do not have C implementation yet.

**Comment by raunak-dev-edu** [comment]
@Pranavchiku Thanks for letting me know. I had inital thought that this will not depend on `math/base/special/rempio2`

**Comment by raunak-dev-edu** [comment]
As, this required `math/base/special/rempio2`. So Closing this issue for now.
