### ISSUE TITLE
[RFC]: Add C implementation for `@stdlib/math/base/special/acscd`

### ISSUE THREAD

**Issue by Pushpendra766** [stdlib-js/stdlib#1915]
### Description

This RFC proposes adding C implementation for [@stdlib/math/base/special/acscd](https://github.com/stdlib-js/stdlib/tree/develop/lib/node_modules/%40stdlib/math/base/special/acscd).

### Related Issues

Related issues #649 

### Questions

No.

### Other

The `acscd` package is dependent on `acsc` and `rad2deg` packages, which are already implemented in C, but the `acsc` package is not marked as done in issue #649  

### Checklist

- [X] I have read and understood the [Code of Conduct](https://github.com/stdlib-js/stdlib/blob/develop/CODE_OF_CONDUCT.md).
- [X] Searched for existing issues and pull requests.
- [X] The issue name begins with `RFC:`.

**Comment by Pushpendra766** [comment]
I want to work on this issue.

**Comment by gunjjoshi** [comment]
Hey @Pushpendra766, there is already an open PR #1904 for this.

**Comment by Pushpendra766** [comment]
Oh, my bad, will close it.

**Comment by kgryte** [comment]
Duplicate of https://github.com/stdlib-js/stdlib/issues/1893.
