### ISSUE TITLE
[RFC]: Add C implementation for `@stdlib/math/base/special/atan2`

### ISSUE THREAD

**Issue by Pushpendra766** [stdlib-js/stdlib#1923]
### Description

This RFC proposes adding C implementation for [@stdlib/math/base/special/atan2](https://github.com/stdlib-js/stdlib/tree/develop/lib/node_modules/%40stdlib/math/base/special/atan2).

### Related Issues

Related issues #649 

### Questions

No.

### Other

The `atan2` package is dependent on :-
`isinfinite` , `copysign`, `signbit`, `isnan`, `atan`, `pinf` and `pi`, and all of these packages are already implemented in C.

### Checklist

- [X] I have read and understood the [Code of Conduct](https://github.com/stdlib-js/stdlib/blob/develop/CODE_OF_CONDUCT.md).
- [X] Searched for existing issues and pull requests.
- [X] The issue name begins with `RFC:`.

**Comment by Pushpendra766** [comment]
I want to work on this issue.

**Comment by Planeshifter** [comment]
@Pushpendra766 Thanks! Just assigned you.

**Comment by gawandeabhishek** [comment]
Hey @Planeshifter , I believe the C implementation of atan2 can be added with this code.

double atan2(const double y, const double x) {
    if (x > 0) {
        return atan(y, x);
    } else if (x < 0 && y >= 0) {
        return atan(y, x) + M_PI;
    } else if (x < 0 && y < 0) {
        return atan(y, x) - M_PI;
    } else if (x = 0 && y > 0) {
        return M_PI / 2;
    } else if (x = 0 && y < 0) {
        return -1 * (M_PI / 2);
    } else {
        return 0.0/0.0;
    }
}

**Comment by gawandeabhishek** [comment]
am I correct?

**Comment by kgryte** [comment]
@gawandeabhishek No, that is not the implementation that we want. And as @Pushpendra766 has already been assigned this issue, I suggest volunteering to work on a different issue.

**Comment by gawandeabhishek** [comment]
Ok
