### ISSUE TITLE
[RFC]: Add C implementation for `@stdlib/math/base/special/maxn`

### ISSUE THREAD

**Issue by USERSATOSHI** [stdlib-js/stdlib#1927]
### Description

This RFC proposes adding C implementation for [@stdlib/math/base/special/maxn](https://github.com/stdlib-js/stdlib/tree/develop/lib/node_modules/%40stdlib/math/base/special/maxn).

### Related Issues

Related issues #649.

### Questions

I would like to ask about the syntax of the C implementation, would it follow *variable length argument* via `#include<stdarg.h>` or *array based argument*

#### possible syntax
```c
// variable length
// we need to provide a way to tell stdarg that arguments have ended which is either done by count or an end value
double stdlib_base_maxn( uint32_t count,  ...) // and va_arg(takes them as double)

// or

// array method

double stdlib_base_maxn(double num[], uint32_t size)
```

> if there is way to create JS-like syntax of maxn , i would be grateful if i could get nudge in that direction via an example or resource like
>
> and if there is a better syntax than above , i would be delighted to know

### Other

The `maxn` package is dependent on :-
`is_positive_zero` , `is_nan`, `ninf` and `pinf` ,and all of these packages are already implemented in C.

### Checklist

- [X] I have read and understood the [Code of Conduct](https://github.com/stdlib-js/stdlib/blob/develop/CODE_OF_CONDUCT.md).
- [X] Searched for existing issues and pull requests.
- [X] The issue name begins with `RFC:`.

**Comment by USERSATOSHI** [comment]
Hi, I would like to work on this issue.

**Comment by kgryte** [comment]
This API is **not** a candidate for a C implementation. Thank you for opening the issue; however, we will not be pursuing this at this time.
