### ISSUE TITLE
[RFC]: add C implementation for `@stdlib/math/base/special/fast/uint32-sqrt`

### ISSUE THREAD

**Issue by Userf1995** [stdlib-js/stdlib#1932]
### Description

This RFC proposes add C implementation for `@stdlib/math/base/special/fast/uint32-sqrt`

      uint32_t stdlib_base_fast_uint32_sqrt( uint32_t  x );

### Related Issues

Related issues #1917 .

### Questions

No.

### Other

No.

### Checklist

- [X] I have read and understood the [Code of Conduct](https://github.com/stdlib-js/stdlib/blob/develop/CODE_OF_CONDUCT.md).
- [X] Searched for existing issues and pull requests.
- [X] The issue name begins with `RFC:`.

**Comment by Rejoan-Sardar** [comment]
Hellow,working on it.

**Comment by Pranavchiku** [comment]
Hey @Rejoan-Sardar I will recommend you to first let https://github.com/stdlib-js/stdlib/pulls/Rejoan-Sardar merged. Let this be open and others may work on it. Thank you :)

**Comment by Pranavchiku** [comment]
can you please populate issue description with proper C API and documentation?

**Comment by Userf1995** [comment]
> Hey @Rejoan-Sardar I will recommend you to first let https://github.com/stdlib-js/stdlib/pulls/Rejoan-Sardar merged. Let this be open and others may work on it. Thank you :)

Hey @Pranavchiku I have addressed all the issues and some issues needs review.

**Comment by kgryte** [comment]
The proposed signature is incorrect.

**Comment by gunjjoshi** [comment]
Hey @Rejoan-Sardar, are you still working on this one ?
