### ISSUE TITLE
[RFC]: add C implementation for `@stdlib/math/base/special/rempio2`

### ISSUE THREAD

**Issue by USERSATOSHI** [stdlib-js/stdlib#1933]
### Description

This RFC proposes C implementation for [@stdlib/math/base/special/rempio2](https://github.com/stdlib-js/stdlib/tree/develop/lib/node_modules/%40stdlib/math/base/special/rempio2)

### Related Issues

Related issues #649

### Questions

No.

### Other

this package is dependent on:-

`high-word-abs-mask`, `high-word-exponent-mask`, `high-word-significand-mask`, `get-high-word`, `get-low-word`, `from-words` 

which are already implemented in C

### Checklist

- [X] I have read and understood the [Code of Conduct](https://github.com/stdlib-js/stdlib/blob/develop/CODE_OF_CONDUCT.md).
- [X] Searched for existing issues and pull requests.
- [X] The issue name begins with `RFC:`.

**Comment by USERSATOSHI** [comment]
I have started the implementation, current completed kernel_rempio2 and medium_repio2

**Comment by gunjjoshi** [comment]
Hey @USERSATOSHI , there is already a similar issue #781 for this one.
