### ISSUE TITLE
[RFC]: add C implementation for  `@stdlib/math/base/special/fast/alpha-max-plus-beta-min`

### ISSUE THREAD

**Issue by USERSATOSHI** [stdlib-js/stdlib#1938]
### Description

This RFC proposes will add C implementation for ` alpha-max-plus-beta-min` with following usage:

```c
double stdlib_base_fast_ampbm(const double x, const double y) 
```

~and factory~
~```c~
~FNP factory( const double alpha, const double beta, const bool nonnegative, const bool ints) // where FNP is a @typedef for a function_pointer~
~```~

### Related Issues

Related issues #649 

### Questions

No.

### Other

This pkg is dependent on:

`abs` which is already implemented in C

### Checklist

- [X] I have read and understood the [Code of Conduct](https://github.com/stdlib-js/stdlib/blob/develop/CODE_OF_CONDUCT.md).
- [X] Searched for existing issues and pull requests.
- [X] The issue name begins with `RFC:`.

**Comment by kgryte** [comment]
Thanks for opening this RFC, @USERSATOSHI. I don't think we should implement the factory API in C, only the main export with fixed alpha and beta, as implemented in `lib/main.js`.

**Comment by USERSATOSHI** [comment]
> Thanks for opening this RFC, @USERSATOSHI. I don't think we should implement the factory API in C, only the main export with fixed alpha and beta, as implemented in `lib/main.js`.

@kgryte thanks for informing! As of right now  i will work on the main implementation.
I have also updated the description.
