### ISSUE TITLE
[RFC]: add `math/base/special/asinf`

### ISSUE THREAD

**Issue by gunjjoshi** [stdlib-js/stdlib#1944]
### Description

This RFC proposes adding `math/base/special/asinf`, which would be a single precision implementation for [`math/base/special/asin`](https://github.com/stdlib-js/stdlib/tree/develop/lib/node_modules/%40stdlib/math/base/special/asin).

```C
float stdlib_base_asinf( const float x )
```

### Related Issues

Related issues #649.

### Questions

No.

### Other

No.

### Checklist

- [X] I have read and understood the [Code of Conduct](https://github.com/stdlib-js/stdlib/blob/develop/CODE_OF_CONDUCT.md).
- [X] Searched for existing issues and pull requests.
- [X] The issue name begins with `RFC:`.

**Comment by gunjjoshi** [comment]
I would like to work  on this.

**Comment by gunjjoshi** [comment]
Also, @kgryte, we will need `PI02F` for this. But as of now, the single precision `float32` constant for `pi/2` is not implemented. So, should I first implement that, or should I directly use hardcoded value for that ?

**Comment by kgryte** [comment]
@gunjjoshi Thanks for opening this. This sounds good.

Re: pi/2. In a separate PR, can you add `@stdlib/constants/float32/half-pi`? Should be done similarly to https://github.com/stdlib-js/stdlib/tree/develop/lib/node_modules/%40stdlib/constants/float32/sqrt-eps and https://github.com/stdlib-js/stdlib/tree/develop/lib/node_modules/%40stdlib/constants/float64/half-pi (the float64 equivalent).

**Comment by kgryte** [comment]
I imagine there will be a number of constants missing in `float32` that have `float64` counterparts and will be needed in single-precision implementations.

**Comment by gunjjoshi** [comment]
Yes @kgryte, I will make a separate [PR](https://github.com/stdlib-js/stdlib/pull/1953) for that.

Also, it is correct that we have missing constants in `float32`. We would be definitely needing them in near future, if we're aiming for single precision implementation of more, if not all of the packages in `math/base/special`.
