### ISSUE TITLE
[RFC]: add C implementation for `@stdlib/math/base/special/erfcx`

### ISSUE THREAD

**Issue by USERSATOSHI** [stdlib-js/stdlib#1949]
### Description

This RFC proposes a C implementation for [@stdlib/math/base/special/erfcx](https://github.com/stdlib-js/stdlib/tree/develop/lib/node_modules/%40stdlib/math/base/special/erfcx)

```c
double stdlib_base_erfcx( const double x ) 
```

### Related Issues

Related issues #649 

### Questions

No.

### Other

`@stdlib/math/base/special/erfcx` is dependent on following packages:

* `PINF` : already implemented in C
* `exp` : already implemented in C
* `floor` : already implemented in C

### Checklist

- [X] I have read and understood the [Code of Conduct](https://github.com/stdlib-js/stdlib/blob/develop/CODE_OF_CONDUCT.md).
- [X] Searched for existing issues and pull requests.
- [X] The issue name begins with `RFC:`.

**Comment by USERSATOSHI** [comment]
A question regarding `erfcx_y100.js`, as the [erfcx_y100.js](https://github.com/stdlib-js/stdlib/blob/develop/lib/node_modules/%40stdlib/math/base/special/erfcx/lib/erfcx_y100.js) implements 100 functions and put them in a  lookup table should we try for same approach in C or go for a much simpler switch statement

**Comment by noobCoderVP** [comment]
Hey there, I would like to work on this issue, can you please assign this issue to me?

**Comment by kgryte** [comment]
@USERSATOSHI I think we should be consistent with the JS implementation. From a logic POV, not any more "complex" than a switch statement.

**Comment by USERSATOSHI** [comment]
> @USERSATOSHI I think we should be consistent with the JS implementation. From a logic POV, not any more "complex" than a switch statement.

thank you for responding , I will then implement with lookup table

**Comment by USERSATOSHI** [comment]
I had one more question 

```c
static double erfcxY100( const double y100 ) {
    double t;
    double(*f)(const double);

    t = stdlib_base_floor( y100 );
    f = table[ (int)t ];
    return f( 2*y100 - ((2*t) + 1)  );
}
```

are we allowed to type cast as table needs t as int while floor returns a double accordingly

**Comment by kgryte** [comment]
Yes, that should be fine.

**Comment by USERSATOSHI** [comment]
> Yes, that should be fine.

thank you for informing
