### ISSUE TITLE
mt19937.factory does not accept 0 as a seed

### ISSUE THREAD

**Issue by charredUtensil** [stdlib-js/stdlib#1963]
### Description

Calling `mt19937.factory({seed:0})` causes:
```
factory.js:427 Uncaught TypeError: invalid option. `seed` option must be either a positive integer less than or equal to the maximum unsigned 32-bit integer or an array-like object containing integer values less than or equal to the maximum unsigned 32-bit integer. Option: ``.
    at Function.factory (factory.js:427:1)
    at <anonymous>:1:9
```

However, [the documentation](https://github.com/stdlib-js/random/tree/main/base/mt19937) states the valid range for a seed is `[0, 4294967295]`

I am using the `mt19937` and `beta` libraries to generate pseudorandom values for a [map generator](https://github.com/charredUtensil/groundhog/blob/main/src/core/common/prng.ts). As part of that, I'm actually using `mt19937` to generate random seeds that I feed back into `mt19937` to generate more independent PRNGs, so it's a bit odd that the range of valid seeds is off by 1 from the range of output values. I suspect the documentation is correct and the generator is wrong.

### Related Issues

Related issues # , # , and # .

### Questions

No.

### Reproduction

```shell
import mt19937 from "@stdlib/random-base-mt19937";
mt19937.factory({seed:0})
```
```


### Expected Results

```shell
A working pseudorandom number generator
```

### Actual Results

```shell
factory.js:427 Uncaught TypeError: invalid option. `seed` option must be either a positive integer less than or equal to the maximum unsigned 32-bit integer or an array-like object containing integer values less than or equal to the maximum unsigned 32-bit integer. Option: ``.
    at Function.factory (factory.js:427:1)
    at <anonymous>:1:9
```

### Version

0.2.1

### Environments

Firefox, Chrome

### Checklist

- [X] Read and understood the [Code of Conduct](https://github.com/stdlib-js/stdlib/blob/develop/CODE_OF_CONDUCT.md).
- [X] Searched for existing issues and pull requests.

**Comment by kgryte** [comment]
@charredUtensil I believe the documentation is wrong here and the implementation correct. It is fairly common for PRNGs to not allow `0` seeds, as this can lead to degenerate starting states. From the original paper,

>  Since any initial seed except zero lies on the same orbit, the choice of an initial seed does not affect the randomness for the whole period.

and

> Before using genrand( ), sgenrand( ) must be called with a nonzero unsigned long integer as a seed.

**Comment by kgryte** [comment]
Also, unrelated to the documentation bug, I suggest using a different PRNG for seeding (e.g., `minstd` or `minstd-shuffle`), in order to ensure that your seeds are independent of your implementation.
