### ISSUE TITLE
RFC: add support for evaluating log1mexp(x)

### ISSUE THREAD

**Issue by kgryte** [stdlib-js/stdlib#197]
## Checklist

> Please ensure the following tasks are completed before submitting a feature request.

-   [x] Read and understood the [Code of Conduct][code-of-conduct].
-   [x] Searched for existing issues and pull requests.
-   [x] The issue name begins with `RFC:`.

## Description

> Description of the feature request.

This RFC proposes to add support for evaluating `ln( 1 - exp(x) )` in a more numerically stable manner. The conventional approaches of `log1p( -exp(x) )` and `ln( -exp1m(x) )` are subject to numerically stability issues when `x` approaches `0` and thus `exp(x)` approaches `1` in the former case and when `x` is large and `-exp1m(x)` approaches `1` in the latter case.

The proposed implementation would seek to divide the domain and provide appropriate approximations depending on the regime. In particular,

```text
log1mexp(x) = ln( -expm1(-x) ); when 0 < x <= ln(2)
log1mexp(x) = log1p( -exp(-x) ); when x > ln(2)
```

Package: `@stdlib/math/base/special/log1mexp`
Alias: `log1mexp`

## Related Issues

> Does this feature request have any related issues?

No.

## Questions

> Any questions for reviewers?

No.

## Other

> Any other information relevant to this feature request? This may include screenshots, references, sample output, and/or implementation notes.

For further background, see associated [numerical analysis](https://cran.r-project.org/web/packages/Rmpfr/vignettes/log1mexp-note.pdf).

[code-of-conduct]: https://github.com/stdlib-js/stdlib/blob/develop/CODE_OF_CONDUCT.md

**Comment by kgryte** [comment]
@rei2hu Given your work on #198, do you think you would be up for tackling this one, as well?

**Comment by rei2hu** [comment]
Sure it seems very similar. I actually just came across a problem trying to update my fork.

On line 66 of [`@stdlib/math/base/special/log1pexp/README.md`](https://github.com/stdlib-js/stdlib/blob/develop/lib/node_modules/%40stdlib/math/base/special/log1pexp/README.md) the path to the module should be `@stdlib/math/base/special/log1pexp` instead of `./../lib`.

**Comment by kgryte** [comment]
@rei2hu Awesome!

And yes, I already updated that on my current WIP branch. See [here](https://github.com/stdlib-js/stdlib/commits/misc-wip-kgryte/lib/node_modules/%40stdlib/math/base/special/log1pexp). :)

**Comment by rei2hu** [comment]
Great, I'll start working from there.

**Comment by kgryte** [comment]
To be clear, still work off of `develop`, as my WIP branch is currently broken for other reasons :(.
