### ISSUE TITLE
RFC: add support for evaluating log1pexp(x)

### ISSUE THREAD

**Issue by kgryte** [stdlib-js/stdlib#198]
## Checklist

> Please ensure the following tasks are completed before submitting a feature request.

-   [x] Read and understood the [Code of Conduct][code-of-conduct].
-   [x] Searched for existing issues and pull requests.
-   [x] The issue name begins with `RFC:`.

## Description

> Description of the feature request.

This RFC proposes to add support for evaluating `ln( 1 + exp(x) )` in a more numerically stable manner. The conventional approach is subject to overflow when `x` is large.

The proposed implementation would seek to divide the domain and provide appropriate approximations depending on the regime. In particular,

```text
log1pexp(x) = exp(x); when x <= -37
log1pexp(x) = log1p( exp(x) ); when -37 < x <= 18
log1pexp(x) = x + exp(-x); when 18 < x <= 33.3
log1pexp(x) = x; when x > 33.3
```

Package: `@stdlib/math/base/special/log1pexp`
Alias: `log1pexp`

## Related Issues

> Does this feature request have any related issues?

No.

## Questions

> Any questions for reviewers?

No.

## Other

> Any other information relevant to this feature request? This may include screenshots, references, sample output, and/or implementation notes.

-   For further background, see associated [numerical analysis](https://cran.r-project.org/web/packages/Rmpfr/vignettes/log1mexp-note.pdf).
-   For example usage in `stdlib`, see computing the [`logcdf`](https://github.com/stdlib-js/stdlib/blob/c3198c73a899be3fd20f18b0af507017fca60ff5/lib/node_modules/%40stdlib/math/base/dist/logistic/logcdf/lib/log1pexp.js) for the logistic distribution.

[code-of-conduct]: https://github.com/stdlib-js/stdlib/blob/develop/CODE_OF_CONDUCT.md

**Comment by rei2hu** [comment]
I'll try my hand at doing this.

**Comment by kgryte** [comment]
@rei2hu Awesome! Thanks for working on this!
