### ISSUE TITLE
[RFC]: Add C Implementation for @stdlib/math/base/special/sin

### ISSUE THREAD

**Issue by xaman27x** [stdlib-js/stdlib#2018]
### Description

This RFC proposes adding native C implementation for @stdlib/math/base/special/sin
`double stdlib_base_sin ( const double x );`

### Related Issues

Issue Tracker: https://github.com/stdlib-js/stdlib/issues/649

### Questions

No.

### Other

No.

### Checklist

- [X] I have read and understood the [Code of Conduct](https://github.com/stdlib-js/stdlib/blob/develop/CODE_OF_CONDUCT.md).
- [X] Searched for existing issues and pull requests.
- [X] The issue name begins with `RFC:`.

**Comment by xaman27x** [comment]
Would like to work on this if approved by the moderators and mentors, as it would simplify the implementation process of `@stdlib/math/base/special/tan` and `@stdlib/math/base/special/cot` functions!

**Comment by Planeshifter** [comment]
@xaman27x Assigned you, thanks for working on this! You want to first make sure that all packages needed for the implementation have C implementations yet. I know we have `kernel-sin` and `kernel-cos`. In case any packages is missing, please create a new one for the missing C implementation and reference it in this one.

**Comment by xaman27x** [comment]
> @xaman27x Assigned you, thanks for working on this! You want to first make sure that all packages needed for the implementation have C implementations yet. I know we have `kernel-sin` and `kernel-cos`. In case any packages is missing, please create a new one for the missing C implementation and reference it in this one.

Sure thing! I'll look into that.
