### ISSUE TITLE
[RFC]: add C implementation for @stdlib/node_modules/math/base/special/rempio2

### ISSUE THREAD

**Issue by xaman27x** [stdlib-js/stdlib#2038]
### Description

This RFC proposes to add C implementation for `math/base/special/rempio2` function, to facilitate itself and the implementations of other dependent functions as well!

### Related Issues

Issue Tracker: https://github.com/stdlib-js/stdlib/issues/649

### Questions

No.

### Other

No.

### Checklist

- [X] I have read and understood the [Code of Conduct](https://github.com/stdlib-js/stdlib/blob/develop/CODE_OF_CONDUCT.md).
- [X] Searched for existing issues and pull requests.
- [X] The issue name begins with `RFC:`.

**Comment by xaman27x** [comment]
If approved, would like to work on this!

**Comment by USERSATOSHI** [comment]
Hi @xaman27x, there is an already existing issue regarding this

Link -> [[RFC]: Add C implementation for @stdlib/math/base/special/rempio2](https://github.com/stdlib-js/stdlib/issues/781)
