### ISSUE TITLE
[RFC]: add support for whole command insertion when pressing up/down in the REPL

### ISSUE THREAD

**Issue by kgryte** [stdlib-js/stdlib#2070]
### Description

This RFC proposes changing the default behavior in the REPL such that, when hitting the up/down arrow, an entire command is inserted, rather than just a line.

Currently, if you enter multi-line input

```
In [1]: function foo() {
    // ...
};

In [2]: <|>
```

and hit the up arrow, you get

```
In [2]:    };
```

This may be useful, but it is likely not what you want. Instead, you'd probably prefer to cycle through the entire command. In which case, when we press the UP arrow, we'd like to re-enter multi-line mode with the entirety of the previous command.

Note that currently we rely on built-in readline/REPL history behavior. In order to support this feature, we may need to maintain our own history record and capture key presses in order to efficiently cycle through entire previous commands.

### Related Issues

- Reverse search is related: https://github.com/stdlib-js/stdlib/issues/2069

### Questions

- Should this be configurable?
- Should we support a mode (e.g., via a modifier key) to allow single-line insertion, as currently supported?

### Other

No.

### Checklist

- [X] I have read and understood the [Code of Conduct](https://github.com/stdlib-js/stdlib/blob/develop/CODE_OF_CONDUCT.md).
- [X] Searched for existing issues and pull requests.
- [X] The issue name begins with `RFC:`.

**Comment by Snehil-Shah** [comment]
Should we allow cycling through failed commands? I think yes as the user can quickly bring it up and fix/edit it further (?)

**Comment by kgryte** [comment]
Yes, I think that makes sense.

**Comment by Snehil-Shah** [comment]
In other REPLs and in built-in readline, this feature only works when hitting the up arrow when the cursor is at the start of the command. In IPython, I think they have the ability to filter as well. Say I type `he` and now I hit up arrow, commands only starting with `he` comes up. Something like this is proposed in #2069.

**Comment by kgryte** [comment]
I think it only working when cursor is at the start of the line makes sense. I believe this is the same behavior as in the terminal.

For filtering, yeah, this should be reserved for reverse search.

**Comment by Snehil-Shah** [comment]
Wait, I think built-in readline also does it similar to IPython. `h<|>` and pressing the up arrow would bring up history starting with `h`. Should I stick with this?

**Comment by kgryte** [comment]
Seems okay.
