### ISSUE TITLE
[RFC]: add `math/base/special/acosf`

### ISSUE THREAD

**Issue by gunjjoshi** [stdlib-js/stdlib#2081]
### Description

This RFC proposes adding `math/base/special/acosf`, which would be a single precision implementation for [`math/base/special/acos`](https://github.com/stdlib-js/stdlib/tree/develop/lib/node_modules/%40stdlib/math/base/special/acos).

```C
float stdlib_base_acosf( const float x )
```

### Related Issues

None.

### Questions

No.

### Other

No.

### Checklist

- [X] I have read and understood the [Code of Conduct](https://github.com/stdlib-js/stdlib/blob/develop/CODE_OF_CONDUCT.md).
- [X] Searched for existing issues and pull requests.
- [X] The issue name begins with `RFC:`.

**Comment by gunjjoshi** [comment]
I would like to work on this.

**Comment by kgryte** [comment]
Assigned.
