### ISSUE TITLE
[RFC]: Add C implementation for `@stdlib/math/base/special/tan`

### ISSUE THREAD

**Issue by anirudhprabhakaran3** [stdlib-js/stdlib#2090]
### Description

This RFC proposes adding a C implementation for [`@stdlib/math/base/special/tan`](https://github.com/stdlib-js/stdlib/tree/develop/lib/node_modules/%40stdlib/math/base/special/tan)

### Related Issues

Helps resolve #649 and unblocks #1663 

### Questions

No.

### Other

No.

### Checklist

- [X] I have read and understood the [Code of Conduct](https://github.com/stdlib-js/stdlib/blob/develop/CODE_OF_CONDUCT.md).
- [X] Searched for existing issues and pull requests.
- [X] The issue name begins with `RFC:`.

**Comment by kgryte** [comment]
This RFC depends on `rempio2` which is not yet implemented in C.

**Comment by kgryte** [comment]
This has now been implemented. Closing...
