### ISSUE TITLE
[RFC]: Add C implementtation for `@stdlib/math/base/special/factorial`

### ISSUE THREAD

**Issue by anirudhprabhakaran3** [stdlib-js/stdlib#2094]
### Description

This RFC proposes adding C implementation for [`@stdlib/math/base/special/factorial`](https://github.com/stdlib-js/stdlib/tree/develop/lib/node_modules/%40stdlib/math/base/special/factorial)

### Related Issues

Helps progress #649 

### Questions

No.

### Other

No.

### Checklist

- [X] I have read and understood the [Code of Conduct](https://github.com/stdlib-js/stdlib/blob/develop/CODE_OF_CONDUCT.md).
- [X] Searched for existing issues and pull requests.
- [X] The issue name begins with `RFC:`.

**Comment by anirudhprabhakaran3** [comment]
This is blocked because C implementation for [`@stdlib/math/base/special/gamma`](https://github.com/stdlib-js/stdlib/tree/develop/lib/node_modules/%40stdlib/math/base/special/gamma) does not exist yet.

**Comment by gunjjoshi** [comment]
We can close this now, it has been completed by #2618.
