### ISSUE TITLE
[RFC]: add `math/base/special/acotf`

### ISSUE THREAD

**Issue by gunjjoshi** [stdlib-js/stdlib#2113]
### Description

This RFC proposes adding `math/base/special/acotf`, which would be the single-precision equivalent of [`math/base/special/acot`](https://github.com/stdlib-js/stdlib/tree/develop/lib/node_modules/%40stdlib/math/base/special/acot).

```C
float stdlib_base_acotf( const float x )
```

### Related Issues

None.

### Questions

No.

### Other

No.

### Checklist

- [X] I have read and understood the [Code of Conduct](https://github.com/stdlib-js/stdlib/blob/develop/CODE_OF_CONDUCT.md).
- [X] Searched for existing issues and pull requests.
- [X] The issue name begins with `RFC:`.

**Comment by gunjjoshi** [comment]
I'd like to work on this.

**Comment by gunjjoshi** [comment]
Hey @kgryte, while implementing this, I got to know that, since we require `atanf` for this, and upon passing `-infinity` to `acotf`, or `-0` to `atanf`, our `atanf` returns `0`, instead of `-0`. This applies for both [C](https://github.com/stdlib-js/stdlib/blob/develop/lib/node_modules/%40stdlib/math/base/special/atanf/src/main.c) and [JavaScript](https://github.com/stdlib-js/stdlib/blob/develop/lib/node_modules/%40stdlib/math/base/special/atanf/lib/main.js) implementations of `atanf`.

This leads to the failure of one particular test case, which checks if `the function returns "-0" if provided "-infinity"`.

**Comment by gunjjoshi** [comment]
In the case of current `acot`, this problem doesn't arise, but it does come up in case of `acotf`.

**Comment by kgryte** [comment]
Which behavior is the correct behavior?

**Comment by gunjjoshi** [comment]
The correct behavior is that of `acot`, i.e, it returns `-0` when provided `-infinity`.

Applying the same implementation for `acotf`, this fails.

**Comment by kgryte** [comment]
The question is more fundamental. Should `atan` distinguish between signed zeros? This is a mathematical question.

**Comment by kgryte** [comment]
It's possible, e.g., that the tests for `acot` are incorrect, but this gets back to what the behavior of `atan` should be.

**Comment by kgryte** [comment]
We get our answer from http://www.dsc.ufcg.edu.br/~cnum/modulos/Modulo2/IEEE754_2008.pdf

> For the functions expm1, exp2m1, exp10m1, logp1, log2p1, log10p1, sin, tan, sinPi, atanPi, asin, atan, sinh, tanh, asinh, and atanh, f (+0) is +0 and f (−0) is −0 with no exception.

Meaning, `atanf` is incorrect here.

**Comment by gunjjoshi** [comment]
When I checked logging the values with `atan`, it returns:

```
atan( -0 ) = -0
atan( +0 ) = 0
```

**Comment by kgryte** [comment]
Yes, but we should not just rely on what the current behavior is in stdlib, as the current behavior could be wrong. In this case, we need to consult the specification to ensure that our current `atan` behavior adheres to IEEE 754 semantics.

In this case, it does. Which just means that our current `atanf` implementation does not handle signed zero correctly.

**Comment by gunjjoshi** [comment]
Yes, and also, upon doing the same for `atanf`, it gives `0` in both cases. 

We might need to modify our `atanf` implementation.

**Comment by kgryte** [comment]
The reason it doesn't is pretty straightforward. We just need to make a small modification to `atanf` which we can observe in `atan`. Namely, the following

https://github.com/stdlib-js/stdlib/blob/edc9c69f219cd5bdcf08fe2f2bf0f03c191776b0/lib/node_modules/%40stdlib/math/base/special/atanf/lib/main.js#L89

should be modified to

```diff
if ( isnanf( x ) ) {
+ if ( isnanf( x ) || x === 0.0 ) {
+    return x;
```

This is a bug in the original Cephes implementation. You'll want to fix in both our JS and C `atanf` implementations.

**Comment by kgryte** [comment]
When you make patch, can you also add corresponding tests to `atanf`?

**Comment by gunjjoshi** [comment]
Sure, I'll do it. Should this be added in the same PR as that of `acotf`, or a seperate one ?

**Comment by kgryte** [comment]
I suggest making a quick patch in a separate PR to keep things clean.

**Comment by gunjjoshi** [comment]
Great, I'll follow that. Thanks for clearing this out. 
This can be a nice example for why we shouldn't rely on just one source, like `cephes`.

**Comment by kgryte** [comment]
Indeed! And the importance of tests! We are apparently missing corresponding tests in `atan`, as well. You can include those in your patch.
