### ISSUE TITLE
[RFC]: add stdlib ASCII art in REPL's default welcome message

### ISSUE THREAD

**Issue by Snehil-Shah** [stdlib-js/stdlib#2175]
### Description

This RFC proposes adding a stdlib ASCII art in the default welcome message in the REPL.

I think it looks cool:

![stdlibjs](https://github.com/stdlib-js/stdlib/assets/130062020/eacd73df-601b-484f-83dd-55e96225e017)

![stdlib](https://github.com/stdlib-js/stdlib/assets/130062020/f5da9189-e019-4c6f-a991-ecdb8930c3c0)

*The above ASCII art was generated using [this](https://patorjk.com/software/taag/#p=display&f=Standard&t=stdlib-js) website*

### Related Issues

None

### Questions

No.

### Other

Inspired by the Julia REPL and many other CLI applications.

### Checklist

- [X] I have read and understood the [Code of Conduct](https://github.com/stdlib-js/stdlib/blob/develop/CODE_OF_CONDUCT.md).
- [X] Searched for existing issues and pull requests.
- [X] The issue name begins with `RFC:`.

**Comment by kgryte** [comment]
@Snehil-Shah We had this as an internal TODO with a link to the same website, so I am okay with moving this forward. My personal preference is the latter ASCII. We typically don't include `-js` or `.js` in our branding, as we don't consider the project just a JavaScript project.

Similar to Julia, you might consider a few different layouts. Say, with a link to our docs and the tag line to the right of the ASCII art.

Feel free to propose other layouts and submit a PR adding this.
