### ISSUE TITLE
[RFC]: add support for computing the secant (sec)

### ISSUE THREAD

**Issue by kgryte** [stdlib-js/stdlib#225]
## Checklist

> Please ensure the following tasks are completed before submitting a feature request.

-   [x] Read and understood the [Code of Conduct][code-of-conduct].
-   [x] Searched for existing issues and pull requests.
-   [x] The issue name begins with `RFC:`.

## Description

> Description of the feature request.

This RFC proposes adding support for computing the secant. The initial implementation is straightforward:

```javascript
return 1.0 / cos( x );
```

Package: `@stdlib/math/base/special/sec`
Alias: `base.sec`

## Related Issues

> Does this feature request have any related issues?

No.

## Questions

> Any questions for reviewers?

No.

## Other

> Any other information relevant to this feature request? This may include screenshots, references, sample output, and/or implementation notes.

Reference implementations:

-   [Julia](https://github.com/JuliaLang/julia/blob/dee7d77c199c4776cf4e06afb7ce920f09ad3c8c/base/special/trig.jl#L958)

[code-of-conduct]: https://github.com/stdlib-js/stdlib/blob/develop/CODE_OF_CONDUCT.md

**Comment by Tranced** [comment]
Would be great if you could assign this to me. The other mathematical functions seem like low hanging fruit too but it would be better to knock out one first.

**Comment by Planeshifter** [comment]
Awesome, thanks for your willingness to work on this! Just assigned you.

**Comment by kgryte** [comment]
@Tranced See [`acoth`](https://github.com/stdlib-js/stdlib/tree/develop/lib/node_modules/%40stdlib/math/base/special/acoth) for a package on which you can model your implementation.

**Comment by kgryte** [comment]
Unassigning this issue so other contributors can feel free to work on this.

**Comment by yashshah1** [comment]
Can I work on this?

**Comment by kgryte** [comment]
@yashshah1 Sure! Go for it! Feel free to ping here or on Gitter if you encounter any issues or have any questions!

**Comment by Hritik1503** [comment]
I am interested to work on this issue under Quine. So please assign me this task to me.

**Comment by fady228** [comment]
@kgryte @Planeshifter assign this issue to me please

**Comment by Planeshifter** [comment]
@fady228 Sure, thanks for looking into adding this package!

**Comment by AbhijitRaut04** [comment]
@Planeshifter Is this issue open currently?

**Comment by Planeshifter** [comment]
@AbhijitRaut04 The package has not been added to `stdlib` (nor is there an open PR) and we have moved away from assigning issues, so please feel free to send a PR! Looking forward to your contribution!

**Comment by AbhijitRaut04** [comment]
@Planeshifter I am a beginner. I have cloned repo after forking into my environment. I am little bit confused about where to write my code. So, Can you please tell me where to write code about this secant function?

**Comment by Planeshifter** [comment]
@AbhijitRaut04 The code should live in the `lib/node_modules/@stdlib/math/base/special/sec` directory.

**Comment by AbhijitRaut04** [comment]
how can i use the functions sin, cos, tan ?

**Comment by kgryte** [comment]
@AbhijitRaut04 I suggest spending some time reading the code of other packages in `@stdlib/math/base/special`. There are plenty of examples of packages using the functionality you describe.

**Comment by AbhijitRaut04** [comment]
@Planeshifter 
@kgryte 
I have raised PR, are there any changes required for secant function ?

**Comment by AbhijitRaut04** [comment]
![Image](https://github.com/user-attachments/assets/67acc179-5eca-4aaa-a1d7-de2966bdb06c)
@Planeshifter Can you tell me how to resolve this issue ?

**Comment by AbhijitRaut04** [comment]
@kgryte  Where can I get the test cases for secant ?

**Comment by AbhijitRaut04** [comment]
@Planeshifter  @kgryte  I have implemented the code for calculating sec. Now I have to add test cases to check whether the function is working fine or not. So for this purpose where can I get the test cases and expected values to check over.
