### ISSUE TITLE
`example` command hanging in REPL when executing multi-line code

### ISSUE THREAD

**Issue by Planeshifter** [stdlib-js/stdlib#2273]
### Description

Encountered an error when trying to run `example( <alias> )` in the REPL, which runs the example code from the respective package's `repl.txt` file. The error seems to occur when the example code spans multiple lines.

### Related Issues

None.

### Questions

No.

### Reproduction

```shell
- `make repl` to start the REPL from the top-level directory
- `example( ttest )` to run the example code for the Student's t test
```

### Expected Results

```shell
All example code in https://github.com/stdlib-js/stdlib/blob/develop/lib/node_modules/%40stdlib/stats/ttest/docs/repl.txt should be printed.
```

### Actual Results

```shell
In [1]: example(ttest)

In [2]: var rnorm = base.random.normal.factory( 0.0, 2.0, { 'seed': 5776 } );

In [3]: var x = new Array( 100 );

In [4]: for ( var i = 0; i < x.length; i++ ) {
```

### Version

0.2.0

### Environments

Node.js

### Checklist

- [X] Read and understood the [Code of Conduct](https://github.com/stdlib-js/stdlib/blob/develop/CODE_OF_CONDUCT.md).
- [X] Searched for existing issues and pull requests.

**Comment by kgryte** [comment]
@Snehil-Shah This is still broken, I believe. Would you mind taking a look?

**Comment by kgryte** [comment]
When I attempt to run `example(ttest)`, the REPL just crashes.
