### ISSUE TITLE
[RFC]: add `@stdlib/math/base/special/nanmax`

### ISSUE THREAD

**Issue by kgryte** [stdlib-js/stdlib#2317]
### Description

This RFC proposes adding the package `@stdlib/math/base/special/nanmax`. If one operand is `NaN`, the other operand is always returned; otherwise, perform normal maximum (e.g., by calling `@stdlib/math/base/special/max`).

```javascript
var m = nanmax( 3.0, 4.0 );
// returns 4.0

m = nanmax( NaN, 4.0 );
// returns 4.0

m = nanmax( 3.0, NaN );
// returns 3.0

m = nanmax( NaN, NaN );
// returns NaN
```

Package: `@stdlib/math/base/special/nanmax`
Alias: `nanmax`

### Related Issues

None.

### Questions

No.

### Other

No.

### Checklist

- [X] I have read and understood the [Code of Conduct](https://github.com/stdlib-js/stdlib/blob/develop/CODE_OF_CONDUCT.md).
- [X] Searched for existing issues and pull requests.
- [X] The issue name begins with `RFC:`.

**Comment by RidamGarg** [comment]
I'd like to work on this. @kgryte

**Comment by kgryte** [comment]
@RidamGarg I suggest first submitting a PR for #2318 and getting that merged, before moving on to work on this one.

**Comment by RidamGarg** [comment]
I generated the PR for #2318 issue. Can you please review that?

**Comment by RidamGarg** [comment]
@kgryte Should I start working on this now?

**Comment by kgryte** [comment]
Yes, go for it!

**Comment by RidamGarg** [comment]
@kgryte Generated The PR https://github.com/stdlib-js/stdlib/pull/2358
