### ISSUE TITLE
[RFC]: add `@stdlib/math/base/special/nanmin`

### ISSUE THREAD

**Issue by kgryte** [stdlib-js/stdlib#2318]
### Description

This RFC proposes adding the package `@stdlib/math/base/special/nanmin`. If one operand is `NaN`, the other operand is always returned; otherwise, perform normal minimum (e.g., by calling `@stdlib/math/base/special/min`).

```javascript
var m = nanmin( 3.0, 4.0 );
// returns 3.0

m = nanmin( NaN, 4.0 );
// returns 4.0

m = nanmin( 3.0, NaN );
// returns 3.0

m = nanmin( NaN, NaN );
// returns NaN
```

Package: `@stdlib/math/base/special/nanmin`
Alias: `nanmin`

### Related Issues

None.

### Questions

No.

### Other

No.

### Checklist

- [X] I have read and understood the [Code of Conduct](https://github.com/stdlib-js/stdlib/blob/develop/CODE_OF_CONDUCT.md).
- [X] Searched for existing issues and pull requests.
- [X] The issue name begins with `RFC:`.

**Comment by RidamGarg** [comment]
I'd like to work on this. @kgryte

**Comment by kgryte** [comment]
@RidamGarg Great! I'll go ahead and assign you. Feel free to submit a PR adding the functionality. See https://github.com/stdlib-js/stdlib/tree/develop/lib/node_modules/%40stdlib/math/base/special/min for a similar package. I suggest copying that package and then making modifications accordingly.

**Comment by RidamGarg** [comment]
Thanks for sharing @kgryte. I'll refer to it & make the required changes.

**Comment by RidamGarg** [comment]
https://github.com/stdlib-js/stdlib/pull/2342
@kgryte made the required changes & Generated the PR request.

**Comment by RidamGarg** [comment]
Hello, @kgryte  I am facing an issue. I copy pasted the repl.text file from @stdlib/math/base/special/min to @stdlib/math/base/special/nanmin but when i am trying to commit it. It's throwing me some linting error. I am not able to solve that
![image](https://github.com/stdlib-js/stdlib/assets/67867319/5820d202-ceb8-4909-a81d-18d49bfe2de0)
![image](https://github.com/stdlib-js/stdlib/assets/67867319/08b4161d-459e-4334-8c3f-1f325d6b0db1)

**Comment by kgryte** [comment]
@Planeshifter Do you see anything obvious? Not immediately clear to me.

**Comment by RidamGarg** [comment]
One more thing  Can You please tell me? How Can I check these linting errors on my system? What command do I need to run?

**Comment by adityacodes30** [comment]
> One more thing Can You please tell me? How Can I check these linting errors on my system? What command do I need to run?

Linting should run automatically pre commit on staged files , make sure to run `make init` to initialise your environment

**Comment by RidamGarg** [comment]
Thanks for sharing the info @adityacodes30
