### ISSUE TITLE
[RFC]: add `@stdlib/array/base/cuany`

### ISSUE THREAD

**Issue by kgryte** [stdlib-js/stdlib#2319]
### Description

This RFC proposes adding the package `@stdlib/array/base/cuany`, which cumulatively tests whether at least one array element in a provided array is truthy. The function should return a new generic array. The package should also provide an `#assign` API for setting output values in a provided output array.

```javascript
var x = [ false, false, true, false, false ];

var y1 = cuany( x );
// returns [ false, false, true, true, true ]

var y2 = [ false, null, false, null, false, null, false, null, false, null ];
var out = cuany.assign( x, y2, 2, 0 );
// returns [ false, null, false, null, true, null, true, null, true, null ]
```

where the `assign` API supports an offset and stride (see, e.g., `@stdlib/array/base/take`).

Both APIs should support accessor arrays (see, e.g., `@stdlib/array/base/take`).

### Related Issues

No.

### Questions

No.

### Other

No.

### Checklist

- [X] I have read and understood the [Code of Conduct](https://github.com/stdlib-js/stdlib/blob/develop/CODE_OF_CONDUCT.md).
- [X] Searched for existing issues and pull requests.
- [X] The issue name begins with `RFC:`.

**Comment by adityacodes30** [comment]
I'd like to take this up

**Comment by kgryte** [comment]
@adityacodes30 Sounds good! Thanks for volunteering to work on this!

**Comment by adityacodes30** [comment]
in the cuany api - the return type would be a accessor array or a indexed one ? provided the input was an accessor one

**Comment by kgryte** [comment]
@adityacodes30 For the main export, the return type should be a "generic" array (e.g., `[ true, false, true ]`; i.e., `Array<boolean>`). For the `assign` API attached to the main export, the return type should be whatever the input array is (see, e.g., https://github.com/stdlib-js/stdlib/blob/3cf2e897adf5128f94bd7279e88ca9d42dfe7caa/lib/node_modules/%40stdlib/array/empty-like/docs/types/index.d.ts#L67).

**Comment by adityacodes30** [comment]
I have question to as to how to export a particular function in an export to use it for the api as in - 

i have 2 function and one main function in main.js named indexed , accessor and cuany (the export)

now i need to use cuany in my assign.js but that doesnt work because of the arraylike2object conversions to support accessor arrays , i want to use the accessor function in my assign api . what are the conventions for doing that and how should i go about it ?

**Comment by kgryte** [comment]
@adityacodes30 I suggest exploring the variety of implementations in `array/base/*`, as you are likely to find something which is applicable for what you are trying to do. At a high level, my sense is that the main export should actually be using the implementations in `assign.js`, rather than the other way around. The main export should allocate a generic array filled with `false` values using `@stdlib/array/base/filled`. That allocated array should then be passed along to the assign implementation as the output array.
