### ISSUE TITLE
[RFC]: add `@stdlib/array/base/cusome`

### ISSUE THREAD

**Issue by kgryte** [stdlib-js/stdlib#2322]
### Description

This RFC proposes adding the package `@stdlib/array/base/cusome`, which cumulatively tests whether at least `n` array elements in a provided array are truthy. The function should return a new generic array. The package should also provide an `#assign` API for setting output values in a provided output array.

```javascript
var x = [ false, false, false, true, true ];

var y1 = cusome( x, 2 );
// returns [ false, false, false, false, true ]

var y2 = [ false, null, false, null, false, null, false, null, false, null ];
var out = cusome.assign( x, 2, y2, 2, 0 );
// returns [ false, null, false, null, false, null, false, null, true, null ]
```

where the `assign` API supports an offset and stride (see, e.g., `@stdlib/array/base/take`).

Both APIs should support accessor arrays (see, e.g., `@stdlib/array/base/take`).

### Related Issues

No.

### Questions

No.

### Other

No.

### Checklist

- [X] I have read and understood the [Code of Conduct](https://github.com/stdlib-js/stdlib/blob/develop/CODE_OF_CONDUCT.md).
- [X] Searched for existing issues and pull requests.
- [X] The issue name begins with `RFC:`.

**Comment by vr-varad** [comment]
@kgryte feeling great to be here again!!!
I wanted to work on this issue.

**Comment by kgryte** [comment]
@vr-varad Thanks for volunteering to work on this. Feel free to submit a PR. There's already some precedent with `array/base/cuevery` and `array/base/cuany`.
