### ISSUE TITLE
[RFC]: add `@stdlib/array/base/cuany-by`

### ISSUE THREAD

**Issue by kgryte** [stdlib-js/stdlib#2323]
### Description

This RFC proposes adding the package `@stdlib/array/base/cuany-by`, which cumulatively tests whether at least one array element in a provided array passes a test implemented by a predicate function. The function should return a new generic array. The package should also provide an `#assign` API for setting output values in a provided output array.

```javascript
function isPositive( value ) {
	return ( value > 0 );
}

var x = [ 0, 0, 0, 1, 0 ];

var y1 = cuanyBy( x, isPositive );
// returns [ false, false, false, true, true ]

var y2 = [ false, null, false, null, false, null, false, null, false, null ];
var out = cuanyBy.assign( x, y2, 2, 0, isPositive );
// returns [ false, null, false, null, false, null, true, null, true, null ]

var bool = ( out === y2 );
// returns true
```

where the `assign` API supports an offset and stride (see, e.g., `@stdlib/array/base/take`).

Both APIs should support accessor arrays (see, e.g., `@stdlib/array/base/take`).

### Related Issues

No.

### Questions

No.

### Other

- See also `@stdlib/array/base/any-by`

### Checklist

- [X] I have read and understood the [Code of Conduct](https://github.com/stdlib-js/stdlib/blob/develop/CODE_OF_CONDUCT.md).
- [X] Searched for existing issues and pull requests.
- [X] The issue name begins with `RFC:`.

**Comment by adityacodes30** [comment]
i would like to take this up

**Comment by kgryte** [comment]
@adityacodes30 Thanks for volunteering to work on this. Assigned. :)

**Comment by yaswanthkosuru** [comment]
i am working on issue .i have algorithm in hand but to write w.r.t existing code it was taking time.I will open PR  with in 48 hours
