### ISSUE TITLE
[RFC]: add `@stdlib/array/base/cuevery-by`

### ISSUE THREAD

**Issue by kgryte** [stdlib-js/stdlib#2324]
### Description

This RFC proposes adding the package `@stdlib/array/base/cuevery-by`, which cumulatively tests whether every array element in a provided array passes a test implemented by a predicate function. The function should return a new generic array. The package should also provide an `#assign` API for setting output values in a provided output array.

```javascript
function isPositive( value ) {
	return ( value > 0 );
}

var x = [ 1, 1, 1, 0, 1 ];

var y1 = cueveryBy( x, isPositive );
// returns [ true, true, true, false, false ]

var y2 = [ false, null, false, null, false, null, false, null, false, null ];
var out = cueveryBy.assign( x, y2, 2, 0, isPositive );
// returns [ true, null, true, null, true, null, false, null, false, null ]

var bool = ( out === y2 );
// returns true
```

where the `assign` API supports an offset and stride (see, e.g., `@stdlib/array/base/take`).

Both APIs should support accessor arrays (see, e.g., `@stdlib/array/base/take`).

### Related Issues

No.

### Questions

No.

### Other

- See also `@stdlib/array/base/every-by`

### Checklist

- [X] I have read and understood the [Code of Conduct](https://github.com/stdlib-js/stdlib/blob/develop/CODE_OF_CONDUCT.md).
- [X] Searched for existing issues and pull requests.
- [X] The issue name begins with `RFC:`.

**Comment by Naresh-kumar-Thodupunoori** [comment]
@kgryte May I work on this!?

**Comment by Indrajeety993648** [comment]
@kgryte I love to work on this  Please assign it to me

**Comment by mayank1365** [comment]
@kgryte please assign this issue to me.
