### ISSUE TITLE
[RFC]: add `@stdlib/array/base/cusome-by`

### ISSUE THREAD

**Issue by kgryte** [stdlib-js/stdlib#2326]
### Description

This RFC proposes adding the package `@stdlib/array/base/cusome-by`, which cumulatively tests whether at least `n` array elements in a provided array passes a test implemented by a predicate function. The function should return a new generic array. The package should also provide an `#assign` API for setting output values in a provided output array.

```javascript
function isPositive( value ) {
	return ( value > 0 );
}

var x = [ 0, 0, 0, 1, 1 ];

var y1 = cusomeBy( x, 2, isPositive );
// returns [ false, false, false, false, true ]

var y2 = [ false, null, false, null, false, null, false, null, false, null ];
var out = cusomeBy.assign( x, 2, y2, 2, 0, isPositive );
// returns [ false, null, false, null, false, null, false, null, true, null ]

var bool = ( out === y2 );
// returns true
```

where the `assign` API supports an offset and stride (see, e.g., `@stdlib/array/base/take`).

Both APIs should support accessor arrays (see, e.g., `@stdlib/array/base/take`).

### Related Issues

No.

### Questions

No.

### Other

- See also `@stdlib/utils/some-by`

### Checklist

- [X] I have read and understood the [Code of Conduct](https://github.com/stdlib-js/stdlib/blob/develop/CODE_OF_CONDUCT.md).
- [X] Searched for existing issues and pull requests.
- [X] The issue name begins with `RFC:`.

**Comment by Naresh-kumar-Thodupunoori** [comment]
May I work on this!

**Comment by Aarya01Patil** [comment]
@kgryte May i work on this issue ?

**Comment by UtkershBasnet** [comment]
I'd like to work on this issue

**Comment by Indrajeety993648** [comment]
@kgryte  Please assign it to me . I would like to work on this issue .

**Comment by srivastavaarpit977** [comment]
@kgryte plz assign this issue to me!!
