### ISSUE TITLE
[RFC]: add `@stdlib/array/base/cuevery-by-right`

### ISSUE THREAD

**Issue by kgryte** [stdlib-js/stdlib#2328]
### Description

This RFC proposes adding the package `@stdlib/array/base/cuevery-by-right`, which cumulatively tests whether every array element in a provided array passes a test implemented by a predicate function, while iterating from right-to-left. The function should return a new generic array. The package should also provide an `#assign` API for setting output values in a provided output array.

```javascript
function isPositive( value ) {
	return ( value > 0 );
}

var x = [ 0, 0, 1, 1, 1 ];

var y1 = cueveryByRight( x, isPositive );
// returns [ true, true, true, false, false ]

var y2 = [ false, null, false, null, false, null, false, null, false, null ];
var out = cueveryByRight.assign( x, y2, 2, 0, isPositive );
// returns [ true, null, true, null, true, null, false, null, false, null ]

var bool = ( out === y2 );
// returns true
```

where the `assign` API supports an offset and stride (see, e.g., `@stdlib/array/base/take`). Note that, by iterating from right to left, the values in the output array are equivalent to having first reversed the input array `x` and then using left-to-right iteration.

Both APIs should support accessor arrays (see, e.g., `@stdlib/array/base/take`).

### Related Issues

No.

### Questions

No.

### Other

- See also `@stdlib/array/base/every-by-right`

### Checklist

- [X] I have read and understood the [Code of Conduct](https://github.com/stdlib-js/stdlib/blob/develop/CODE_OF_CONDUCT.md).
- [X] Searched for existing issues and pull requests.
- [X] The issue name begins with `RFC:`.

**Comment by Naresh-kumar-Thodupunoori** [comment]
May I work on this!?

**Comment by siddharthbaleja7** [comment]
I would like to solve this issue.Could you please assign this issue to me?

**Comment by kgryte** [comment]
@siddharthbaleja7 Thank you for volunteering to work on this. Please feel free to submit a PR implementing this feature.

**Comment by BarryByte** [comment]
@kgryte I'm interested in taking on the task of implementing the @stdlib/array/base/cuevery-by-right package. Here’s a brief outline of how I plan to approach it:

Understanding the Task: I’ll start by thoroughly reading the contributing guidelines, Code of Conduct, and license policy to ensure I'm aligned with the project's standards and practices.

Setting Up the Environment: I’ll set up my local development environment following the provided instructions. If necessary, I’ll use the pre-configured development containers to streamline the process.

Reviewing the Codebase: I’ll review similar packages like @stdlib/array/base/cuevery-by-right and @stdlib/array/base/take to understand the existing conventions and implementations.

Implementation Plan:

cueveryByRight Function: Implement the function to iterate from right-to-left, applying the predicate, and returning a new array with the results.
assign API: Extend the function to support assigning values to a provided output array, including handling offset and stride.
Accessor Arrays: Ensure both APIs support accessor arrays.
Testing and Documentation: I’ll write tests to cover various scenarios and document the package thoroughly to ensure it’s easy to use and understand.

I’ll make sure to follow all the contributing guidelines and submit a pull request that meets the project's standards. Looking forward to contributing!
