### ISSUE TITLE
[RFC]: add `@stdlib/array/base/cunone-by-right`

### ISSUE THREAD

**Issue by kgryte** [stdlib-js/stdlib#2329]
### Description

This RFC proposes adding the package `@stdlib/array/base/cunone-by-right`, which cumulatively tests whether no array element in a provided array passes a test implemented by a predicate function, while iterating from right-to-left. The function should return a new generic array. The package should also provide an `#assign` API for setting output values in a provided output array.

```javascript
function isPositive( value ) {
	return ( value > 0 );
}

var x = [ 1, 1, 0, 0, 0 ];

var y1 = cunoneByRight( x, isPositive );
// returns [ true, true, true, false, false ]

var y2 = [ false, null, false, null, false, null, false, null, false, null ];
var out = cunoneByRight.assign( x, y2, 2, 0, isPositive );
// returns [ true, null, true, null, true, null, false, null, false, null ]

var bool = ( out === y2 );
// returns true
```

where the `assign` API supports an offset and stride (see, e.g., `@stdlib/array/base/take`). Note that, by iterating from right to left, the values in the output array are equivalent to having first reversed the input array `x` and then using left-to-right iteration.

Both APIs should support accessor arrays (see, e.g., `@stdlib/array/base/take`).

### Related Issues

No.

### Questions

No.

### Other

- See also `@stdlib/array/base/none-by-right`

### Checklist

- [X] I have read and understood the [Code of Conduct](https://github.com/stdlib-js/stdlib/blob/develop/CODE_OF_CONDUCT.md).
- [X] Searched for existing issues and pull requests.
- [X] The issue name begins with `RFC:`.

**Comment by Naresh-kumar-Thodupunoori** [comment]
@kgryte May I work on this!!

**Comment by Apocalypse96** [comment]
@kgryte  Hey I would  love to solve this issue

**Comment by UtkershBasnet** [comment]
I'd like to work on this issue

**Comment by AbhinavKRN** [comment]
@kgryte can you assign this issue to me?
