### ISSUE TITLE
RFC: add support for computing the inverse/arc cotangent (acot)

### ISSUE THREAD

**Issue by kgryte** [stdlib-js/stdlib#233]
## Checklist

> Please ensure the following tasks are completed before submitting a feature request.

-   [x] Read and understood the [Code of Conduct][code-of-conduct].
-   [x] Searched for existing issues and pull requests.
-   [x] The issue name begins with `RFC:`.

## Description

> Description of the feature request.

This RFC proposes adding support for computing the inverse (arc) cotangent. The initial implementation is straightforward:

```javascript
return atan( 1.0 / x );
```

Package: `@stdlib/math/base/special/acot`
Alias: `base.acot`

## Related Issues

> Does this feature request have any related issues?

No.

## Questions

> Any questions for reviewers?

No.

## Other

> Any other information relevant to this feature request? This may include screenshots, references, sample output, and/or implementation notes.

Reference implementations:

-   [Julia](https://github.com/JuliaLang/julia/blob/dee7d77c199c4776cf4e06afb7ce920f09ad3c8c/base/special/trig.jl#L983)

[code-of-conduct]: https://github.com/stdlib-js/stdlib/blob/develop/CODE_OF_CONDUCT.md

**Comment by JithinKS97** [comment]
Hey thanks for the awesome library. I'm interested in taking up this issue. Can you guide me how to get started?

**Comment by kgryte** [comment]
@JithinKS97 Awesome! Thanks for reaching out!

The easiest way to get started would be to base your contribution on a similar package in `@stdlib/math/base/special`. For example, see [`acoth`](https://github.com/stdlib-js/stdlib/tree/develop/lib/node_modules/%40stdlib/math/base/special/acoth).

I would probably suggest the following:

1. Copy and paste all of [`acoth`](https://github.com/stdlib-js/stdlib/tree/develop/lib/node_modules/%40stdlib/math/base/special/acoth) to a folder named `acot` in the `@stdlib/math/base/special` namespace.
2. Modify the copyright years of all files in the package to `2020`.
3. Modify all the files to reflect `acot`, including descriptions, etc.
4. Update all tests and example output to reflect `acot` return values.
5. Consult the [developer guide](https://github.com/stdlib-js/stdlib/blob/develop/docs/development.md) for additional guidance on getting started.
6. Once your implementation is ready, simply open a PR and we'll review and provide feedback. :) 

Does that make sense and sound like a path forward?

**Comment by JithinKS97** [comment]
Yeah definitely...Will get back once I've something.

**Comment by JithinKS97** [comment]
I got started and adding acot part was very easy. But for generating the test fixtures, in acoth test, I found that linspace function provided by julia is used. Linspace is deprecated and they have a new function called range. Should I switch back to older version of Julia?
https://discourse.julialang.org/t/undefvarerror-linspace-not-defined/13269

**Comment by kgryte** [comment]
@JithinKS97 Yeah, sorry. We have yet to migrate to Julia `v1.x`. We are still on `v0.5`. Unless there is another reference, such as R or NumPy, can just rely on Julia `v0.5`.

That work for you?

**Comment by JithinKS97** [comment]
Yes thanks...I downgraded to Julia v0.5, but I'm not able add JSON package. Pkg.add("JSON") yields the error
```
ERROR: GitError(Code:ERROR, Class:Net, curl error: Couldn't resolve proxy 'proxyHost'
)
 in macro expansion at ./libgit2/error.jl:99 [inlined]
 in clone(::String, ::String, ::Base.LibGit2.CloneOptions) at ./libgit2/repository.jl:191
 in #clone#112(::String, ::Bool, ::Ptr{Void}, ::Nullable{Base.LibGit2.AbstractCredentials}, ::Function, ::String, ::String) at ./libgit2/libgit2.jl:327
 in (::Base.LibGit2.#kw##clone)(::Array{Any,1}, ::Base.LibGit2.#clone, ::String, ::String) at ./<missing>:0
 in (::Base.Pkg.Dir.##4#6{String,String})() at ./pkg/dir.jl:49
 in cd(::Base.Pkg.Dir.##4#6{String,String}, ::String) at ./file.jl:59
 in init(::String, ::String) at ./pkg/dir.jl:47
 in #cd#1(::Array{Any,1}, ::Function, ::Function, ::String, ::Vararg{Any,N}) at ./pkg/dir.jl:28
 in add(::String) at ./pkg/pkg.jl:100
```
Trying to fix it now

**Comment by kgryte** [comment]
@JithinKS97 In thinking about this, go ahead and use Julia `v1.x`. As you mentioned originally, you may need to modify the test fixture generation script, as some of the functions may be deprecated.

This will actually be useful for us, as it will demonstrate how other test fixture runners need to be updated in the project.

Sorry for the back and forth.

**Comment by JithinKS97** [comment]
Thanks...I've a way forward now.

**Comment by kgryte** [comment]
Awesome! Thanks for working on this!

**Comment by JithinKS97** [comment]
Yeah sure..Need a couple of days to understand the paradigm in Julia language. I think it will be worth it.

**Comment by kgryte** [comment]
@JithinKS97 Agreed. Should definitely help us out across the project in migrating to Julia `v1.x` for benchmarking and testing. We just have not had the bandwidth to do it.

**Comment by JithinKS97** [comment]
As the domain of the function should we provide ```[-inf , inf]``` or ```(-inf, inf)``` considering that providing Infinity gives back 0 and -Infinity -0.

**Comment by JithinKS97** [comment]
Since providing ```Infinity and -Infinity``` gives ```0 and -0``` for the function acot(x) = atan(1.0/x). Should we provide the domain as ```[-inf, inf]``` or ```(-inf, inf)``` in the docs. I can see that in the docs of acoth, we have provided open interval. Should we follow the same thing here as well?

**Comment by JithinKS97** [comment]
I'm almost done with the changes, should I squash all of my commits to one before raising the PR?

**Comment by kgryte** [comment]
@JithinKS97 

Re: restricting the domain. No need to restrict the domain. The domain of [`atan`](https://github.com/stdlib-js/stdlib/tree/31d3d55dea3895f586c7eaf630a029a62c03c4c3/lib/node_modules/%40stdlib/math/base/special/atan) is unrestricted, and similarly for `acot` (see [here](https://mathworld.wolfram.com/InverseCotangent.html)). That the values can be `+-0` is fine. Maintaining signed zero when providing `-Infinity` is useful when considering underflow in the argument to `atan`.

Re: squashing. No need. We can do that on our end once we approve and merge the PR.

Thanks again for all your effort on this!
