### ISSUE TITLE
[RFC]: add `@stdlib/array/base/cusome-by-right`

### ISSUE THREAD

**Issue by kgryte** [stdlib-js/stdlib#2330]
### Description

This RFC proposes adding the package `@stdlib/array/base/cusome-by-right`, which cumulatively tests whether at least `n` array elements in a provided array pass a test implemented by a predicate function, while iterating from right-to-left. The function should return a new generic array. The package should also provide an `#assign` API for setting output values in a provided output array.

```javascript
function isPositive( value ) {
	return ( value > 0 );
}

var x = [ 1, 1, 0, 0, 0 ];

var y1 = cusomeByRight( x, 2, isPositive );
// returns [ false, false, false, false, true ]

var y2 = [ false, null, false, null, false, null, false, null, false, null ];
var out = cusomeByRight.assign( x, 2, y2, 2, 0, isPositive );
// returns [ false, null, false, null, false, null, false, null, true, null ]

var bool = ( out === y2 );
// returns true
```

where the `assign` API supports an offset and stride (see, e.g., `@stdlib/array/base/take`). Note that, by iterating from right to left, the values in the output array are equivalent to having first reversed the input array `x` and then using left-to-right iteration.

Both APIs should support accessor arrays (see, e.g., `@stdlib/array/base/take`).

### Related Issues

No.

### Questions

No.

### Other

- See also `@stdlib/utils/some-by-right`

### Checklist

- [X] I have read and understood the [Code of Conduct](https://github.com/stdlib-js/stdlib/blob/develop/CODE_OF_CONDUCT.md).
- [X] Searched for existing issues and pull requests.
- [X] The issue name begins with `RFC:`.

**Comment by Naresh-kumar-Thodupunoori** [comment]
@kgryte May I work on this!!

**Comment by BarryByte** [comment]
@kgryte May i work on this issue ? It is labelled as good first issue, it might help me to start contributing to this organization.

**Comment by mayank1365** [comment]
@kgryte please assign this issue to me.

**Comment by AbhinavKRN** [comment]
@kgryte Can you assign this issue to me?

**Comment by srivastavaarpit977** [comment]
Hey @kgryte I want to work on this issue.....plz assign this issue to me !!

**Comment by GittyHarsha** [comment]
Hi, 
is it expected to use `@stdlib/utils/some-by-right` to implement `@stdlib/array/base/cusome-by-right` ? 
If so, doesn’t this approach result in quadratic time complexity?

**Comment by kgryte** [comment]
@GittyHarsha No, you should not use `@stdlib/utils/some-by-right` to implement the proposed API. The implementation should be similar to other similar packages in `@stdlib/array/base`.

**Comment by GittyHarsha** [comment]
Hi,
I got a doubt while implementing the `#assign` API.
In reference to `@stdlib/array/base/take/lib/assign.js`, 
the accessor arrays of type complex and boolean are explicitly handled.
I think for `@stdlib/array/base/cusome-by-right`, there is no need to explicitly handle any types of accessor arrays?

**Comment by kgryte** [comment]
@GittyHarsha You do need to handle accessor arrays; however, I think you are right that you don't need to special case either ComplexXXArrays or BooleanArray.

E.g., in https://github.com/stdlib-js/stdlib/blob/develop/lib/node_modules/%40stdlib/array/base/cuany/lib/assign.js, we special case complex and boolean arrays, with a fallback to a general accessor utility. For your case, I think you only need the general accessor utility.

**Comment by GittyHarsha** [comment]
Hi @kgryte ,
Unlike other packages in array/base `@stdlib/array/base/cusome-by-right` package is quite different concerning the `#assign` API.
In this package, the input array and output array do not need to have the same primitive data type.
For example: in the package `@stdlib/array/base/cuany`, `#assign` API, the input array is of type boolean[] and output array is of type (boolean | null)[]

But in this package, the input type can be number[] and the output array can be (boolean | null)[].

Thus, I propose the following interface member definition for the `#assign` API in the "index.d.ts" file.

	`assign<T, U extends Collection | AccessorArrayLike<unknown>>( x: Collection | AccessorArrayLike<unknown>, n: number, y: U, stride: number, offset: number, predicate: Predicate<T, U>, thisArg?: ThisParameterType<Predicate<T, U>> ): U;`

I request your comments on this.
Thanks!
