### ISSUE TITLE
[RFC]: add `@stdlib/iter/cuany`

### ISSUE THREAD

**Issue by kgryte** [stdlib-js/stdlib#2331]
### Description

This RFC proposes adding the package `@stdlib/iter/cuany`, which cumulatively tests whether at least one iterated value is truthy. The function should be a transform iterator, continuing to iterate while source iterator values are available.

```javascript
var array2iterator = require( '@stdlib/array/to-iterator' );

var arr = array2iterator( [ false, false, false, true, false ] );

var it = iterCuAny( arr );

var v = it.next().value;
// returns false

v = it.next().value;
// returns false

v = it.next().value;
// returns false

v = it.next().value;
// returns true

v = it.next().value;
// returns true

var bool = it.next().done;
// returns true
```

### Related Issues

No.

### Questions

No.

### Other

- See also `@stdlib/iter/any`

### Checklist

- [X] I have read and understood the [Code of Conduct](https://github.com/stdlib-js/stdlib/blob/develop/CODE_OF_CONDUCT.md).
- [X] Searched for existing issues and pull requests.
- [X] The issue name begins with `RFC:`.

**Comment by RidamGarg** [comment]
I'd like to work on this. @kgryte

**Comment by Jaysukh-409** [comment]
@RidamGarg Thanks for volunteering yourself. I am assigning this to you. Go ahead and submit PR as required.

**Comment by RidamGarg** [comment]
Generated The PR #2440. Please review it once
