### ISSUE TITLE
[RFC]: add `@stdlib/iter/cuevery`

### ISSUE THREAD

**Issue by kgryte** [stdlib-js/stdlib#2332]
### Description

This RFC proposes adding the package `@stdlib/iter/cuevery`, which cumulatively tests whether every iterated value is truthy. The function should be a transform iterator, continuing to iterate while source iterator values are available.

```javascript
var array2iterator = require( '@stdlib/array/to-iterator' );

var arr = array2iterator( [ true, true, true, false, true ] );

var it = iterCuEvery( arr );

var v = it.next().value;
// returns true

v = it.next().value;
// returns true

v = it.next().value;
// returns true

v = it.next().value;
// returns false

v = it.next().value;
// returns false

var bool = it.next().done;
// returns true
```

### Related Issues

No.

### Questions

No.

### Other

- See also `@stdlib/iter/every`

### Checklist

- [X] I have read and understood the [Code of Conduct](https://github.com/stdlib-js/stdlib/blob/develop/CODE_OF_CONDUCT.md).
- [X] Searched for existing issues and pull requests.
- [X] The issue name begins with `RFC:`.

**Comment by RidamGarg** [comment]
I'd like to work on this. @kgryte

**Comment by kgryte** [comment]
Sounds good! Thanks for volunteering to work on this, @RidamGarg!

**Comment by Dipti0704** [comment]
i would liketo work on this issue kindly assign this to me

**Comment by RidamGarg** [comment]
@kgryte please assign it to @Dipti0704 not getting much time to work on this. Thank You!

**Comment by kgryte** [comment]
Done. @Dipti0704 Please feel free to submit a PR implementing this feature.

**Comment by Dipti0704** [comment]
thanks for assigning.. i will soon raise a pr sir

**Comment by adityacodes30** [comment]
i am working on this will pr in ~24h
