### ISSUE TITLE
[RFC]: add `@stdlib/iter/cunone`

### ISSUE THREAD

**Issue by kgryte** [stdlib-js/stdlib#2333]
### Description

This RFC proposes adding the package `@stdlib/iter/cunone`, which cumulatively tests whether every iterated value is falsy. The function should be a transform iterator, continuing to iterate while source iterator values are available.

```javascript
var array2iterator = require( '@stdlib/array/to-iterator' );

var arr = array2iterator( [ false, false, false, true, false ] );

var it = iterCuNone( arr );

var v = it.next().value;
// returns true

v = it.next().value;
// returns true

v = it.next().value;
// returns true

v = it.next().value;
// returns false

v = it.next().value;
// returns false

var bool = it.next().done;
// returns true
```

### Related Issues

No.

### Questions

No.

### Other

- See also `@stdlib/iter/none`

### Checklist

- [X] I have read and understood the [Code of Conduct](https://github.com/stdlib-js/stdlib/blob/develop/CODE_OF_CONDUCT.md).
- [X] Searched for existing issues and pull requests.
- [X] The issue name begins with `RFC:`.

**Comment by ruthwikchikoti** [comment]
Hi @kgryte , could you please assign this issue to me?

**Comment by kgryte** [comment]
@ruthwikchikoti Yes, and I suggest you focus on addressing RFC **before** working on https://github.com/stdlib-js/stdlib/issues/1632. The README issue is less useful than adding this feature.

**Comment by ruthwikchikoti** [comment]
@kgryte review this !!

**Comment by ruthwikchikoti** [comment]
@kgryte  please review ?

**Comment by adityacodes30** [comment]
seems like the linked pr has not been rectified in over 2 months, ill go ahead and start on this if thats okay

**Comment by kgryte** [comment]
@adityacodes30 Yes, that is fine. I have now closed the prior linked PR due to inactivity.

**Comment by adityacodes30** [comment]
Great , I'll deliver on this in ~72h
