### ISSUE TITLE
[RFC]: add `@stdlib/iter/cusome`

### ISSUE THREAD

**Issue by kgryte** [stdlib-js/stdlib#2334]
### Description

This RFC proposes adding the package `@stdlib/iter/cusome`, which cumulatively tests whether at least `n` iterated values are truthy. The function should be a transform iterator, continuing to iterate while source iterator values are available.

```javascript
var array2iterator = require( '@stdlib/array/to-iterator' );

var arr = array2iterator( [ false, false, false, true, true ] );

var it = iterCuSome( arr, 2 );

var v = it.next().value;
// returns false

v = it.next().value;
// returns false

v = it.next().value;
// returns false

v = it.next().value;
// returns false

v = it.next().value;
// returns true

var bool = it.next().done;
// returns true
```

### Related Issues

No.

### Questions

No.

### Other

- See also `@stdlib/iter/some`

### Checklist

- [X] I have read and understood the [Code of Conduct](https://github.com/stdlib-js/stdlib/blob/develop/CODE_OF_CONDUCT.md).
- [X] Searched for existing issues and pull requests.
- [X] The issue name begins with `RFC:`.

**Comment by TheNourhan** [comment]
Can you assign this to me please?

**Comment by kgryte** [comment]
@TheNourhan Thanks for volunteering to work on this. Please feel free to submit a PR implementing this feature.
