### ISSUE TITLE
[RFC]: add `@stdlib/iter/cuevery-by`

### ISSUE THREAD

**Issue by kgryte** [stdlib-js/stdlib#2336]
### Description

This RFC proposes adding the package `@stdlib/iter/cuevery-by`, which cumulatively tests whether every iterated value passes a test implemented by a predicate function. The returned iterator should be a transform iterator, continuing to iterate while source iterator values are available.

```javascript
var array2iterator = require( '@stdlib/array/to-iterator' );

function isPositive( value ) {
	return ( value > 0 );
}

var arr = array2iterator( [ 1, 1, 1, 0, 1 ] );

var it = iterCuEveryBy( arr, isPositive );

var v = it.next().value;
// returns true

v = it.next().value;
// returns true

v = it.next().value;
// returns true

v = it.next().value;
// returns false

v = it.next().value;
// returns false

var bool = it.next().done;
// returns true
```

The `predicate` function should be provided two arguments:

- **value**: the iterated value.
- **index**: iteration index (zero-based).

### Related Issues

No.

### Questions

No.

### Other

- See also `@stdlib/iter/every-by`

### Checklist

- [X] I have read and understood the [Code of Conduct](https://github.com/stdlib-js/stdlib/blob/develop/CODE_OF_CONDUCT.md).
- [X] Searched for existing issues and pull requests.
- [X] The issue name begins with `RFC:`.

**Comment by bhargav5667** [comment]
Can i work on this issue

**Comment by kgryte** [comment]
@bhargav5667 Thanks for volunteering to work on this issue. Yes, please feel free to submit a PR implementing the requested functionality.

**Comment by bhargav5667** [comment]
@stdlib/iter/cuevery-by #2482
