### ISSUE TITLE
[RFC]: add `@stdlib/iter/cunone-by`

### ISSUE THREAD

**Issue by kgryte** [stdlib-js/stdlib#2337]
### Description

This RFC proposes adding the package `@stdlib/iter/cunone-by`, which cumulatively tests whether no iterated value passes a test implemented by a predicate function. The returned iterator should be a transform iterator, continuing to iterate while source iterator values are available.

```javascript
var array2iterator = require( '@stdlib/array/to-iterator' );

function isPositive( value ) {
	return ( value > 0 );
}

var arr = array2iterator( [ 0, 0, 0, 1, 0 ] );

var it = iterCuNoneBy( arr, isPositive );

var v = it.next().value;
// returns true

v = it.next().value;
// returns true

v = it.next().value;
// returns true

v = it.next().value;
// returns false

v = it.next().value;
// returns false

var bool = it.next().done;
// returns true
```

The `predicate` function should be provided two arguments:

- **value**: the iterated value.
- **index**: iteration index (zero-based).

### Related Issues

No.

### Questions

No.

### Other

- See also `@stdlib/iter/none-by`

### Checklist

- [X] I have read and understood the [Code of Conduct](https://github.com/stdlib-js/stdlib/blob/develop/CODE_OF_CONDUCT.md).
- [X] Searched for existing issues and pull requests.
- [X] The issue name begins with `RFC:`.

**Comment by Ad11xx** [comment]
Hi @kgryte , can I solve this?

**Comment by kgryte** [comment]
@Ad11xx Thanks for volunteering to work on this. Please feel free to submit a PR implementing this feature.

**Comment by Ad11xx** [comment]
Thanks a lot! 
if it is possible is there any file I can refer to regarding the code practices?

**Comment by kgryte** [comment]
Yes, you should look at both `@stdlib/iter/none-by` (which is a sink iterator) and `@stdlib/iter/for-each`, which is a transform iterator. The package you are planning to add should be a combination of the two.

**Comment by chiru200513** [comment]
i would like to start working on this feature . is there anyone currently working on it or can i start ?
And also how about the below code?
function iterCuNoneBy(iterator, predicate) {
    let cumulative = true;  // Start assuming that no elements satisfy the predicate

    return {
        next: function() {
            const next = iterator.next();
            if (next.done) {
                return { value: undefined, done: true };
            }

            // If any element satisfies the predicate, cumulative becomes false
            if (cumulative && predicate(next.value)) {
                cumulative = false;
            }

            return { value: cumulative, done: false };
        }
    };
}

module.exports = iterCuNoneBy;
