### ISSUE TITLE
RFC: add support for computing the inverse hyperbolic cotangent (acoth)

### ISSUE THREAD

**Issue by kgryte** [stdlib-js/stdlib#236]
## Checklist

> Please ensure the following tasks are completed before submitting a feature request.

-   [x] Read and understood the [Code of Conduct][code-of-conduct].
-   [x] Searched for existing issues and pull requests.
-   [x] The issue name begins with `RFC:`.

## Description

> Description of the feature request.

This RFC proposes adding support for computing the inverse hyperbolic cotangent. The initial implementation is straightforward:

```javascript
return atanh( 1.0 / x );
```

Package: `@stdlib/math/base/special/acoth`
Alias: `base.acoth`

## Related Issues

> Does this feature request have any related issues?

No.

## Questions

> Any questions for reviewers?

No.

## Other

> Any other information relevant to this feature request? This may include screenshots, references, sample output, and/or implementation notes.

Reference implementations:

-   [Julia](https://github.com/JuliaLang/julia/blob/dee7d77c199c4776cf4e06afb7ce920f09ad3c8c/base/special/trig.jl#L983)

[code-of-conduct]: https://github.com/stdlib-js/stdlib/blob/develop/CODE_OF_CONDUCT.md

**Comment by BrunoFenzl** [comment]
@kgryte I would like to work on these math functions, if they are still open.

**Comment by kgryte** [comment]
@BrunoFenzl That would be awesome! Go for it! Let me know if you have any questions. :)

**Comment by BrunoFenzl** [comment]
@kgryte cool! Will do.

**Comment by BrunoFenzl** [comment]
@kgryte I have a few questions. I did an implementation but there are a few things I have never seen before and can't find documentation about. 
One thing that is missing is to translate the tex docs in the acoth.js file. I have no clue of tex and unfortunately could not find any docs on how to translate the function in tex.
The other thing is when I try to push one commit, I get an error from git saying I have one REPL error linting in my file. What is REPL?

`Commit failed - exit code 1 received, with output: 'Linting file: lib/node_modules/@stdlib/math/base/special/acoth/README.md
{"file":"....../stdlib/lib/node_modules/@stdlib/math/base/special/acoth/docs/repl.txt","errors":[{"id":"@stdlib/_tools/repl-txt/rules/doctest","severity":"error","message":"Displayed return value is `NaN`, but function returns `0` instead","start":16,"end":24}]}

REPL help lint errors.'`

any help much appreciated!

**Comment by kgryte** [comment]
@BrunoFenzl Feel free to go ahead and create a WIP pull request. Will be easier to address the issues you mention in your comment via PR.

In order to go override the `git push` hook (for the time being), add the `--no-verify` flag to the command, thus skipping tests and linting. This will allow you to push and to create the PR.

In the meantime, see the [REPL text](https://github.com/stdlib-js/stdlib/blob/develop/docs/repl_text.md) guide, which hopefully explains a bit more about the `repl.txt` file. In short, the lint error you encountered stems from the fact that we evaluate examples and ensure that the example output matches the real output. We refer to this as "doc testing", and we try to apply it throughout project documentation in order to ensure that documentation does not "drift" from actual output due to, e.g., changes in the underlying implementation.

Regarding TeX, yeah, we need to document this better. Addressing your specific problem will be more easily done via PR review.

Hope the above helps! Thanks for working on this!

**Comment by BrunoFenzl** [comment]
I submitted a first draft for this issue at #241. I will be glad to hear some feedback!
Thanks for the REPL link.
