### ISSUE TITLE
encoding

### ISSUE THREAD

**Issue by ghost** [stdlib-js/stdlib#240]
I just tested the word2vec-pure-js locally via WLinux and couldn't reproduce the encoding problems :weinen:

**Comment by kgryte** [comment]
@LemonAndroid You sure you have the right GitHub repository for filing this issue? We don't currently have any `word2vec` functionality.

**Comment by kgryte** [comment]
As I don't believe this issue applies to this repository, I am going to close this issue. Feel free to re-open, if I am mistaken.
