### ISSUE TITLE
[RFC]: add `math/base/special/fmod`

### ISSUE THREAD

**Issue by gunjjoshi** [stdlib-js/stdlib#2405]
### Description

This RFC proposes adding `math/base/special/fmod`, which would follow this reference implementation: https://github.com/JuliaMath/openlibm/blob/master/src/e_fmod.c

This would enable us to have a function that works the same way as the modulus operator in `javascript` does.

### Related Issues

None.

### Questions

No.

### Other

No.

### Checklist

- [X] I have read and understood the [Code of Conduct](https://github.com/stdlib-js/stdlib/blob/develop/CODE_OF_CONDUCT.md).
- [X] Searched for existing issues and pull requests.
- [X] The issue name begins with `RFC:`.

**Comment by kgryte** [comment]
Thanks, @gunjjoshi! This sounds good and would be a good addition.
