### ISSUE TITLE
[RFC]: add REPL text lint rule for catching semicolon omission in examples

### ISSUE THREAD

**Issue by kgryte** [stdlib-js/stdlib#2428]
### Description

This RFC proposes adding tooling support for warning when semicolons are omitted from examples in REPL text help files. For reference, semicolons are used to silence/suppress the display of return values in the REPL. As an example,

```
> function foo() { return 'bar'; }
> foo()
'bar'
```

The above should trigger a warning (or perhaps more strongly an error) to indicate that the function declaration should not be displayed as return output. Instead, the above should be

```
> function foo() { return 'bar'; };
> foo()
'bar'
```

Discussion of return value suppression can be found in the REPL developer guide: https://github.com/stdlib-js/stdlib/blob/481690174833259628032a259dbe7d26bbde807d/docs/repl_text.md#examples.

### Related Issues

n/a

### Questions

No.

### Other

No.

### Checklist

- [X] I have read and understood the [Code of Conduct](https://github.com/stdlib-js/stdlib/blob/develop/CODE_OF_CONDUCT.md).
- [X] Searched for existing issues and pull requests.
- [X] The issue name begins with `RFC:`.

**Comment by kgryte** [comment]
The need for this RFC arose in https://github.com/stdlib-js/stdlib/pull/2421 where, during PR review, it can be easy to overlook inadvertent omission of semicolons.

**Comment by Snehil-Shah** [comment]
Would just updating this [file](https://github.com/stdlib-js/stdlib/blob/develop/lib/node_modules/%40stdlib/_tools/repl-txt/rules/code-semicolons/lib/main.js) with a complementary check do the trick?

**Comment by kgryte** [comment]
@Snehil-Shah Yes, it seems we can simply update the existing lint rule and update the rule description accordingly.

**Comment by Snehil-Shah** [comment]
![image](https://github.com/stdlib-js/stdlib/assets/130062020/2f8d4d76-2a7f-417f-925c-b76df912f6df)

It works. Should I push this? (with any changes?)

**Comment by kgryte** [comment]
@Snehil-Shah That looks reasonable. You'll also want to update the lint rule description, I believe, in the `package.json` to something more general.
