### ISSUE TITLE
Julia version in docs should be limited to <= 0.7

### ISSUE THREAD

**Issue by BrunoFenzl** [stdlib-js/stdlib#243]
## Checklist

> Please ensure the following tasks are completed before filing a bug report.

-   [x] Read and understood the [Code of Conduct][code-of-conduct].
-   [x] Searched for existing issues and pull requests.

## Description

Julia 1.x adds breaking changes in the code, preventing builds to run successfully. While stdlib does not update julia, the docs should reflect the version constraint.

Encountered an error when .
Developing a feature branch. Solution was to downgrade julia.

## Related Issues

> Does this issue have any related issues?

No

## Questions

> Any questions for reviewers?

No.

## Other

> Any other information relevant to this issue? This may include screenshots, references, stack traces, sample output, and/or implementation notes.

No

#### Reproduction

> What steps are required to reproduce the unexpected output?

In order to reproduce this bug, do the following:

Install julia 1.x and try to run benchmarks. `make benchmark-julia`

#### Expected Results

> What are the expected results?

Build runs :)

#### Actual Results

> What are the actual results?
Build breaks with following error:

The following are the actual results:

```text
Running benchmark: .../stdlib/lib/node_modules/@stdlib/array/convert-same/benchmark/julia/benchmark.jl
ERROR: LoadError: LoadError: LoadError: UndefVarError: @printf not defined
Stacktrace:
 [1] top-level scope
 [2] #macroexpand#32 at ./expr.jl:92 [inlined]
 [3] macroexpand at ./expr.jl:91 [inlined]
 [4] docm(::LineNumberNode, ::Module, ::Any, ::Any, ::Bool) at ./docs/Docs.jl:509 (repeats 2 times)
 [5] @doc(::LineNumberNode, ::Module, ::String, ::Vararg{Any,N} where N) at ./boot.jl:451
 [6] include at ./boot.jl:317 [inlined]
 [7] include_relative(::Module, ::String) at ./loading.jl:1041
 [8] include(::Module, ::String) at ./sysimg.jl:29
 [9] exec_options(::Base.JLOptions) at ./client.jl:229
 [10] _start() at ./client.jl:421
```

#### Environments

> What environments are affected (e.g., `Node v0.4.x`, `Chrome`, `IE 11`)? If Node.js, include the `npm` version, operating system, and any other potentially relevant platform information.

The following environments are affected:

MacOS Mojave 10.14
Nodejs v8.9.4
NPM 6.4.1

[code-of-conduct]: https://github.com/stdlib-js/stdlib/blob/develop/CODE_OF_CONDUCT.md

**Comment by kgryte** [comment]
@BrunoFenzl Thanks for filing this issue! Yes, you are correct: the development guide should be more stringent until the time comes that the project upgrades to `>=1.x`.
