### ISSUE TITLE
Unexpected dependencies in package.json

### ISSUE THREAD

**Issue by hfhchan-plb** [stdlib-js/stdlib#2469]
### Description

In all the `@stdlib/assert-is-*` packages, `@stdlib/cli-ctor` and `@stdlib-fs-read-file` are listed as dependencies, when they should be `devDependencies`.

This causes huge deps trees when importing something simple like `@stdlib/math-base-special-ldexp`.

### Environments

N/A

### Checklist

- [X] Read and understood the [Code of Conduct](https://github.com/stdlib-js/stdlib/blob/develop/CODE_OF_CONDUCT.md).
- [X] Searched for existing issues and pull requests.

**Comment by kgryte** [comment]
@hfhchan-plb It seems you are using outdated versions of `stdlib` packages. In the referenced issue (https://github.com/SukkaW/nolyfill/issues/79), the version for `@stdlib/assert-is-boolean` is `v0.0.8`. The most recent version is `v0.2.1`. That, in turn, depends on `@stdlib/assert-has-tostringtag-support` which no longer directly depends on `@stdlib/cli-ctor`. See https://www.npmjs.com/package/@stdlib/assert-has-tostringtag-support?activeTab=dependencies and compare with the dependency tree you show in https://github.com/SukkaW/nolyfill/issues/79.

**Comment by hfhchan-plb** [comment]
You're right. `@segment/tsub` was pulling in old versions of this library.
