### ISSUE TITLE
Menu filter in documentation broken

### ISSUE THREAD

**Issue by joshhopkins** [stdlib-js/stdlib#247]
## Checklist

> Please ensure the following tasks are completed before filing a bug report.

-   [x] Read and understood the [Code of Conduct][code-of-conduct].
-   [x] Searched for existing issues and pull requests.

## Description

> Description of the issue.

Unable to filter documentation menu. Encountered an error when searching documentation [here](https://stdlib.io/develop/docs/api/%40stdlib/datasets/).

## Related Issues

> Does this issue have any related issues?

Not that I can see.

## Questions

> Any questions for reviewers?

No.

## Other

> Any other information relevant to this issue? This may include screenshots, references, stack traces, sample output, and/or implementation notes.

#### Demo

> If relevant, provide a link to a live demo.

For a live demo of the issue, see

-   (https://stdlib.io/develop/docs/api/%40stdlib/datasets/)

#### Reproduction

> What steps are required to reproduce the unexpected output?

In order to reproduce this bug, do the following:

- Go to documentation
- Type in menu search field

#### Expected Results

> What are the expected results?

The following results are expected:

```text
(Menu to be filtered)
```

#### Actual Results

> What are the actual results?

The following are the actual results:

```text
(Nothing)
```

#### Environments

> What environments are affected (e.g., `Node v0.4.x`, `Chrome`, `IE 11`)? If Node.js, include the `npm` version, operating system, and any other potentially relevant platform information.

The following environments are affected:

- Safari MacOS 12

[code-of-conduct]: https://github.com/stdlib-js/stdlib/blob/develop/CODE_OF_CONDUCT.md

**Comment by kgryte** [comment]
@joshhopkins Sorry about this. This is a known issue. We have not been able to dedicate the time to actually implementing search. :(

**Comment by kgryte** [comment]
Filtering is now fixed thanks to @Planeshifter!
