### ISSUE TITLE
RFC: Cartesian product function

### ISSUE THREAD

**Issue by joshhopkins** [stdlib-js/stdlib#248]
## Checklist

> Please ensure the following tasks are completed before submitting a feature request.

-   [x] Read and understood the [Code of Conduct][code-of-conduct].
-   [x] Searched for existing issues and pull requests.
-   [x] The issue name begins with `RFC:`.

## Description

> Description of the feature request.

The Cartesian product (cross-product) is essentially an operation which returns a product set from multiple supplied sets.

https://en.wikipedia.org/wiki/Cartesian_product

## Related Issues

> Does this feature request have any related issues?

Not that I can see.

## Questions

> Any questions for reviewers?

No.

## Other

> Any other information relevant to this feature request? This may include screenshots, references, sample output, and/or implementation notes.

No.

[code-of-conduct]: https://github.com/stdlib-js/stdlib/blob/develop/CODE_OF_CONDUCT.md

**Comment by kgryte** [comment]
This function has been [added](https://github.com/stdlib-js/stdlib/tree/2a69883abfecebf1636e0eacf33d52338ba96ef3/lib/node_modules/%40stdlib/array/base/cartesian-product), along with other Cartesian product [variations](https://github.com/stdlib-js/stdlib/tree/2a69883abfecebf1636e0eacf33d52338ba96ef3/lib/node_modules/%40stdlib/array/base).
