### ISSUE TITLE
RFC: add complete elliptic integral of the first kind (ellipk)

### ISSUE THREAD

**Issue by rreusser** [stdlib-js/stdlib#250]
## Checklist

> Please ensure the following tasks are completed before submitting a feature request.

-   [x] Read and understood the [Code of Conduct][code-of-conduct].
-   [x] Searched for existing issues and pull requests.
-   [x] The issue name begins with `RFC:`.

## Description

> Description of the feature request.

This RFC proposes to add the [complete elliptic integral of the first kind][ellip]. It's not a bad one to implement, though managing the various definitions require care.

At this point, I've elected to use the input parameter `m` since, with `m = k^2`, `k^2 < 0` requires `m` to be imaginary which is just slightly awkward. `m` seems fine and definitely like the most popular choice, with the exception of Boost.

Reference implementations are:
- [Elliptic.jl][ellipticjl]: this uses the textbook series representation.
- [SpecialFunctions.jl][specialfunctionsjl]: The piecewise polynomial approach, with [reference][fukushima]. Seems nice.
- [scipy][scipy]: It appears this uses the iterative approach as well
- [elliptic-integrals-js][elliptic-js]: Iterative as well.

Clearly the iterative approach is most popular. I've selected the piecewise polynomial approach which sounds according to [Fukushima][fukushima] like it's somewhat faster—and certainly simpler.

## Related Issues

> Does this feature request have any related issues?

No.

## Questions

> Any questions for reviewers?

No.

## Other

No.

[code-of-conduct]: https://github.com/stdlib-js/stdlib/blob/develop/CODE_OF_CONDUCT.md
[ellip]: https://en.wikipedia.org/wiki/Elliptic_integral#Complete_elliptic_integral_of_the_first_kind
[ellipticjl]: https://github.com/nolta/Elliptic.jl/blob/d4fbc72a4117d5382106bc6eb3421140b7c8cd65/src/Elliptic.jl#L76-L83
[specialfunctionsjl]: https://github.com/JuliaMath/SpecialFunctions.jl/blob/02a173fbe24a61c4b392aec17a9764ac5727feb1/src/ellip.jl#L16
[fukushima]: https://pdfs.semanticscholar.org/8112/c1f56e833476b61fc54d41e194c962fbe647.pdf
[scipy]: https://github.com/scipy/scipy/blob/722bfc3f2cb4884c7ef3eb87cefcb91ff7479208/scipy/special/cephes/ellik.c
[elliptic-js]: https://github.com/duetosymmetry/elliptic-integrals-js

**Comment by kgryte** [comment]
Closing this, as `ellipk` has now been added. :)
