### ISSUE TITLE
RFC: add complete elliptic integral of the second kind (ellipe)

### ISSUE THREAD

**Issue by rreusser** [stdlib-js/stdlib#251]
## Checklist

> Please ensure the following tasks are completed before submitting a feature request.

-   [x] Read and understood the [Code of Conduct][code-of-conduct].
-   [x] Searched for existing issues and pull requests.
-   [x] The issue name begins with `RFC:`.

## Description

This is very nearly analogous to ellipk (see: #250), though it does require ellipk as a dependency for one of the branches. Using the piecewise polynomial approach, it's complete and working for `m > 0` and just needs cleanup and `m < 0`.

## Related Issues

> Does this feature request have any related issues?

See #250 for links to reference implementations.

## Questions

There's room to implement `ellipke` for computing both the first and second kind at the same time, though it would result in a lot of pointless duplication of coefficient data. It would be nice if that was somehow sharable, but it makes for awkward "kernel" packages that don't seem highly desirable for everything.

## Other

> Any other information relevant to this feature request? This may include screenshots, references, sample output, and/or implementation notes.

No.

[code-of-conduct]: https://github.com/stdlib-js/stdlib/blob/develop/CODE_OF_CONDUCT.md

**Comment by rreusser** [comment]
It's probably appropriate to look beyond incremental progress so the final implementation is coherent.

`scipy` has `ellipkm1` for the complete elliptic integral of the first kind *near 1* in terms of `p = 1 - m` rather than `m`. That seems like a nice thing to offer.

`Elliptic.jl` [overloads E but not K](https://github.com/nolta/Elliptic.jl) for incomplete elliptic integrals, perhaps to conform to textbook notation? (For some reason `K(m) -> F(phi, m)` for the first kind, but `E(m) -> E(phi, m)` for the second kind.) I think `ellipfinc` and `ellipeinc` sound nicer, perhaps?

**Comment by kgryte** [comment]
The `ellipkm1` implementation sounds good. Add agreed on `ellipfinc` and `ellipeinc` naming.

**Comment by kgryte** [comment]
I am sympathetic to `ellipke` with duplicated coefficient data. Would opt away from any kind of kernel function just for sharing coefficients. If desired, a separate RFC for `ellipke` can be created.

**Comment by kgryte** [comment]
I am closing this issue, as `ellipe` has now been implemented.
