### ISSUE TITLE
Incomplete code coverage in `blas/base/dznrm2` and `blas/base/scnrm2`

### ISSUE THREAD

**Issue by kgryte** [stdlib-js/stdlib#2543]
For context, see the coverage report posted to https://github.com/stdlib-js/stdlib/commit/fcc96033b25b424ceca4a583c9c6cbf3ef943631#commitcomment-143981597.

Current unit tests for both `blas/base/dznrm2` and `blas/base/scnrm2` fail to cover all branches, resulting in less than 100% code coverage. It would be good if we could add more test cases to those packages to ensure full coverage.

**Comment by kgryte** [comment]
See `@stdlib/lapack/base/dlassq` for some ideas.

**Comment by gururaj1512** [comment]
Working on it..!

**Comment by gururaj1512** [comment]
@kgryte, Is there any to check coverage report before commiting and pushing?

**Comment by kgryte** [comment]
@gururaj1512 See the development guide: https://github.com/stdlib-js/stdlib/blob/4b0d2abf2706178f83da028fc39fe0fdc3d2c073/docs/development.md#testing
