### ISSUE TITLE
Documentation link on homepage is incorrect

### ISSUE THREAD

**Issue by MatthewCochrane** [stdlib-js/stdlib#255]
## Checklist

> Please ensure the following tasks are completed before filing a bug report.

-   [x] Read and understood the [Code of Conduct][code-of-conduct].
-   [x] Searched for existing issues and pull requests.

## Description

> When the `documentation` link in the header of the homepage is clicked it takes the user to https://stdlib.io/develop/docs/api/@stdlib/ , which is a directory index not an actual web page.

## Related Issues

> Does this issue have any related issues?

No

## Questions

> Any questions for reviewers?

No.

## Other

> Any other information relevant to this issue? This may include screenshots, references, stack traces, sample output, and/or implementation notes.

#### Demo

> If relevant, provide a link to a live demo.

For a live demo of the issue, see

-   https://stdlib.io/ and click `documentation` in the top menu bar
-   It will take you here: https://stdlib.io/develop/docs/api/@stdlib/

#### Reproduction

> What steps are required to reproduce the unexpected output?

In order to reproduce this bug, do the following:

-   Visit https://stdlib.io/
-    click `documentation`

#### Expected Results

> What are the expected results?

I think it should direct the user to this url: https://stdlib.io/develop/docs/api/@stdlib/stdlib

#### Actual Results

> What are the actual results?

It will take you to a directory listing: https://stdlib.io/develop/docs/api/@stdlib/

#### Environments

> What environments are affected (e.g., `Node v0.4.x`, `Chrome`, `IE 11`)? If Node.js, include the `npm` version, operating system, and any other potentially relevant platform information.

The following environments are affected:

-   Chrome Version 72.0.3626.109 (Official Build) (64-bit)

[code-of-conduct]: https://github.com/stdlib-js/stdlib/blob/develop/CODE_OF_CONDUCT.md

**Comment by gvwilson** [comment]
same

**Comment by kgryte** [comment]
We recently launched new API docs! Still a couple bugs to fix which we are working on at the moment, but should be accessible now. See https://stdlib.io/docs/api.
