### ISSUE TITLE
[RFC]: add `@stdlib/fs/resolve-parent-paths`

### ISSUE THREAD

**Issue by Snehil-Shah** [stdlib-js/stdlib#2565]
### Description

This RFC proposes adding `@stdlib/fs/resolve-parent-paths` similar to [`@stdlib/fs/resolve-parent-path`](https://github.com/stdlib-js/stdlib/tree/develop/lib/node_modules/%40stdlib/fs/resolve-parent-path), which instead of a single path, accepts either an array of paths or a regular expression.

### Related Issues

No.

### Questions

No.

### Other

No.

### Checklist

- [X] I have read and understood the [Code of Conduct](https://github.com/stdlib-js/stdlib/blob/develop/CODE_OF_CONDUCT.md).
- [X] Searched for existing issues and pull requests.
- [X] The issue name begins with `RFC:`.

**Comment by kgryte** [comment]
@Snehil-Shah Sounds good to me. Thanks for this suggestion!

**Comment by Snehil-Shah** [comment]
@kgryte For regexp paths, we would have to test the regex with every possible path at each directory level. I wonder how much this would hurt perf?

**Comment by kgryte** [comment]
@Snehil-Shah Yeah, it won't be great. For simple regular expressions, it should be fine, and not much worse than normal string comparison.

**Comment by Snehil-Shah** [comment]
@kgryte I meant, that for an array of strings, we can check if each of the resolved directory (made from each path in array) exists or not. But in case of regexp, we would have to traverse the entire directory at each level to test if it exists or not. So, say if a directory has a 100 files/folders, we would have to traverse and test all of them to see if they satisfy the regexp. Or is there another way that I'm overlooking?

**Comment by kgryte** [comment]
That's correct. We'd need to use readdir, rather than exists. Maybe we should just limit to an array of strings and not support regular expressions.

**Comment by Snehil-Shah** [comment]
Yeah, we should just stick to an array of strings, as the read-dir approach seems to greatly increase time complexity

**Comment by kgryte** [comment]
Works for me! We can always add sthg for regexps later, possibly a different package.

**Comment by Snehil-Shah** [comment]
Should I also create an RFC for `resolve-parent-paths-by` to complete the API set?

**Comment by kgryte** [comment]
Yes, that would be good. Thanks!
