### ISSUE TITLE
SSL certificate is expired

### ISSUE THREAD

**Issue by rmccue** [stdlib-js/stdlib#258]
## Checklist

> Please ensure the following tasks are completed before filing a bug report.

-   [x] Read and understood the [Code of Conduct][code-of-conduct].
-   [x] Searched for existing issues and pull requests.

## Description

> Description of the issue.

Your SSL certificate for https://stdlib.io/ has expired.

[code-of-conduct]: https://github.com/stdlib-js/stdlib/blob/develop/CODE_OF_CONDUCT.md

**Comment by eboCode** [comment]
The browsers I tried this link in are showing various ‘Security Error’ and ‘Privacy Error’ messages, which may discourage new visitors...

Clicking the advanced button in another says:

> This server could not prove that it is stdlib.io; its security certificate expired 16 days ago.

**Comment by kgryte** [comment]
@rmccue Thanks for filing the issue. Will work to update the certificate shortly!

**Comment by nicwaller** [comment]
The certificate has been expired for more than 2 months. Is there some kind of blocker to getting a new cert installed? Is having a working website just not a priority at all? This doesn't exactly inspire faith in the stdlib-js project.

**Comment by kgryte** [comment]
@nicwaller If you feel something is amiss, feel free to contribute to the project, either with code or financially. Unfortunately, sometimes the main contributors have other obligations which take priority in order to provide material support. Making critical comments does not inspire motivation.

The issue has been resolved. The certificate has been renewed.

**Comment by nhnicwaller** [comment]
@kgryte Thanks for resolving the issue.

I signed up on Patreon to make a small monetary donation to this project. While doing so, I noticed that the **Sponsor** button on GitHub presents an error message which I've reported as issue #259.

**Comment by kgryte** [comment]
@nhnicwaller Thanks! I saw that!
