### ISSUE TITLE
RFC: add BLAS Level 1 sdot routine

### ISSUE THREAD

**Issue by splrk** [stdlib-js/stdlib#261]
## Checklist

> Please ensure the following tasks are completed before submitting a feature request.

-   [x] Read and understood the [Code of Conduct][code-of-conduct].
-   [x] Searched for existing issues and pull requests.
-   [x] The issue name begins with `RFC:`.

## Description

This RFC proposes implementing the dot (or inner) product routine for a single precision floats as defined in [BLAS Level 1][blas-level-1] routines. Specifically adding `@stdlib/blas/base/sdot` is proposed.

## Related Issues

> Does this feature request have any related issues?

No.

## Questions

> Any questions for reviewers?

No.

## Other

> Any other information relevant to this feature request? This may include screenshots, references, sample output, and/or implementation notes.

No.

[code-of-conduct]: https://github.com/stdlib-js/stdlib/blob/develop/CODE_OF_CONDUCT.md

[blas-level-1]: http://www.netlib.org/blas/#_level_1

**Comment by kgryte** [comment]
@splrk What are `sdsdot` and `dsdot`?

**Comment by splrk** [comment]
`sdsdot` and `dsdot` are `sdot` and `ddot` that

>  Compute the inner product of two vectors with extended precision accumulation and result.  

That is a quote from the [LAPACK sdsdot documentation][blas-sdsdot] documentation.

From the implementation it looks like they will run a little slower, but give you a little more accurate result.  Maybe these routines would be a good place to experiment with pairwise summation (no. 328 in [`develop\TODO`][devel-todo]) instead of the LAPACK implementation?

(Sorry about adding them at first. I wrote the RFC then realized it would probably be better to write and RC per routine rather than group them together)



[blas-sdsdot]: http://www.netlib.org/lapack/explore-html/df/d28/group__single__blas__level1_gaddc89585ced76065053abffb322c5a22.html#gaddc89585ced76065053abffb322c5a22

[devel-todo]: https://github.com/stdlib-js/stdlib/blob/develop/TODO.md

**Comment by kgryte** [comment]
@splrk Thanks for the clarification! Yes, agreed. We should also add `sdsdot` and `dsdot`, each under its own RFC.

Regarding pairwise summation, we can probably hold off on this for the time being. Thanks for having a look over the TODOs!
