### ISSUE TITLE
RFC: Add BLAS Level 1 ddot routine

### ISSUE THREAD

**Issue by splrk** [stdlib-js/stdlib#262]
## Checklist

> Please ensure the following tasks are completed before submitting a feature request.

-   [x] Read and understood the [Code of Conduct][code-of-conduct].
-   [x] Searched for existing issues and pull requests.
-   [x] The issue name begins with `RFC:`.

## Description

> Description of the feature request.

This RFC proposes implementing the dot (or inner) product routine for a double-precision floating-pint arrays as defined in [BLAS Level 1][blas-level-1] routines. Specifically adding `@stdlib/blas/base/ddot` is proposed.

## Related Issues

> Does this feature request have any related issues?

Related issues #261 

## Questions

> Any questions for reviewers?

No.

## Other

> Any other information relevant to this feature request? This may include screenshots, references, sample output, and/or implementation notes.

No.

[code-of-conduct]: https://github.com/stdlib-js/stdlib/blob/develop/CODE_OF_CONDUCT.md

[blas-level-1]: http://www.netlib.org/blas/#_level_1

**Comment by kgryte** [comment]
@splrk Thanks for filing the RFC. This will be a welcome addition!
