### ISSUE TITLE
[BUG]: `string/truncate` behaves abnormally when truncating strings to length 3

### ISSUE THREAD

**Issue by Snehil-Shah** [stdlib-js/stdlib#2630]
### Description

Encountered an error when truncating strings to length 3.

### Demo

![image](https://github.com/user-attachments/assets/31202e6f-dd15-4be8-b684-115a67b91f7b)

### Reproduction

- truncate any string to length 3.

### Expected Results

```
In [1]: truncate('hell', 3)
Out[1]: '...'

In [2]: ans.length
Out[2]: 3
```

### Actual Results

```
In [1]: truncate('hell', 3)
Out[1]: 'hell...'

In [2]: ans.length
Out[2]: 7
```

### Version

https://github.com/stdlib-js/stdlib/tree/c89a171db9b4664582fab09dc95a5cc3b58f9f21

### Environments

Node.js

### Node.js / npm Version

Node @20.13.1, npm @10.5.2

### Platform

Ubuntu 20.04.6 LTS (container)

### Checklist

- [X] Read and understood the [Code of Conduct](https://github.com/stdlib-js/stdlib/blob/develop/CODE_OF_CONDUCT.md).
- [X] Searched for existing issues and pull requests.

**Comment by Snehil-Shah** [comment]
![image](https://github.com/user-attachments/assets/5e365dea-46cc-400d-8235-a2e29e2a7e4b)

And also, should the string be truncated if the target length is equal to the given string's length? I think not..

**Comment by kgryte** [comment]
> should the string be truncated if the target length is equal to the given string's length?

No. I don't think so.

> truncate any string to length 3.

Yes, that seems like a bug.
