### ISSUE TITLE
RFC: add BLAS Level 1 sscal routine

### ISSUE THREAD

**Issue by splrk** [stdlib-js/stdlib#264]
## Checklist

> Please ensure the following tasks are completed before submitting a feature request.

-   [X] Read and understood the [Code of Conduct][code-of-conduct].
-   [X] Searched for existing issues and pull requests.
-   [X] The issue name begins with `RFC:`.

## Description

> Description of the feature request.

This RFC proposes to add a routine to scale a vector by a scalar as defined in [BLAS Level 1][blas-level-1] routines.  Specifically adding `@stdlib/blas/base/sscal` is proposed.

## Related Issues

> Does this feature request have any related issues?

No.

## Questions

> Any questions for reviewers?

No.

## Other

> Any other information relevant to this feature request? This may include screenshots, references, sample output, and/or implementation notes.

No.

[code-of-conduct]: https://github.com/stdlib-js/stdlib/blob/develop/CODE_OF_CONDUCT.md

[blas-level-1]: http://www.netlib.org/blas/#_level_1

**Comment by kgryte** [comment]
@splrk Thanks for submitting this RFC and for working on this!
