### ISSUE TITLE
Missing documentation

### ISSUE THREAD

**Issue by gvwilson** [stdlib-js/stdlib#269]
## Checklist

> Please ensure the following tasks are completed before filing a bug report.

-   [X] Read and understood the [Code of Conduct][code-of-conduct].
-   [X] Searched for existing issues and pull requests.

## Description

Viewing documentation at <https://stdlib.io/docs/api/v0.0.90/@stdlib/symbol>, get the error message:

```
{"message":"Route GET:/docs/api/v0.0.90/@stdlib/symbol?fragment=true not found","error":"Not Found","statusCode":404}
```

**Comment by kgryte** [comment]
@gvwilson Thanks for filing this issue! Indeed, we are missing some namespace docs and adding them is on our internal TODO list.

**Comment by kgryte** [comment]
This has now been addressed in the latest documentation [release](https://stdlib.io/docs/api/latest/@stdlib/symbol).
