### ISSUE TITLE
404 when attempting to install napi-argv_float

### ISSUE THREAD

**Issue by loamietom** [stdlib-js/stdlib#2714]
### Description

When I have deleted my `package-lock.json` and `node_modules` folder I am seeing this error:

```
❯ npm i
npm ERR! code 128
npm ERR! An unknown git error occurred
npm ERR! command git --no-replace-objects ls-remote ssh://git@github.com/stdlib-js/napi-argv_float.git
npm ERR! ERROR: Repository not found.
npm ERR! fatal: Could not read from remote repository.
npm ERR!
npm ERR! Please make sure you have the correct access rights
npm ERR! and the repository exists.

npm ERR! A complete log of this run can be found in: /Users/tomhill/.npm/_logs/2024-07-31T02_01_18_760Z-debug-0.log
```

I have one dependency on `stdlib` in my `package.json`

`    "@stdlib/stats-base": "^0.3.1",`

And a dev dependency on `@stdlib/types`

`"@stdlib/types": "^0.3.2",`

This issue has only come up after I removed my `node_modules` and has occured in the last few days.

Let me know if you need further info.

```shell
- delete node_modules
- npm i
```

### Version

0.3.1

### Environments

Node.js

### Node.js / npm Version

Node 18.19.1 / npm 10.2.4

### Platform

macOS

### Checklist

- [X] Read and understood the [Code of Conduct](https://github.com/stdlib-js/stdlib/blob/develop/CODE_OF_CONDUCT.md).
- [X] Searched for existing issues and pull requests.

**Comment by Planeshifter** [comment]
@loamietom Thanks for bringing this to our attention and apologies for the issue. We are able to reproduce and will look into fixing this ASAP.

**Comment by loamietom** [comment]
Cheers - thanks @Planeshifter 🙏

**Comment by Planeshifter** [comment]
@loamietom This should now be resolved. After blowing away `package-lock.json` and `node_modules`, I am now able to install the latest version of `@stdlib/stats-base` again. We had wrong dependencies in a PR that was merged a while ago and which subsequently caused the issue you encountered after we released a new round of package updates over the last few days. Please let us know if you encounter any further issues; if not, we will close this issue out soon. Thanks again for bringing this to our attention!

**Comment by loamietom** [comment]
Hi @Planeshifter - yes I have just tried to reinstall and worked fine this time. Thanks so much, I appreciate your quick response.
