### ISSUE TITLE
RFC: implement equivalent of p.adjust from R

### ISSUE THREAD

**Issue by vincerubinetti** [stdlib-js/stdlib#274]
## Checklist

> Please ensure the following tasks are completed before submitting a feature request.

-   [x] Read and understood the [Code of Conduct][code-of-conduct].
-   [x] Searched for existing issues and pull requests.
-   [x] The issue name begins with `RFC:`.

## Description

Implement the equivalent of [p.adjust](https://stat.ethz.ch/R-manual/R-devel/library/stats/html/p.adjust.html) in R, with the different methods such as bonferroni and fdr.

Apologies if this is already a feature, but I couldn't find it anywhere in the documentation. Also, feel free to close if this is outside the scope of the project. I don't know if your goal is to replicate all the functionality of R.

*EDIT* Seems like it would be a lot of work to implement, especially if you want to include all those different methods. But the benefit to me is that I could switch completely over to `stdlib` (and I've been really happy with the quality of it so far!) and move away from separate packages like `multtest` (which lol, I just realized is also @Planeshifter).

[code-of-conduct]: https://github.com/stdlib-js/stdlib/blob/develop/CODE_OF_CONDUCT.md

**Comment by kgryte** [comment]
@vincerubinetti Thanks for this RFC. @Planeshifter Thoughts?

**Comment by kgryte** [comment]
@vincerubinetti After discussing with @Planeshifter, we're going to get started on this ASAP. Will keep you updated! Thanks again for the RFC!

**Comment by kgryte** [comment]
This has now been added in the [`padjust`](https://github.com/stdlib-js/stdlib/tree/90145d59bd746ba47ce71f2a0f369709e0bae829/lib/node_modules/%40stdlib/stats/padjust) package.
