### ISSUE TITLE
Update "Twitter" Text to "X" in Footer Links

### ISSUE THREAD

**Issue by Harshinireddy05** [stdlib-js/stdlib#2788]
### Description:
The website currently references Twitter in the footer navigation links as shown in the attached image. Given Twitter's recent rebranding to "X", we need to update the footer to reflect this change.

### Expected Behavior:
The link text should be updated from "Twitter" to "X".

### Actual Behavior:
The footer link still displays "Twitter".

### Screenshot:
![image](https://github.com/user-attachments/assets/f43b3d44-b003-40c6-b37a-8bc954c17ac7)

**Comment by Harshinireddy05** [comment]
@stdlib-bot I feel this is a valid issue and I'm working on it now.

**Comment by kgryte** [comment]
These changes have already been upstreamed. They will be public once we deploy an updated build of the website. As such, I am closing this issue.
