### ISSUE TITLE
`idamax.ndarray` does not support negative strides

### ISSUE THREAD

**Issue by Pranavchiku** [stdlib-js/stdlib#2792]
### Description

Encountered an error when adding negative stride tests for `lapack/base/dlacn2`

### Related Issues

Required for PR: #2790.

### Questions

No.

### Reproduction

```shell
var idamax = require('@stdlib/blas/base/idamax');
var Float64Array = require( '@stdlib/array/float64' );
var X = new Float64Array( [ 4.0, 999.9, 999.9, 3.0, 999.9, 999.9, 2.0, 999.9, 999.9, 1.0 ] );
console.log( "idamax( N, X, strideX, offsetX ): ", idamax.ndarray( 4, X, -3, 9 ) );
```

### Expected Results

```shell
% node a.js 
idamax( N, X, strideX, offsetX ):  3
```

### Actual Results

```shell
% node a.js 
idamax( N, X, strideX, offsetX ):  -1
```

### Version

latest main

### Environments

Node.js

### Node.js / npm Version

v20.9.0

### Platform

mac

### Checklist

- [X] Read and understood the [Code of Conduct](https://github.com/stdlib-js/stdlib/blob/develop/CODE_OF_CONDUCT.md).
- [X] Searched for existing issues and pull requests.

**Comment by Pranavchiku** [comment]
The following diff fixes `ndarray` implementation:

```diff
diff --git a/lib/node_modules/@stdlib/blas/base/idamax/lib/ndarray.js b/lib/node_modules/@stdlib/blas/base/idamax/lib/ndarray.js
index 8b9fd18fc9..48543ebcf3 100644
--- a/lib/node_modules/@stdlib/blas/base/idamax/lib/ndarray.js
+++ b/lib/node_modules/@stdlib/blas/base/idamax/lib/ndarray.js
@@ -49,7 +49,7 @@ function idamax( N, x, strideX, offsetX ) {
        var v;
        var i;
 
-       if ( N < 1 || strideX <= 0 ) {
+       if ( N < 1 ) {
                return -1;
        }
        idx = 0;
diff --git a/lib/node_modules/@stdlib/blas/base/idamax/test/test.ndarray.js b/lib/node_modules/@stdlib/blas/base/idamax/test/test.ndarray.js
index 6a53cb7a07..926bbc9e6e 100644
--- a/lib/node_modules/@stdlib/blas/base/idamax/test/test.ndarray.js
+++ b/lib/node_modules/@stdlib/blas/base/idamax/test/test.ndarray.js
@@ -108,19 +108,17 @@ tape( 'if provided an `N` parameter equal to `1`, the function returns `0`', fun
        t.end();
 });
```

But to support `ndarray.native` implementation, we need to change `C` and `Fortran` signature to include `offset` parameter and this asks us to diverge from https://github.com/OpenMathLib/OpenBLAS/blob/develop/lapack-netlib/CBLAS/src/cblas_idamax.c.

```c
int c_idamax( const int N, const double *X, const int strideX, const int offsetX )
```

```fortran
integer function idamax( N, dx, stride, offset )
```

**Comment by kgryte** [comment]
Not supporting negative strides is intentional, as this is what is supported by reference BLAS: https://www.netlib.org/lapack/explore-html/dd/d52/group__iamax_gacec03c5109f531c06b4fb301cf1a2d7a.html#gacec03c5109f531c06b4fb301cf1a2d7a.

If you need to use a negative stride, simply compute the offset of the last element and then flip the sign of the stride. For computing the max, iteration direction does not matter, as you are returning a scalar. In short, perform the workaround in code.

**Comment by kgryte** [comment]
Exactly. Address the lack of negative stride support downstream, not upstream.

**Comment by kgryte** [comment]
We do something similar in https://github.com/stdlib-js/stdlib/blob/153bb1aac042aeabffb18e0082ced6c3c66cbcdf/lib/node_modules/%40stdlib/blas/base/dsymv/lib/dsymv.js#L108.

**Comment by Pranavchiku** [comment]
okay, closing this then. Thank you for the clarification!

**Comment by Pranavchiku** [comment]
Opening with reference to talk on slack to support negative strides in JS implementation but not in C and Fortran.
