### ISSUE TITLE
[RFC]: add JS implementation for `sign`

### ISSUE THREAD

**Issue by Pranavchiku** [stdlib-js/stdlib#2856]
### Description

This RFC proposes adding JS implementation equivalent to [`sign`](https://gcc.gnu.org/onlinedocs/gcc-7.5.0/gfortran/SIGN.html) present in Fortran. This is used often in LAPACK/BLAS packages.

```js
/**
* Returns `x` multipled by `signum( y )`.
*
* @param {number} x - scalar element
* @param {number} y - scalar element
* @returns {number} computed value
*
* @example
* var out = sign( 1.0, -0.9 );
* // out => -1.0
*/
function sign( x, y ) {
	return x * signum( y );
}
```

Where we already have implementation for [`signum`](https://github.com/stdlib-js/stdlib/tree/develop/lib/node_modules/%40stdlib/math/base/special/signum)

alias: `@stdlib/math/base/special/sign`
reference: [`@stdlib/math/base/special/max`](https://github.com/stdlib-js/stdlib/tree/develop/lib/node_modules/%40stdlib/math/base/special/max)

### Related Issues

Related issues #2464.

### Questions

No.

### Other

cc @kgryte 

### Checklist

- [X] I have read and understood the [Code of Conduct](https://github.com/stdlib-js/stdlib/blob/develop/CODE_OF_CONDUCT.md).
- [X] Searched for existing issues and pull requests.
- [X] The issue name begins with `RFC:`.

**Comment by kgryte** [comment]
@Pranavchiku How is this different from copysign?

**Comment by Pranavchiku** [comment]
I missed it, sorry, closing it. 

Note: Use `copysign` in https://github.com/stdlib-js/stdlib/pull/2819.
