### ISSUE TITLE
[BUG]: REPL no longer supports TAB completion (e.g., `random.strided.<TAB>`)

### ISSUE THREAD

**Issue by kgryte** [stdlib-js/stdlib#2882]
### Description

Encountered an error when attempting to see the list of potential matches in the REPL. If you don't know the possibilities, you are left in the dark as to what to type next.

### Related Issues

n/a

### Questions

@Snehil-Shah Is there a reason why this no longer works? Does one of your open PRs address this already?

### Reproduction

```shell
$ make repl
```

```
In [1]: random.strided.<TAB>
```

### Expected Results

Should display the list of possibilities.

### Actual Results

Nothing displays.

### Environments

Node.js

### Checklist

- [X] Read and understood the [Code of Conduct](https://github.com/stdlib-js/stdlib/blob/develop/CODE_OF_CONDUCT.md).
- [X] Searched for existing issues and pull requests.

**Comment by Snehil-Shah** [comment]
@kgryte Weird. It does work when you type something after the dot.

![image](https://github.com/user-attachments/assets/b0108863-c103-488a-a440-4b5d3a72de68)

Will investigate and push a patch soon.

**Comment by kgryte** [comment]
@Snehil-Shah Thanks for investigating!

**Comment by Snehil-Shah** [comment]
@kgryte Found the root. While implementing auto-closing symbols, we added completion support for settings. For that you also added [this](https://github.com/Snehil-Shah/stdlib/commit/83142377ae560b0b7b741437d117ea4aa6a0bd6d#diff-7d1738b88b0eac8a5ec3b4926c749b012b9d3d984ad9635657269434f6dc8ce6) (`completer.js`: L183-188). I am not sure I understand why it was added. Do you remember it by any chance? It works fine without it.

**Comment by kgryte** [comment]
IIRC, that originates from when we were using the built-in `readline` completion logic. When we relied on that, I believe that the path to reaching that regexp was different.

**Comment by kgryte** [comment]
Hmm...now I am not so sure. In that same commit, we explicitly added the corresponding RegExp. I am not sure how/why we were reaching that branch. Could be related to doing something like `foo[]<TAB>`.

**Comment by Snehil-Shah** [comment]
Just checked with the default `readline` completer and the behavior is same as the new one. The new completer engine and the old one use the same logic underneath, it's about what the completer is generating for the given line.

Yeah, you are right, i guess its related to `foo[<TAB>]` as doing it does result in weird behavior without the RegExp.

![image](https://github.com/user-attachments/assets/cbbdb322-945c-40d2-a7fe-cc410d4da43e)

Maybe we can just remove the dot from the RegExp symbols?

**Comment by kgryte** [comment]
Are there any instances where we wouldn't want TAB completion after `.`?

**Comment by kgryte** [comment]
@Snehil-Shah I believe just removing `.` from the reserved characters regexp should be fine.

**Comment by Snehil-Shah** [comment]
Tried some weird combinations: `.<TAB>`, `foo..<TAB>`, and no abnormal behavior was detected. Should be fine to remove the `.`.
