### ISSUE TITLE
[RFC]: add `assert/is-same-array-like-object`

### ISSUE THREAD

**Issue by kgryte** [stdlib-js/stdlib#2886]
### Description

This RFC proposes adding a new assertion package to test whether two arguments are both array-like objects and have the same values.

Package: `@stdlib/assert/is-same-array-like-object`
Alias: `isSameArrayLikeObject`

### Related Issues

No.

### Questions

No.

### Other

[`@stdlib/assert/is-same-array-like`](https://github.com/stdlib-js/stdlib/tree/cf8b445d3429b4b16db5ae99269f148482f11422/lib/node_modules/%40stdlib/assert/is-same-array-like) provides a reference implementation. One should only need to

- update descriptions
- use `is-array-like-object`
- update tests

### Checklist

- [X] I have read and understood the [Code of Conduct](https://github.com/stdlib-js/stdlib/blob/develop/CODE_OF_CONDUCT.md).
- [X] Searched for existing issues and pull requests.
- [X] The issue name begins with `RFC:`.

**Comment by yaswanthkosuru** [comment]
i am working on this issue
