### ISSUE TITLE
[RFC]: add `@stdlib/assert/is-same-typed-array-like`

### ISSUE THREAD

**Issue by kgryte** [stdlib-js/stdlib#2887]
### Description

This RFC proposes adding a new assertion package to test whether two arguments are both typed-array-like objects and have the same values.

Package: `@stdlib/assert/is-same-typed-array-like`
Alias: `isSameTypedArrayLike`

### Related Issues

No.

### Questions

No.

### Other

[`@stdlib/assert/is-same-array-like`](https://github.com/stdlib-js/stdlib/tree/cf8b445d3429b4b16db5ae99269f148482f11422/lib/node_modules/%40stdlib/assert/is-same-array-like) provides a reference implementation. One should only need to

- update descriptions
- use `is-typed-array-like`
- update tests
- update examples and documentation

### Checklist

- [X] I have read and understood the [Code of Conduct](https://github.com/stdlib-js/stdlib/blob/develop/CODE_OF_CONDUCT.md).
- [X] Searched for existing issues and pull requests.
- [X] The issue name begins with `RFC:`.

**Comment by adityacodes30** [comment]
i would like to take this up , working , will pr in 24 -48h

**Comment by Amrit02102004** [comment]
> i would like to take this up , working , will pr in 24 -48h

Did you worked on it or else I also would like to take up this issue

**Comment by adityacodes30** [comment]
Working , pr by weekend
