### ISSUE TITLE
[RFC]: add `@stdlib/assert/is-same-accessor-array`

### ISSUE THREAD

**Issue by kgryte** [stdlib-js/stdlib#2888]
### Description

This RFC proposes adding a new assertion package to test whether two arguments are both accessor arrays and have the same values.

Package: `@stdlib/assert/is-same-accessor-array`
Alias: `isSameAccessorArray`

### Related Issues

No.

### Questions

No.

### Other

[`@stdlib/assert/is-same-array-like`](https://github.com/stdlib-js/stdlib/tree/cf8b445d3429b4b16db5ae99269f148482f11422/lib/node_modules/%40stdlib/assert/is-same-array-like) provides a reference implementation. One should only need to

- update descriptions
- use `is-accessor-array`
- update tests
- update examples and documentation

### Checklist

- [X] I have read and understood the [Code of Conduct](https://github.com/stdlib-js/stdlib/blob/develop/CODE_OF_CONDUCT.md).
- [X] Searched for existing issues and pull requests.
- [X] The issue name begins with `RFC:`.

**Comment by aayush0325** [comment]
I've went through the codebase for similar packages and I'd love to work on this issue.

**Comment by aayush0325** [comment]
```javascript

@example
var Complex128Array = require( '@stdlib/array/complex128' );
var isSameAccessorArray = require( '@stdlib/assert/is-same-accessor-array' );

var x = new Complex128Array( [ 1, 2, 1, 2 ] );
var y = new Complex128Array( [ 1, 2, 1, 2 ] );

var out = isSameAccessorArray( x, y );
// returns true

@example
var Complex128Array = require( '@stdlib/array/complex128' );
var isSameAccessorArray = require( '@stdlib/assert/is-same-accessor-array' );

var x = new Complex128Array( [ 1, 2, 1, 2 ] );
var y = new Complex128Array( [ 2, 1, 2, 1 ] );

var out = isSameAccessorArray( x, y );
// returns false

@example
var Complex128Array = require( '@stdlib/array/complex128' );
var isSameAccessorArray = require( '@stdlib/assert/is-same-accessor-array' );

var x = new Complex128Array( [ 1, 2, 1, 2 ] );
var y = [ 1, 2, 3 ];

var out = isSameAccessorArray( x, y );
// returns false

```

I've went through '@stdlib/assert/is-accessor-array' and i found out that only Complex64Array and Complex128Array are accepted as accessor arrays in '@stdlib/assert/is-accessor-array/test/test.js'


Based on that I've come up with these examples, I hope this is what you're looking for @kgryte. I have a basic patch ready for this feature and i can raise a PR soon if you're satisfied with this. I'd love to correct myself if you feel that this is not what you were looking for.

Note that I'm using Complex128Array and Complex64Array for writing tests and examples only, in the core feature my code applies the '@stdlib/assert/is-accessor-array' only so if there is any other way to make an accessor array that will give the expected response
