### ISSUE TITLE
RFC: paired t-test

### ISSUE THREAD

**Issue by zross** [stdlib-js/stdlib#291]
## Checklist

-   [x] Read and understood the [Code of Conduct][code-of-conduct].
-   [x] Searched for existing issues and pull requests.
-   [x] The issue name begins with `RFC:`.

## Description

> This project is great! I'm wondering if you would consider adding a paired t-test. I'm seeing a t-test and two-sample t-test but not a paired t-test. 

## Other

> I've looked for this in simple-stats and jStat also and am not seeing it (so it could be unique here!). I'm seeing a possible js implementation in [this gist](https://gist.github.com/bellbind/801c5de20aa4f310062363f3f95a099e).

[code-of-conduct]: https://github.com/stdlib-js/stdlib/blob/develop/CODE_OF_CONDUCT.md

**Comment by Planeshifter** [comment]
Thanks for the kind words and your interest in the project!

A paired t-test is available as part of the `ttest` function via supplying two arrays, see the documentation: 

https://stdlib.io/docs/api/v0.0.90/@stdlib/stats/ttest

**Comment by zross** [comment]
Apologies! That is so annoying of me -- I was looking for it under ttest2. Sorry about that.

**Comment by kgryte** [comment]
As this is resolved, closing this issue. Thanks for your interest!
