### ISSUE TITLE
RFC: Wilcoxon signed rank (paired samples)

### ISSUE THREAD

**Issue by zross** [stdlib-js/stdlib#294]
## Checklist

-   [x] Read and understood the [Code of Conduct][code-of-conduct].
-   [x] Searched for existing issues and pull requests.
-   [x] The issue name begins with `RFC:`.

## Description

> Perhaps it's possible to include the Wilcoxon signed rank test?

For reference, in R this is: 

```r
wilcox.test(var~grp, paired = TRUE)
```

[code-of-conduct]: https://github.com/stdlib-js/stdlib/blob/develop/CODE_OF_CONDUCT.md

**Comment by zross** [comment]
A possible implementation: https://gist.github.com/noahhai/8f279164ca9b389225ed860d12d25a9e

**Comment by kgryte** [comment]
@zross Quick update. @Planeshifter added a Wilcoxon implementation which can be found [here](https://github.com/stdlib-js/stdlib/tree/59178362c5d7a83abf7239a2811f2b1e06202ab8/lib/node_modules/%40stdlib/stats/wilcoxon).

**Comment by zross** [comment]
This is exciting, thank you!
