### ISSUE TITLE
function `reverse` currently mishandles strings that include surrogate code units

### ISSUE THREAD

**Issue by Andrew-Cottrell** [stdlib-js/stdlib#295]
https://github.com/stdlib-js/stdlib/blob/74eacccbb64db595b1d2e9f0b99eed8427931ddf/lib/node_modules/%40stdlib/string/reverse/lib/reverse.js#L51

FYI, function `reverse` currently mishandles [strings that include surrogate code units](https://www.compart.com/en/unicode/block/U+1D400).

    reverse( '𝑨𝑩𝑪' ) !== '𝑪𝑩𝑨'; // true

This limitation could be [documented](https://stdlib.io/docs/api/v0.0.90/@stdlib/string/reverse) or the implementation could be changed. For example

    function reverse( str ) {
        if ( !isString( str ) ) {
            throw new TypeError( 'invalid argument. First argument must be a string primitive. Value: `' + str + '`.' );
        }
        return Array.from( str ).reverse().join( '' );
    }

**Comment by kgryte** [comment]
@Andrew-Cottrell Thank you for bringing this to our attention. We'll work on getting a patch shortly.

**Comment by kgryte** [comment]
@Andrew-Cottrell Just pushed a patch. I added your test case [here](https://github.com/stdlib-js/stdlib/blob/6bca56ed70c81ac56c111c2453d5224dffdc7142/lib/node_modules/%40stdlib/string/reverse/test/test.js#L77). Tests pass, so I will consider this resolved. Available on the latest `develop`.
