### ISSUE TITLE
[BUG]: setting seed=0 leads to non-deterministic behavior

### ISSUE THREAD

**Issue by mglezer** [stdlib-js/stdlib#2952]
### Description

I expect that setting the seed to any positive integer, including zero, should lead to deterministic behavior. This is, for example, how Python's built-in random library works. However this is not the case for `@stdlib/random-shuffle`; the seed seems to be silently ignored. Either seeding with zero should produce deterministic behavior, or it should fail loudly, just like with negative seed values.

### Related Issues

Related issues # , # , and # .

### Questions

No.

### Reproduction

```shell
In the node REPL:


> const shuffle = require('@stdlib/random-shuffle')
> shuffle.factory({ seed: 0 })([1,2,3])
> shuffle.factory({ seed: 0 })([1,2,3])
```
```


### Expected Results

```shell
Either

> const shuffle = require('@stdlib/random-shuffle')
> shuffle.factory({ seed: 0 })([1,2,3])
[[ SOME PERMUTATION ]]
> shuffle.factory({ seed: 0 })([1,2,3])
[[ THE SAME PERMUTATION ]]
```

or, throw an error and require strictly positive seeds.
```


### Actual Results

```shell
> const shuffle = require('@stdlib/random-shuffle')
> shuffle.factory({ seed: 0 })([1,2,3])
[ 3, 2, 1 ]
> shuffle.factory({ seed: 0 })([1,2,3])
[ 2, 3, 1 ]
```
```


### Version

0.2.1

### Environments

Node.js

### Browser Version

_No response_

### Node.js / npm Version

_No response_

### Platform

_No response_

### Checklist

- [X] Read and understood the [Code of Conduct](https://github.com/stdlib-js/stdlib/blob/develop/CODE_OF_CONDUCT.md).
- [X] Searched for existing issues and pull requests.

**Comment by kgryte** [comment]
@mglezer You're right. It seems to be due to the following line: https://github.com/stdlib-js/stdlib/blob/7b02c160d8c9ecf6742ea0178c733f938e0c94c4/lib/node_modules/%40stdlib/random/shuffle/lib/factory.js#L66.

@Planeshifter Looking back through the code history, is there a reason why you wrote this to have a weak check (e.g., `if ( config.seed ) {...}`)?

**Comment by kgryte** [comment]
@mglezer Thanks for reporting. This issue was resolved in https://github.com/stdlib-js/stdlib/pull/3007, and the patch should be made available in the next round of package releases.

cc @Planeshifter
