### ISSUE TITLE
[@stdlib/math/base/special/haversin] Incorrect operator in definition equation image

### ISSUE THREAD

**Issue by Andrew-Cottrell** [stdlib-js/stdlib#301]
https://github.com/stdlib-js/stdlib/blob/19d5e91311a86c4888d22ca055c4924b3a32ffd4/lib/node_modules/%40stdlib/math/base/special/haversin/README.md

The definition equation image has a _plus_ (`+`) operator where a _minus_ (`−`) operator should be.

**Comment by kgryte** [comment]
@Andrew-Cottrell You're right! Will fix shortly. Thanks for catching this!

**Comment by Andrew-Cottrell** [comment]
FYI, the image continues to display the incorrect operator. I guess an automated or manual build step is required to re-generate the `equation_haversine.svg` file.

https://github.com/stdlib-js/stdlib/blob/b4d11aac1aa74441653f0ba195a184fd5cc51de0/lib/node_modules/%40stdlib/math/base/special/haversin/docs/img/equation_haversine.svg

**Comment by kgryte** [comment]
@Andrew-Cottrell You're right! Forgot to regenerate the SVG and update the image URL. Doing now...

**Comment by kgryte** [comment]
@Andrew-Cottrell Should be fixed now!

**Comment by Andrew-Cottrell** [comment]
Looks good to me 🙂

**Comment by kgryte** [comment]
@Andrew-Cottrell Great! Thanks for flagging this!
