### ISSUE TITLE
kernelBetainc incorrect documentation

### ISSUE THREAD

**Issue by jackschmidt** [stdlib-js/stdlib#302]
## Checklist

> Please ensure the following tasks are completed before filing a bug report.

-   [x] Read and understood the [Code of Conduct][code-of-conduct].
-   [x] Searched for existing issues and pull requests.

## Description

> Description of the issue.

The documentation and the source code disagree on the order of the boolean arguments to kernelBetainc.

[docs](https://github.com/stdlib-js/stdlib/tree/develop/lib/node_modules/%40stdlib/math/base/special/kernel-betainc#kernelbetainc-out-x-a-b-regularized-upper-) last arguments are: regularized, upper

[code](https://github.com/stdlib-js/stdlib/blob/f706d236a7369966ded040913678cd23eb738e2a/lib/node_modules/%40stdlib/math/base/special/kernel-betainc/lib/main.js#L55) last arguments are: invert, normalized
[code](https://github.com/stdlib-js/stdlib/blob/f706d236a7369966ded040913678cd23eb738e2a/lib/node_modules/%40stdlib/math/base/special/kernel-betainc/lib/main.js#L35-L36) documentation that invert means upper, and normalized means regularized

<s>Additionally, the [code for the case where storage is newly allocated](https://github.com/stdlib-js/stdlib/blob/f706d236a7369966ded040913678cd23eb738e2a/lib/node_modules/%40stdlib/math/base/special/kernel-betainc/lib/main.js#L57) drops the last argument.</s>

The [numerical cases code](https://github.com/stdlib-js/stdlib/blob/f706d236a7369966ded040913678cd23eb738e2a/lib/node_modules/%40stdlib/math/base/special/kernel-betainc/lib/kernel_betainc.js#L78-L79) agrees with the main.js code and disagrees with the website documentation.

The non-kernel function is [documented](https://github.com/stdlib-js/stdlib/tree/f706d236a7369966ded040913678cd23eb738e2a/lib/node_modules/%40stdlib/math/base/special/betainc#betainc-x-a-b-regularized-upper-) as regularized, upper.

The non-kernel function's [code](https://github.com/stdlib-js/stdlib/blob/f706d236a7369966ded040913678cd23eb738e2a/lib/node_modules/%40stdlib/math/base/special/betainc/lib/betainc.js#L55-L61) correctly reverses the arguments to match `kernelBetainc`'s code. Additionally it statically allocates storage, <s>so the bug in the "allocate new storage" is not seen.</s>

The name "invert" for "upper" may also cause confusion with inverse distribution. "upper" and "regularized" seem like fine names to use consistently in both the documentation and the code.

## Related Issues

> Does this issue have any related issues?

I did not see any.

## Questions

> Any questions for reviewers?

No.

## Other

> Any other information relevant to this issue? This may include screenshots, references, stack traces, sample output, and/or implementation notes.

No

#### Demo

> If relevant, provide a link to a live demo.

No.

#### Reproduction

> What steps are required to reproduce the unexpected output?

```javascript
out1=[0,0];
out1 = kernelBetainc( out1, 0.2, 1.0, 2.0, true, true );
out2 = kernelBetainc( 0.2, 1.0, 2.0, true, true );
```

#### Expected Results

> What are the expected results?

out1 and out2 should be (exactly) equal.

#### Actual Results

> What are the actual results?

<s>Not equal</s> (Equal, typo in my code, not yours!)

#### Environments

> What environments are affected (e.g., `Node v0.4.x`, `Chrome`, `IE 11`)? If Node.js, include the `npm` version, operating system, and any other potentially relevant platform information.

all environments where the code can run

[code-of-conduct]: https://github.com/stdlib-js/stdlib/blob/develop/CODE_OF_CONDUCT.md

**Comment by kgryte** [comment]
@jackschmidt Thanks for reporting this bug! We'll work to get a fix shortly.

**Comment by kgryte** [comment]
@Planeshifter Can you look into this?

**Comment by kgryte** [comment]
@Planeshifter We should also add additional tests [here](https://github.com/stdlib-js/stdlib/blob/f706d236a7369966ded040913678cd23eb738e2a/lib/node_modules/%40stdlib/math/base/special/kernel-betainc/test/test.js#L105).

**Comment by Planeshifter** [comment]
Thank you for filing this issue! 

We can confirm the errors in the documentation as well as the inconsistent naming and will fix it shortly.

But would you be able to please elaborate a bit more on the unexpected output you are seeing?

When running your example code 

```
out1=[0,0];
out1 = kernelBetainc( out1, 0.2, 1.0, 2.0, true, true );
out2 = kernelBetainc( 0.2, 1.0, 2.0, true, true );
```
I see both `out1` and `out2`  having the values `[ 0.64, 1.6 ]`.

From what I can tell, the implementation doesn't drop an argument; it's just that the names do not align when only five arguments are supplied and the output array is omitted:

```
function kernelBetainc( out, x, a, b, invert, normalized ) {
	if ( arguments.length === 5 ) {
		return compute( new Array( 2 ), out, x, a, b, invert ); // here `out` is `x`, `x` is `a`, `a` is `b` etc.
	}
	return compute( out, x, a, b, invert, normalized );
}
```

**Comment by jackschmidt** [comment]
Thank you!

My apologies. Yes, the variables are simply renamed. No code error, just disagreement with docs.

Thanks again! I am looking for a stable version of the upper binomial cdf (my simple 1 - summation has returned negative probabilities) and I think your project will work well.

**Comment by Planeshifter** [comment]
No worries, thanks for the confirmation!

Will post here once the documentation is updated.

With respect to a binomial CDF, just a pointer that we have statistical distributions including functions like PDF, CDF, and quantiles living at https://github.com/stdlib-js/stdlib/tree/develop/lib/node_modules/%40stdlib/stats/base/dists in case you haven't seen them.

**Comment by Planeshifter** [comment]
With commit 384f5d0ed2fefa7dad236c1e2f39110e5117dd38, we have now updated the documentation and changed the parameter order of `kernelBetainc` to match both `@stdlib/math/base/special/betainc` and the documentation of  `@stdlib/math/base/special/kernel-betainc`. Closing this issue, but please let us know in case you encounter any further issues. Thanks again!
