### ISSUE TITLE
[BUG]: dependencies missing on npm registry

### ISSUE THREAD

**Issue by thomasfsteeples** [stdlib-js/stdlib#3060]
### Description

Some stdlib packages don't include their stdlib dependencies in the npm registry version of their package.json. 

For example, @stdlib/math lists @stdlib/constants as a dependency in its [package.json](https://github.com/stdlib-js/math/blob/main/package.json) on Github, but it is not included in its [package.json](https://www.npmjs.com/package/@stdlib/math/) on npm. As a result, if I run a function from @stdlib/math whose implementation depends on @stdlib/constants, I get an import error as the stdlib dependencies cannot be found. 

### Reproduction

1. Run `npm add @stdlib/math`
2. Observe that `constants` is missing from `node_modules/@stdlib`

### Environments

N/A

### Checklist

- [x] Read and understood the [Code of Conduct](https://github.com/stdlib-js/stdlib/blob/develop/CODE_OF_CONDUCT.md).
- [x] Searched for existing issues and pull requests.

**Comment by Planeshifter** [comment]
@thomasfsteeples Thanks for bringing this to our attention! I can confirm the issue; we will look into publishing a fix for this as soon as we can.

**Comment by Planeshifter** [comment]
@thomasfsteeples A new patch has been published for the top-level namespace packages. This issue should now be resolved. Please let us know if you encounter any further issues and many thanks again for reporting!

**Comment by kgryte** [comment]
@Planeshifter @thomasfsteeples Can this issue now be closed?

**Comment by Planeshifter** [comment]
Closing as this issue has been resolved.
