### ISSUE TITLE
[RFC]: Incomplete code coverage for `blas/ext/base/dnanasumors`

### ISSUE THREAD

**Issue by headlessNode** [stdlib-js/stdlib#3073]
See https://coverage.stdlib.io/blas/ext/base/dnanasumors/index.html.

Need to add a test case in each of the relevant test files. The test case should handle the situation where the stride is `0` and the first element is `NaN`.

For reference see #3051

**Comment by Vishal-Kumar2006** [comment]
Test Case for ndarray.js

strideX= 0 and First Element is NaN
Input: N = 4, x = [NaN, 2.0, 3.0, 4.0], strideX = 0, offsetX = 0
