### ISSUE TITLE
[RFC]: Incomplete code coverage for `blas/ext/base/dnansumors`

### ISSUE THREAD

**Issue by headlessNode** [stdlib-js/stdlib#3075]
see https://coverage.stdlib.io/blas/ext/base/dnansumors/index.html.

Need to add a test case in each of the relevant test files. The test case should handle the situation where the stride is `0` and the first element is `NaN`.

For reference see #3051.

**Comment by abdullahsadik00** [comment]
Hi @headlessNode can I work on this issue
