### ISSUE TITLE
[BUG]: Incorrect `JSDoc` closing marker in the ESLint rule `jsdoc-no-space-aligned-asterisks`

### ISSUE THREAD

**Issue by headlessNode** [stdlib-js/stdlib#3109]
### Description

In the `fix` function here: https://github.com/stdlib-js/stdlib/blob/develop/lib/node_modules/%40stdlib/_tools/eslint/rules/jsdoc-no-space-aligned-asterisks/lib/main.js#L97

the `JSDoc` comments are incorrectly formatted for applying a fix. Specifically, the closing marker is incorrect, leading to improperly formatted comments when using the `ESLint` auto-fixing.

### Related Issues

None.

### Questions

No.

### Demo

N/A

### Reproduction

```shell
N/A
```

### Expected Results

```shell
N/A
```

### Actual Results

```shell
N/A
```

### Version

N/A

### Environments

N/A

### Browser Version

N/A

### Node.js / npm Version

N/A

### Platform

N/A

### Checklist

- [x] Read and understood the [Code of Conduct](https://github.com/stdlib-js/stdlib/blob/develop/CODE_OF_CONDUCT.md).
- [x] Searched for existing issues and pull requests.

**Comment by Shreyyy07** [comment]
Hey!!
I want  contribute to this issue and this is going to be my first contribution.
