### ISSUE TITLE
[RFC]: Incomplete code coverage for `blas/ext/base/dnannsumkbn2`

### ISSUE THREAD

**Issue by headlessNode** [stdlib-js/stdlib#3186]
### Description

This RFC proposes to add a test case in each of the relevant test files. The test case should handle the situation where the stride is `0` and the first element is `NaN`.

Coverage report: https://coverage.stdlib.io/blas/ext/base/dnannsumkbn2/index.html
For reference see: #3051 

### Related Issues

Related issues # , # , and # .

### Questions

No.

### Other

No.

### Checklist

- [x] I have read and understood the [Code of Conduct](https://github.com/stdlib-js/stdlib/blob/develop/CODE_OF_CONDUCT.md).
- [x] Searched for existing issues and pull requests.
- [x] The issue name begins with `RFC:`.

**Comment by AyushkhatiDev** [comment]
@kgryte  I’ve submitted PR #3199 to address this issue. However, I faced an `npm install` issue during development. The changes are manually verified and tested with available setups. Kindly review and let me know if there are any concerns.

**Comment by saurabhraghuvanshii** [comment]
hii @headlessNode  the code mention in #3051 is replicate here .

**Comment by headlessNode** [comment]
@saurabhraghuvanshii In what context?

**Comment by saurabhraghuvanshii** [comment]
@headlessNode I mean for test - case we refer #3051 here to add.

**Comment by headlessNode** [comment]
@saurabhraghuvanshii Yes. But there are some differences between the function in #3051 and `blas/ext/base/dnannsumkbn2`. You can go through the function documentation to understand that difference.

**Comment by saurabhraghuvanshii** [comment]
@headlessNode ok, is you working on this?

**Comment by headlessNode** [comment]
@saurabhraghuvanshii No. You can work on it if you want.

**Comment by saurabhraghuvanshii** [comment]
@headlessNode ok

**Comment by saurabhraghuvanshii** [comment]
@headlessNode  as I see in dnannsumkbn2/lib/ndarray.js is incomplete in report as you mention , so should i work on only ndarray.js
