### ISSUE TITLE
[RFC]: add `assert/is-phone-number`

### ISSUE THREAD

**Issue by ghost** [stdlib-js/stdlib#3195]
## **Description**
This RFC proposes adding new function for validating the phone number

The stdlib.js library offers a wide range of utility functions, including robust checks for various data formats such as email addresses (is-email-address) and others. However, it currently lacks a utility function to validate phone numbers, which is a common requirement in many applications.
To fill this gap, I propose adding a new function, **is-phone-number, to the /assert/ module.**

### Expected Behavior:
The is-phone-number function should:

- Accept a string input.
- Validate the input against commonly used phone number formats.
- Support international and local phone number patterns.
- Return true if the input is a valid phone number, and false otherwise.

### Related Issues

Related issues # , # , and # .

### Questions

No.

### Other

No.

### Checklist

- [x] I have read and understood the [Code of Conduct](https://github.com/stdlib-js/stdlib/blob/develop/CODE_OF_CONDUCT.md).
- [x] Searched for existing issues and pull requests.
- [x] The issue name begins with `RFC:`.

**Comment by kgryte** [comment]
Thank you for opening this RFC. However, I do have concerns regarding how feasible creating a robust solution will be given widespread variability in phone number formats and conventions. You should provide a sketch of your proposed solution as a comment in this RFC **before** opening a PR adding a new package in order to avoid wasted effort.

**Comment by RaviSadam** [comment]
@kgryte 
I think coming up with simple regex won't be sufficient for phone number checking. I found this page on the internet (https://www.globalcallforwarding.com/international-call-prefixes/) where they specify all the country-specific phone number formats. I came up with a simple solution, which is to write regex for each specific country and check the given string against these regex patterns. If the user specifies the country code, that's fine—the regex will work well in these cases. However, if the user doesn't provide the country code along with the phone number, what should we do?

**Comment by ghost** [comment]
@kgryte 
I have read an article from Wikipedia ([click here] (https://en.wikipedia.org/wiki/List_of_mobile_telephone_prefixes_by_country))Where they have listed almost all the country phone number format. And I conclude that we can't validate a phone number by one simple regex. So, my approach is writing a regex for each country phone format and then check the given string against each regex pattern. If you're ok with that I will provide a google sheet(link) with country specific phone number regex.

**Comment by AbhijitRaut04** [comment]
@kgryte and @RaviSadam  I have got this common phone number formats.

Examples of Phone Number Formats
1.	United States (US) and Canada
o	Format: `+1 (XXX) XXX-XXXX`
o	Example: `+1 415 555 2671`
2.	United Kingdom (UK)
o	Format: `+44 XXXX XXXXXX`
o	Example: `+44 20 7946 0958`
3.	India
o	Format: `+91 XXXXX-XXXXX`
o	Example: `+91 98765 43210`
4.	Australia
o	Format: `+61 X XXXX XXXX`
o	Example: `+61 4 1234 5678`
5.	Germany
o	Format: `+49 XXXX XXXXXX`
o	Example: `+49 30 12345678`
6.	France
o	Format: `+33 X XX XX XX XX`
o	Example: `+33 1 23 45 67 89`
7.	China
o	Format: `+86 XXXX XXXX XXXX`
o	Example: `+86 10 1234 5678`
8.	Japan
o	Format: `+81 XX XXXX XXXX`
o	Example: `+81 90 1234 5678`
9.	South Africa
o	Format: `+27 XX XXX XXXX`
o	Example: `+27 83 123 4567`
10.	Brazil
o	Format: `+55 XX XXXXX-XXXX`
o	Example: `+55 21 98765-4321`
11.	Russia
o	Format: `+7 XXX XXX XX XX`
o	Example: `+7 495 123 45 67`
12.	Mexico
o	Format: `+52 XX XXXX XXXX`
o	Example: `+52 55 1234 5678`
13.	Saudi Arabia
o	Format: `+966 X XXX XXXX`
o	Example: `+966 5 123 4567`
14.	Nigeria
o	Format: `+234 XXX XXX XXXX`
o	Example: `+234 803 123 4567`
15.	South Korea
o	Format: `+82 XX XXXX XXXX`
o	Example: `+82 10 1234 5678`
16.	Italy
o	Format: `+39 XXX XXXX XXX`
o	Example: `+39 06 1234 5678`
17.	Spain
o	Format: `+34 XXX XXX XXX`
o	Example: `+34 612 345 678`
18.	Argentina
o	Format: `+54 XX XXXX XXXX`
o	Example: `+54 11 1234 5678`
19.	Pakistan
o	Format: `+92 XXX XXXXXXX`
o	Example: `+92 300 1234567`
20.	Egypt
o	Format: `+20 X XXX XXXX`
o	Example: `+20 10 123 4567`

Special Number Types
1.	Toll-Free Numbers
o	US Example: `+1 800 123 4567`
o	India Example: `+91 1800 123 456`
2.	Premium Rate Numbers
o	UK Example: `+44 900 123 4567`
o	Australia Example: `+61 1900 654 321`
3.	Emergency Numbers
o	US: `911`
o	EU: `112`
o	India: `112`
4.	Shortcodes
o	SMS Services: `12345`
o	Banking Services: `56789`

**Comment by kgryte** [comment]
What about phone numbers, such as in the US, which are missing the country code? or the area code? What about countries with more than one calling code? Etc.

I am very skeptical that we can reasonably support phone number validation in `stdlib`. If you take a look at Google's [libphonenumber](https://github.com/google/libphonenumber), the logic required for phone number validation is massive. And I, personally, don't want to maintain such complexity, especially given that telephone number formats are a moving target.

**Comment by ghost** [comment]
@kgryte 
Yeap Completely understand.
Thank you 😊
