### ISSUE TITLE
[RFC]: Incomplete code coverage for `blas/ext/base/dnannsumkbn`

### ISSUE THREAD

**Issue by headlessNode** [stdlib-js/stdlib#3201]
### Description

This RFC proposes to add a test case in each of the relevant test files. The test case should handle the situation where the stride is `0` and the first element is `NaN`.

Coverage report: https://coverage.stdlib.io/blas/ext/base/dnannsumkbn/index.html
For reference see: https://github.com/stdlib-js/stdlib/pull/3051

### Related Issues

Related issues # , # , and # .

### Questions

No.

### Other

No.

### Checklist

- [x] I have read and understood the [Code of Conduct](https://github.com/stdlib-js/stdlib/blob/develop/CODE_OF_CONDUCT.md).
- [x] Searched for existing issues and pull requests.
- [x] The issue name begins with `RFC:`.

**Comment by yas8say** [comment]
Hi there, how can i get started ?

**Comment by headlessNode** [comment]
@yas8say For a general idea of what's needed, refer to the PR linked in the post.

**Comment by saurabhraghuvanshii** [comment]
Hii @headlessNode I am working on it.

**Comment by saurabhraghuvanshii** [comment]
hii @headlessNode  i open PR but why run_affected_tests / Run affected tests (pull_request)  are failed
