### ISSUE TITLE
[RFC]: refactor `math/base/special/cexp` to follow latest project conventions

### ISSUE THREAD

**Issue by aayush0325** [stdlib-js/stdlib#3393]
### Description

This RFC proposes refactoring of `math/base/special/cexp` to use in house stdlib functions for operations like `exp`, `sin`, `cos` and `copysign`.

### Related Issues

None.

### Questions

No.

### Other

No.

### Checklist

- [x] I have read and understood the [Code of Conduct](https://github.com/stdlib-js/stdlib/blob/develop/CODE_OF_CONDUCT.md).
- [x] Searched for existing issues and pull requests.
- [x] The issue name begins with `RFC:`.

**Comment by kgryte** [comment]
@aayush0325 Thanks for opening this issue. Yes, we should definitely update to use stdlib functions and also replace the usage of the `INFINITY` and `NAN` macros. For the former, we have a constant package. For the latter, we should just use `0.0 / 0.0`.

**Comment by aayush0325** [comment]
@kgryte i have done just that in the pr linked to this issue!
