### ISSUE TITLE
[RFC]: Update `complex/float32` and `complex/float64`  adding magnitude and angle functions for complex number

### ISSUE THREAD

**Issue by vivekmaurya001** [stdlib-js/stdlib#3395]
### Description

This RFC proposes adding functions to find parameters for polar representation of complex number like `mag` and  `ang` 

### Related Issues

Related issues # , # , and # .

### Questions

No.

### Other

No.

### Checklist

- [x] I have read and understood the [Code of Conduct](https://github.com/stdlib-js/stdlib/blob/develop/CODE_OF_CONDUCT.md).
- [x] Searched for existing issues and pull requests.
- [x] The issue name begins with `RFC:`.

**Comment by vivekmaurya001** [comment]
@kgryte  can i start working on it if u like

**Comment by kgryte** [comment]
As discussed during office hours, the proposed functions are already present:

- https://github.com/stdlib-js/stdlib/tree/develop/lib/node_modules/%40stdlib/math/base/special/cabs
- https://github.com/stdlib-js/stdlib/tree/develop/lib/node_modules/%40stdlib/math/base/special/cabsf
- https://github.com/stdlib-js/stdlib/tree/develop/lib/node_modules/%40stdlib/math/base/special/cphase

The only one which is not currently present is `cphasef`; however, an RFC for that function can be opened as a separate issue.

As such, I will go head and close this issue.
