### ISSUE TITLE
RFC: add support for computing Unicode-aware string length

### ISSUE THREAD

**Issue by ShraddheyaS** [stdlib-js/stdlib#353]
## Checklist

> Please ensure the following tasks are completed before submitting a feature request.

-   [X] Read and understood the [Code of Conduct][code-of-conduct].
-   [X] Searched for existing issues and pull requests.
-   [X] The issue name begins with `RFC:`.

## Description

> Description of the feature request.

This RFC proposes adding support for computing Unicode-aware string length.

## Related Issues

> Does this feature request have any related issues?

Related issues #296, #297, and #298.

## Questions

> Any questions for reviewers?

If this is accepted, what could be the package location and name?

## Other

> Any other information relevant to this feature request? This may include screenshots, references, sample output, and/or implementation notes.

We could use the [string iterator][string-iterator-MDN] as it is Unicode aware.
Cursory implementation:

```
let iterator = str[ Symbol.iterator ]();
let _char = iterator.next();
let _len = 0;
while( !_char.done ) {
  len++;
  _char = iterator.next();
}
return _len;
```

[code-of-conduct]: https://github.com/stdlib-js/stdlib/blob/develop/CODE_OF_CONDUCT.md
[string-iterator-MDN]: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String/@@iterator

**Comment by kgryte** [comment]
As for the package name: `@stdlib/string/len`.

Regarding implementation, we'd need to support non-Symbol environments (e.g., ES5 and older versions of Node.js), so cannot rely on string iterator. We'd actually need to implement the string parsing logic ourselves.
