### ISSUE TITLE
RFC: Add support for getting Unicode code point from string at specified position

### ISSUE THREAD

**Issue by ShraddheyaS** [stdlib-js/stdlib#356]
## Checklist

> Please ensure the following tasks are completed before submitting a feature request.

-   [X] Read and understood the [Code of Conduct][code-of-conduct].
-   [X] Searched for existing issues and pull requests.
-   [X] The issue name begins with `RFC:`.

## Description

> Description of the feature request.

This RFC proposes adding support for getting the Unicode code point from a string at a specified position.
Package: `@stdlib/string/code-point-at`
Alias: `codePointAt`
Function prototype: `codePointAt( string, position[, backward] )`

## Related Issues

> Does this feature request have any related issues?

No.

## Questions

> Any questions for reviewers?

No.

## Other

> Any other information relevant to this feature request? This may include screenshots, references, sample output, and/or implementation notes.

* [MDN codePointAt][mdn-code-point-at]

[code-of-conduct]: https://github.com/stdlib-js/stdlib/blob/develop/CODE_OF_CONDUCT.md
[mdn-code-point-at]: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String/codePointAt

**Comment by kgryte** [comment]
@ShraddheyaS Thanks! Sounds good. This will be a welcome addition. :)
