### ISSUE TITLE
RFC: Add support for getting next extended grapheme cluster break

### ISSUE THREAD

**Issue by ShraddheyaS** [stdlib-js/stdlib#357]
## Checklist

> Please ensure the following tasks are completed before submitting a feature request.

-   [X] Read and understood the [Code of Conduct][code-of-conduct].
-   [X] Searched for existing issues and pull requests.
-   [X] The issue name begins with `RFC:`.

## Description

> Description of the feature request.

This RFC proposes to add support for getting next extended grapheme cluster break in a string after a specified position.
Package: `@stdlib/string/next-grapheme-cluster-break`
Alias: `nextGraphemeClusterBreak`
Function prototype: `nextGraphemeClusterBreak( str[, fromIndex] )`

## Related Issues

> Does this feature request have any related issues?

No.

## Questions

> Any questions for reviewers?

No.

## Other

> Any other information relevant to this feature request? This may include screenshots, references, sample output, and/or implementation notes.

No.

[code-of-conduct]: https://github.com/stdlib-js/stdlib/blob/develop/CODE_OF_CONDUCT.md

**Comment by kgryte** [comment]
@ShraddheyaS Thanks! We can also probably add a companion utility: `@stdlib/string/prev-grapheme-cluster-break`.

**Comment by ShraddheyaS** [comment]
@kgryte I am wondering what the best way of implementing `@stdlib/string/prev-grapheme-cluster-break` would be. We can have duplicate code like [should_break.js](https://github.com/stdlib-js/stdlib/blob/develop/lib/node_modules/%40stdlib/string/num-grapheme-clusters/lib/should_break.js) etc. in both the packages or use `@stdlib/string/next-grapheme-cluster-break` directly to implement `@stdlib/string/prev-grapheme-cluster-break`. Basically a tradeoff between code reusability and performance.

**Comment by kgryte** [comment]
@ShraddheyaS That is a good question. I am not sure the best approach here. I don't see an easy way to make the interface for `should_break` user friendly. Meaning, not clear to me how to make this a "public" package for general consumption.

And not clear to me what kind of abstraction layer we could use to wrap `should_break` to make it a general utility.
