### ISSUE TITLE
RFC: Add support to determine if a position in a string marks the start of a UTF-16 surrogate pair

### ISSUE THREAD

**Issue by ShraddheyaS** [stdlib-js/stdlib#359]
## Checklist

> Please ensure the following tasks are completed before submitting a feature request.

-   [X] Read and understood the [Code of Conduct][code-of-conduct].
-   [X] Searched for existing issues and pull requests.
-   [X] The issue name begins with `RFC:`.

## Description

> Description of the feature request.

This RFC proposes to add support to determine if a position in a string marks the start of a [UTF-16][utf-16] surrogate pair.
Package: `@stdlib/assert/has-utf16-surrogate-pair-at`
Alias: `hasUTF16SurrogatePairAt`
Interface: `hasUTF16SurrogatePairAt( str, pos )`

## Related Issues

> Does this feature request have any related issues?

No.

## Questions

> Any questions for reviewers?

No.

## Other

> Any other information relevant to this feature request? This may include screenshots, references, sample output, and/or implementation notes.

No.

[code-of-conduct]: https://github.com/stdlib-js/stdlib/blob/develop/CODE_OF_CONDUCT.md
[utf-16]: https://en.wikipedia.org/wiki/UTF-16

**Comment by kgryte** [comment]
@ShraddheyaS Awesome! This would be great to add to `stdlib`. :)
