### ISSUE TITLE
RFC: Add support for getting previous extended grapheme cluster break

### ISSUE THREAD

**Issue by ShraddheyaS** [stdlib-js/stdlib#362]
## Checklist

> Please ensure the following tasks are completed before submitting a feature request.

-   [X] Read and understood the [Code of Conduct][code-of-conduct].
-   [X] Searched for existing issues and pull requests.
-   [X] The issue name begins with `RFC:`.

## Description

> Description of the feature request.

This RFC proposes to add support for getting previous extended grapheme cluster break in a string before a specified position.
Package: `@stdlib/string/prev-grapheme-cluster-break`
Alias: `prevGraphemeClusterBreak`
Function prototype: `prevGraphemeClusterBreak( str, beforeIndex )`

## Related Issues

> Does this feature request have any related issues?

No.

## Questions

> Any questions for reviewers?

No.

## Other

> Any other information relevant to this feature request? This may include screenshots, references, sample output, and/or implementation notes.

No.

[code-of-conduct]: https://github.com/stdlib-js/stdlib/blob/develop/CODE_OF_CONDUCT.md

**Comment by mobljs** [comment]
can I use it now ?

**Comment by kgryte** [comment]
@mobljs We do have functionality for getting the next extended grapheme cluster break; however, we have yet to add similar functionality for getting the **previous** grapheme cluster break.

You need the latter, rather than the former? Or stated otherwise, what is your use case?

**Comment by kgryte** [comment]
This was added in https://github.com/stdlib-js/stdlib/commit/f52f807a13a7bda15a7f9ec072e68f314491062e. Closing...
