### ISSUE TITLE
npm audit security report

### ISSUE THREAD

**Issue by antonkatz** [stdlib-js/stdlib#366]
After installing stdlib just now

 === npm audit security report ===                        
                                                                                
┌──────────────────────────────────────────────────────────────────────────────┐
│                                Manual Review                                 │
│            Some vulnerabilities require your attention to resolve            │
│                                                                              │
│         Visit https://go.npm.me/audit-guide for additional guidance          │
└──────────────────────────────────────────────────────────────────────────────┘
┌───────────────┬──────────────────────────────────────────────────────────────┐
│ High          │ Prototype Pollution                                          │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Package       │ dot-prop                                                     │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Patched in    │ >=4.2.1 <5.0.0 || >=5.1.1                                    │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Dependency of │ @stdlib/stdlib                                               │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Path          │ @stdlib/stdlib > update-notifier > configstore > dot-prop    │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ More info     │ https://npmjs.com/advisories/1213                            │
└───────────────┴──────────────────────────────────────────────────────────────┘

**Comment by kgryte** [comment]
This is not a security vulnerability which affects this project. `update-notifier` is only used in our command-line interfaces (CLIs) and is thus not used in library code, and we do not provide public access to any of its APIs.

Closing...
