### ISSUE TITLE
TypeScript types not provided for @stdlib/array/to-iterator and to-iterator-right

### ISSUE THREAD

**Issue by EricCrosson** [stdlib-js/stdlib#371]
## Checklist

> Please ensure the following tasks are completed before filing a bug report.

-   [X] Read and understood the [Code of Conduct][code-of-conduct].
-   [X] Searched for existing issues and pull requests.

## Description

> Description of the issue.

Encountered an error when writing the following TypeScript code:

``` typescript
import toIterator from '@stdlib/array/to-iterator'
```

The issue is that there is no `types` property in the to-iterator package.json, so the ~imported~ required package is untyped.

This prevents type-safe use between the to-iterator (helper) function and functions taking the data in iterator form.

Note: `to-iterator-right` is in the same state

## Related Issues

> Does this issue have any related issues?

## Questions

> Any questions for reviewers?

No.

## Other

> Any other information relevant to this issue? This may include screenshots, references, stack traces, sample output, and/or implementation notes.

#### Reproduction

> What steps are required to reproduce the unexpected output?

In order to reproduce this bug, do the following:

- in a TypeScript project, install @stdlib/stdlib
- try to `import toIterator from '@stdlib/array/to-iterator'`

#### Expected Results

> What are the expected results?

The following results are expected:

No compilation error because types are provided for the `to-iterator` sub-package just as they are other packages, e.g. @stdlib/stats/incr/mean

#### Actual Results

> What are the actual results?

The following are the actual results:

```text
Could not find a declaration file for module.... implicitly has `any` type
```

#### Environments

> What environments are affected (e.g., `Node v0.4.x`, `Chrome`, `IE 11`)? If Node.js, include the `npm` version, operating system, and any other potentially relevant platform information.

The following environments are affected:

- I am using Node.js, but anywhere using TypeScript

[code-of-conduct]: https://github.com/stdlib-js/stdlib/blob/develop/CODE_OF_CONDUCT.md

**Comment by kgryte** [comment]
@EricCrosson Thanks for filing this issue.

@Planeshifter is currently working on adding full TypeScript support. Any updates on the type declarations for these particular packages?

**Comment by kgryte** [comment]
@EricCrosson types have been created in 9208302ef62a0d0d4ae4dcc2ca61898a2460d06a and bf455a8e608f8f3804040ea7db88f4ab70774e17 and should be available in the next release.

If you find any other missing types which we should prioritize as we continue moving toward 100% coverage, let us know.

Thanks, @Planeshifter, for adding these!
