### ISSUE TITLE
RFC: reduce the time it takes to clone the repository

### ISSUE THREAD

**Issue by aminya** [stdlib-js/stdlib#373]
## Checklist

> Please ensure the following tasks are completed before submitting a feature request.

-   [x] Read and understood the [Code of Conduct][code-of-conduct].
-   [x] Searched for existing issues and pull requests.
-   [x] The issue name begins with `RFC:`.

## Description

> Description of the feature request.

I noticed that this repository is very huge, and it takes a long time to clone, which makes it hard to contribute. 

![image](https://user-images.githubusercontent.com/16418197/108497976-d841e480-7271-11eb-933c-26013c30c6b6.png)

There are multiple ways to reduce the size:
- Generate the duplicated files instead of copying them
- Moving some of the files to other links or repositories
- Using git lfs
- Removing the files that are not used anymore from the history.
<details>
	<summary>Example script for cleaning history</summary>

PowerShell
```ps1
# clone:
# git clone https://github.com/stdlib-js/stdlib.git
# cd "stdlib"

$paths = "some/folder",
         "some/file"

foreach ($path in $paths) {
   # using https://github.com/newren/git-filter-repo
   git filter-repo --invert-paths --path $path
   if (test-path $path) {
      rm $path -Recurse -Force
   }
   git reflog expire --expire=now --all && git gc --prune=now --aggressive
}
```

```
git remote add origin git@github.com:stdlib-js/stdlib.git
git push --set-upstream origin master -f
git push --force --all origin 
```

</details>

## Related Issues

> Does this feature request have any related issues?

## Questions

> Any questions for reviewers?

No.

## Other

> Any other information relevant to this feature request? This may include screenshots, references, sample output, and/or implementation notes.

No.

[code-of-conduct]: https://github.com/stdlib-js/stdlib/blob/develop/CODE_OF_CONDUCT.md

**Comment by kgryte** [comment]
@aminya Thanks for filing this issue. We are certainly interested in exploring approaches for making this project easier to contribute to.

Re: clone times. One thing we suggest in our [development guide](https://github.com/stdlib-js/stdlib/blob/develop/docs/development.md#download), and which is not included in your suggestions above, is to limit the clone depth. We do this on our CI environments and seem to have decent success.

**Comment by kgryte** [comment]
Another possibility for reducing clone time is performing a shallow clone + sparse checkout. This is discussed on [SO](https://stackoverflow.com/questions/600079/how-do-i-clone-a-subdirectory-only-of-a-git-repository).
