### ISSUE TITLE
IS_NODE returning wrong result in Node.js versions >14.6.0

### ISSUE THREAD

**Issue by Planeshifter** [stdlib-js/stdlib#375]
## Checklist

> Please ensure the following tasks are completed before filing a bug report.

-   [x] Read and understood the [Code of Conduct][code-of-conduct].
-   [x] Searched for existing issues and pull requests.

## Description

> Description of the issue.

The value exported by `@stdlib/assert/is-node` is equal to `false`  in Node.js versions greater than or equal to 14.6.0.

## Questions

> Any questions for reviewers?

No.

## Other

> Any other information relevant to this issue? This may include screenshots, references, stack traces, sample output, and/or implementation notes.

#### Reproduction

> What steps are required to reproduce the unexpected output?

In order to reproduce this bug, do the following:

-   Switch to Node `v14.6.0`
-   Run the examples of `@stdlib/assert/is-node`.
-   Observe `false` being printed to the terminal.

#### Expected Results

> What are the expected results?

The following results are expected:

```text
var IS_NODE = require( '@stdlib/assert/is-node' );
// returns true
```

#### Actual Results

> What are the actual results?

The following are the actual results:

```text
var IS_NODE = require( '@stdlib/assert/is-node' );
// returns false
```

#### Environments

> What environments are affected (e.g., `Node v0.4.x`, `Chrome`, `IE 11`)? If Node.js, include the `npm` version, operating system, and any other potentially relevant platform information.

The following environments are affected:

-  All Node.js versions starting with `14.6.0`.

[code-of-conduct]: https://github.com/stdlib-js/stdlib/blob/develop/CODE_OF_CONDUCT.md

**Comment by Planeshifter** [comment]
Fixed per 8b99c9f3b9f8c447f046efb088656a6322a6aea3.

**Comment by kgryte** [comment]
Did some further investigating. After checking the results of `nativeClass` and `Object.prototype.toString` in newer versions of Node v14, I found the following discrepancy:

```
In [1]: Object.prototype.toString.call( require( 'process' ) )
Out[1]: '[object process]'

In [2]: nativeClass( require( 'process' ) )
Out[2]: '[object Object]'
```

Looks like discrepancy stems from this code: https://github.com/stdlib-js/stdlib/blob/44ec72fe845adaed3ea24c3d7d8607dfea0959ca/lib/node_modules/%40stdlib/utils/native-class/lib/polyfill.js#L51


During the transition from 14.5 to 14.6, looks like Node came to rely exclusively on `Symbol.toStringTag` for indicating the “native class”. When an environment supports `Symbol.toStringTag`, we try to remove so we can uncover the underlying result of calling [`Object.prototype.toString`](https://github.com/stdlib-js/stdlib/blob/44ec72fe845adaed3ea24c3d7d8607dfea0959ca/lib/node_modules/%40stdlib/utils/native-class/lib/polyfill.js#L68).

Prior to 14.6, the result of the latter was still `[object process]`. Afterward, after removing `Symbol.toStringTag`, the result is `[object Object]`.

I think a better workaround would be use `Object.prototype.toString` directly when resolving the native class of `process`. While this opens up the possibility of "brand" impersonation, this would retain original behavior and is arguably a bit more robust than allowing either `[object Object]` or `[object process]`.

**Comment by s3o0od888** [comment]
v14.6.0

**Comment by s3o0od888** [comment]
Unc0ver v14.6.0
