### ISSUE TITLE
npm package too big for jsDelivr

### ISSUE THREAD

**Issue by domoritz** [stdlib-js/stdlib#383]
I'm trying to load this package from [jsDelivr CDN](https://www.jsdelivr.com/package/npm/@stdlib/stdlib) but it fails because the package is over 100 MB. Are there any files that could be removed to reduce the package size?

**Comment by domoritz** [comment]
Probably related to https://github.com/stdlib-js/stdlib/issues/373

**Comment by domoritz** [comment]
A local installation also is hundreds of MBs.

**Comment by Planeshifter** [comment]
Thanks for reaching out! Indeed, the project is currently not as easily consumable as it should be. One of our next steps is to finish the tooling to publish individual namespace packages to npm (e.g., all of `@stdlib/assert` or all of `@stdlib/random`). Will keep you posted.

However, we do have distributable UMD bundles of the project that you might want to look at. They are also available via the jsDelivr CDN:
 
https://github.com/stdlib-js/stdlib/tree/develop/dist#usage

**Comment by kgryte** [comment]
@domoritz Beside using one of the UMD bundles, you can also do one of the following:

1.  If your target environment supports ESM, you could consider our experimental [ESM](https://github.com/stdlib-js/esm) build.

2.  Install locally, vendor, and host.

3.  Use project tooling, similar to how we do [here](https://github.com/stdlib-js/stdlib/blob/0f1fc5d028cf3180e134a855153299ecbed048ff/dist/math-base-special-flat/scripts/build.js), to create your own UMD bundle.

Would any of the above possibly work?

**Comment by domoritz** [comment]
Awesome to hear that improvements are in the works.

I wanted to play with stdlib in observable and was hoping to have a simple import of the library. I saw https://observablehq.com/@kgryte/stdlib?collection=@kgryte/stdlib uses a specific import from `https://unpkg.com/@stdlib/stdlib@0.0.32/dist/stdlib-flat.min.js` but it would be nice to use the standard `require` or `import` syntax from Observable.

The ESM bundle doesn't seem to work on Observable yet, btw. 
<img width="641" alt="Screen Shot 2021-03-02 at 19 03 56" src="https://user-images.githubusercontent.com/589034/109693522-9c92fe80-7b3e-11eb-8c40-6f931f7520dd.png">

**Comment by kgryte** [comment]
@domoritz Here is an [example](https://observablehq.com/@rreusser/stdlib-erf-and-erfinv) of loading individual ESM modules into Observable.

**Comment by domoritz** [comment]
🙌 thanks for the link. `stdlib = require('@stdlib/dist-tree')` is perfect for experimenting and the esm imports for individual packages are perfect once you know what you need.

**Comment by kgryte** [comment]
Awesome. Let us know if we can be of any further help. :)

**Comment by kgryte** [comment]
**Update**: individual packages are now [consumable](https://www.npmjs.com/org/stdlib). While the individual packages do not expose UMD bundles atm, one can locally install and then bundle for use in web applications.

**Comment by kgryte** [comment]
Every standalone package currently contains [UMD bundles](https://github.com/stdlib-js/ndarray-fancy/tree/9da39d78da9dc14f3c07745def8b181b04ac211a), along with instructions as to how to use in, e.g., Observable.

@Planeshifter Is there anything more we can do here?

**Comment by kgryte** [comment]
Posting a final update here. I've updated an Observable notebook, which demonstrates how to perform [benchmarks](https://observablehq.com/@kgryte/stdlib-writing-benchmarks), to use standalone package UMD bundles.

I've further created a [test notebook](https://observablehq.com/d/81afcc9a4310b76c), which attempts to load the various UMD bundles across (almost) all standalone repositories. Note that this notebook takes several minutes to run. In short, all UMD bundles for those packages which are browser-compatible are able to be loaded into Observable via jsDelivr.

Accordingly, I will go ahead and close this issue. If further issues arise, we can revisit by either reopening this issue or opening a new issue.
