### ISSUE TITLE
How to push to stdlib fork?

### ISSUE THREAD

**Issue by saurabhraghuvanshii** [stdlib-js/stdlib#3892]
### Description

Encountered an error when :  when you push to forked repo it failed with some error pushing to github failed 
 And while running make lint it also give error like filed name should be in lowercase. And also Makefile.txt should be Makefile.

### Questions

No.

### Reproduction

```shell
- push to forked repo using git push origin develop
- make lint / npm run lint.
```

### Expected Results

```shell

```

### Actual Results

```shell

```

### Environments

Node.js, Chrome

### Checklist

- [x] Read and understood the [Code of Conduct](https://github.com/stdlib-js/stdlib/blob/develop/CODE_OF_CONDUCT.md).
- [x] Searched for existing issues and pull requests.

**Comment by gunjjoshi** [comment]
> And while running make lint it also give error like filed name should be in lowercase. And also Makefile.txt should be Makefile.

@saurabhraghuvanshii These are not "issues", but the project conventions that should be followed. You'll have to refactor your code accordingly, so that you're following the conventions.

**Comment by saurabhraghuvanshii** [comment]
@gunjjoshi ok but how i push repo to github to my forked repo

**Comment by saurabhraghuvanshii** [comment]
I used git push --force but it also failed

**Comment by gunjjoshi** [comment]
@saurabhraghuvanshii You can try going through the contributing guidelines here, for reference: https://github.com/stdlib-js/stdlib/blob/develop/CONTRIBUTING.md#step-0-github

**Comment by saurabhraghuvanshii** [comment]
@gunjjoshi sir read it and done every thing it show same error as previous .

Encountered an error when running README JavaScript examples.
