### ISSUE TITLE
"ReferenceError: __dirname is not defined" - Using the library client side is failing because of references to __dirname

### ISSUE THREAD

**Issue by chriszrc** [stdlib-js/stdlib#390]
## Checklist
-   [x] Read and understood the [Code of Conduct][code-of-conduct].
-   [x] Searched for existing issues and pull requests.

## Description
Using the stdlib dependency in a client side application (using `npm install @stdlib/stdlib`) results in the following error:

ReferenceError: __dirname is not defined     at Object../node_modules/@stdlib/stdlib/lib/node_modules/@stdlib/blas/ext/base/gapxsumpw/lib/index.js (index.js:54)

## Questions

No.

#### Reproduction

In order to reproduce this bug, do the following:

-   create a client side app
-   add the stdlib dependency
-   run it

#### Environments

> What environments are affected (e.g., `Node v0.4.x`, `Chrome`, `IE 11`)? If Node.js, include the `npm` version, operating system, and any other potentially relevant platform information.

The following environments are affected:

-  Node 12.16.1

[code-of-conduct]: https://github.com/stdlib-js/stdlib/blob/develop/CODE_OF_CONDUCT.md

**Comment by kgryte** [comment]
@chriszrc How are you trying to load `stdlib` in a client side application? Are you using a bundler, such as Webpack or browserify, or are you trying to load as an ES module?

**Comment by chriszrc** [comment]
Hi,

It's an angular app, so yes, written with es modules, but bundled with
webpack. Interestingly, changing the stdlib dependency to point directly at
github rather than npm ( `"@stdlib/stdlib":"github:stdlib-js/stdlib#develop",`) allows everything to work just fine

**Comment by kgryte** [comment]
@chriszrc There may be an issue with your webpack configuration.

@Planeshifter Perhaps you have some insight here, given your experience with using stdlib with webpack?

**Comment by kgryte** [comment]
@chriszrc Tracked it down. The latest version on GitHub has a bug fix. Will publish a new version tomorrow with the fix. Does that work for you?

**Comment by chriszrc** [comment]
@kgryte nice! yes, as I mentioned, pointing directly to github worked fine, but yes, having it up to date on npm is certainly better-

**Comment by kgryte** [comment]
@chriszrc A new version has been published. Let me know if you run into any issues. :)
