### ISSUE TITLE
Bad require

### ISSUE THREAD

**Issue by denis-migdal** [stdlib-js/stdlib#391]
## Description

When using mt19937/lib/factory.js, I had the following error : "isPositiveInteger is not a function".

Indeed, it is imported as :
`var isPositiveInteger = require( '@stdlib/assert/is-positive-integer' ).isPrimitive;`

While being exported as :
```
function isPositiveInteger( value ) {
	return ( isPrimitive( value ) || isObject( value ) );
}
// EXPORTS //

module.exports = isPositiveInteger;
```

When fixing it, I have the same error with isInteger, then with isNumber, then with randu.

Version I use is 0.0.93.

I previously used version 0.0.60 and didn't have this error.

## Related Issues
None

**Comment by denis-migdal** [comment]
Okay, I got this.

You have both a main.js and index.js file in the same directory. My webpack configuration fetched the main.js instead of the index.js. main.js had priority over index.js in my configuration.

Having both index and main files in the same directory seems (to me) to be a dangerous idea for a library.

**Comment by Planeshifter** [comment]
Glad to hear the problem was resolved!

Since each package comes with a `package.json` file with an appropriate [`main` entry](https://github.com/stdlib-js/stdlib/blob/eba25c1098acac67c87ea89967dc1ebb90925cbd/lib/node_modules/%40stdlib/assert/is-positive-integer/package.json#L16), you should not have to concern yourself with the internal structure of the package but be able to point Webpack directly to the package's folder and let the module resolution be done through `package.json` (provided [mainFields](https://webpack.js.org/configuration/resolve/#resolvemainfields) includes `main` in your Webpack configuration, which IIRC it does by default).

**Comment by denis-migdal** [comment]
Thanks for your answer. I checked my webpack configuration and stdlib's package.json.

stdlib package.json files have their main field written as : `"main": "./lib",`.

Maybe it should be better to explicitly point to the file : `"main": "./lib/index.js",` ?


(I am self taught in webpack/node, so I might be lacking some knowledge about best practices).

**Comment by kgryte** [comment]
@denis-migdal Was there a particular reason you had configured webpack to prefer `main.js` or `index.js`?

We generally assume throughout the project that users (and bundlers) will rely on the Node.js module resolution algorithm which assigns special status to `index.js` as the default file which is resolved when only a directory is specified (e.g., `./lib`; this is similar to the privileged status of `index.html` files in web servers).

**Comment by denis-migdal** [comment]
This is indeed the default behavior.

However, such behavior can be changed depending on the project. For example, in web servers, we might want to prefer e.g. index.php over index.html.

I tried to check, node does not seem to have an option to prefer e.g. main.js over index.js, so that's a behavior specific to Webpack. This is quite useful in some situations, but it shouldn't be used for dependencies with a package.json as it changes the expected default behavior.

I think I will open an issue in Webpack git repository and close this one as Webpack is at fault here.

**Comment by denis-migdal** [comment]
Issue for Webpack posted here: https://github.com/webpack/webpack/issues/13170

**Comment by kgryte** [comment]
Thanks, @denis-migdal!
