### ISSUE TITLE
[BUG]: Cannot find module `@stdlib/lapack` under pnpm

### ISSUE THREAD

**Issue by softcraft-development** [stdlib-js/stdlib#4131]
### Description

I have a brand new & largely empty package where I installed `@stdlib/stdlib` (^0.3.0). To get started I wrote the following test in `vitest`:

```
import * as s from "@stdlib/stdlib"
import { describe, expect, it } from "vitest"

describe("stdlib", () => {
  it("loads the library", () => {
    expect(s).toBeDefined()
  })
})
```

Running the test generates this error:
```
Error: Cannot find module '@stdlib/lapack'
Require stack:
- [root]/node_modules/.pnpm/@stdlib+stdlib@0.3.0/node_modules/@stdlib/stdlib/lib/main.js
- [root]/node_modules/.pnpm/@stdlib+stdlib@0.3.0/node_modules/@stdlib/stdlib/lib/index.js
 ❯ Object.<anonymous> ../../node_modules/.pnpm/@stdlib+stdlib@0.3.0/node_modules/@stdlib/stdlib/lib/main.js:190:32
```

Indeed, `lapack` is not installed at that location, nor is it in any other location in my project.

Note that I'm using `pnpm` as my package manager. I'm not certain whether this is a significant issue or not. The command I used to install stdlib was very standard: `pnpm add @stdlib/stdlib`.

### Related Issues

Related issues # , # , and # .

### Questions

No.

### Reproduction

```shell
- Create a new Node.js package
- `pnpm add @stdlib/stdlib`
- `import * as s from "@stdlib/stdlib"`
```

### Expected Results

```shell
Node should not throw the error when loading `@stdlib/stdlib`. I expect `lapack` should be included via the dependencies.
```

### Actual Results

```shell
Error: Cannot find module '@stdlib/lapack'
Require stack:
- [root]/node_modules/.pnpm/@stdlib+stdlib@0.3.0/node_modules/@stdlib/stdlib/lib/main.js
- [root]/node_modules/.pnpm/@stdlib+stdlib@0.3.0/node_modules/@stdlib/stdlib/lib/index.js
 ❯ Object.<anonymous> ../../node_modules/.pnpm/@stdlib+stdlib@0.3.0/node_modules/@stdlib/stdlib/lib/main.js:190:32
```

### Version

0.3.0

### Environments

Node.js

### Node.js / npm Version

20.16.0

### Checklist

- [x] Read and understood the [Code of Conduct](https://github.com/stdlib-js/stdlib/blob/develop/CODE_OF_CONDUCT.md).
- [x] Searched for existing issues and pull requests.

**Comment by softcraft-development** [comment]
Update: manually running `pnpm add @stdlib/lapack` allowed the test to execute successfully. 

I saw in the README that LAPACK is intended to be an optional dependency for performance. At first glance it looks like the pure JS fallback isn't working correctly -- at least under my pnpm-based setup. 

I'm happy to help diagnose this; just let me know what you need. The code that I'm running isn't publicly available but I could probably whip up a test jig if necessary.

**Comment by kgryte** [comment]
@softcraft-development Thanks for reporting this. We just published a patch fixing this issue. Let us know if you encounter any further issues!

**Comment by softcraft-development** [comment]
Just tested it and it works great now. Thanks for the fast turnaround!

**Comment by kgryte** [comment]
@softcraft-development Thanks for reporting back. I'll go ahead and close.
