### ISSUE TITLE
Implement double factorial

### ISSUE THREAD

**Issue by kgryte** [stdlib-js/stdlib#44]
[Double factorial](https://github.com/boostorg/math/blob/develop/include/boost/math/special_functions/factorials.hpp#L74). `@stdlib/math/base/special/double-factorial`.

**Comment by chrisdamba** [comment]
What name should the function have, `factorial2` or `doublefactorial` ?

**Comment by kgryte** [comment]
Let's follow Python and Mathematica and go with `factorial2`.

**Comment by kgryte** [comment]
@rreusser Did you ever make any headway on your implementation? Or stated otherwise, how close were you to finishing an implementation for `factorial2`?
