### ISSUE TITLE
`assert.isIteratorLike` is too restrictive

### ISSUE THREAD

**Issue by lightmare** [stdlib-js/stdlib#471]
### Description

Currently the function looks like this:
```js
function isIteratorLike( value ) {
	return (
		value !== null &&
		typeof value === 'object' && // too narrow
		isFunction( value.next ) &&
		value.next.length === 0 // too narrow
	);
}
```

[ES spec](https://tc39.es/ecma262/multipage/abstract-operations.html#sec-getiterator) requires that `Type(iterator)` is `Object`. Which includes functions.
```js
// Type(x) is Object
typeof x === "object" ? x !== null : typeof x === "function"
```

Then [ES spec](https://tc39.es/ecma262/multipage/control-abstraction-objects.html#sec-iterator-interface) puts no restriction on `next.length`. Iterators created by calling generator functions have `next.length === 1` because they accept an argument that becomes the result of evaluating `yield`.

### Related Issues

Related issues # , # , and # .

### Questions

No.

### Reproduction

```js
var isIteratorLike = require('@stdlib/assert/is-iterator-like')

function next(arg) { return { value: ++this.v, done: this.v > 10 }}
function itor() { return Object.assign(_=>{}, { v: 0, next }) }

console.log(isIteratorLike(itor()))
```

### Expected Results

```shell
true
```

That this should print `true` can be confirmed by checking that built-ins treat the function returned by `itor()` as valid iterator:
```js
Array.from({[Symbol.iterator]: itor})
```

### Actual Results

```shell
false
```

### Version

@stdlib/assert 0.0.12

### Environments

Node.js

### Node.js / npm Version

17.2.0

### Checklist

- [X] Read and understood the [Code of Conduct](https://github.com/stdlib-js/stdlib/blob/develop/CODE_OF_CONDUCT.md).
- [X] Searched for existing issues and pull requests.

**Comment by kgryte** [comment]
@lightmare Thanks for filing this issue.

I pushed https://github.com/stdlib-js/stdlib/commit/f7ee9af36ded6f62728bbf032e6adc33a89031d2 which relaxes the requirements to (1) allow `value` to be a `function` and (2) to no longer check that `next` is a nullary function.

I believe that should resolve this issue.

**Comment by kgryte** [comment]
With the most recent `@stdlib/assert` [release](https://github.com/stdlib-js/assert/releases/tag/v0.1.1), this should be [resolved](https://github.com/stdlib-js/assert/blob/c4083a3d8471bd73e6efaf49e3e774dff840d31d/is-iterator-like/lib/main.js).
