### ISSUE TITLE
Missing node-gyp on sub modules

### ISSUE THREAD

**Issue by chambo-e** [stdlib-js/stdlib#478]
### Description

Hello 👋 

When we try to install a sub package with yarn (not tested with npm) we have an error indicating that node-gyp is missing.

If I understand correctly it's in the dependencies of `@stdlib/stdlib` but not in the subpackages

A workaround might be to use `@stdlib/stdlib` to access subpackages but that is quite heavy to only use some functions

### Related Issues

Related issues # , # , and # .

### Reproduction

```shell
In a clean project (without node-gyp in PATH)

- yarn add @stdlib/math-base-special-ldexp
```

### Actual Results

```shell
Usage Error: Couldn't find a script name "node-gyp" in the top-level (used by @stdlib/math-base-special-abs@npm:0.0.5). This typically happens because some package depends on "node-gyp" to build itself, but didn't list it in their dependencies. To fix that, please run "yarn add node-gyp" into your top-level workspace. You also can open an issue on the repository of the specified package to suggest them to use an optional peer dependency.
```

### Environments

Node.js

### Node.js / npm Version

17

### Platform

MacOS/Linux

### Checklist

- [X] Read and understood the [Code of Conduct](https://github.com/stdlib-js/stdlib/blob/develop/CODE_OF_CONDUCT.md).
- [X] Searched for existing issues and pull requests.

**Comment by kgryte** [comment]
@chambo-e Thanks for reporting this issue. Our best guess is that yarn is not respecting the `gypfile: false` field in the `package.json` and is thus attempting to build the native add-ons, even though this is not intended.

We've pushed a [fix](https://github.com/stdlib-js/stdlib/commit/ca7bb5dfcaa1cb5ea2b5a7bcc00863cc2e723c1c) that should be included in the next release. Hopefully, this will resolve the issue.

**Comment by chambo-e** [comment]
@kgryte Thanks a lot, I'll try as soon as the new release is published :)

**Comment by kgryte** [comment]
New versions of sub-packages have now been published. This issue should now be resolved.

**Comment by chambo-e** [comment]
@kgryte new versions works great, thanks !

**Comment by kgryte** [comment]
@chambo-e Awesome! Thanks for reporting back! 😅
