### ISSUE TITLE
Current stdlib version triggers a bug in npm 6

### ISSUE THREAD

**Issue by mmomtchev** [stdlib-js/stdlib#489]
### Description

Encountered an error when trying to install stdlib with npm 6

```
nvm use 12
npm i @stdlib/ndarray
```

(or `npm i @stdlib/stdlib`)

### Related Issues

https://github.com/npm/cli/issues/1600

### Questions

No.

### Reproduction

```shell
nvm use 12
npm i @stdlib/ndarray
```

### Actual Results

```shell
Installation hangs indefinitely because of an infinite loop in `npm`
```

### Version

0.0.13

### Environments

Node.js

### Node.js / npm Version

npm 6.14.15

### Platform

All

### Checklist

- [X] Read and understood the [Code of Conduct](https://github.com/stdlib-js/stdlib/blob/develop/CODE_OF_CONDUCT.md).
- [X] Searched for existing issues and pull requests.

**Comment by kgryte** [comment]
As npm v6 is several versions behind and no longer maintained, will go ahead and close this issue.
