### ISSUE TITLE
[RFC]: logcdf fuction for Normal distribution

### ISSUE THREAD

**Issue by d2phap** [stdlib-js/stdlib#499]
### Description

I'm looking for `logcdf(x, mu, sigma)` fuction for Normal distribution. I could find the `cdf()` but `logcdf`!

scipy already implemented this, but I need to use JavaScript. It would be nice to have this function implemented in stdlib.
Thank you!

https://docs.scipy.org/doc/scipy/reference/generated/scipy.stats.norm.html

<img width="1035" alt="image" src="https://user-images.githubusercontent.com/3154213/179680915-54493019-58d8-4ec9-9e67-29805f282153.png">

### Related Issues

Related issues # , # , and # .

### Questions

No.

### Other

No.

### Checklist

- [X] I have read and understood the [Code of Conduct](https://github.com/stdlib-js/stdlib/blob/develop/CODE_OF_CONDUCT.md).
- [X] Searched for existing issues and pull requests.
- [X] The issue name begins with `RFC:`.

**Comment by kgryte** [comment]
@d2phap Support for adding the normal distribution `logcdf` has been added. https://github.com/stdlib-js/stdlib/commit/d2004aa90966e9a77b23b722372690570cf04aa0

The associated standalone [package](https://github.com/stdlib-js/stats-base-dists-normal-logcdf) has not yet been published to npm; however, you can install directly from [GitHub](https://github.com/stdlib-js/stats-base-dists-normal-logcdf).

We'll circle back when this package is published. We don't yet have an estimated timeline for publishing.

**Comment by d2phap** [comment]
Thank you so much!

**Comment by Planeshifter** [comment]
Version `0.0.1` of the standalone [package](https://github.com/stdlib-js/stats-base-dists-normal-logcdf) has now been published  to `npm`:  

https://www.npmjs.com/package/@stdlib/stats-base-dists-normal-logcdf

Am closing this issue, but please let us know if you encounter any issues or have additional comments!
