### ISSUE TITLE
[Bug]: lintr configuration needs to be updated due to breaking changes

### ISSUE THREAD

**Issue by kgryte** [stdlib-js/stdlib#500]
### Description

Encountered an error when attempting to lint R files after installing the latest `lintr` package (`3.x`).

The `lintr` configuration in https://github.com/stdlib-js/stdlib/blob/232d92dcd2f07187ab1973d88e25cf5354a97633/tools/lint/r/linter.R#L42 needs to be updated to accommodate breaking changes, such as deprecated rules, etc.

Should also consider pinning package versions in https://github.com/stdlib-js/stdlib/blob/232d92dcd2f07187ab1973d88e25cf5354a97633/etc/r/requirements.txt.

cc @steff456 

### Related Issues

(None)

### Questions

No.

### Reproduction

```shell
- Install R packages as specified in `/etc/r`. These packages are unversioned. The latest version of `lintr` should be installed.
- Attempt to lint an R file.
```

### Expected Results

```shell
The command should work.
```

### Actual Results

```shell
The command does not work, due to broken configuation.
```

### Environments

Node.js

### Checklist

- [X] Read and understood the [Code of Conduct](https://github.com/stdlib-js/stdlib/blob/develop/CODE_OF_CONDUCT.md).
- [X] Searched for existing issues and pull requests.

**Comment by kgryte** [comment]
@Planeshifter Did you already resolve this? IIRC, you updated the R linter and our various R files a while back.

**Comment by Planeshifter** [comment]
Yes, I believe we can close this out.
