### ISSUE TITLE
[RFC]: add support for testing whether a value equals the current year

### ISSUE THREAD

**Issue by kgryte** [stdlib-js/stdlib#517]
### Description

This RFC proposes adding support for asserting whether a provided integer value equals the current year.

The implementation can use the package <https://github.com/stdlib-js/stdlib/tree/develop/lib/node_modules/%40stdlib/time/current-year> to dynamically resolve the current year (local time) and then perform a comparison with a provided input value.

For example,

```javascript
var currentYear = require( '@stdlib/time/current-year' );

function isCurrentYear( value ) {
    return ( value === currentYear() );
}
```

Package name: `@stdlib/assert/is-current-year`.
Alias: `isCurrentYear`.

### Related Issues

No.

### Questions

No.

### Other

No.

### Checklist

- [X] I have read and understood the [Code of Conduct](https://github.com/stdlib-js/stdlib/blob/develop/CODE_OF_CONDUCT.md).
- [X] Searched for existing issues and pull requests.
- [X] The issue name begins with `RFC:`.

**Comment by Planeshifter** [comment]
@kgryte Hmm, should we change the implementation to first check whether the supplied value is a `Date` object and if so, extract the current year from it? Seems one may want this package to both accept numbers representing the years and also `Date` objects.

**Comment by kgryte** [comment]
Yeah, I think you are right. Checking for a `Date` object to support that use case makes sense to me. Obv, a user could also do

```javascript
var d = new Date();

var bool = isCurrentYear( d.getFullYear() );
// returns <boolean>
```

However, an advantage to us handling this is that we can the use of the correct API (i.e., `d.getFullYear()`), which might be a source of user errors otherwise.

In short, I'm in favor of internally branching based on value type.

**Comment by Planeshifter** [comment]
Implementation finished and pushed.
