### ISSUE TITLE
[RFC]: Add Jacobi elliptic functions

### ISSUE THREAD

**Issue by rreusser** [stdlib-js/stdlib#632]
### Description

This RFC proposes to add jacobi elliptic functions under the math.special namespace. I've come up with a suitably licensed implementation [here](https://observablehq.com/@rreusser/jacobi-elliptic-functions) and propose to move it over with variations:

`ellipj()`: returns three values: sn, cn dn
`ellipj.am`: computes am (the [jacobi amplitude](https://en.wikipedia.org/wiki/Jacobi_elliptic_functions#Definition_as_inverses_of_elliptic_integrals)), from which other functions are computed
`ellipj.sn`: computes sn alone
`ellipj.cn`: computes cn alone
`ellipj.dn`: computes dn alone

Packages typically return everything together since 95% of the work is in computing the [jacobi amplitude](https://en.wikipedia.org/wiki/Jacobi_elliptic_functions#Definition_as_inverses_of_elliptic_integrals), and only the final output differs. ~~I'm not sure if an `assign` interface à la sincos is useful here, though I'm not opposed to adding it.~~ I think an assign interface _does_ make sense, as I believe the primary purpose is to avoid memory allocation when looping heavily.

### Questions

A small note on implementation is that some implementations include a m-near-unity approximation which I don't like. The Jacobi elliptic functions are periodic with period 4 * K where k is the complete elliptic integral of the first kind (see: [ellipk](https://github.com/stdlib-js/stdlib/tree/develop/lib/node_modules/%40stdlib/math/base/special/ellipk)). Depending on the precise tolerance, for m = 0.999999 the functions look like:

<img width="660" alt="Screen Shot 2022-11-25 at 8 06 17 AM" src="https://user-images.githubusercontent.com/572717/204024489-648e53ac-9d1e-4d72-91cf-0109205b40b2.png">

With the approximation from Abramowitz & Stegun 16.15.1 for m = 0.9999999, we have:

<img width="658" alt="Screen Shot 2022-11-25 at 8 06 24 AM" src="https://user-images.githubusercontent.com/572717/204024616-d74033cb-d343-4c09-a248-2e0638ed4339.png">

It's a fine approximation for the first quarter-period, but completely wrong otherwise. From [scipy docs](https://docs.scipy.org/doc/scipy/reference/generated/scipy.special.ellipj.html):

> Computation is by means of the arithmetic-geometric mean algorithm, except when m is within 1e-9 of 0 or 1. In the latter case with m close to 1, the approximation applies only for phi < pi/2.

My vote, in order, is:
1. Omit this approximation altogether, as long as there's not slow convergence or loss of accuracy
2. If the approximation can't be avoided, then waste cycles computing K over and over in order to sort out the periodicity
3. Least desirable option would be to permit the function to return incorrect values with a footnote about this behavior

### Other

No.

### Checklist

- [X] I have read and understood the [Code of Conduct](https://github.com/stdlib-js/stdlib/blob/develop/CODE_OF_CONDUCT.md).
- [X] Searched for existing issues and pull requests.
- [X] The issue name begins with `RFC:`.

**Comment by kgryte** [comment]
@rreusser No opinion regarding 1-3. Fine with (1) if you think that preferable. We should just be sure to document how the behavior diverges from, e.g., SciPy et al in a "Notes" section in the README, or perhaps just in the JSDoc comment of the implementation file. Recording this knowledge will probably be useful for posterity.
