### ISSUE TITLE
[RFC]: Add C implementation for `@stdlib/math/base/special/exp`

### ISSUE THREAD

**Issue by kgryte** [stdlib-js/stdlib#640]
### Description

This RFC proposes adding a C implementation for [`@stdlib/math/base/special/exp`](https://github.com/stdlib-js/stdlib/tree/b43a75923e47775446d3b6d7219ee42e07f7ce63/lib/node_modules/%40stdlib/math/base/special/exp).

```c
double stdlib_base_exp( const double x );
```

### Related Issues

None.

### Questions

No.

### Other

No.

### Checklist

- [X] I have read and understood the [Code of Conduct](https://github.com/stdlib-js/stdlib/blob/develop/CODE_OF_CONDUCT.md).
- [X] Searched for existing issues and pull requests.
- [X] The issue name begins with `RFC:`.

**Comment by Pranavchiku** [comment]
I won't be able to proceed on this one until #652 gets merged, as logic required the use of `ldexp`.
