### ISSUE TITLE
RFC: add support for asserting if an object contains a nested key path

### ISSUE THREAD

**Issue by kgryte** [stdlib-js/stdlib#65]
## Checklist

> Please ensure the following tasks are completed before filing an issue.

* [x] Read and understood the [Code of Conduct][code-of-conduct].
* [x] Searched for existing issues and pull requests.
* [x] If this is a general question, searched the [FAQ][faq] for an existing answer.
* [x] If this is a feature request, the issue name begins with `RFC: `.

## Description

> Description of the issue (or feature request).

Check whether an object contains a nested key path.

Package: `@stdlib/assert/deep-has-own-property`.
Alias: `deepHasOwn`

Example:

```javascript
var obj = { 'a': { 'b': { 'c': 'd' } } };

var bool = deepHasOwn( obj, 'a.b.c' );
// returns true

bool = deepHasOwn( obj, 'a.b.c.d.e' );
// returns false
```

Notes:

- Should provide a factory method, similar to `@stdlib/utils/deep-get`.
- Should return only `true` or `false` (i.e., be a predicate function).
- Should check for only **own** properties.

## Related Issues

> Does this issue (or feature request) have any related issues?

None.

## Questions

> Any questions for reviewers?

No.

## Other

> Any other information relevant to this issue (or feature request)? This may include screenshots, references, stack traces, sample output, and/or implementation notes.

No.

[code-of-conduct]: https://github.com/stdlib-js/stdlib/blob/develop/CODE_OF_CONDUCT.md
[faq]: https://github.com/stdlib-js/stdlib/blob/develop/FAQ.md

**Comment by ognjenjevremovic** [comment]
Hey @kgryte, is this still open?
If so, how should it differentiate from the _deepGet_ method?

I suppose this should return a value if the path exists, else _undefined_ should be returned instead?

**Comment by kgryte** [comment]
@ognjenjevremovic The issue still is open. The difference from `deepGet` is that `deepHas` should be a predicate function, thus returning only `true` or `false`. For `deepGet`, a path could exist and yet still return `undefined`.

Feel free to submit a PR. Made edits to the original issue.

**Comment by ognjenjevremovic** [comment]
Thank you so much for the input and a fast reply @kgryte.
I'm going to take a deeper look at this one.

**Comment by kgryte** [comment]
@ognjenjevremovic Awesome. Thanks!

**Comment by ognjenjevremovic** [comment]
Just a few more question @kgryte; should this one provide a support for deep paths being specified as either a delimited `string` or a key `array`, similar to `@stdlib/utils/deep-get`?
And should the `factory` property be exposed for creating a reusable `deepHasOwn` function by using the same set of provided separator `options`?

**Comment by kgryte** [comment]
@ognjenjevremovic Yes, sounds reasonable. You can basically recycle the `deep-get` implementation but modify the return value logic. Accordingly, providing support for paths being specified by either an array or delimited string should follow suit.

**Comment by ognjenjevremovic** [comment]
Hey @kgryte, sorry for my late response.
I am having **huge** troubles making the tests run properly, the last couple of days...

Can you please assist me in debugging?
Since I've rebased, I keep getting the following errors :
`
/home/ognjen/repos/stdlib/tools/make/lib/test/javascript.mk:44: recipe for target 'test-javascript-local' failed
make: *** [test-javascript-local] Error 1
`

That is however, when I initialized  the hooks, for linting/test errors, with
`
make init
`

I've written the tests and they seem to be working fine for the `@stdlib/assert/deep-has-own-property`, when setting the TESTS_FILTER flag, prior to running them.
I thought by making a fresh clone of the repo will perhaps help solve the problem, however the error is still present when running

`
make test
`

with no changes in the source code whatsoever.

**Comment by kgryte** [comment]
Can you run the `make test` command using the `VERBOSE` flag?

```bash
$ VERBOSE=1 make test
```
The error log shown above is not much to work with. :)

**Comment by kgryte** [comment]
It is a bit odd that `make test` does not work, while `make TESTS_FILTER=.*/foo/bar/.* test` would work, as the make recipe is the same. What differs is the computed file list.

What is your OS and what version of Node are you running?

Sorry that you are having issues. :(

**Comment by ognjenjevremovic** [comment]
Sure thing.
Doing it just now, though tests can take around ~15-20mins.

Yeah, I tried to debug it for the last 3 days, as it's actually permitting me to make a few final commits (most of which has to do with linting errors and a few failing test scenarios) and do a PR, as of git hooks.

The error, as far as I could tell, comes from the `@stdlib/math/` dir tests.
As running `make TESTS_FILTER=.*/math/.* test` causes the problem each time (though those could not be the only ones, as I ran most of them separately, directory by directory, until I saw that those are the ones that are causing the errors).

I'm running Ubuntu 17.04 and Node v6.11.2.

**Comment by kgryte** [comment]
You are encountering this error on `push`, correct? I do not believe that the git hooks run tests on `commit`. Instead, the `commit` hook should just be running lint.

You said that you pulled down the latest changes from the `upstream` repo (i.e., the main project repository)?

When running the tests, you should see the test log. What is the failed test? Or does the command fail silently?

**Comment by ognjenjevremovic** [comment]
Yeah, that's correct; I can not `push` the latest changes (the commits are stored locally :)).

Yes, everything's up to date with the latest changes to the main repo `develop` branch.

Sadly, it doesn't say much about the error; the only output I get is the one I've pasted straight from the terminal window.
`
/home/ognjen/repos/stdlib/tools/make/lib/test/javascript.mk:44: recipe for target 'test-javascript-local' failed make: *** [test-javascript-local] Error 1
`

I'm not quite sure if it has anything to do with dependencies.
Though, `make` runs with no problem.

I'm waiting for the last round of tests, now with the `VERBOSE` flag, so I can give you more info.

However, running tests with `make TESTS_FILTER=.*/some/path/*. test` runs with no problem.
Depending on the `path` that is - as I already mention previously, the `make TESTS_FILTER=.*/math/*. test` produces the exact same output/error as running the `make test`.

**Comment by ognjenjevremovic** [comment]
Last few tests and an error output :

`    ✔ alpha: 2.6548627613287, beta: 6.954499271853653, y: 0.36071266603830693, expected: 0.36071266603830693`
`    ✔ within tolerance. alpha: 2.164144120216137. beta: 7.029800248379493. y: 0.3113947603804268. E: 0.31139476038042674. Δ: 5.551115123125783e-17. tol: 2.765741061775866e-16.`
`    ✔ alpha: 0.975648844590119, beta: 2.047832948643205, y: 6.131133752538203, expected: 6.131133752538203`
`    ✔ alpha: 9.425459061679401, beta: 4.480806427513445, y: 2.0117557048152683, expected: 2.0117557048152683`
`    ✔ alpha: 6.718380617444311, beta: 3.67699328910776, y: 2.291798292638805, expected: 2.291798292638805`
`    ✔ within tolerance. alpha: 9.680688166086341. beta: 9.568864368066365. y: 0.5638201535279117. E: 0.5638201535279116. Δ: 1.1102230246251565e-16. tol: 5.007728929555025e-16.`
`    ✔ alpha: 4.6001104596645, beta: 9.453378451224095, y: 0.33576895052121924, expected: 0.33576895052121924`
`    ✔ alpha: 1.5255040667969844, beta: 7.052887294798185, y: 0.2498980149982572, expected: 0.2498980149982572`

`/home/ognjen/repositories/stdlib/tools/make/lib/test/javascript.mk:44: recipe for target 'test-javascript-local' failed`
`make: *** [test-javascript-local] Error 1`

![imageedit_2_2779294241](https://user-images.githubusercontent.com/14274816/29848510-6b6bc6f2-8d21-11e7-8508-a962f713a4e5.png)

**Comment by kgryte** [comment]
This makes it seem like it just died without actually having failed. I think you have reproduced something we see randomly on Travis CI, but have never seen anywhere else in the "wild"!!!!

This is quite interesting. But alas, I have no way of debugging. Would actually need to sit down at your machine. :(

Are you running in a virtual machine, by chance?

As long as the tests for your particular contribution pass, you can bypass the git hook as follows:

```bash
$ git push origin <remote> --no-verify
```

**Comment by kgryte** [comment]
I was able to reproduce locally! So, it is possible that, because we print so much test output, that the terminal session runs out of memory and/or is killed by the kernel. This would be especially likely in the `math` namespace as some of the tests generate thousands of lines of test results.

Sorry about this. We have an item in our todo list to support only running tests for changed files, rather than for the entire codebase on `push`. For now, feel free to bypass the lint hook for `git push` using `--no-verify`.

**Comment by ognjenjevremovic** [comment]
Thanks a lot @kgryte !
To be honest, I was fighting this *waaay* too long.
This is my 3rd sleepless night, trying to figure out what's happening.

I tried to avoid pushing with `--no-verify`, as it felt like ~*cheating*~ not right thing to do.

**Comment by kgryte** [comment]
Yeah, sorry about that. :( If you run into an issue like this again, definitely reach out sooner. We are here to help. :)

And yeah, to avoid putting anyone else through what you have been through, I am going to disable running tests in the `push` hook until we figure out a better solution.

**Comment by kgryte** [comment]
Disabled running tests in the following commit: https://github.com/stdlib-js/stdlib/commit/fcbabafe97c9f80506736312446be4e45fefb3aa. 

If you merge/rebase the latest `develop` changes and run `make init`, you should no longer have to run tests on push. :)

**Comment by ognjenjevremovic** [comment]
Thanks so much for the help @kgryte.
I finally made the PR :).

I'll be offline for the next 14-16 hours or so (sleep + working hours).
I'll be sure to check the progress on the build/PR once back.

**Comment by kgryte** [comment]
Sounds good. :)
