### ISSUE TITLE
[RFC]: Add C implementation for `@stdlib/math/base/special/round`

### ISSUE THREAD

**Issue by Pranavchiku** [stdlib-js/stdlib#735]
### Description

This RFC proposes adding C implementation for [`@stdlib/math/base/special/round`](https://github.com/stdlib-js/stdlib/tree/develop/lib/node_modules/%40stdlib/math/base/special/round).

```c
double stdlib_base_round( const double x );
```

### Related Issues

None.

### Questions

No.

### Other

No.

### Checklist

- [X] I have read and understood the [Code of Conduct](https://github.com/stdlib-js/stdlib/blob/develop/CODE_OF_CONDUCT.md).
- [X] Searched for existing issues and pull requests.
- [X] The issue name begins with `RFC:`.

**Comment by anirudhprabhakaran3** [comment]
Hello! I was interested in https://github.com/stdlib-js/stdlib/issues/1756, and it mentions that that issue is blocked till this gets solved. Can I look into this?

Or is there already a PR for fixing this?

**Comment by Pranavchiku** [comment]
Yup, https://github.com/stdlib-js/stdlib/pull/1450

**Comment by anirudhprabhakaran3** [comment]
Aah yes I see it now. Was able to see it on my laptop, but not on GitHub mobile. Thanks!

**Comment by vivek-anand-singh** [comment]
@kgryte @Pranavchiku I was interested in solving the issue #1756 but this issue is blocking . Can I resolve this issue ?

**Comment by kgryte** [comment]
@gunjjoshi This is already done, correct?

**Comment by gunjjoshi** [comment]
@kgryte Yes, this was completed by #1450.
