### ISSUE TITLE
Update base math implementations to use package constants

### ISSUE THREAD

**Issue by kgryte** [stdlib-js/stdlib#74]
## Checklist

> Please ensure the following tasks are completed before filing an issue.

* [x] Read and understood the [Code of Conduct][code-of-conduct].
* [x] Searched for existing issues and pull requests.
* [x] If this is a general question, searched the [FAQ][faq] for an existing answer.
* [x] If this is a feature request, the issue name begins with `RFC: `.

## Description

> Description of the issue.

Some of the base implementations in the `stdlib` math use constants internally which are available as packages; e.g., `@stdlib/math/constants/float64-half-pi`, etc.

To ensure consistency across the codebase, would be of benefit to replace internal constants with package constants, where available.

For constants not having package constants, these values can stay as is.

## Related Issues

> Does this issue have any related issues?

No.

## Questions

> Any questions for reviewers?

No.

[code-of-conduct]: https://github.com/stdlib-js/stdlib/blob/master/CODE_OF_CONDUCT.md
[faq]: https://github.com/stdlib-js/stdlib/blob/master/FAQ.md

**Comment by chrisdamba** [comment]
Thanks for creating this, I can start with the `PIO2` constant clean-up. Can this be a WIP task as we look for other internal constants apart from the known `PIO2` ones?

**Comment by kgryte** [comment]
Sounds good. I will update the project [board](https://github.com/stdlib-js/stdlib/projects/5).
