### ISSUE TITLE
[RFC]: Add C implementation for `@stdlib/math/base/special/cospi`

### ISSUE THREAD

**Issue by Pranavchiku** [stdlib-js/stdlib#746]
### Description

This RFC proposes adding C implementation for [`@stdlib/math/base/special/cospi`](https://github.com/stdlib-js/stdlib/blob/develop/lib/node_modules/%40stdlib/math/base/special/cospi).

```c
double stdlib_base_cospi( const double x );
```

### Related Issues

None.

### Questions

No.

### Other

No.

### Checklist

- [X] I have read and understood the [Code of Conduct](https://github.com/stdlib-js/stdlib/blob/develop/CODE_OF_CONDUCT.md).
- [X] Searched for existing issues and pull requests.
- [X] The issue name begins with `RFC:`.

**Comment by Pranavchiku** [comment]
This depends on [`@stdlib/math/base/special/sin`](https://github.com/stdlib-js/stdlib/tree/develop/lib/node_modules/%40stdlib/math/base/special/sin) which depends on [`@stdlib/math/base/special/rempio2`](https://github.com/stdlib-js/stdlib/tree/develop/lib/node_modules/%40stdlib/math/base/special/rempio2).

**Comment by ashrafX22** [comment]
Hello,can i work on this issue? @kgryte @Pranavchiku

**Comment by Pranavchiku** [comment]
Umm no, you'll need to first implement [`@stdlib/math/base/special/rempio2`](https://github.com/stdlib-js/stdlib/tree/develop/lib/node_modules/%40stdlib/math/base/special/rempio2), that might be difficult at this moment.

**Comment by kgryte** [comment]
This has now been implemented. Closing...
