### ISSUE TITLE
[RFC]: Add C implementation for `@stdlib/math/base/special/coth`

### ISSUE THREAD

**Issue by Pranavchiku** [stdlib-js/stdlib#754]
### Description

This RFC proposes adding C implementation for [`@stdlib/math/base/special/coth`](https://github.com/stdlib-js/stdlib/tree/develop/lib/node_modules/%40stdlib/math/base/special/coth).

```c
double stdlib_base_coth( const double x );
```

### Related Issues

#752 .

### Questions

No.

### Other

No.

### Checklist

- [X] I have read and understood the [Code of Conduct](https://github.com/stdlib-js/stdlib/blob/develop/CODE_OF_CONDUCT.md).
- [X] Searched for existing issues and pull requests.
- [X] The issue name begins with `RFC:`.

**Comment by lovelindhoni** [comment]
Hey  @Pranavchiku @kgryte I would like to work on this issue :)

**Comment by Pranavchiku** [comment]
Thanks for your interest, assigned it to you.
