### ISSUE TITLE
RFC: add constant pi divided by four

### ISSUE THREAD

**Issue by kgryte** [stdlib-js/stdlib#76]
## Checklist

> Please ensure the following tasks are completed before filing an issue.

* [x] Read and understood the [Code of Conduct][code-of-conduct].
* [x] Searched for existing issues and pull requests.
* [x] If this is a general question, searched the [FAQ][faq] for an existing answer.
* [x] If this is a feature request, the issue name begins with `RFC: `.

## Description

> Description of the issue (or feature request).

Along lines similar to `@stdlib/math/constants/float64-half-pi`, this RFC proposes the addition of a new constant package to `@stdlib/math/constants`; namely, `pi/4`. The constant `pi/4` finds common occurrence in various math implementations; e.g., `acos`, `asin`, `atan`.

Package name possibilities include:

```
@stdlib/math/constants/float64-pi-over-four
@stdlib/math/constants/float64-quarter-pi
@stdlib/math/constants/float64-pi-div-four
@stdlib/math/constants/float64-pio4
@stdlib/math/constants/float64-fourth-pi
```

The last name possibility is consistent with `float64-half-pi`, but is a bit more awkward/less commonly said. Individuals may be more likely to say "pi over four" than "fourth pi". But then again, individuals may be more likely to say "pi over two" rather than "half pi". In terms of conventions, a separate convention for similar type constants could be imposed where the divisor is greater than `2`; i.e., keep `*-half-pi` type names, but then also have `*-pi-over-three`, `*-pi-over-four`, etc.

FWIW, Boost follows the convention `*-fourth-pi`.

## Related Issues

> Does this issue (or feature request) have any related issues?

Acceptance of this proposal would impact PR #75.

## Questions

> Any questions for reviewers?

* According to what naming convention should the proposed package follow?

[code-of-conduct]: https://github.com/stdlib-js/stdlib/blob/master/CODE_OF_CONDUCT.md
[faq]: https://github.com/stdlib-js/stdlib/blob/master/FAQ.md

**Comment by Planeshifter** [comment]
Think we should rule out `@stdlib/math/constants/float64-quarter-pi`. I would be fine with `@stdlib/math/constants/float64-fourth-pi`; if we believe we might have many constants with denominators >4, might be better to go with `pi-over-four`, although I am not sure whether that's the case. Your thoughts, @chrisdamba?

**Comment by chrisdamba** [comment]
I'm all for self-descriptive nomenclature, thus `pi-over-four` sounds good, although if we are to follow the Boost convention then I would say `fourth-pi`.

**Comment by kgryte** [comment]
At this point, since we already have an established convention (e.g., `half-pi`), probably best to follow that convention: `fourth-pi`. If we find the need to revisit later, we can do so at that time.

@chrisdamba You willing to submit a PR adding this constant? Can follow the template provided by `half-pi`.

**Comment by chrisdamba** [comment]
Awesome, let me revise and submit the PR.
