### ISSUE TITLE
[RFC]: Add C implementation for `@stdlib/math/base/special/ellipe`

### ISSUE THREAD

**Issue by Pranavchiku** [stdlib-js/stdlib#772]
### Description

This RFC proposes adding C implementation for [`@stdlib/math/base/special/ellipe`](https://github.com/stdlib-js/stdlib/blob/develop/lib/node_modules/%40stdlib/math/base/special/ellipe).

```c
double stdlib_base_ellipe( const double m );
```

### Related Issues

#766.

### Questions

No.

### Other

No.

### Checklist

- [X] I have read and understood the [Code of Conduct](https://github.com/stdlib-js/stdlib/blob/develop/CODE_OF_CONDUCT.md).
- [X] Searched for existing issues and pull requests.
- [X] The issue name begins with `RFC:`.

**Comment by gunjjoshi** [comment]
Hey, can I get assigned for this issue ? @Pranavchiku

**Comment by kgryte** [comment]
@gunjjoshi Sounds good. Feel free to submit a PR adding the implementation.

**Comment by gunjjoshi** [comment]
Hey @kgryte , upon trying to commit the changes, I get a console message saying that `cppcheck` is not installed. Even though after installing it using `brew install cppcheck`, it says the same thing. Do you have any ideas regarding this ?

<img width="1286" alt="Screenshot 2024-03-02 at 01 40 23" src="https://github.com/stdlib-js/stdlib/assets/67432819/78ea14a2-023f-4363-94e0-273a44e4365b">

**Comment by gunjjoshi** [comment]
Also, after installing it, all the files in `/lib` such as `poly_p1.js`, `poly_p2.js`, `poly_p3.js`.... change automatically.
Thus resulting in lint errors arising due to different expected values.

**Comment by kgryte** [comment]
Run [`make install-deps-cppcheck`](https://github.com/stdlib-js/stdlib/blob/615bcf165b0a9a9aad5f6591024e2dd1655c8914/tools/make/lib/install/cppcheck.mk#L151)

**Comment by kgryte** [comment]
Also, not sure why the files in `/lib` would change automatically. `cppcheck` is only for linting. It is not a runtime C or JS dep.

**Comment by gunjjoshi** [comment]
> Also, not sure why the files in `/lib` would change automatically. `cppcheck` is only for linting. It is not a runtime C or JS dep.

Thanks, I'll check if something is wrong on my side once again.
