### ISSUE TITLE
[RFC]: Add C implementation for `@stdlib/math/base/special/acovercos`

### ISSUE THREAD

**Issue by Pranavchiku** [stdlib-js/stdlib#775]
### Description

This RFC proposes adding C implementation for [`@stdlib/math/base/special/acovercos`](https://github.com/stdlib-js/stdlib/blob/develop/lib/node_modules/%40stdlib/math/base/special/acovercos).

```c
#include "stdlib/math/base/special/asin.h"

double stdlib_base_acovercos( const double x ) {
    return stdlib_base_asin( 1.0 + x );
}
```
Package: `@stdlib/math/base/special/acovercos`

### Related Issues

None.

### Questions

No.

### Other

Reference packages:
- [`@stdlib/math/base/special/acosh`](https://github.com/stdlib-js/stdlib/blob/develop/lib/node_modules/%40stdlib/math/base/special/acosh)

### Checklist

- [X] I have read and understood the [Code of Conduct](https://github.com/stdlib-js/stdlib/blob/develop/CODE_OF_CONDUCT.md).
- [X] Searched for existing issues and pull requests.
- [X] The issue name begins with `RFC:`.

**Comment by Pratik772846** [comment]
@kgryte @Pranavchiku I would like to work on this issue.

**Comment by Pranavchiku** [comment]
Thanks @Pratik772846 for your interest, but I'll wait till your PR #1405 gets merged.

**Comment by Pratik772846** [comment]
@Pranavchiku Can you please assign this issue to me now.

**Comment by Pranavchiku** [comment]
Awesome, go ahead :)

**Comment by adarshpalaskar1** [comment]
Hello, can I work on this issue?

**Comment by Pranavchiku** [comment]
I will keep door open for both, yes @adarshpalaskar1 you may proceed on it. Thanks for your interest!
