### ISSUE TITLE
[RFC]: Add C implementation for `@stdlib/math/base/special/acoversin`

### ISSUE THREAD

**Issue by Pranavchiku** [stdlib-js/stdlib#776]
### Description

This RFC proposes adding C implementation for [`@stdlib/math/base/special/acoversin`](https://github.com/stdlib-js/stdlib/blob/develop/lib/node_modules/%40stdlib/math/base/special/acoversin).

```c
#include "stdlib/math/base/special/asin.h"

double stdlib_base_acoversin( const double x ) { 
    return stdlib_base_asin( 1.0 - x );
}
```

### Related Issues

None.

### Questions

No.

### Other

Reference package:

- [`@stdlib/math/base/special/acosh`](https://github.com/stdlib-js/stdlib/blob/develop/lib/node_modules/%40stdlib/math/base/special/acosh)

### Checklist

- [X] I have read and understood the [Code of Conduct](https://github.com/stdlib-js/stdlib/blob/develop/CODE_OF_CONDUCT.md).
- [X] Searched for existing issues and pull requests.
- [X] The issue name begins with `RFC:`.

**Comment by PraneGIT** [comment]
hey @kgryte @Pranavchiku I would like to work on this.

**Comment by Pranavchiku** [comment]
Thanks for your interest, go ahead!

**Comment by aman-095** [comment]
Hey @kgryte @Pranavchiku I would like to work on this.

**Comment by Pranavchiku** [comment]
Go ahead once you address review at #1419.

**Comment by Pranavchiku** [comment]
Feel free to open up a PR for this, thank you for your contributions!
