### ISSUE TITLE
Refactor and update existing base BLAS packages according to current project conventions

### ISSUE THREAD

**Issue by kgryte** [stdlib-js/stdlib#788]
# BLAS Updates

> Refactor and clean-up existing base BLAS packages according to current project conventions.

Existing base BLAS packages need to be updated according to current project conventions before we can continue building out additional BLAS functionality. What follows is a general list of necessary changes, along with a list of packages which should be updated.

An example commit implementing (most of) these changes can be found in <https://github.com/stdlib-js/stdlib/commit/d66d80cfcbab1da95cb5ae8cfae4a1fc4c5129d1> (`saxpy`).

## Updates

1. replace `nullptr` with `NULL`
2. remove namespace (and anything else C++) and use `static` functions
3. rename file from `addon.cpp` to `addon.c`
4. update include.gypi to reference `addon.c` file
5. use argv macros for handling add-on callback arguments
6. update benchmarks to use utility functions for generating arrays of random numbers, rather than explicit loops
7. change "destination array" and "returns y" to "output array" and "returns output array" respectively
8. change "deep equal" to "returns expected value"
9. remove use of `floor`
10. README and repl.txt copy edits
11. in `*.native.js` files, use utilities for creating offset views, rather than explicit typed array creation
12. update `manifest.json` file to include `argv` utility dependencies
13. update `manifest.json` to use space indentation to match other project JSON files
14. update `manifest.json` to include separate build configurations for compiling the addon, the benchmarks, and the examples.

## Packages

- [x] ccopy
- [x] cswap
- [x] dasum
- [x] daxpy
- [x] dcopy
- [x] ddot
- [x] dnrm2
- [x] dscal
- [x] dsdot
- [x] dswap
- [x] sasum
- [x] saxpy
- [x] scopy ( #797 )
- [x] sdot ( #798 )
- [x] sdsdot ( #799 )
- [x] snrm2 ( #800 )
- [x] sscal
- [x] sswap ( #794 )

**Comment by Pranavchiku** [comment]
Working on [`blas/base/sswap`](https://github.com/stdlib-js/stdlib/tree/develop/lib/node_modules/%40stdlib/blas/base/sswap).

**Comment by Pranavchiku** [comment]
On `blas/base/scopy`.

**Comment by Pranavchiku** [comment]
Refactoring [`blas/base/sdot`](https://github.com/stdlib-js/stdlib/tree/develop/lib/node_modules/%40stdlib/blas/base/sdot).

**Comment by Pranavchiku** [comment]
Refactoring [`blas/base/sdsdot`](https://github.com/stdlib-js/stdlib/tree/develop/lib/node_modules/%40stdlib/blas/base/sdsdot).

**Comment by Pranavchiku** [comment]
Refactoring [`blas/base/snrm2`](https://github.com/stdlib-js/stdlib/tree/develop/lib/node_modules/%40stdlib/blas/base/snrm2).

**Comment by kgryte** [comment]
This work has now been completed. Closing...
