### ISSUE TITLE
[RFC]: Add `@stdlib/iter/do-while-each`

### ISSUE THREAD

**Issue by kgryte** [stdlib-js/stdlib#808]
### Description

This RFC proposes adding an iterator utility to invoke a function for each iterated value until a predicate function returns `false`.

This is the iterator equivalent of [`@stdlib/utils/do-while-each`](https://github.com/stdlib-js/stdlib/tree/develop/lib/node_modules/%40stdlib/utils/do-while-each).

Package: `@stdlib/iter/do-while-each`
Alias: `iterDoWhileEach`

### Related Issues

None.

### Questions

No.

### Other

No.

### Checklist

- [X] I have read and understood the [Code of Conduct](https://github.com/stdlib-js/stdlib/blob/develop/CODE_OF_CONDUCT.md).
- [X] Searched for existing issues and pull requests.
- [X] The issue name begins with `RFC:`.

**Comment by Arnav2824** [comment]
@Planeshifter @kgryte I understood this issue, Please assign this to me

**Comment by kgryte** [comment]
Thanks for volunteering to work on this, @Arnav2824. Please feel free to submit a PR implementing this feature.

**Comment by PraneGIT** [comment]
@kgryte if this is still open can i work on this

**Comment by Planeshifter** [comment]
@PraneGIT Since I don't see any indication that Arnav2824 started working on this issue and it has been more than a week, I just unassigned him and assigned the issue to you. Feel free to submit a PR!
