### ISSUE TITLE
[RFC]: Add `@stdlib/string/base/replace-before`

### ISSUE THREAD

**Issue by kgryte** [stdlib-js/stdlib#811]
### Description

This RFC proposes adding a utility to replace the substring before the first occurrence of a specified search string.

Similar to other base string APIs, the package should assume valid inputs.

Logic should be similar to [`@stdlib/string/substring-before`](https://github.com/stdlib-js/stdlib/tree/develop/lib/node_modules/%40stdlib/string/substring-before).

Package: `@stdlib/string/base/replace-before`
Alias: `replaceBefore`

### Related Issues

None.

### Questions

No.

### Other

No.

### Checklist

- [X] I have read and understood the [Code of Conduct](https://github.com/stdlib-js/stdlib/blob/develop/CODE_OF_CONDUCT.md).
- [X] Searched for existing issues and pull requests.
- [X] The issue name begins with `RFC:`.

**Comment by HarshitaKalani** [comment]
Should I use str2 as the new string which will replace str? So the new function would be replaceBefore(str, search, str2), right?
Also, what if str2 and str are of different lengths?

**Comment by kgryte** [comment]
@HarshitaKalani How about the following signature:

```javascript
replaceBefore( str, search, replacement )
```

And it is fine if `str` and `replacement` are different. The resulting string will just be a different length.

**Comment by HarshitaKalani** [comment]
Sure thanks
