### ISSUE TITLE
[RFC]: Add `@stdlib/string/base/replace-before-last`

### ISSUE THREAD

**Issue by kgryte** [stdlib-js/stdlib#813]
### Description

This RFC proposes adding a utility to replace the substring before the last occurrence of a specified search string.

Similar to other base string APIs, the package should assume valid inputs.

Logic should be similar to [`@stdlib/string/substring-before-last`](https://github.com/stdlib-js/stdlib/tree/develop/lib/node_modules/%40stdlib/string/substring-before-last).

Package: `@stdlib/string/base/replace-before-last`
Alias: `replaceBeforeLast`

### Related Issues

None.

### Questions

No.

### Other

No.

### Checklist

- [X] I have read and understood the [Code of Conduct](https://github.com/stdlib-js/stdlib/blob/develop/CODE_OF_CONDUCT.md).
- [X] Searched for existing issues and pull requests.
- [X] The issue name begins with `RFC:`.

**Comment by varunsh17** [comment]
I have read and understood the requirements needed for this issue. 
Can I be assigned so that I can start working immediately?
Thanks

**Comment by AuenKr** [comment]
I have almost completed replace-after and replace-after-last issue which is very similar to this issue, can i get assign for this issue?

**Comment by kgryte** [comment]
Looks like @AuenKr has already submitted a PR for this, so will assign accordingly.
