### ISSUE TITLE
[RFC]: Add `@stdlib/string/base/replace-after-last`

### ISSUE THREAD

**Issue by kgryte** [stdlib-js/stdlib#814]
### Description

This RFC proposes adding a utility to replace the substring after the last occurrence of a specified search string.

Similar to other base string APIs, the package should assume valid inputs.

Logic should be similar to [`@stdlib/string/substring-after-last`](https://github.com/stdlib-js/stdlib/tree/develop/lib/node_modules/%40stdlib/string/substring-after-last).

Package: `@stdlib/string/base/replace-after-last`
Alias: `replaceAfterLast`

### Related Issues

None.

### Questions

No.

### Other

No.

### Checklist

- [X] I have read and understood the [Code of Conduct](https://github.com/stdlib-js/stdlib/blob/develop/CODE_OF_CONDUCT.md).
- [X] Searched for existing issues and pull requests.
- [X] The issue name begins with `RFC:`.

**Comment by AuenKr** [comment]
Hey @kgryte, Can i work on this issue?

**Comment by varunsh17** [comment]
I have read the requirements needed for this issue,
Can I be assigned so that I can start working ?
Thanks

**Comment by kgryte** [comment]
Looks like @AuenKr has already submitted a PR for this, so will assign accordingly.
