### ISSUE TITLE
[RFC]: Add `@stdlib/utils/every-own-by`

### ISSUE THREAD

**Issue by kgryte** [stdlib-js/stdlib#818]
### Description

This RFC proposes adding a utility to test whether every "own" property of a provided object satisfies a predicate function.

This is the object keys equivalent of [`@stdlib/utils/every-by`](https://github.com/stdlib-js/stdlib/tree/develop/lib/node_modules/%40stdlib/utils/every-by).

Package: `@stdlib/utils/every-own-by`
Alias: `everyOwnBy`

### Related Issues

None.

### Questions

No.

### Other

No.

### Checklist

- [X] I have read and understood the [Code of Conduct](https://github.com/stdlib-js/stdlib/blob/develop/CODE_OF_CONDUCT.md).
- [X] Searched for existing issues and pull requests.
- [X] The issue name begins with `RFC:`.

**Comment by PraneGIT** [comment]
@kgryte assign me this please.

**Comment by Planeshifter** [comment]
@PraneGIT Great, just did; looking forward to your contribution!
