### ISSUE TITLE
[RFC]: Add `@stdlib/utils/any-own-by`

### ISSUE THREAD

**Issue by kgryte** [stdlib-js/stdlib#819]
### Description

This RFC proposes adding a utility to test whether any "own" property of a provided object satisfies a predicate function.

This is the object keys equivalent of [`@stdlib/utils/any-by`](https://github.com/stdlib-js/stdlib/tree/develop/lib/node_modules/%40stdlib/utils/any-by).

Package: `@stdlib/utils/any-own-by`
Alias: `anyOwnBy`

### Related Issues

None.

### Questions

No.

### Other

No.

### Checklist

- [X] I have read and understood the [Code of Conduct](https://github.com/stdlib-js/stdlib/blob/develop/CODE_OF_CONDUCT.md).
- [X] Searched for existing issues and pull requests.
- [X] The issue name begins with `RFC:`.

**Comment by Pranavbj** [comment]
@Pranavchiku @Planeshifter   I would like to work on this issue.

**Comment by Pranavchiku** [comment]
Thanks @Pranavbj for your interest! Assigned this to you.

**Comment by Rec0iL99** [comment]
Hi @Pranavbj, are you still working on this? If not, I would like to take this on.

**Comment by Planeshifter** [comment]
@Rec0iL99 Feel free to work on this package, I just assigned the issue to you since there hasn't been any public progress on Pranav's part since being assigned on Feb 27th.
