### ISSUE TITLE
[RFC]: Add `@stdlib/utils/some-own-by`

### ISSUE THREAD

**Issue by kgryte** [stdlib-js/stdlib#821]
### Description

This RFC proposes adding a utility to test whether some "own" properties of a provided object satisfies a predicate function.

This is the object keys equivalent of [`@stdlib/utils/some-by`](https://github.com/stdlib-js/stdlib/tree/develop/lib/node_modules/%40stdlib/utils/some-by).

Package: `@stdlib/utils/some-own-by`
Alias: `someOwnBy`

### Related Issues

None.

### Questions

No.

### Other

No.

### Checklist

- [X] I have read and understood the [Code of Conduct](https://github.com/stdlib-js/stdlib/blob/develop/CODE_OF_CONDUCT.md).
- [X] Searched for existing issues and pull requests.
- [X] The issue name begins with `RFC:`.

**Comment by vr-varad** [comment]
hey @kgryte @Planeshifter 
is this issue some what says this

```
var someByOwn = require( '@your-package/some-by-own' );

function isGreaterThanTen( value ) {
    return ( value > 10 );
}

var obj = { a: 5, b: 15, c: 8, d: 20 };

var bool = someByOwn( obj, 2, isGreaterThanTen );
// returns true
```

I want to work on this

**Comment by performant23** [comment]
Hey there! I noticed this issue doesn't have anyone assigned to it, and I'm free to help out since I don't have any issue at hand. Would you please assign it to me (@kgryte, @Planeshifter, @Pranavchiku)? 
Thank you so much!

**Comment by Pranavchiku** [comment]
Why not? Go ahead :)
