### ISSUE TITLE
[RFC]: Add `@stdlib/utils/every-in-by`

### ISSUE THREAD

**Issue by kgryte** [stdlib-js/stdlib#822]
### Description

This RFC proposes adding a utility to test whether every "own" and inherited property of a provided object satisfies a predicate function.

This is the `for-in` equivalent of [`@stdlib/utils/every-by`](https://github.com/stdlib-js/stdlib/tree/develop/lib/node_modules/%40stdlib/utils/every-by).

Package: `@stdlib/utils/every-in-by`
Alias: `everyInBy`

### Related Issues

None.

### Questions

No.

### Other

No.

### Checklist

- [X] I have read and understood the [Code of Conduct](https://github.com/stdlib-js/stdlib/blob/develop/CODE_OF_CONDUCT.md).
- [X] Searched for existing issues and pull requests.
- [X] The issue name begins with `RFC:`.

**Comment by saisrikardumpeti** [comment]
would you explain this more i am not able to understand this?

**Comment by kgryte** [comment]
By example,

```javascript
function predicate( value, key, obj ) {
	return ( value > 0 );
}

var o = {
	'a': 1,
	'b': 2,
	'c': 3,
	'd': 4
};

var bool = everyInBy( o, predicate );
// returns true

o.a = -2;
bool = everyInBy( o, predicate );
// returns false
```

Pay attention to the OP. Namely, it should also work for inherited properties.

**Comment by saisrikardumpeti** [comment]
i have created this test function will this work or should i make changes?
```js
function predicate( value, key, obj ) {
	return ( value > 0 );
}

function everyByIn(obj, predicate, thisArg) {
  var out

  if ( !isObject( obj ) ) {
		throw new TypeError( format( 'invalid argument. First argument must be a object. Value: `%s`.', obj ) );
	}
	if ( !isFunction( predicate ) ) {
		throw new TypeError( format( 'invalid argument. Second argument must be a function. Value: `%s`.', predicate ) );
	}

  for (const key in obj) {
    if (obj.hasOwnProperty(key)) {
      out = predicate.call(thisArg, obj[key], key, obj)
      if (!out) {
        return false
      }
    } 
  }
  return true
}
```

**Comment by kgryte** [comment]
You don't want the `hasOwnProperty` check, as this function should also check inherited properties, as mentioned in the OP.

**Comment by kgryte** [comment]
You can also inline the `predicate.call` expression into the conditional. No need for a temporary variable in this case.

**Comment by kgryte** [comment]
Otherwise, yes, what you have proposed is a good start. Feel free to open a PR with the implementation and associated package files.

@Planeshifter Should we go ahead and rename the package to `@stdlib/object/every-in-by`?

**Comment by saisrikardumpeti** [comment]
cool i am excited on this one i will make changes regarding to it. then comment it before making a PR.

**Comment by kgryte** [comment]
Sounds good! Thanks for working on it!

**Comment by saisrikardumpeti** [comment]
no worries happy to contribute.

**Comment by saisrikardumpeti** [comment]
here is the updated function.

```js
function everyByIn(obj, predicate, thisArg) {
  
  var key
  
  if (!isObject(obj)) {
    throw new TypeError(format('invalid argument. First argument must be an object. Value: `%s`.', obj));
  }
  if (!isFunction(predicate)) {
    throw new TypeError(format('invalid argument. Second argument must be a function. Value: `%s`.', predicate));
  }

  // Use a for...in loop to iterate through all enumerable properties, including inherited ones
  for (key in obj) {
    if (!predicate.call(thisArg, obj[key], key, obj)) {
      return false;
    }
  }

  return true;
}
```

**Comment by saisrikardumpeti** [comment]
everything is working fine locally.

**Comment by kgryte** [comment]
That looks reasonable. Note that we author everything in ES5, so no `const`.

**Comment by saisrikardumpeti** [comment]
i have updated the comment code.

**Comment by saisrikardumpeti** [comment]
> That looks reasonable. Note that we author everything in ES5, so no `const`.

from next time i will keep that in my mind.

**Comment by saisrikardumpeti** [comment]
shall i make a PR now or wait.

**Comment by kgryte** [comment]
Go ahead and open a PR.

**Comment by kgryte** [comment]
You'll obviously need to add docs, tests, and benchmarks similar to other packages.

**Comment by saisrikardumpeti** [comment]
ok, i will make PR by tonight.
