### ISSUE TITLE
[RFC]: Add `@stdlib/utils/any-in-by`

### ISSUE THREAD

**Issue by kgryte** [stdlib-js/stdlib#823]
### Description

This RFC proposes adding a utility to test whether any "own" and inherited property of a provided object satisfies a predicate function.

This is the `for-in` equivalent of [`@stdlib/utils/any-by`](https://github.com/stdlib-js/stdlib/tree/develop/lib/node_modules/%40stdlib/utils/any-by).

Package: `@stdlib/utils/any-in-by`
Alias: `anyInBy`

### Related Issues

None.

### Questions

No.

### Other

No.

### Checklist

- [X] I have read and understood the [Code of Conduct](https://github.com/stdlib-js/stdlib/blob/develop/CODE_OF_CONDUCT.md).
- [X] Searched for existing issues and pull requests.
- [X] The issue name begins with `RFC:`.

**Comment by itsspriyansh** [comment]
Hey @Pranavchiku @Planeshifter 
I would like to work on this issue.

**Comment by Pranavchiku** [comment]
Go ahead, looking forward to your contributions.

**Comment by itsspriyansh** [comment]
@Pranavchiku I have raised a PR #1411 for this.

**Comment by Pranavchiku** [comment]
We'll review in a while, thanks for your contributions!
