### ISSUE TITLE
[RFC]: Add `@stdlib/utils/some-in-by`

### ISSUE THREAD

**Issue by kgryte** [stdlib-js/stdlib#825]
### Description

This RFC proposes adding a utility to test whether some "own" and inherited properties of a provided object satisfies a predicate function.

This is the `for-in` equivalent of [`@stdlib/utils/some-by`](https://github.com/stdlib-js/stdlib/tree/develop/lib/node_modules/%40stdlib/utils/some-by).

Package: `@stdlib/utils/some-in-by`
Alias: `someInBy`

### Related Issues

None.

### Questions

No.

### Other

No.

### Checklist

- [X] I have read and understood the [Code of Conduct](https://github.com/stdlib-js/stdlib/blob/develop/CODE_OF_CONDUCT.md).
- [X] Searched for existing issues and pull requests.
- [X] The issue name begins with `RFC:`.

**Comment by performant23** [comment]
Hey, @kgryte , @Planeshifter, and @Pranavchiku, since I don't have any issue assigned at hand, I wanted to work on this one and have reviewed 'some-by'. Can it please be assigned to me?

**Comment by Pranavchiku** [comment]
Thanks for your contributions! Go ahead, assigned to you :)

**Comment by performant23** [comment]
Thank you so much for assigning me!

So far, here's my understanding: we're developing a utility designed to test whether some “own” and inherited properties of a provided object satisfy a predicate function. Contrasted with some-by, we'd consider inherited properties of the object not just object's own properties. This would basically handle a wider range of use cases. In my main implementation, the condition to have one of these to be true is an important point: object: obj.hasOwnProperty( key ), obj.__proto__.hasOwnProperty( key ) before moving on satisfiability of predicate.

So my question was that the implementation checks for properties and its immediate prototype. What would we handle prototype chains? Like if an object's prototype itself is an object with another prototype? Do we need to handle these cases?

Edit: As of the latest commit, we're checking for immediate prototype without deeper chaining
