### ISSUE TITLE
[RFC]: Add `@stdlib/napi/create-double`

### ISSUE THREAD

**Issue by kgryte** [stdlib-js/stdlib#826]
### Description

This RFC proposes add C APIs for converting a double-precision floating-point C value to a JavaScript object.

This is the reverse of [`@stdlib/napi/argv-double`](https://github.com/stdlib-js/stdlib/tree/develop/lib/node_modules/%40stdlib/napi/argv-double).

Package: `@stdlib/napi/create-double`

### Related Issues

None.

### Questions

No.

### Other

No.

### Checklist

- [X] I have read and understood the [Code of Conduct](https://github.com/stdlib-js/stdlib/blob/develop/CODE_OF_CONDUCT.md).
- [X] Searched for existing issues and pull requests.
- [X] The issue name begins with `RFC:`.

**Comment by noobCoderVP** [comment]
Hey @kgryte, I would like to work on this issue. I am a new contributor and contributing a new package will help me understanding the codebase. could you please guide me?

**Comment by kgryte** [comment]
@noobCoderVP I suggest finding a different issue than this one. I realized today that this one is more subtle and not a good first issue. There should be other good first issues to work on.

**Comment by noobCoderVP** [comment]
Okay fine, I will find a new one. thanks!

**Comment by kgryte** [comment]
This feature was addressed in https://github.com/stdlib-js/stdlib/commit/3aa17cd6be87b47d5d01c1556e519413a3c4bdbe.
