### ISSUE TITLE
[RFC]: Levenshtein distance between two strings

### ISSUE THREAD

**Issue by Planeshifter** [stdlib-js/stdlib#835]
### Description

This RFC proposes adding a function to calculate the Levenshtein (edit) distance between two strings.

Package: `@stdlib/string/base/distances/levenshtein`.

The function should have the following signature `(a: string, b: string): number`.

The Levenstein (edit) distance is a popular metric for quantifying the difference between two strings. It is used in a variety of applications, including spell checking, natural language processing, and text mining.

See:
 - [Levenshtein distance](https://en.wikipedia.org/wiki/Levenshtein_distance)

### Related Issues

None.

### Questions

No.

### Other

No.

### Checklist

- [X] I have read and understood the [Code of Conduct](https://github.com/stdlib-js/stdlib/blob/develop/CODE_OF_CONDUCT.md).
- [X] Searched for existing issues and pull requests.
- [X] The issue name begins with `RFC:`.

**Comment by Infinage** [comment]
Hi @Planeshifter,

I am interested in working on this. Here is a rough snippet of the solution:

```
/* 
Reference: https://www.baeldung.com/cs/levenshtein-distance-computation (Algo# 4)
Reference: https://leetcode.com/problems/edit-distance/solutions/25846/c-o-n-space-dp/
*/
const levenstein = ( a: string, b: string ): number => {
    const n = a.length, m = b.length;
    const row: number[] = [ ...Array( m + 1 ).keys() ];

    for ( let i = 0; i <= n - 1; i++ ) {
        let pre = row[ 0 ];
        row[ 0 ] = i + 1;
        for ( let j = 0; j <= m - 1; j++ ) {
            let temp = row[ j + 1 ];
            if (a[ i ] == b[ j ]) {
                row[ j + 1 ] = pre;
            } else {
                row[ j + 1 ] = Math.min( pre, Math.min( row[ j ], row[ j + 1 ] ) ) + 1;
            }
            pre = temp;
        }
    }

    return row[ m ];
}

console.assert( levenstein( "algorithm", "altruistic" ) == 6 )
console.assert( levenstein( "1638452297", "444488444" ) == 9 )
console.assert( levenstein( "", "" ) == 0 )
console.assert( levenstein( "", "a" ) == 1 )
console.assert( levenstein( "aaapppp", "" ) == 7 )
console.assert( levenstein( "frog", "fog" ) == 1 )
console.assert( levenstein( "fly", "ant" ) == 3 )
console.assert( levenstein( "elephant", "hippo" ) == 7 )
console.assert( levenstein( "hippo", "elephant" ) == 7 )
console.assert( levenstein( "hippo", "zzzzzzzz" ) == 8 )
console.assert( levenstein( "hello", "hallo" ) == 1 )
console.assert( levenstein( "congratulations", "conmgeautlatins" ) == 5 )
```

Could you also suggest some similar packages that I could build this functionality from? Any other pointers to be kept in mind during development? Thanks!

**Comment by Infinage** [comment]
Hi @Planeshifter, I have raised a PR (https://github.com/stdlib-js/stdlib/pull/1030) for this issue. Could you please check and let me know in case of any corrections? Thanks!

**Comment by Planeshifter** [comment]
Upon first look, this looks great, thanks @Infinage! Will review shortly.
