### ISSUE TITLE
@stdlib/os-arch returns architecture of node, not of the cpu.

### ISSUE THREAD

**Issue by ArmelChesnais** [stdlib-js/stdlib#837]
### Description

pulling arch when running in an x64 build of Node on an arm64 CPU (mac m1) will return x64, not arm64.

This was discovered while trying to determine the CPU arch of an electron app running an x64 version of the app on an m1 mac (arm64).

### Questions

No.

### Expected Results

```shell
arch value should be `arm64` when running in a NodeJS x64 build running on an arm64 CPU
```

### Actual Results

```shell
arch value returns the NodeJS build arch, not the CPU arch.
```

### Environments

Node.js

### Node.js / npm Version

16.15.0

### Checklist

- [X] Read and understood the [Code of Conduct](https://github.com/stdlib-js/stdlib/blob/develop/CODE_OF_CONDUCT.md).
- [X] Searched for existing issues and pull requests.

**Comment by kgryte** [comment]
@ArmelChesnais Thanks for filing this issue. `@stdlib/os-arch` returns the value of [`process.arch`](https://nodejs.org/api/process.html#processarch), which is supplied by Node.js. So if the architecture is not correct, this would be due to an upstream issue in Node.js core.

**Comment by kgryte** [comment]
...or in this case, this could be due to how the electron app was built.

In short, I don't think the issue lies with stdlib, I'm afraid.

**Comment by ArmelChesnais** [comment]
it may be a good idea to update the documentation in that case, as it is then currently incorrect:
```Operating system CPU architecture.```
Should instead indicate that it reports the architecture that NodeJS was built for, not that of the system itself is.
```NodeJS build architecture Target```
Or along those lines.

As per NodeJS documentation:
[`The operating system CPU architecture for which the Node.js binary was compiled.`](https://nodejs.org/api/process.html#processarch)

Which is incidentally being differentiated in upcoming Node versions through the `os` module offering [os.arch()](https://nodejs.org/api/os.html#osarch) and [os.machine()](https://nodejs.org/api/os.html#osmachine), which indicate the difference between the NodeJS build and the actual CPU architecture.

**Comment by kgryte** [comment]
Thanks for the suggestion. Agreed. We should update the description.

**Comment by kgryte** [comment]
The package description was updated in https://github.com/stdlib-js/stdlib/commit/7d6544c40894f14a16391d3850f1cb174e4b678f and will be part of the next release.

**Comment by kgryte** [comment]
This has been resolved: https://github.com/stdlib-js/os-arch/tree/f7d812a2dcc40bf68b37d2e7ebd58e7817abf62a. Closing...
