### ISSUE TITLE
[RFC]: Add `@stdlib/string/base/altcase`

### ISSUE THREAD

**Issue by kgryte** [stdlib-js/stdlib#850]
### Description

This RFC proposes adding support for converting a string to alternating case.

E.g.,

```javascript
altcase( 'foo bar' );
// returns 'fOo bAr'
```

Package: `@stdlib/string/base/altcase`
Alias: `altcase`

### Related Issues

None.

### Questions

No.

### Other

See [`@stdlib/string/base/constantcase`](https://github.com/stdlib-js/stdlib/blob/develop/lib/node_modules/%40stdlib/string/base/constantcase/lib/main.js) for a similar package.

### Checklist

- [X] I have read and understood the [Code of Conduct](https://github.com/stdlib-js/stdlib/blob/develop/CODE_OF_CONDUCT.md).
- [X] Searched for existing issues and pull requests.
- [X] The issue name begins with `RFC:`.

**Comment by Jaysukh-409** [comment]
I understand the issue. Can anyone explain me what should I do when there are special character present or when there are any space present ?
```
altcase("Hello world!")  
output : hElLo wOrLd!
```
I am changing every odd place character to it's lowercase and even place character to it's uppercase if it's not special character or blank space.

**Comment by kgryte** [comment]
@Jaysukh-409 You can keep spaces and special characters. So the example output you show above seems reasonable to me.
