### ISSUE TITLE
[RFC]: Add `@stdlib/string/base/stickycase`

### ISSUE THREAD

**Issue by kgryte** [stdlib-js/stdlib#852]
### Description

This RFC proposes adding support for converting a string to "sticky caps" case (also known as "studly case" or sponge case), where capitalization is random.

E.g.,

```javascript
stickycase( 'foo bar' );
// returns 'fOo bAR'
```

Package: `@stdlib/string/base/stickycase`
Alias: `stickycase`

### Related Issues

None.

### Questions

- We should use `@stdlib/random/base/bernoulli`. We could consider supporting a `p` (probability) parameter in which randomness of capitalization is controlled by a specified probability.
- Should this package be named differently? (e.g., `spongecase`?)

### Other

See [`@stdlib/string/base/constantcase`](https://github.com/stdlib-js/stdlib/blob/develop/lib/node_modules/%40stdlib/string/base/constantcase/lib/main.js) for a similar package.

### Checklist

- [X] I have read and understood the [Code of Conduct](https://github.com/stdlib-js/stdlib/blob/develop/CODE_OF_CONDUCT.md).
- [X] Searched for existing issues and pull requests.
- [X] The issue name begins with `RFC:`.

**Comment by anudeeps0306** [comment]
@kgryte 

The proposed package name stickycase seems appropriate for describing the behavior of converting a string to "sticky caps" case. However, considering that the term "studly case" or "sponge case" is also commonly used to describe this capitalization style, it might be beneficial to choose a more general name that encompasses these variations. Therefore, spongecase could be a more suitable name for the package as it's broader and includes other common terms for the same concept.

To implement support for a probability parameter (p) in controlling the randomness of capitalization, the following steps can be taken:

1) Modify the stickycase function to accept an additional parameter p representing the probability of capitalization.
2) Validate the p parameter to ensure it's a valid probability value between 0 and 1.
3) Use the @stdlib/random/base/bernoulli module to generate random numbers based on the specified probability p.
4) Utilize the generated random numbers to decide whether each character in the input string should be capitalized or not.

Can I start working on this issue?

**Comment by kgryte** [comment]
I suggest keeping the name as `stickycase`.  There's a larger question whether this API should support PRNG seeding, but that can always be a follow-up enhancement. As a starting point, what you outline is fine. Feel free to submit a PR with an initial draft implementation.

**Comment by anudeeps0306** [comment]
@kgryte As the output would be random, how should I create an example?

![image](https://github.com/stdlib-js/stdlib/assets/71971574/84e939fc-aaab-459a-bd07-af138c843c6f)

**Comment by Planeshifter** [comment]
@anudeeps0306 You can use return annotations like `// returns <string>` in case the output is random.
