### ISSUE TITLE
[RFC]: Add `@stdlib/string/last`

### ISSUE THREAD

**Issue by kgryte** [stdlib-js/stdlib#854]
### Description

This RFC proposes adding support for returning the last (visual) character(s) of a string.

Signature:

```javascript
last( str[, n][options] )
```

where `n` specifies the number of visual characters to return. Default: `1`.

E.g.,

```javascript
last( 'foo bar' );
// returns 'r'

last( '🐶🐮🐷🐰🐸', 2 );
// returns '🐰🐸'
```

Package: `@stdlib/string/last`
Alias: `last`

### Related Issues

None.

### Questions

No.

### Other

See [`@stdlib/string/first`](https://github.com/stdlib-js/stdlib/tree/develop/lib/node_modules/%40stdlib/string/first) for a similar package.

### Checklist

- [X] I have read and understood the [Code of Conduct](https://github.com/stdlib-js/stdlib/blob/develop/CODE_OF_CONDUCT.md).
- [X] Searched for existing issues and pull requests.
- [X] The issue name begins with `RFC:`.

**Comment by Pushpendra766** [comment]
Hey @kgryte ,
If this issue is still to be worked on, I would like to work, please assign.

**Comment by Planeshifter** [comment]
@Pushpendra766 Yes, this package is still needed. I just assigned you. It would be good to model the implementation closely after [@stdlib/string/first](https://github.com/stdlib-js/stdlib/tree/develop/lib/node_modules/%40stdlib/string/first), as the package should support the same modes and have a similar API.

**Comment by Pushpendra766** [comment]
Sure, will work on it then.

**Comment by kgryte** [comment]
@Pushpendra766 To clarify, please first work on `@stdlib/string/base/last`, and model after the following package: https://github.com/stdlib-js/stdlib/tree/develop/lib/node_modules/%40stdlib/string/base/first

**Comment by kgryte** [comment]
This feature request is actually comprised of multiple new packages, and I advise working on one at a time. The easiest and most straightforward is `@stdlib/string/base/last`. From there, we can move to the others after you've gotten the first successfully merged.

**Comment by Pushpendra766** [comment]
Sure, thanks for providing a reference.

**Comment by adityacodes30** [comment]
@Pushpendra766 if you're not working on this, might i take this up ?

**Comment by adityacodes30** [comment]
I would like to work on this once related pr(s) are merged

**Comment by kgryte** [comment]
As @Pushpendra766 has not responded or opened a PR implementing this feature, I'll go ahead and assign @adityacodes30 to pick this up once the base packages are merged.

**Comment by Pushpendra766** [comment]
Hey @kgryte ,
Due to some issues with my system I wasn't able to complete my work on it.
And now that my system is back on track again. Can I continue it ?

**Comment by kgryte** [comment]
@Pushpendra766 I'm sorry to hear that you encountered difficulties. Given recent progress, I suggest picking up another good first issue.
