### ISSUE TITLE
[RFC]: Add `@stdlib/string/for-each`

### ISSUE THREAD

**Issue by kgryte** [stdlib-js/stdlib#855]
### Description

This RFC proposes adding support for invoking a callback for each (visual) character of a string.

Signature:

```javascript
forEach( str, clbk[, thisArg] )
```

where `clbk` (similar to [`@stdlib/utils/for-each`](https://github.com/stdlib-js/stdlib/tree/ee2d245f666240fc94f6bdfcf78d62f1883773a8/lib/node_modules/%40stdlib/utils/for-each)) is provided

- **value**: visual character
- **idx**: starting character index
- **str**: input string

Package: `@stdlib/string/for-each`
Alias: `forEach`

### Related Issues

None.

### Questions

No.

### Other

Will require iterating over grapheme cluster breaks. See [`@stdlib/string/reverse`](https://github.com/stdlib-js/stdlib/blob/develop/lib/node_modules/%40stdlib/string/reverse) for such an example.

### Checklist

- [X] I have read and understood the [Code of Conduct](https://github.com/stdlib-js/stdlib/blob/develop/CODE_OF_CONDUCT.md).
- [X] Searched for existing issues and pull requests.
- [X] The issue name begins with `RFC:`.

**Comment by Infinage** [comment]
Hi @kgryte - I have raised a PR (PR# https://github.com/stdlib-js/stdlib/pull/1027) for this issue. Could you please look into and approve it if things looks good? For some weird reason I am seeing this error: `FatalError: error TS6266: Option 'locale' can only be specified on command line.`. I will check into this issue, cancel and raise a new PR if I am able to find a fix.

**Comment by kgryte** [comment]
@Planeshifter The encountered error seems to be a TypeScript error. You have any thoughts?

**Comment by Infinage** [comment]
Hi @kgryte & @Planeshifter, I tried a couple changes to the index.d.ts file such as changing the variable names, setting `// tslint:disable-line:max-line-length` to `/* tslint:disable:max-line-length */` but was still unsuccessful :(

**Comment by kgryte** [comment]
@Infinage I don't think this has anything to do with the specific file. This seems to me like a `tsconfig` issue. @Planeshifter would know more. I don't think this is blocking for your PR.

**Comment by Planeshifter** [comment]
Yes, don't worry about it; the error is due to the `locale` field being erroneously set in the `tsconfig.json` file, which now errors with the latest TypeScript version. We already fixed this in the top-level `tsconfig.json` file, but in [our lint configuration](https://github.com/stdlib-js/stdlib/blob/e218a81d90f7379deaaec0ab141ebd5637374d9a/etc/dtslint/tsconfig.json#L13) it was still set. This should be fixed going forward by https://github.com/stdlib-js/stdlib/commit/e5561756992c54f788208bba5623c8adc335b719.

**Comment by Infinage** [comment]
Thanks @kgryte & @Planeshifter! All the tests are now passing. I have merged and squashed my code changes. Could you please approve for a merge if everything looks good?

**Comment by Planeshifter** [comment]
Great, thank you, will review today!
