### ISSUE TITLE
[RFC]: Add `@stdlib/array/base/first`

### ISSUE THREAD

**Issue by kgryte** [stdlib-js/stdlib#857]
### Description

This RFC proposes adding support for returning the first element of an array-like object, with support for the accessor protocol.

```javascript
first( [ 1, 2, 3 ] );
// returns 1

z = new Complex128Array( [ 1, 2, 3, 4 ] );
first( z );
// returns <Complex128>
```

Package: `@stdlib/array/base/first`
alias: `first`

### Related Issues

None.

### Questions

No.

### Other

See [`@stdlib/array/base/last`](https://github.com/stdlib-js/stdlib/tree/develop/lib/node_modules/%40stdlib/array/base/last) for an example of a similar package which supports the accessor protocol.

### Checklist

- [X] I have read and understood the [Code of Conduct](https://github.com/stdlib-js/stdlib/blob/develop/CODE_OF_CONDUCT.md).
- [X] Searched for existing issues and pull requests.
- [X] The issue name begins with `RFC:`.

**Comment by Jaysukh-409** [comment]
Basically, I need to create a new feature file which return the first element from the array-like object. Right ?
