### ISSUE TITLE
[RFC]: Add `@stdlib/array/base/last`

### ISSUE THREAD

**Issue by kgryte** [stdlib-js/stdlib#858]
### Description

This RFC proposes adding support for returning the last element of an array-like object, with support for the accessor protocol.

```javascript
last( [ 1, 2, 3 ] );
// returns 3

z = new Complex128Array( [ 1, 2, 3, 4 ] );
last( z );
// returns <Complex128>
```

Package: `@stdlib/array/base/last`
alias: `last`

### Related Issues

None.

### Questions

No.

### Other

See [`@stdlib/array/base/copy`](https://github.com/stdlib-js/stdlib/tree/develop/lib/node_modules/%40stdlib/array/base/copy) for an example of a similar package which supports the accessor protocol.

### Checklist

- [X] I have read and understood the [Code of Conduct](https://github.com/stdlib-js/stdlib/blob/develop/CODE_OF_CONDUCT.md).
- [X] Searched for existing issues and pull requests.
- [X] The issue name begins with `RFC:`.

**Comment by Infinage** [comment]
Hi @kgryte, I have worked on this issues & raised a PR for the same. Could you review my PR: https://github.com/stdlib-js/stdlib/pull/1023 & let me know in case of corrections?
