### ISSUE TITLE
[RFC]: Add C implementation for `@stdlib/math/base/special/acsc`

### ISSUE THREAD

**Issue by Pranavchiku** [stdlib-js/stdlib#859]
### Description

This RFC proposes adding native C implementation for [`@stdlib/math/base/special/acsc`](https://github.com/stdlib-js/stdlib/blob/develop/lib/node_modules/%40stdlib/math/base/special/acsc/).

```c
double stdlib_base_acsc( const double x );
```

### Related Issues

None.

### Questions

No.

### Other

No.

### Checklist

- [X] I have read and understood the [Code of Conduct](https://github.com/stdlib-js/stdlib/blob/develop/CODE_OF_CONDUCT.md).
- [X] Searched for existing issues and pull requests.
- [X] The issue name begins with `RFC:`.

**Comment by rajutkarsh07** [comment]
@Pranavchiku can I work in this issue

**Comment by Planeshifter** [comment]
@rajutkarsh07 Great, thanks for taking this on! Just assigned you.

**Comment by kgryte** [comment]
@Planeshifter Before assigning an issue, best to confirm that it has not already been worked on. In this case, Pranav already has a WIP PR.
