### ISSUE TITLE
[RFC]: Add C implementation for `@stdlib/math/base/special/acsch`

### ISSUE THREAD

**Issue by Pranavchiku** [stdlib-js/stdlib#860]
### Description

This RFC proposes adding native C implementation for [`stdlib/math/base/special/acsch`](https://github.com/stdlib-js/stdlib/tree/develop/lib/node_modules/@stdlib/math/base/special/acsch).

```c
double stdlib_base_acsch( const double x );
```

### Related Issues

None.

### Questions

No.

### Other

No.

### Checklist

- [X] I have read and understood the [Code of Conduct](https://github.com/stdlib-js/stdlib/blob/develop/CODE_OF_CONDUCT.md).
- [X] Searched for existing issues and pull requests.
- [X] The issue name begins with `RFC:`.

**Comment by raunak-dev-edu** [comment]
Hey @Pranavchiku @kgryte , I would like to work on this issue but let me know how this is different from issue #861 ( asec) and #859 (acsc). What's make different to each of these three functions

**Comment by kgryte** [comment]
@raunak-dev-edu They are different functions, as may be observed by examining the JS implementations of the various packages. Each of the linked issues achieves something similar; however, the implementations will be different.

**Comment by yaswanthkosuru** [comment]
hi @kgryte @Pranavchiku @rotu To solve these i want to add all files inside @stdlib/math/base/special/acsch
update readme.md
 include.gypi
 binding.gyp
 include/stdlib/math/base/special/
 src
 manifest.json
 lib
 examples
 benchmark
 test)(similar to https://github.com/stdlib-js/stdlib/pull/769) and implement acsch functionality.
did my understand up to now is correct. Did i continue to implement same as said.

**Comment by Pranavchiku** [comment]
Yes, please feel free to open a draft PR.

**Comment by Snehil-Shah** [comment]
@yaswanthkosuru are you still working on this? If not, can I take this up?

**Comment by yaswanthkosuru** [comment]
> @yaswanthkosuru are you still working on this? If not, can I take this up?
yesterday unfortunately my system crashed so I close pr
I still working. i lost git file  but i backup saved code .so i  create new ubuntu system .i reopen new  pr within 1 day

**Comment by Userf1995** [comment]
@yaswanthkosuru are you still working on this? If not, can I take this up?

**Comment by Snehil-Shah** [comment]
> @yaswanthkosuru are you still working on this? If not, can I take this up?

I am working on it.
