### ISSUE TITLE
[RFC]: Add C implementation for `@stdlib/math/base/special/asec`

### ISSUE THREAD

**Issue by Pranavchiku** [stdlib-js/stdlib#861]
### Description

This RFC proposes adding C implementation for [`@stdlib/math/base/special/asec`](https://github.com/stdlib-js/stdlib/blob/develop/lib/node_modules/%40stdlib/math/base/special/asec).

```c
double stdlib_base_asec( const double x );
```

### Related Issues

None.

### Questions

No.

### Other

No.

### Checklist

- [X] I have read and understood the [Code of Conduct](https://github.com/stdlib-js/stdlib/blob/develop/CODE_OF_CONDUCT.md).
- [X] Searched for existing issues and pull requests.
- [X] The issue name begins with `RFC:`.

**Comment by anudeeps0306** [comment]
@Pranavchiku @kgryte Can I work on this issue

**Comment by Pranavchiku** [comment]
Go ahead, I'll assign you this.

**Comment by gunjjoshi** [comment]
Hey @anudeeps0306, are you still working on this ?

**Comment by anudeeps0306** [comment]
@gunjjoshi yes
