### ISSUE TITLE
[RFC]: Add C implementation for `@stdlib/math/base/special/asech`

### ISSUE THREAD

**Issue by Pranavchiku** [stdlib-js/stdlib#862]
### Description

This RFC proposes adding C implementation for [`@stdlib/math/base/special/asech`](https://github.com/stdlib-js/stdlib/blob/develop/lib/node_modules/%40stdlib/math/base/special/asech/).

```c
double stdlib_math_asech( const double x );
```

### Related Issues

None.

### Questions

No.

### Other

No.

### Checklist

- [X] I have read and understood the [Code of Conduct](https://github.com/stdlib-js/stdlib/blob/develop/CODE_OF_CONDUCT.md).
- [X] Searched for existing issues and pull requests.
- [X] The issue name begins with `RFC:`.

**Comment by guruharsha1** [comment]
@Pranavchiku can you please assign this to me

**Comment by kgryte** [comment]
Thanks for volunteering to work on this @guruharsha1. Please feel free to submit a PR adding this feature.

**Comment by Snehil-Shah** [comment]
@guruharsha1 hey, are you still working on this? If not, mind if I take this up?

**Comment by Userf1995** [comment]
I was just compieted it.I will make my PR
