### ISSUE TITLE
[RFC]: Add `@stdlib/random/strided/chi`

### ISSUE THREAD

**Issue by kgryte** [stdlib-js/stdlib#885]
### Description

This RFC proposes adding support for filling a strided array with pseudorandom numbers drawn from a chi distribution. This is the strided interface analog of `@stdlib/random/base/chi`.

Package: `@stdlib/random/strided/chi`
Alias: `chi`

### Related Issues

None.

### Questions

No.

### Other

- A package with a similar implementation/API design is [`@stdlib/random/strided/exponential`](https://github.com/stdlib-js/stdlib/tree/develop/lib/node_modules/%40stdlib/random/strided/exponential).

### Checklist

- [X] I have read and understood the [Code of Conduct](https://github.com/stdlib-js/stdlib/blob/develop/CODE_OF_CONDUCT.md).
- [X] Searched for existing issues and pull requests.
- [X] The issue name begins with `RFC:`.

**Comment by Madankh** [comment]
Hi i'm first time contributor can you explain me where do i need to add @stdlib/random/strided/chi

**Comment by Planeshifter** [comment]
@Madankh The package should live in https://github.com/stdlib-js/stdlib/tree/develop/lib/node_modules/%40stdlib/random/strided. If you would like to take this on, [@stdlib/random/strided/exponential](https://github.com/stdlib-js/stdlib/tree/develop/lib/node_modules/%40stdlib/random/strided/exponential) will be a good starting point that you can copy and adjust, as mentioned in the RFC.
