### ISSUE TITLE
[RFC]: Add `@stdlib/random/strided/geometric`

### ISSUE THREAD

**Issue by kgryte** [stdlib-js/stdlib#887]
### Description

This RFC proposes adding support for filling a strided array with pseudorandom numbers drawn from a geometric distribution. This is the strided interface analog of `@stdlib/random/base/geometric`.

Package: `@stdlib/random/strided/geometric`
Alias: `geometric`

### Related Issues

None.

### Questions

No.

### Other

- A package with a similar implementation/API design is [`@stdlib/random/strided/exponential`](https://github.com/stdlib-js/stdlib/tree/develop/lib/node_modules/%40stdlib/random/strided/exponential).

### Checklist

- [X] I have read and understood the [Code of Conduct](https://github.com/stdlib-js/stdlib/blob/develop/CODE_OF_CONDUCT.md).
- [X] Searched for existing issues and pull requests.
- [X] The issue name begins with `RFC:`.

**Comment by payalpm** [comment]
@kgryte @rreusser assign me can u tell me whats going in this project
