### ISSUE TITLE
[RFC]: Add `@stdlib/random/strided/rayleigh`

### ISSUE THREAD

**Issue by kgryte** [stdlib-js/stdlib#889]
### Description

This RFC proposes adding support for filling a strided array with pseudorandom numbers drawn from a Rayleigh distribution. This is the strided interface analog of `@stdlib/random/base/rayleigh`.

Package: `@stdlib/random/strided/rayleigh`
Alias: `rayleigh`

### Related Issues

None.

### Questions

No.

### Other

- A package with a similar implementation/API design is [`@stdlib/random/strided/exponential`](https://github.com/stdlib-js/stdlib/tree/develop/lib/node_modules/%40stdlib/random/strided/exponential).

### Checklist

- [X] I have read and understood the [Code of Conduct](https://github.com/stdlib-js/stdlib/blob/develop/CODE_OF_CONDUCT.md).
- [X] Searched for existing issues and pull requests.
- [X] The issue name begins with `RFC:`.

**Comment by rafiya2003** [comment]
can you assign me this work?

**Comment by Planeshifter** [comment]
@rafiya2003 Just assigned you, thanks for your interest in working on this! You may use [@stdlib/random/strided/exponential](https://github.com/stdlib-js/stdlib/tree/develop/lib/node_modules/%40stdlib/random/strided/exponential) as a basis, while changing the distribution parameter and documentation to align with what we have for Rayleigh distribution PRNGs such as [@stdlib/random/base/rayleigh](https://github.com/stdlib-js/stdlib/tree/develop/lib/node_modules/%40stdlib/random/base/rayleigh).

**Comment by rafiya2003** [comment]
I am a newbie and honestly I did not get my task. what am I supposed to do?
