### ISSUE TITLE
RFC: add logaddexp

### ISSUE THREAD

**Issue by kgryte** [stdlib-js/stdlib#89]
## Checklist

> Please ensure the following tasks are completed before filing an issue.

* [x] Read and understood the [Code of Conduct][code-of-conduct].
* [x] Searched for existing issues and pull requests.
* [x] If this is a general question, searched the [FAQ][faq] for an existing answer.
* [x] If this is a feature request, the issue name begins with `RFC: `.

## Description

> Description of the issue (or feature request).

This RFC proposes to add `@stdlib/math/base/special/logaddexp`. The ability to accurately compute `log( exp( x1 ) + exp( x2 ) )` is useful in statistics where probabilities are so small as to exceed the normal range of floating-point numbers.

## Related Issues

> Does this issue (or feature request) have any related issues?

No.

## Questions

> Any questions for reviewers?

* Beside `numpy`, do any other reference implementations exist?
* Is it possible to find primary source literature to support the implementation?

## Other

> Any other information relevant to this issue (or feature request)? This may include screenshots, references, stack traces, sample output, and/or implementation notes.

References:

* [numpy](https://github.com/numpy/numpy/blob/5f3c0c2ba7f0c794a483c7e74722f95bdd3bb827/numpy/core/src/npymath/npy_math_internal.h.src#L585)
* [scipy](https://docs.scipy.org/doc/numpy/reference/generated/numpy.logaddexp.html#numpy.logaddexp)
* [logsumexp](https://en.wikipedia.org/wiki/LogSumExp)

[code-of-conduct]: https://github.com/stdlib-js/stdlib/blob/develop/CODE_OF_CONDUCT.md
[faq]: https://github.com/stdlib-js/stdlib/blob/develop/FAQ.md

**Comment by kgryte** [comment]
@rei2hu Would you be interested in adding this new feature? Along the same lines as `log1pexp` and `log1mexp`.

**Comment by rei2hu** [comment]
Sure, it looks straightforward enough.

Should I credit NumPy's implementation at the top of the main file? I think I remember seeing that done for a few things, but I tried grepping for numpy and nothing related showed up.

**Comment by kgryte** [comment]
@rei2hu Awesome! Thank you!

Re: attribution. No, as the [log-sum-exp](https://en.wikipedia.org/wiki/LogSumExp#log-sum-exp_trick_for_log-domain_calculations) "trick" is well-known, and we can implement `logaddexp` without reference to an external implementation.
