### ISSUE TITLE
[RFC]: Add C implementation for `@stdlib/math/base/special/lucas`

### ISSUE THREAD

**Issue by Pranavchiku** [stdlib-js/stdlib#892]
### Description

This RFC proposes adding C implementation for [`@stdlib/math/base/special/lucas`](https://github.com/stdlib-js/stdlib/blob/develop/lib/node_modules/%40stdlib/math/base/special/lucas)

```c
double stdlib_base_lucas( const int32_t x );
```

### Related Issues

None.

### Questions

No.

### Other

No.

### Checklist

- [X] I have read and understood the [Code of Conduct](https://github.com/stdlib-js/stdlib/blob/develop/CODE_OF_CONDUCT.md).
- [X] Searched for existing issues and pull requests.
- [X] The issue name begins with `RFC:`.

**Comment by Jordan-Gallivan** [comment]
@Pranavchiku I'd like to continue contributing by helping out with this one.  After two iterations I [hopefully] will get this one done with far less trouble.

**Comment by Jordan-Gallivan** [comment]
Before I get started, do you want the input to be a double (per the above example) or an integer?

**Comment by Pranavchiku** [comment]
On looking examples of readme, we can go for `double` to `double`.

**Comment by kgryte** [comment]
@Pranavchiku @Jordan-Gallivan Similar to `negaLucas`, we should prob go with

```c
double stdlib_base_lucas( const int32_t n );
```

Doubles are not "valid" inputs for this API. In JS, we're more defensive and have to guard against `double` input. Similar to `negaLucas`, we don't need to do so for the C implementation.

In which case, I'd suggest updating the OP accordingly.

**Comment by kgryte** [comment]
@Pranavchiku Also, the function name seems incorrect in the OP. s/_math_/_base_/

**Comment by Pranavchiku** [comment]
Pardon me for that, might have made mistake in a hurry, and sorry Jordan for leading you astray.

**Comment by Jordan-Gallivan** [comment]
@Pranavchiku no worries! Glad I checked.  Should have this finished up tonight
