### ISSUE TITLE
[RFC]: Add C implementation for `@stdlib/math/base/special/negalucas`

### ISSUE THREAD

**Issue by Pranavchiku** [stdlib-js/stdlib#893]
### Description

This RFC proposes adding C implementation for [`@stdlib/math/base/special/negalucas`](https://github.com/stdlib-js/stdlib/tree/develop/lib/node_modules/%40stdlib/math/base/special/negalucas).

```c
int stdlib_math_negalucas( const int x );
```

### Related Issues

None.

### Questions

No.

### Other

No.

### Checklist

- [X] I have read and understood the [Code of Conduct](https://github.com/stdlib-js/stdlib/blob/develop/CODE_OF_CONDUCT.md).
- [X] Searched for existing issues and pull requests.
- [X] The issue name begins with `RFC:`.

**Comment by Jordan-Gallivan** [comment]
I'd like to contribute to this.  I'm currently working on the C implementation of the tribonacci function and should be able to leverage what I've learned working that for this.

**Comment by Planeshifter** [comment]
Awesome, that would be great!

**Comment by Jordan-Gallivan** [comment]
I've put together a few items for this, but definitely want to make sure the tribonacci PR is closed before moving forward so I ensure I don't miss anything this time around.

Thanks for letting me contribute!

**Comment by kgryte** [comment]
@Jordan-Gallivan Feel free to begin working on addressing this feature request, now that #903 is merged.
