### ISSUE TITLE
[RFC]: Add C implementation for `@stdlib/math/base/special/tribonacci`

### ISSUE THREAD

**Issue by Pranavchiku** [stdlib-js/stdlib#895]
### Description

This RFC proposes adding C implementation for [`@stdlib/math/base/special/tribonacci`](https://github.com/stdlib-js/stdlib/blob/develop/lib/node_modules/%40stdlib/math/base/special/tribonacci).

```c
int stdlib_math_tribonacci( const int x );
```

### Related Issues

None.

### Questions

No.

### Other

No.

### Checklist

- [X] I have read and understood the [Code of Conduct](https://github.com/stdlib-js/stdlib/blob/develop/CODE_OF_CONDUCT.md).
- [X] Searched for existing issues and pull requests.
- [X] The issue name begins with `RFC:`.

**Comment by Jordan-Gallivan** [comment]
I would like to help out on this issue if able.

**Comment by kgryte** [comment]
@Jordan-Gallivan That would be great! Let me review and get https://github.com/stdlib-js/stdlib/pull/783 merged first. Once merged, I'll circle back and you can begin work. https://github.com/stdlib-js/stdlib/pull/783 will be useful as a reference implementation you can use to help with the `tribonacci` work proposed here.

**Comment by Jordan-Gallivan** [comment]
@kgryte Thanks! I'm new to the open source contribution so I wanna make sure I do this by the book.  Looking over the project and referencing other implementations, it looks like it should just reference the tribonocci value at an index of an array of tribonocci numbers.  That should be super easy to put to practice, I just wanted to make sure you don't want the implementation to do the actual recursion to generate the tribonocci value of n

**Comment by kgryte** [comment]
Yes, that is correct. A lookup table is fine and follows the existing implementation [strategy](https://github.com/stdlib-js/stdlib/blob/5eeb4a7d006bd7dd518ad7078c3a3daad41559f5/lib/node_modules/%40stdlib/math/base/special/tribonacci/lib/main.js).

**Comment by kgryte** [comment]
@Jordan-Gallivan In the meantime, you may want to consult our [contributing guide](https://github.com/stdlib-js/stdlib/blob/develop/CONTRIBUTING.md) and the linked development guide for help getting your local dev setup up and running. If you encounter any issues, LMK.

**Comment by kgryte** [comment]
@Jordan-Gallivan #783 was merged. You can use [`fibonacci`](https://github.com/stdlib-js/stdlib/tree/develop/lib/node_modules/%40stdlib/math/base/special/fibonacci) as a reference implementation which can be replicated for `tribonacci`.

**Comment by Jordan-Gallivan** [comment]
@kgryte Just submitted my Pull Request.  Please let me know if that answers the mail.  

I really appreciate you letting me contribute to this project.  Like I said, I'm new to open source and every rep helps me get better, and I hope I helped the project!

Feel free to pass along any feedback good/bad/otherwise so I can continue to improve.  I'd be happy to help again in the future if this is up to snuff.

Thanks!

**Comment by kgryte** [comment]
@Jordan-Gallivan Awesome! Welcome to open source! Let's plan on continuing the feedback loop on the PR, which will hopefully be a good avenue for introducing you to more of `stdlib`. :)

**Comment by Pranavchiku** [comment]
Great work @Jordan-Gallivan! Congratulations for your first PR! 🎉

**Comment by Jordan-Gallivan** [comment]
@Pranavchiku thanks! Happy to help
