### ISSUE TITLE
"numerical computing" is more common than "numeric computing"

### ISSUE THREAD

**Issue by pcowgill** [stdlib-js/stdlib#93]
## Checklist

> Please ensure the following tasks are completed before filing an issue.

* [x] Read and understood the [Code of Conduct][code-of-conduct].
* [x] Searched for existing issues and pull requests.
* [x] If this is a general question, searched the [FAQ][faq] for an existing answer.
* [x] If this is a feature request, the issue name begins with `RFC: `.

## Description

> Description of the issue (or feature request).

The README should say "numerical computing" rather than "numeric computing".

## Related Issues

> Does this issue (or feature request) have any related issues?

No.

## Questions

> Any questions for reviewers?

No.

## Other

> Any other information relevant to this issue (or feature request)? This may include screenshots, references, stack traces, sample output, and/or implementation notes.

https://trends.google.com/trends/explore?date=all&q=%22numeric%20computing%22,%22numerical%20computing%22

[code-of-conduct]: https://github.com/stdlib-js/stdlib/blob/develop/CODE_OF_CONDUCT.md
[faq]: https://github.com/stdlib-js/stdlib/blob/develop/FAQ.md

**Comment by kgryte** [comment]
@pcowgill Thanks for the link. I think, however, we will pass on changing our usage of "numeric computing" to "numerical computing". We find references to both within the field, and our intent is to indicate "computing with numbers", while avoiding confusion with numerical analysis.

If this becomes a stumbling block in the future, we can revisit, but, for the time being, we will leave as is.
