### ISSUE TITLE
[RFC]: Add `@stdlib/random/array/cauchy`

### ISSUE THREAD

**Issue by kgryte** [stdlib-js/stdlib#932]
### Description

This RFC proposes adding support for creating an array containing pseudorandom numbers drawn from a Cauchy distribution. This is the array creation analog of `@stdlib/random/base/cauchy`.

Package: `@stdlib/random/array/cauchy`
Alias: `cauchy`

### Related Issues

None.

### Questions

No.

### Other

- A package with a similar implementation/API design is [`@stdlib/random/array/beta`](https://github.com/stdlib-js/stdlib/tree/develop/lib/node_modules/%40stdlib/random/array/beta).

### Checklist

- [X] I have read and understood the [Code of Conduct](https://github.com/stdlib-js/stdlib/blob/develop/CODE_OF_CONDUCT.md).
- [X] Searched for existing issues and pull requests.
- [X] The issue name begins with `RFC:`.

**Comment by ayesha-firdaus** [comment]
can you please assign me this work?

**Comment by Planeshifter** [comment]
Of course, thanks for attempting this! Implementation should be very similar to [@stdlib/random/array/beta](https://github.com/stdlib-js/stdlib/tree/develop/lib/node_modules/%40stdlib/random/array/beta); for documentation of distribution parameters, [@stdlib/random/base/cauchy](https://github.com/stdlib-js/stdlib/tree/develop/lib/node_modules/%40stdlib/random/base/cauchy) is a good reference.
