### ISSUE TITLE
[RFC]: Add `@stdlib/random/array/weibull`

### ISSUE THREAD

**Issue by kgryte** [stdlib-js/stdlib#945]
### Description

This RFC proposes adding support for creating an array containing pseudorandom numbers drawn from a Weibull distribution. This is the array creation analog of `@stdlib/random/base/weibull`.

Package: `@stdlib/random/array/weibull`
Alias: `weibull`

### Related Issues

None.

### Questions

No.

### Other

- A package with a similar implementation/API design is [`@stdlib/random/array/beta`](https://github.com/stdlib-js/stdlib/tree/develop/lib/node_modules/%40stdlib/random/array/beta).

### Checklist

- [X] I have read and understood the [Code of Conduct](https://github.com/stdlib-js/stdlib/blob/develop/CODE_OF_CONDUCT.md).
- [X] Searched for existing issues and pull requests.
- [X] The issue name begins with `RFC:`.

**Comment by Hritik1503** [comment]
I am interested to work on this issue under Quine. So please assign me this task to me.
