### ISSUE TITLE
[RFC]: Add `@stdlib/random/strided/weibull`

### ISSUE THREAD

**Issue by kgryte** [stdlib-js/stdlib#946]
### Description

This RFC proposes adding support for filling a strided array with pseudorandom numbers drawn from a Weibull distribution. This is the strided interface analog of `@stdlib/random/base/weibull`.

Package: `@stdlib/random/strided/weibull`
Alias: `weibull`

### Related Issues

None.

### Questions

No.

### Other

- A package with a similar implementation/API design is [`@stdlib/random/strided/beta`](https://github.com/stdlib-js/stdlib/tree/develop/lib/node_modules/%40stdlib/random/strided/beta).

### Checklist

- [X] I have read and understood the [Code of Conduct](https://github.com/stdlib-js/stdlib/blob/develop/CODE_OF_CONDUCT.md).
- [X] Searched for existing issues and pull requests.
- [X] The issue name begins with `RFC:`.

**Comment by Hritik1503** [comment]
I am interested to work on this issue under Quine. So please assign me this task to me.

**Comment by amitjimiwal** [comment]
Hey @kgryte , I have implemented this issue with reference to the [@stdlib/random/strided/beta](https://github.com/stdlib-js/stdlib/tree/develop/lib/node_modules/%40stdlib/random/strided/beta). I am new to open source just wanted to know that implementation will be same except some variables changes and function name changes. Lemme know :), I haven't made a PR yet.

**Comment by amitjimiwal** [comment]
Made a PR @kgryte for the issue. Waiting for the review.
