### ISSUE TITLE
Bug: missing API documentation

### ISSUE THREAD

**Issue by backspaces** [stdlib-js/stdlib#95]
## Checklist

> Please ensure the following tasks are completed before filing an issue.

* [x] Read and understood the [Code of Conduct][code-of-conduct].
* [x] Searched for existing issues and pull requests.
* [x] If this is a general question, searched the [FAQ][faq] for an existing answer.
* [x] If this is a feature request, the issue name begins with `RFC: `.

## Description

> Description of the issue (or feature request).

I may be missing something, but after looking around, and using your Issues template, I couldn't find APIs for the wrappers over the C/Fortran libraries like LaPack etc.

Where are the API docs?

## Related Issues

> Does this issue (or feature request) have any related issues?

I couldn't tell.

## Questions

> Any questions for reviewers?

Have I missed something? Saw the video on youtube and wanted to try the project for linear algebra using LaPack or similar. Can't find API docs.

[code-of-conduct]: https://github.com/stdlib-js/stdlib/blob/develop/CODE_OF_CONDUCT.md
[faq]: https://github.com/stdlib-js/stdlib/blob/develop/FAQ.md

**Comment by Planeshifter** [comment]
Thank you for your interest in `stdlib`. You were not able to find any API documentation because this part of the library is in its infancy and under active development. As of now, a subset of BLAS wrappers with JS fallbacks is exported in `@stdlib/math/blas`. We will let you know once we have made considerable progress on this.

**Comment by DanielRuf** [comment]
Also interesting that "view documentation" leads me to https://stdlib.io/develop/docs/api/@stdlib/plot/ which is just a directory index.

**Comment by kgryte** [comment]
@DanielRuf Yeah, sorry. The website is still a work-in-progress. Lots to do and never enough time. For the `plot` constructor docs, you need only go down one more level: https://stdlib.io/develop/docs/api/@stdlib/plot/ctor/.

**Comment by DanielRuf** [comment]
Right. I saw it and then saw the sidenav. I'll try to find some spare time to work and experiment with stdlib and probably help with the docs.

**Comment by kgryte** [comment]
We recently updated our API docs. We still have some work to do, but you should now be able to navigate the complete API docs on-line, without having to walk the Github repository. See https://stdlib.io/docs/api.
