### ISSUE TITLE
RFC: complex division

### ISSUE THREAD

**Issue by rreusser** [stdlib-js/stdlib#96]
## Checklist

> Please ensure the following tasks are completed before filing an issue.

* [x] Read and understood the [Code of Conduct][code-of-conduct].
* [x] Searched for existing issues and pull requests.
* [x] If this is a general question, searched the [FAQ][faq] for an existing answer.
* [x] If this is a feature request, the issue name begins with `RFC: `.

## Description

> Description of the issue (or feature request).

Complex multiplication is implemented. Complex division seems like an obvious addition the library.

## Questions

> Any questions for reviewers?

Is this already in progress somewhere? Just checking. Otherwise seems straightforward.

Numerical recipes has a reasonable *description of an implementation*. I can dig a bit more and check the implementation of python etc to see just how careful you need to get about floating point subtleties. Any related concerns on this front?

## Other

> Any other information relevant to this issue (or feature request)? This may include screenshots, references, stack traces, sample output, and/or implementation notes.

[code-of-conduct]: https://github.com/stdlib-js/stdlib/blob/develop/CODE_OF_CONDUCT.md
[faq]: https://github.com/stdlib-js/stdlib/blob/develop/FAQ.md

**Comment by kgryte** [comment]
@rreusser Complex division would be a welcome addition. The package name should be

```
@stdlib/math/base/complex/divide
```

For reference implementations and inspiration, see [Julia](https://github.com/JuliaLang/julia/blob/a945af3aaef528da7813174c17d705b6383f7ea3/base/complex.jl#L306).
